Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2018-10, with the labels that each got.

#1794 Adds .local directory for tools configurations.
  .gitignore
Labels: Microsoft submitter

#1699 Update Move-SPEnterpriseSearchLinksDatabases.md
  sharepoint/sharepoint-ps/sharepoint-server/Move-SPEnterpriseSearchLinksDatabases.md
Labels: area:sp-server-powershell

#1682 Update connect-sharepoint-online.md
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
Labels: area:spo-powershell

#1373 Update Copy-SPAccessServicesDatabaseCredentials.md
  sharepoint/sharepoint-ps/sharepoint-server/Copy-SPAccessServicesDatabaseCredentials.md
Labels: area:sp-server-powershell

#1698 Update Set-SPEnterpriseSearchFileFormatState.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPEnterpriseSearchFileFormatState.md
Labels: area:sp-server-powershell

#1330 Update sharepoint-server-cmdlets.md
  sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md
Labels: area:sp-server-powershell

#1531 Clarify parameters that are not present in SP2010
  sharepoint/sharepoint-ps/sharepoint-server/Install-SPSolution.md
Labels: area:sp-server-powershell

#1376 Update sharepoint-server.md
  sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md
Labels: area:sp-server-powershell

#1799 link update for sharing setting
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#1802 Adds link to teams powershell overview.
  skype/docs-conceptual/index.md
Labels: Microsoft submitter

#1801 Adds link to Teams PowerShell Overview.
  skype/docs-conceptual/intro.md
Labels: Microsoft submitter

#1803 Fixes broken link.
  sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md
Labels: Microsoft submitter

#1798 Remove Identity parameters.
  exchange/exchange-ps/exchange/reporting/Get-UserAnalyticsConfig.md
Labels: Microsoft submitter, area:exchange

#1805 Updates to New-Mailbox
  exchange/exchange-ps/exchange/active-directory/Add-ADPermission.md
  exchange/exchange-ps/exchange/active-directory/Remove-ADPermission.md
  exchange/exchange-ps/exchange/client-access-servers/New-OwaVirtualDirectory.md
  exchange/exchange-ps/exchange/client-access-servers/Set-ClientAccessServer.md
  exchange/exchange-ps/exchange/client-access/Get-CASMailbox.md
  exchange/exchange-ps/exchange/client-access/Test-WebServicesConnectivity.md
  exchange/exchange-ps/exchange/mail-flow/New-ReceiveConnector.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxImportRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Remove-MailboxPermission.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/role-based-access-control/Get-RoleGroup.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Remove-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/unified-messaging/Enable-UMMailbox.md
  exchange/exchange-ps/exchange/unified-messaging/Set-UmServer.md
Labels: Microsoft submitter

#1806 Master to Live
  .gitignore
  exchange/exchange-ps/exchange/active-directory/Add-ADPermission.md
  exchange/exchange-ps/exchange/active-directory/Remove-ADPermission.md
  exchange/exchange-ps/exchange/client-access-servers/New-OwaVirtualDirectory.md
  exchange/exchange-ps/exchange/client-access-servers/Set-ClientAccessServer.md
  exchange/exchange-ps/exchange/client-access/Get-CASMailbox.md
  exchange/exchange-ps/exchange/client-access/Test-WebServicesConnectivity.md
  exchange/exchange-ps/exchange/mail-flow/New-ReceiveConnector.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxImportRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Remove-MailboxPermission.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/reporting/Get-UserAnalyticsConfig.md
  exchange/exchange-ps/exchange/role-based-access-control/Get-RoleGroup.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Remove-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/unified-messaging/Enable-UMMailbox.md
  exchange/exchange-ps/exchange/unified-messaging/Set-UmServer.md
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
  sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md
  sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
  sharepoint/sharepoint-ps/sharepoint-server/Copy-SPAccessServicesDatabaseCredentials.md
  sharepoint/sharepoint-ps/sharepoint-server/Install-SPSolution.md
  sharepoint/sharepoint-ps/sharepoint-server/Move-SPEnterpriseSearchLinksDatabases.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPEnterpriseSearchFileFormatState.md
  sharepoint/sharepoint-ps/sharepoint-server/Test-SPO365LinkSettings.md
  sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md
  skype/docs-conceptual/index.md
  skype/docs-conceptual/intro.md
  skype/docs-conceptual/overview.md
  tools/microsoft-teams-generator-tool/config/default.json
  tools/microsoft-teams-generator-tool/services/log.store.service.js
  tools/office-cmdlet-updater/.eslintrc
  tools/office-cmdlet-updater/.gitignore
  tools/office-cmdlet-updater/.prettierrc
  tools/office-cmdlet-updater/README.md
  tools/office-cmdlet-updater/config/default.json
  tools/office-cmdlet-updater/constants/commands.js
  tools/office-cmdlet-updater/constants/errors.js
  tools/office-cmdlet-updater/controllers/markdown.controller.js
  tools/office-cmdlet-updater/db/index.js
  tools/office-cmdlet-updater/helpers/di.container.js
  tools/office-cmdlet-updater/index.js
  tools/office-cmdlet-updater/package.json
  tools/office-cmdlet-updater/services/config.service.js
  tools/office-cmdlet-updater/services/log.parse.service.js
  tools/office-cmdlet-updater/services/log.store.service.js
  tools/office-cmdlet-updater/services/mail.notification.service.js
  tools/office-cmdlet-updater/services/markdown.service.js
  tools/office-cmdlet-updater/services/power.shell.service.js
Labels: Microsoft submitter

#1804 Fix link
  sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md
Labels: Microsoft submitter

#1812 Addes description for -EnableVideoBasedSharing param.
  skype/skype-ps/skype/New-CsMediaConfiguration.md
Labels: Microsoft submitter

#988 Update Register-SPAppPrincipal.md
  sharepoint/sharepoint-ps/sharepoint-server/Register-SPAppPrincipal.md
Labels: area:sp-server-powershell

#1253 Update Set-SPSite.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPSite.md
Labels: area:sp-server-powershell

#1064 Update example
  sharepoint/sharepoint-ps/sharepoint-server/New-SPSecureStoreApplication.md
Labels: area:sp-server-powershell

#1240 Corrected Synopsis
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPConnection.md
Labels: area:pnp-powershell

#1243 Added connection requirement
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUnifiedGroup.md
Labels: area:pnp-powershell

#1254 Set-CustomLayoutsPage example
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPCustomLayoutsPage.md
Labels: area:sp-server-powershell

#1020 Update Install-SPApplicationContent.md
  sharepoint/sharepoint-ps/sharepoint-server/Install-SPApplicationContent.md
Labels: area:sp-server-powershell

#1273 Update Get-PnPFolder.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md
Labels: area:pnp-powershell

#1349 adding sharepoint-pnp module overview page
  sharepoint/sharepoint-ps/sharepoint-pnp/sharepoint-pnp.md
Labels: area:pnp-powershell

#1410 Update Get-PnPApp.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPApp.md
Labels: area:pnp-powershell

#1455 Update Remove-SPAppPrincipalPermission.md
  sharepoint/sharepoint-ps/sharepoint-server/Remove-SPAppPrincipalPermission.md
Labels: area:sp-server-powershell

#1471 Moved Set-PnPView Cmdlet from Fields to Lists
  sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
Labels: area:pnp-powershell

#1810 Updates to Set-OrganizationConfig
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter

#1756 Updated to reflect the async behavior of the cmdlet
  sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTenantCdnOrigin.md
Labels: area:pnp-powershell

#1697 Update Uninstall-SPAppInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Uninstall-SPAppInstance.md
Labels: area:sp-server-powershell

#1704 Update Get-SPUser.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPUser.md
Labels: area:sp-server-powershell

#1521 Doc changes to make modern authentication easier
  sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md
Labels: area:pnp-powershell

#1813 Still trying to fix the dang link.
  sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md
Labels: Microsoft submitter

#1818 Update Set-CsMeetingConfiguration.md
  skype/skype-ps/skype/Set-CsMeetingConfiguration.md
Labels: Microsoft submitter

#1815 Update Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter, area:exchange

#1820 Text change to the KathleenReiter email address example.
  exchange/exchange-ps/exchange/reporting/Get-UserAnalyticsConfig.md
Labels: Microsoft submitter

#1821 Master to Live
  README.md
  exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/mailboxes/Enable-Mailbox.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/reporting/Get-UserAnalyticsConfig.md
  sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTenantCdnOrigin.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPApp.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPConnection.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUnifiedGroup.md
  sharepoint/sharepoint-ps/sharepoint-pnp/sharepoint-pnp.md
  sharepoint/sharepoint-ps/sharepoint-server/Copy-SPActivitiesToWorkflowService.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPUser.md
  sharepoint/sharepoint-ps/sharepoint-server/Install-SPApplicationContent.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPSecureStoreApplication.md
  sharepoint/sharepoint-ps/sharepoint-server/Register-SPAppPrincipal.md
  sharepoint/sharepoint-ps/sharepoint-server/Remove-SPAppPrincipalPermission.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPCustomLayoutsPage.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPSite.md
  sharepoint/sharepoint-ps/sharepoint-server/Uninstall-SPAppInstance.md
  skype/skype-ps/skype/New-CsMediaConfiguration.md
  skype/skype-ps/skype/Set-CsMeetingConfiguration.md
  teams/teams-ps/teams/New-Team.md
Labels: Microsoft submitter

#1823 Update Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#1824 Corrects a typo: sever -> server
  exchange/exchange-ps/exchange/organization/Get-ExchangeSettings.md
  exchange/exchange-ps/exchange/policy-and-compliance/Get-TransportRule.md
Labels: area:exchange

#1825 remove duplicate line
  sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md
Labels: area:sp-server-powershell

#1835 Update Stop-SPDistributedCacheServiceInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Stop-SPDistributedCacheServiceInstance.md
Labels: area:sp-server-powershell

#1856 typo: Double word "any"
  exchange/exchange-ps/exchange/antispam-antimalware/Set-MalwareFilterPolicy.md
Labels: area:exchange

#1857 typo: Double word "protection"
  exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
Labels: area:exchange

#1855 typo: Double word "can"
  exchange/exchange-ps/exchange/encryption-and-certificates/Set-IRMConfiguration.md
Labels: area:exchange

#1854 typo: Double word "are"
  exchange/exchange-ps/exchange/mail-flow/Set-RemoteDomain.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxSentItemsConfiguration.md
Labels: area:exchange

#1843 typo: Double word "the"
  exchange/docs-conceptual/exchange-server/exchange-management-shell.md
  exchange/exchange-ps/exchange/client-access/Set-ImapSettings.md
  exchange/exchange-ps/exchange/client-access/Set-PopSettings.md
  exchange/exchange-ps/exchange/database-availability-groups/Test-ReplicationHealth.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/New-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-SiteMailboxProvisioningPolicy.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppStateUpdateInterval.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPInternalAppStateUpdateInterval.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPWebApplicationHttpThrottlingMonitor.md
Labels: area:exchange

#1845 typo: Double word "that"
  exchange/exchange-ps/exchange/antispam-antimalware/Get-IPAllowListProvidersConfig.md
  exchange/exchange-ps/exchange/antispam-antimalware/Get-IPBlockListProvidersConfig.md
  exchange/exchange-ps/exchange/antispam-antimalware/Set-IPAllowListProvidersConfig.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Set-SmimeConfig.md
  skype/skype-ps/skype/Test-CsIM.md
Labels: area:exchange

#1871 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter, area:exchange

#1866 Update Get-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#1865 Update Grant-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#1864 Update Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#1867 Update Get-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Get-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#1873 master to live, see commits for details.
  README.md
  exchange/docs-conceptual/exchange-server/exchange-management-shell.md
  exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/antispam-antimalware/Get-IPAllowListProvidersConfig.md
  exchange/exchange-ps/exchange/antispam-antimalware/Get-IPBlockListProvidersConfig.md
  exchange/exchange-ps/exchange/antispam-antimalware/Get-MailboxJunkEmailConfiguration.md
  exchange/exchange-ps/exchange/antispam-antimalware/Set-IPAllowListProvidersConfig.md
  exchange/exchange-ps/exchange/antispam-antimalware/Set-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/client-access/Set-ImapSettings.md
  exchange/exchange-ps/exchange/client-access/Set-PopSettings.md
  exchange/exchange-ps/exchange/database-availability-groups/Test-ReplicationHealth.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Set-IRMConfiguration.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Set-SmimeConfig.md
  exchange/exchange-ps/exchange/mail-flow/Set-RemoteDomain.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxSentItemsConfiguration.md
  exchange/exchange-ps/exchange/organization/Get-ExchangeSettings.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/policy-and-compliance/Get-TransportRule.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/New-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-SiteMailboxProvisioningPolicy.md
  repo_docs/FAQ.md
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
  sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
  sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Test-PnPOffice365GroupAliasIsUsed.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppStateUpdateInterval.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPInternalAppStateUpdateInterval.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPWebApplicationHttpThrottlingMonitor.md
  sharepoint/sharepoint-ps/sharepoint-server/Stop-SPDistributedCacheServiceInstance.md
  skype/skype-ps/skype/Get-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Test-CsIM.md
  tools/office-cmdlet-updater/config/default.json
  tools/office-cmdlet-updater/constants/commands.js
  tools/office-cmdlet-updater/db/index.js
  tools/office-cmdlet-updater/services/log.parse.service.js
  tools/office-cmdlet-updater/services/log.store.service.js
  tools/office-cmdlet-updater/services/markdown.service.js
  tools/office-cmdlet-updater/services/power.shell.service.js
  whiteboard/whiteboard-ps/whiteboard/whiteboard.md
Labels: Microsoft submitter

#1841 Add document for Get/Set-CsOnlineVoicemailUserSettings cmdlets
  skype/skype-ps/skype/Get-CsOnlineVoicemailUserSettings.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md
Labels: Microsoft submitter

#1863 Chrisda to Master
  exchange/exchange-ps/exchange/active-directory/Dump-ProvisioningCache.md
  exchange/exchange-ps/exchange/active-directory/Get-ADPermission.md
  exchange/exchange-ps/exchange/active-directory/Get-DomainController.md
  exchange/exchange-ps/exchange/active-directory/Get-OrganizationalUnit.md
  exchange/exchange-ps/exchange/active-directory/Reset-ProvisioningCache.md
  exchange/exchange-ps/exchange/database-availability-groups/Resume-MailboxDatabaseCopy.md
  exchange/exchange-ps/exchange/database-availability-groups/Set-MailboxDatabaseCopy.md
  exchange/exchange-ps/exchange/database-availability-groups/Suspend-MailboxDatabaseCopy.md
  exchange/exchange-ps/exchange/database-availability-groups/Update-MailboxDatabaseCopy.md
  exchange/exchange-ps/exchange/devices/Set-ActiveSyncOrganizationSettings.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Enable-ExchangeCertificate.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Export-ExchangeCertificate.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Remove-ExchangeCertificate.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Disable-MailboxQuarantine.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Enable-MailboxQuarantine.md
  exchange/exchange-ps/exchange/mailboxes/Enable-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxExportRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxExportRequest.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxImportRequest.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Test-MigrationServerAvailability.md
  exchange/exchange-ps/exchange/organization/Set-ExchangeSettings.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/Get-MailboxSearch.md
Labels: Microsoft submitter

#1859 Corrected syntax error
  sharepoint/sharepoint-ps/sharepoint-pnp/Publish-PnPApp.md
Labels: Microsoft submitter

#1839 Add run guidance.
  tools/office-cmdlet-updater/README.md
Labels: Microsoft submitter, area:tools

#1876 Update Remove-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#1880 Remove 2019 from applicable per Dave Howe.
  skype/skype-ps/skype/Test-CsMcxPushNotification.md
Labels: Microsoft submitter

#1881 Remove 2019 from applicable per Dave Howe.
  skype/skype-ps/skype/Test-CsPersistentChatMessage.md
Labels: Microsoft submitter

#1887 Chrisda to Master
  exchange/exchange-ps/exchange/client-access/Test-OutlookConnectivity.md
  exchange/exchange-ps/exchange/database-availability-groups/Set-MailboxDatabaseCopy.md
  exchange/exchange-ps/exchange/devices/Set-ActiveSyncOrganizationSettings.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/New-EmailAddressPolicy.md
  exchange/exchange-ps/exchange/mail-flow/New-SendConnector.md
  exchange/exchange-ps/exchange/mail-flow/Test-Mailflow.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Set-MailboxServer.md
  exchange/exchange-ps/exchange/mailboxes/Connect-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Remove-UserPhoto.md
  exchange/exchange-ps/exchange/move-and-migration/New-MigrationEndpoint.md
  exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md
  exchange/exchange-ps/exchange/organization/Set-PerimeterConfig.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-MailboxSearch.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Get-ComplianceRetentionEvent.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Get-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/New-ComplianceRetentionEvent.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/New-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Remove-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsAVConferenceTimeReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsActiveUserReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsClientDeviceDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsClientDeviceReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsConferenceReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsP2PAVTimeReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsP2PSessionReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsPSTNConferenceTimeReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsPSTNUsageDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsUserActivitiesReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsUsersBlockedReport.md
  exchange/exchange-ps/exchange/reporting/Get-GroupActivityReport.md
  exchange/exchange-ps/exchange/reporting/Get-LicenseVsUsageSummaryReport.md
  exchange/exchange-ps/exchange/reporting/Get-MailboxActivityReport.md
  exchange/exchange-ps/exchange/reporting/Get-MailboxUsageDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-MailboxUsageReport.md
  exchange/exchange-ps/exchange/reporting/Get-O365ClientBrowserDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-O365ClientBrowserReport.md
  exchange/exchange-ps/exchange/reporting/Get-O365ClientOSDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-O365ClientOSReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOSkyDriveProDeployedReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOSkyDriveProStorageReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOTeamSiteDeployedReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOTeamSiteStorageReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOTenantStorageMetricReport.md
  exchange/exchange-ps/exchange/reporting/Get-StaleMailboxDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-StaleMailboxReport.md
  exchange/exchange-ps/exchange/role-based-access-control/Get-RoleGroup.md
  exchange/exchange-ps/exchange/role-based-access-control/New-ManagementScope.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-PublicFolder.md
  exchange/exchange-ps/exchange/users-and-groups/Enable-MailUser.md
  exchange/exchange-ps/exchange/users-and-groups/Get-MailUser.md
Labels: Microsoft submitter, area:exchange

#1888 Describe behavior of new -role parameter
  teams/teams-ps/teams/Remove-TeamUser.md
Labels: Microsoft submitter

#1895 Merges Master to Live. See commits for details.
  exchange/exchange-ps/exchange/client-access/Test-OutlookConnectivity.md
  exchange/exchange-ps/exchange/database-availability-groups/Set-MailboxDatabaseCopy.md
  exchange/exchange-ps/exchange/devices/Set-ActiveSyncOrganizationSettings.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/New-EmailAddressPolicy.md
  exchange/exchange-ps/exchange/mail-flow/New-SendConnector.md
  exchange/exchange-ps/exchange/mail-flow/Test-Mailflow.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Set-MailboxServer.md
  exchange/exchange-ps/exchange/mailboxes/Connect-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Remove-UserPhoto.md
  exchange/exchange-ps/exchange/move-and-migration/New-MigrationEndpoint.md
  exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md
  exchange/exchange-ps/exchange/organization/Set-PerimeterConfig.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-MailboxSearch.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Get-ComplianceRetentionEvent.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Get-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/New-ComplianceRetentionEvent.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/New-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Remove-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsAVConferenceTimeReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsActiveUserReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsClientDeviceDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsClientDeviceReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsConferenceReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsP2PAVTimeReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsP2PSessionReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsPSTNConferenceTimeReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsPSTNUsageDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsUserActivitiesReport.md
  exchange/exchange-ps/exchange/reporting/Get-CsUsersBlockedReport.md
  exchange/exchange-ps/exchange/reporting/Get-GroupActivityReport.md
  exchange/exchange-ps/exchange/reporting/Get-LicenseVsUsageSummaryReport.md
  exchange/exchange-ps/exchange/reporting/Get-MailboxActivityReport.md
  exchange/exchange-ps/exchange/reporting/Get-MailboxUsageDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-MailboxUsageReport.md
  exchange/exchange-ps/exchange/reporting/Get-O365ClientBrowserDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-O365ClientBrowserReport.md
  exchange/exchange-ps/exchange/reporting/Get-O365ClientOSDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-O365ClientOSReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOSkyDriveProDeployedReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOSkyDriveProStorageReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOTeamSiteDeployedReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOTeamSiteStorageReport.md
  exchange/exchange-ps/exchange/reporting/Get-SPOTenantStorageMetricReport.md
  exchange/exchange-ps/exchange/reporting/Get-StaleMailboxDetailReport.md
  exchange/exchange-ps/exchange/reporting/Get-StaleMailboxReport.md
  exchange/exchange-ps/exchange/role-based-access-control/Get-RoleGroup.md
  exchange/exchange-ps/exchange/role-based-access-control/New-ManagementScope.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-PublicFolder.md
  exchange/exchange-ps/exchange/users-and-groups/Enable-MailUser.md
  exchange/exchange-ps/exchange/users-and-groups/Get-MailUser.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTenant.md
  teams/teams-ps/teams/Remove-TeamUser.md
Labels: Microsoft submitter

#1901 Update Set-DistributionGroup.md
  exchange/exchange-ps/exchange/users-and-groups/Set-DistributionGroup.md
Labels: Microsoft submitter, area:exchange

#1896 Add doc for additional parameters and supported languages
  skype/skype-ps/skype/Get-CsOnlineVoicemailUserSettings.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md
Labels: Microsoft submitter

#1904 Merges Master to Live. See commits for details.
  exchange/docs-conceptual/office-365-scc/office-365-scc-powershell.md
  exchange/exchange-ps/exchange/users-and-groups/Set-DistributionGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  skype/skype-ps/skype/Get-CsOnlineVoicemailUserSettings.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md
Labels: Microsoft submitter

#1918 Chrisda to master
  exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md
  exchange/exchange-ps/exchange/mail-flow/Set-MailboxTransportService.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter

#1914 Updating article to add WebSuggestedReplies
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter

#1913 Update sharepoint-online.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#1911 Create Add-SPOSiteDesignTask
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesignTask.md
Labels: Microsoft submitter

#1919 fixing typo
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubSiteAssociation.md
Labels: Microsoft submitter

#1912 Create Get-SPOSiteScriptFromList
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScriptFromList.md
Labels: Microsoft submitter

#1906 Create Remove-SPOSiteDesignTask
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteDesignTask.md
Labels: Microsoft submitter

#1905 Create Get-SPOSiteDesignTask
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDesignRun.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDesignRunStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDesignTask.md
Labels: Microsoft submitter

#1963 typo: pubic -> public
  skype/skype-ps/skype/Remove-CsPublicProvider.md
Labels: area:skype

#1969 Adds CsOnlineSipDomain cmdlets.
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlineSipDomain.md
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter

#1970 Update Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#1991 Update Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#1993 Update Get-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlineSipDomain.md
Labels: Microsoft submitter

#1998 Fixed example text for "-SkipServer"
  skype/skype-ps/skype/Start-CsPool.md
Labels: area:skype

#1996 Improves the documentation of RequireAcceptingAccountMatchInvitedAccount
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell

#1992 Update Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2002 Merges master to live. See commits for details.
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2003 Update Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#2007 Update Get-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2006 Update Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2005 Update Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#1995 Improves LegacyAuthProtocolsEnabled documentation
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell

#2008 Update Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2009 Merges master to live. See commits for details.
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2011 Fix table.
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2010 Update connect-sharepoint-online.md
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
Labels: area:spo-powershell
