Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2018-11, with the labels that each got.

#2018 Update New-ProtectionAlert.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-ProtectionAlert.md
Labels: Microsoft submitter

#2014 Update connect to exchange online.
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md
Labels: area:exchange

#2021 Small fix in wording
  teams/teams-ps/teams/Remove-TeamUser.md
Labels: area:teams

#2023 Master to Live
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/organization/Get-OrganizationConfig.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-ProtectionAlert.md
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
  teams/teams-ps/teams/Remove-TeamUser.md
  tools/office-cmdlet-updater/README.md
  tools/office-cmdlet-updater/config/default.json
  tools/office-cmdlet-updater/services/fs.service.js
  tools/office-cmdlet-updater/services/markdown.service.js
Labels: Microsoft submitter

#2025 Update Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2042 Update Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2045 Merges Master to Live. See commits for details.
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2051 Update Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2054 Update Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2057 Adds carriage return for item 3.
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2059 Update Set-CsMeetingConfiguration.md
  skype/skype-ps/skype/Set-CsMeetingConfiguration.md
Labels: Microsoft submitter

#2058 Dariomws306 object 3
  skype/skype-ps/skype/Clear-CsOnlineTelephoneNumberReservation.md
  skype/skype-ps/skype/Get-CsAudioConferencingProvider.md
  skype/skype-ps/skype/Get-CsOnlineApplicationEndpoint.md
  skype/skype-ps/skype/Get-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Get-CsTeamsGuestCallingConfiguration.md
  skype/skype-ps/skype/Get-CsTeamsGuestMeetingConfiguration.md
  skype/skype-ps/skype/Get-CsTeamsMeetingBroadcastConfiguration.md
  skype/skype-ps/skype/Get-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/Get-CsTeamsMeetingConfiguration.md
  skype/skype-ps/skype/Get-CsTeamsUpgradeConfiguration.md
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Get-CsUser.md
  skype/skype-ps/skype/Grant-CsDialPlan.md
  skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/New-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/Set-CsMeetingConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsGuestCallingConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsGuestMeetingConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsMeetingBroadcastConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingConfiguration.md
Labels: area:skype

#2060 Update Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2063 Update Get-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2061 Update Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2066 Updates numbered bullets.
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2062 Get-RecoverableItems was backported (E16/E19)
  exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md
Labels: Microsoft submitter, area:exchange

#2070 Update Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2072 Merges Master to Live. See commits for details.
  exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2050 Remove New-UMIPGateway Support in Exchange Online
  exchange/exchange-ps/exchange/unified-messaging/New-UMIPGateway.md
Labels: area:exchange

#2041 Restore-RecoverableItems was backported (E16/E19)
  exchange/exchange-ps/exchange/mailboxes/Restore-RecoverableItems.md
Labels: area:exchange

#2074 Update exchange/exchange-ps/exchange/organization/Set-OrganizationCon…
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter

#2085 Updates to DLP reports cmdlets
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetailReport.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetectionsReport.md
Labels: Microsoft submitter

#2087 Update exchange/exchange-ps/exchange/policy-and-compliance-content-se…
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
Labels: Microsoft submitter

#2082 Update Get-CsOnlineTelephoneNumber.md
  skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md
Labels: Microsoft submitter

#2105 Merges master to live. See commits for details.
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPSiteSubscriptionEdiscoveryHub.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPSite.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPRoutingMachinePool.md
  sharepoint/sharepoint-ps/sharepoint-server/Test-SPProjectServiceApplication.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
  teams/teams-ps/teams/New-Team.md
Labels: Microsoft submitter

#1980 OutVariable usage example added
  exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md
Labels: area:exchange

#2112 Added MiniMaven attribute to select topics
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/exchange-online-powershell.md
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md
  exchange/docs-conceptual/office-365-scc/office-365-scc-powershell.md
Labels: Microsoft submitter

#2113 Master to Live
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/exchange-online-powershell.md
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md
  exchange/docs-conceptual/office-365-scc/office-365-scc-powershell.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
Labels: Microsoft submitter

#2111 tweaked description of 50K mailbox limit
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
Labels: Microsoft submitter

#2118 Updated PhishFilterPolicy cmdlet topics
  exchange/exchange-ps/exchange/advanced-threat-protection/Get-PhishFilterPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-PhishFilterPolicy.md
Labels: Microsoft submitter

#2135 Merges Master to Live. See commits for details.
  exchange/exchange-ps/exchange/advanced-threat-protection/Get-PhishFilterPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-PhishFilterPolicy.md
  exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
  sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPRoleDefinition.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Disable-PnPFeature.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Disable-PnPResponsiveUI.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPLabel.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSiteCollectionAdmin.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUnifiedGroupMembers.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUnifiedGroupOwners.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Grant-PnPTenantServicePrincipalPermission.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Save-PnPProvisioningTemplate.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPField.md
  sharepoint/sharepoint-ps/sharepoint-server/Move-SPSite.md
  sharepoint/sharepoint-ps/sharepoint-server/Remove-SPSiteSubscriptionFeaturePackMember.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  tools/office-cmdlet-updater/README.md
  tools/office-cmdlet-updater/config/default.json
  tools/office-cmdlet-updater/controllers/cli.controller.js
  tools/office-cmdlet-updater/controllers/markdown.controller.js
  tools/office-cmdlet-updater/helpers/di.container.js
  tools/office-cmdlet-updater/index.js
  tools/office-cmdlet-updater/package.json
  tools/office-cmdlet-updater/services/cli.service.js
  tools/office-cmdlet-updater/services/cmdlet.service.js
  tools/office-cmdlet-updater/services/markdown.service.js
Labels: Microsoft submitter

#2136 Updated to ReportOnly parameter
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxExportRequestStatistics.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxImportRequestStatistics.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxRestoreRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-MoveRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMailboxMigrationRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMigrationRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMoveRequestStatistics.md
Labels: Microsoft submitter

#2137 Master to Live
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxExportRequestStatistics.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxImportRequestStatistics.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxRestoreRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-MoveRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMailboxMigrationRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMigrationRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMoveRequestStatistics.md
Labels: Microsoft submitter

#2148 Restore changes.
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#2149 Restores overwritten description.
  skype/skype-ps/skype/Grant-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#2151 Restores overwritten description.
  skype/skype-ps/skype/Remove-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#2150 Reverts overwritten description.
  skype/skype-ps/skype/Get-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#2109 Update Add-SPOGeoAdministrator.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOGeoAdministrator.md
Labels: area:spo-powershell

#2153 Update Get-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#2154 Merges Master to Live. See commits for details.
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOGeoAdministrator.md
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#2097 Update Add-SPOTheme.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTheme.md
Labels: area:spo-powershell

#2096 Update sharepoint-online.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: area:spo-powershell

#2095 Update Set-SPOSiteScript.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteScript.md
Labels: area:spo-powershell

#2141 Chrisda to master
  exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/New-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Remove-Mailbox.md
  exchange/exchange-ps/exchange/organization/Set-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/users-and-groups/Get-User.md
Labels: Microsoft submitter, area:exchange

#2160 Merges Master to Live. See commits for details.
  exchange/docs-conceptual/exchange-server/recipient-filters/recipientfilter-properties.md
  exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/New-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Remove-Mailbox.md
  exchange/exchange-ps/exchange/organization/Set-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/users-and-groups/Get-User.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTheme.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteScript.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#2167 Update disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md
Labels: Microsoft submitter

#2147 Update Set-OrganizationConfig.md. Add descriptions for new parameters for ConnectorsEnabled flag
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter, area:exchange

#2169 Update to indicate t-bot setting is being deprecated
  skype/skype-ps/skype/Set-CsTeamsClientConfiguration.md
Labels: Microsoft submitter

#2172 Publishing latest changes
  exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  skype/skype-ps/skype/Set-CsAddressBookNormalizationConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsClientConfiguration.md
  skype/skype-ps/skype/Set-CsVoiceTestConfiguration.md
Labels: Microsoft submitter

#2168 Update Remove-MigrationBatch.md
  exchange/exchange-ps/exchange/move-and-migration/Remove-MigrationBatch.md
Labels: Microsoft submitter, area:exchange

#2155 Update New-CsPlatformServiceSettings.md
  skype/skype-ps/skype/New-CsPlatformServiceSettings.md
Labels: area:skype

#2184 Chrisda to Master
  exchange/exchange-ps/exchange/federation-and-hybrid/Set-RemoteMailbox.md
  exchange/exchange-ps/exchange/mail-flow/Get-MessageTrace.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxAutoReplyConfiguration.md
  exchange/exchange-ps/exchange/move-and-migration/Remove-MigrationUser.md
  exchange/exchange-ps/exchange/move-and-migration/Remove-PublicFolderMigrationRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Remove-PublicFolderMoveRequest.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/policy-and-compliance/Set-SupervisoryReviewRule.md
Labels: Microsoft submitter

#2197 Update disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md
Labels: Microsoft submitter

#2214 Update Remove-CalendarEvents.md
  exchange/exchange-ps/exchange/mailboxes/Remove-CalendarEvents.md
Labels: Microsoft submitter, area:exchange
