Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2018-09, with the labels that each got.

#1680 Master to Live
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
Labels: Microsoft submitter

#1679 Update Move-CsUser.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#1692 Chrisda to Master
  exchange/exchange-ps/exchange/users-and-groups/Undo-SoftDeletedUnifiedGroup.md
Labels: Microsoft submitter

#1693 Master to Live
  exchange/exchange-ps/exchange/users-and-groups/Undo-SoftDeletedUnifiedGroup.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#1714 Chrisda
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter

#1715 Chrisda to Master
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter

#1716 Update Set-Mailbox.md to add new parameter
  exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md
Labels: Microsoft submitter, area:exchange

#1718 Updating skype.md to allow CAB file to be built
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter

#1720 Updates for CVI cmdlet documentation
  skype/skype-ps/skype/Get-CsTeamsVideoInteropServicePolicy.md
  skype/skype-ps/skype/Get-CsVideoInteropServiceProvider.md
  skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md
  skype/skype-ps/skype/New-CsVideoInteropServiceProvider.md
  skype/skype-ps/skype/Remove-CsVideoInteropServiceProvider.md
  skype/skype-ps/skype/Set-CsVideoInteropServiceProvider.md
Labels: Microsoft submitter

#1730 Updates to *-RemoteDomain cmdlets
  exchange/exchange-ps/exchange/mail-flow/Get-RemoteDomain.md
  exchange/exchange-ps/exchange/mail-flow/New-RemoteDomain.md
  exchange/exchange-ps/exchange/mail-flow/Remove-RemoteDomain.md
  exchange/exchange-ps/exchange/mail-flow/Set-RemoteDomain.md
Labels: Microsoft submitter

#1737 Chrisda to Master
  exchange/exchange-ps/exchange/advanced-threat-protection/Disable-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Enable-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Remove-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Remove-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/client-access-servers/New-WebServicesVirtualDirectory.md
  exchange/exchange-ps/exchange/client-access-servers/Set-OwaVirtualDirectory.md
  exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/mail-flow/New-InboundConnector.md
  exchange/exchange-ps/exchange/mail-flow/Set-InboundConnector.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxSentItemsConfiguration.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-TeamsRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroup.md
  exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter

#1738 Master to Live
  exchange/exchange-ps/exchange/advanced-threat-protection/Disable-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Enable-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Remove-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Remove-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishRule.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/client-access-servers/New-WebServicesVirtualDirectory.md
  exchange/exchange-ps/exchange/client-access-servers/Set-OwaVirtualDirectory.md
  exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/mail-flow/Get-RemoteDomain.md
  exchange/exchange-ps/exchange/mail-flow/New-InboundConnector.md
  exchange/exchange-ps/exchange/mail-flow/New-RemoteDomain.md
  exchange/exchange-ps/exchange/mail-flow/Remove-RemoteDomain.md
  exchange/exchange-ps/exchange/mail-flow/Set-InboundConnector.md
  exchange/exchange-ps/exchange/mail-flow/Set-MailboxTransportService.md
  exchange/exchange-ps/exchange/mail-flow/Set-RemoteDomain.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxSentItemsConfiguration.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-TeamsRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroup.md
  exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter

#1742 Update Set-CsAuthConfig.md
  skype/skype-ps/skype/Set-CsAuthConfig.md
Labels: Microsoft submitter, area:skype

#1746 Chrisda to Master
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/client-access/Get-CASMailboxPlan.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxLocation.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxPlan.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/role-based-access-control/Add-ManagementRoleEntry.md
  exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRole.md
  exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/role-based-access-control/Remove-ManagementRole.md
  exchange/exchange-ps/exchange/role-based-access-control/Set-ManagementRoleEntry.md
  exchange/exchange-ps/exchange/users-and-groups/Get-Recipient.md
  repo_docs/NEW_CMDLETS.md
Labels: Microsoft submitter

#1747 Updates to New/Set-SupervisoryReviewPolicy
  exchange/exchange-ps/exchange/policy-and-compliance/New-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/policy-and-compliance/Set-SupervisoryReviewRule.md
Labels: Microsoft submitter

#1748 Master to Live
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/client-access/Get-CASMailboxPlan.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxLocation.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxPlan.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/policy-and-compliance/Set-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/role-based-access-control/Add-ManagementRoleEntry.md
  exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRole.md
  exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/role-based-access-control/Remove-ManagementRole.md
  exchange/exchange-ps/exchange/role-based-access-control/Set-ManagementRoleEntry.md
  exchange/exchange-ps/exchange/users-and-groups/Get-Recipient.md
  repo_docs/NEW_CMDLETS.md
Labels: Microsoft submitter

#1749 Updates to New-MailUser
  exchange/exchange-ps/exchange/users-and-groups/New-MailUser.md
Labels: Microsoft submitter

#1745 Update New-MoveRequest.md
  exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md
Labels: area:exchange

#1762 Update Set-CsAuthConfig.md
  skype/skype-ps/skype/Set-CsAuthConfig.md
Labels: Microsoft submitter

#1767 Merges Master to Live. See commits for details.
  exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/Set-DlpSensitiveInformationTypeRulePackage.md
  exchange/exchange-ps/exchange/users-and-groups/New-MailUser.md
  skype/skype-ps/skype/New-CSOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CSOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsAuthConfig.md
  tools/README.md
  tools/microsoft-teams-generator-tool/.eslintrc
  tools/microsoft-teams-generator-tool/.gitignore
  tools/microsoft-teams-generator-tool/.prettierrc
  tools/microsoft-teams-generator-tool/README.md
  tools/microsoft-teams-generator-tool/config/default.json
  tools/microsoft-teams-generator-tool/constants/commands.js
  tools/microsoft-teams-generator-tool/constants/errors.js
  tools/microsoft-teams-generator-tool/controllers/markdown.controller.js
  tools/microsoft-teams-generator-tool/db/index.js
  tools/microsoft-teams-generator-tool/helpers/di.container.js
  tools/microsoft-teams-generator-tool/index.js
  tools/microsoft-teams-generator-tool/package.json
  tools/microsoft-teams-generator-tool/services/log.parse.service.js
  tools/microsoft-teams-generator-tool/services/log.store.service.js
  tools/microsoft-teams-generator-tool/services/mail.notification.service.js
  tools/microsoft-teams-generator-tool/services/markdown.service.js
  tools/microsoft-teams-generator-tool/services/power.shell.service.js
Labels: Microsoft submitter

#1770 Update Get-MailTrafficATPReport.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Get-MailTrafficATPReport.md
Labels: Microsoft submitter, area:exchange

#1771 Update Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Get-MailDetailATPReport.md
Labels: Microsoft submitter, area:exchange

#1772 Update Start-HistoricalSearch.md
  exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md
Labels: Microsoft submitter, area:exchange

#1773 Chrisda to Master
  exchange/exchange-ps/exchange/client-access/Test-CalendarConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-EcpConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-ImapConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-PopConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-PowerShellConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-WebServicesConnectivity.md
  exchange/exchange-ps/exchange/devices/Test-ActiveSyncConnectivity.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxExportRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxImportRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/unified-messaging/Test-UMConnectivity.md
Labels: Microsoft submitter

#1774 Master to Live
  exchange/exchange-ps/exchange/advanced-threat-protection/Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Get-MailTrafficATPReport.md
  exchange/exchange-ps/exchange/client-access/Test-CalendarConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-EcpConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-ImapConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-PopConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-PowerShellConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-WebServicesConnectivity.md
  exchange/exchange-ps/exchange/devices/Test-ActiveSyncConnectivity.md
  exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxExportRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxImportRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/unified-messaging/Test-UMConnectivity.md
Labels: Microsoft submitter

#1775 Remove WhatIf parameter from Set-CASMailboxPlan
  exchange/exchange-ps/exchange/client-access/set-CASMailboxPlan.md
Labels: area:exchange

#1780 Chrisda to Master
  exchange/exchange-ps/exchange/antispam-antimalware/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/antispam-antimalware/New-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/mailboxes/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxExportRequest.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxImportRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxExportRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxImportRequest.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/New-RetentionPolicyTag.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-RetentionPolicyTag.md
  exchange/exchange-ps/exchange/server-health-and-performance/Get-ThrottlingPolicyAssociation.md
  exchange/exchange-ps/exchange/server-health-and-performance/New-ThrottlingPolicy.md
  exchange/exchange-ps/exchange/server-health-and-performance/Set-ThrottlingPolicy.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Add-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/unified-messaging/Export-UMPrompt.md
  exchange/exchange-ps/exchange/unified-messaging/New-UMDialPlan.md
  exchange/exchange-ps/exchange/unified-messaging/Set-UMAutoAttendant.md
Labels: Microsoft submitter

#1789 Updates to HiddenFromExchangeClientsEnabled param in Set-UnifiedGroup
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter

#1790 Master to Live
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter
