Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2018-12, with the labels that each got.

#2211 Corrected minor typo + markdown bug
  skype/skype-ps/skype/Grant-CsVoiceRoutingPolicy.md
Labels: area:skype

#2210 Minor typos + changed -whatif description
  skype/skype-ps/skype/Grant-CsTenantDialPlan.md
Labels: area:skype

#2209 Minor typo corrections.
  skype/skype-ps/skype/Grant-CsThirdPartyVideoSystemPolicy.md
Labels: area:skype

#2208 Minor typos & grammar fix-up.
  skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md
Labels: area:skype

#2207 Minor typo & grammar corrections.
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: area:skype

#2205 Corrected minor typo
  skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md
Labels: area:skype

#2206 Minor typo and MD formatting corrections.
  skype/skype-ps/skype/Grant-CsTeamsInteropPolicy.md
Labels: area:skype

#2204 Corrected tiny typo
  skype/skype-ps/skype/Set-CsPersistentChatRoom.md
Labels: area:skype

#2203 Fixed small typo
  skype/skype-ps/skype/Set-CsPersistentChatCategory.md
Labels: area:skype

#2189 Update Set-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#2198 Adding in update for new-team, which is going out
  teams/teams-ps/teams/New-Team.md
Labels: Microsoft submitter

#2200 Update New-CSOnlinePSTNGateway.md
  skype/skype-ps/skype/New-CSOnlinePSTNGateway.md
Labels: Microsoft submitter

#2201 Update Set-CSOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CSOnlinePSTNGateway.md
Labels: Microsoft submitter

#2229 Update Update-SPRepopulateMicroblogFeedCache.md
  sharepoint/sharepoint-ps/sharepoint-server/Update-SPRepopulateMicroblogFeedCache.md
Labels: area:sp-server-powershell

#2216 Update Set-SPUser.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPUser.md
Labels: area:sp-server-powershell

#2238 Merges Master to Live. See commits for details.
  exchange/exchange-ps/exchange/mailboxes/Remove-CalendarEvents.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHubSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPSubscriptionSettingsServiceApplication.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPUser.md
  sharepoint/sharepoint-ps/sharepoint-server/Update-SPRepopulateMicroblogFeedCache.md
  skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md
  skype/skype-ps/skype/Grant-CsTenantDialPlan.md
  skype/skype-ps/skype/Grant-CsThirdPartyVideoSystemPolicy.md
  skype/skype-ps/skype/Grant-CsVoiceRoutingPolicy.md
  skype/skype-ps/skype/New-CSOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CSOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsPersistentChatCategory.md
  skype/skype-ps/skype/Set-CsPersistentChatRoom.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/New-Team.md
Labels: Microsoft submitter

#2242 Update Get-MobileDeviceStatistics.md
  exchange/exchange-ps/exchange/devices/Get-MobileDeviceStatistics.md
Labels: Microsoft submitter

#2247 Update Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#2251 Update Remove-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#2250 Update Get-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Get-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#2249 Update Grant-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#2248 Update Get-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#2246 Update Connect-SPOService.md
  sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md
Labels: area:spo-powershell

#2254 Merges Master to Live. See commits for details.
  exchange/exchange-ps/exchange/devices/Get-MobileDeviceStatistics.md
  sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOExternalUser.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHubSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md
  skype/skype-ps/skype/Get-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Remove-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Test-CsFederatedPartner.md
Labels: Microsoft submitter

#2255 Merges Master to Live. See commits for details.
  skype/skype-ps/skype/New-CsClsScenario.md
Labels: Microsoft submitter

#2260 Corrected MD bugs
  skype/skype-ps/skype/Set-CsCallViaWorkPolicy.md
Labels: area:skype

#2259 Corrected a markdown bug.
  skype/skype-ps/skype/Set-CsBusyOptions.md
Labels: area:skype

#2271 Update Get-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2270 Update Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2269 Update Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2191 Update Get-SPOHubSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHubSite.md
Labels: area:spo-powershell

#2275 Merges master to live. see commits.
  exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHubSite.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlineSipDomain.md
  skype/skype-ps/skype/Set-CsBusyOptions.md
  skype/skype-ps/skype/Set-CsCallViaWorkPolicy.md
  skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md
Labels: Microsoft submitter

#2228 Adding documentation for new SfB Voice Apps' cmdlets
  skype/skype-ps/skype/Export-CsAutoAttendantHolidays.md
  skype/skype-ps/skype/Find-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Get-CsAutoAttendant.md
  skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md
  skype/skype-ps/skype/Get-CsAutoAttendantStatus.md
  skype/skype-ps/skype/Get-CsAutoAttendantSupportedLanguage.md
  skype/skype-ps/skype/Get-CsAutoAttendantSupportedTimeZone.md
  skype/skype-ps/skype/Get-CsAutoAttendantTenantInformation.md
  skype/skype-ps/skype/Get-CsOnlineApplicationInstanceAssociation.md
  skype/skype-ps/skype/Get-CsOnlineApplicationInstanceAssociationStatus.md
  skype/skype-ps/skype/Get-CsOnlineSchedule.md
  skype/skype-ps/skype/Import-CsAutoAttendantHolidays.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/New-CsAutoAttendant.md
  skype/skype-ps/skype/New-CsAutoAttendantCallFlow.md
  skype/skype-ps/skype/New-CsAutoAttendantCallHandlingAssociation.md
  skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md
  skype/skype-ps/skype/New-CsAutoAttendantDialScope.md
  skype/skype-ps/skype/New-CsAutoAttendantMenu.md
  skype/skype-ps/skype/New-CsAutoAttendantMenuOption.md
  skype/skype-ps/skype/New-CsAutoAttendantPrompt.md
  skype/skype-ps/skype/New-CsOnlineApplicationInstanceAssociation.md
  skype/skype-ps/skype/New-CsOnlineAudioFile.md
  skype/skype-ps/skype/New-CsOnlineSchedule.md
  skype/skype-ps/skype/Remove-CsAutoAttendant.md
  skype/skype-ps/skype/Remove-CsOnlineApplicationInstanceAssociation.md
  skype/skype-ps/skype/Remove-CsOnlineSchedule.md
  skype/skype-ps/skype/Set-CsAutoAttendant.md
  skype/skype-ps/skype/Set-CsOnlineSchedule.md
  skype/skype-ps/skype/Update-CsAutoAttendant.md
Labels: area:skype

#2281 Updates for call park policy
  skype/skype-ps/skype/Get-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallParkPolicy.md
  teams/teams-ps/teams/Get-Team.md
Labels: Microsoft submitter

#2277 Update to the cmdlet per new changes
  exchange/exchange-ps/exchange/reporting/Get-SupervisoryReviewActivity.md
Labels: Microsoft submitter

#2290 Update TOC for call park policy cmdlets
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter

#2289 Merges Master to Live. See commits for details.
  sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPUPABulkImportJob.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPEnterpriseSearchService.md
  skype/skype-ps/skype/Get-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/skype.md
  teams/teams-ps/teams/Get-Team.md
Labels: Microsoft submitter

#2291 Added important note about the MOERA addresses
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter, area:exchange

#2295 Chrisda to master
  exchange/exchange-ps/exchange/email-addresses-and-address-books/New-OfflineAddressBook.md
  sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPUPABulkImportJob.md
Labels: Microsoft submitter

#2265 Update Remove-SyncMailPublicFolder.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Remove-SyncMailPublicFolder.md
Labels: area:exchange

#2266 Update New-SyncMailPublicFolder.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/New-SyncMailPublicFolder.md
Labels: area:exchange

#2287 Applies to was incorrect
  exchange/exchange-ps/exchange/mailboxes/Restore-RecoverableItems.md
Labels: Microsoft submitter, area:exchange

#2286 Update: Applies was incorrect
  exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md
Labels: Microsoft submitter, area:exchange

#2288 Update Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/mailboxes/Restore-RecoverableItems.md
Labels: Microsoft submitter, area:exchange

#2296 Update Remove-CalendarEvents.md
  exchange/exchange-ps/exchange/mailboxes/Remove-CalendarEvents.md
Labels: Microsoft submitter

#2297 Update Set-UnifiedGroup.md
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter

#2305 Add note to description too.
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2307 Merges Master to Live. See commits for details.
  exchange/exchange-ps/exchange/email-addresses-and-address-books/New-OfflineAddressBook.md
  exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/mailboxes/Remove-CalendarEvents.md
  exchange/exchange-ps/exchange/mailboxes/Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/New-SyncMailPublicFolder.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Remove-SyncMailPublicFolder.md
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
  sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPUPABulkImportJob.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/New-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Remove-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Remove-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
Labels: Microsoft submitter

#2310 Update Get-ActiveSyncDeviceStatistics.md
  exchange/exchange-ps/exchange/devices/Get-ActiveSyncDeviceStatistics.md
Labels: Microsoft submitter

#2311 Update for Example 1 after review with PM
  exchange/exchange-ps/exchange/reporting/Get-SupervisoryReviewActivity.md
Labels: Microsoft submitter

#2312 Adds related link and moves not to description from synopsis.
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#2219 Set-SPOTenant: Revise the description for DisabledWebPartIds param
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter, area:spo-powershell

#2194 Update Revoke-SPOHubSiteRights.md
  sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOHubSiteRights.md
Labels: area:spo-powershell

#2190 Docfix for DisabledWebPartIds in Set-SPOTenant
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell

#2313 Merges Master to Live. see commits for details.
  exchange/exchange-ps/exchange/devices/Get-ActiveSyncDeviceStatistics.md
  sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOHubSiteRights.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
  skype/skype-ps/skype/Set-CsOnlineVoiceUser.md
Labels: Microsoft submitter

#2341 Merges Master to Live. See commits for details.
  skype/skype-ps/skype/Set-CsWatcherNodeConfiguration.md
Labels: Microsoft submitter

#2342 Teams Calling Policy
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter

#2352 Calling Policy update
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter

#2354 Adds links to finding and using the module.
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter

#2356 Update Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#2357 Update Get-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#2361 Merged Master to Live. See commits for details.
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#2343 Update exchange-management-shell.md
  exchange/docs-conceptual/exchange-server/exchange-management-shell.md
Labels: area:exchange

#2345 Chrisda to Master
  exchange/exchange-ps/exchange/client-access/Get-CASMailboxPlan.md
  exchange/exchange-ps/exchange/client-access/set-CASMailboxPlan.md
  exchange/exchange-ps/exchange/devices/New-DeviceTenantRule.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxAutoReplyConfiguration.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxPlan.md
  exchange/exchange-ps/exchange/mailboxes/New-SiteMailbox.md
  exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxPlan.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Get-SiteMailbox.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Get-SiteMailboxDiagnostics.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Get-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/New-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Remove-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-SiteMailbox.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Test-SiteMailbox.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Update-SiteMailbox.md
  exchange/exchange-ps/exchange/users-and-groups/New-MailUser.md
  exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter
