Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2019-06, with the labels that each got.

#3496 Patch 16
  skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
Labels: area:skype, area:teams

#3499 Changed Alias to MailNickName
  teams/teams-ps/teams/Get-Team.md
Labels: area:skype, area:teams

#3495 Merges Master to Live. See commits for details.
  skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Get-Team.md
Labels: Microsoft submitter

#3500 Moving roll out text to top of content
  sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md
Labels: area:spo-powershell

#3503 Publishing master with updated status
  sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md
Labels: Microsoft submitter

#3400 Updated sample to work with two factor authentication
  sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md
Labels: area:spo-powershell

#3466 Add additional example
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPCustomAction.md
Labels: area:pnp-powershell

#3440 Changed to Get-SPOGeoCrossMoveCompatibilityStatus
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoMoveCompatibilityStatus.md
Labels: area:spo-powershell

#3504 Publish latest changes to live
  sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoMoveCompatibilityStatus.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPCustomAction.md
Labels: Microsoft submitter

#3506 Update Set-CsUser.md
  skype/skype-ps/skype/Set-CsUser.md
Labels: Microsoft submitter, area:skype, area:teams

#3505 Added an example querying Calendar perms
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxFolderPermission.md
Labels: area:exchange

#3497 Update connect-to-scc-powershell.md
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md
Labels: area:exchange

#3501 Added EnableUnauthenticatedSender param
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
Labels: area:exchange

#3509 Removed AddtoLatestVersion example
  sharepoint/sharepoint-ps/sharepoint-server/Install-SPSolution.md
Labels: area:sp-server-powershell

#3510 Update Set-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
Labels: area:skype, area:teams

#3511 Update New-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/New-CsOnlineApplicationInstance.md
Labels: area:skype, area:teams

#3516 Merge Master to Live. See commits for details.
  .openpublishing.publish.config.json
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxFolderPermission.md
  sharepoint/sharepoint-ps/sharepoint-server/Install-SPSolution.md
  skype/skype-ps/skype/New-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
Labels: Microsoft submitter

#3518 Chrisda to Master
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/mailboxes/Get-Clutter.md
  exchange/exchange-ps/exchange/mailboxes/Get-FocusedInbox.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxLocation.md
  exchange/exchange-ps/exchange/mailboxes/Set-Clutter.md
  exchange/exchange-ps/exchange/mailboxes/Set-FocusedInbox.md
  exchange/exchange-ps/exchange/organization/Get-ExchangeDiagnosticInfo.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter

#3519 Master to Live
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/mailboxes/Get-Clutter.md
  exchange/exchange-ps/exchange/mailboxes/Get-FocusedInbox.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxLocation.md
  exchange/exchange-ps/exchange/mailboxes/Set-Clutter.md
  exchange/exchange-ps/exchange/mailboxes/Set-FocusedInbox.md
  exchange/exchange-ps/exchange/organization/Get-ExchangeDiagnosticInfo.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter

#3527 Update Move-CsRgsConfiguration.md
  skype/skype-ps/skype/Move-CsRgsConfiguration.md
Labels: area:skype, area:teams

#3514 Added better description for -Url parameter
  sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPWeb.md
Labels: area:pnp-powershell

#3531 Update New-DlpEdmSschema.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpEdmSschema.md
Labels: Microsoft submitter

#3532 Update New-DlpEdmSschema.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpEdmSschema.md
Labels: Microsoft submitter

#3525 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
Labels: Microsoft submitter, area:exchange

#3538 Update Get-SPOGeoMoveCompatibilityStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoMoveCompatibilityStatus.md
Labels: Microsoft submitter

#3537 Updates to New/Set-AntiPhisPolicy cmdlets
  exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
Labels: Microsoft submitter

#3533 Update Get-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroupLinks.md
Labels: area:exchange

#3539 Master to Live
  exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroupLinks.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoMoveCompatibilityStatus.md
  sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPWeb.md
  skype/skype-ps/skype/Move-CsRgsConfiguration.md
  skype/skype-ps/skype/Set-CsMediaConfiguration.md
Labels: Microsoft submitter

#3555 Merges Master to Live. See commits for details.
  skype/skype-ps/skype/Get-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsInteropPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsInteropPolicy.md
Labels: Microsoft submitter

#3564 Update Set-Team.md
  teams/teams-ps/teams/Set-Team.md
Labels: Microsoft submitter

#3563 Update Set-Team.md
  teams/teams-ps/teams/Set-Team.md
Labels: Microsoft submitter

#3562 Update New-Team.md
  teams/teams-ps/teams/New-Team.md
Labels: Microsoft submitter

#3567 updated search-mailbox as per work item 118875008
  exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md
Labels: Microsoft submitter

#3561 Update Get-InformationBarrierPoliciesApplicationStatus.md
  exchange/exchange-ps/exchange/policy-and-compliance/Get-InformationBarrierPoliciesApplicationStatus.md
Labels: Microsoft submitter

#3560 Update Get-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/policy-and-compliance/Get-InformationBarrierPolicy.md
Labels: Microsoft submitter

#3559 Update Get-InformationBarrierRecipientStatus.md
  exchange/exchange-ps/exchange/policy-and-compliance/Get-InformationBarrierRecipientStatus.md
Labels: Microsoft submitter

#3558 Update Start-InformationBarrierPoliciesApplication.md
  exchange/exchange-ps/exchange/policy-and-compliance/Start-InformationBarrierPoliciesApplication.md
Labels: Microsoft submitter

#3557 Update Set-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/policy-and-compliance/Set-InformationBarrierPolicy.md
Labels: Microsoft submitter

#3556 Update New-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-InformationBarrierPolicy.md
Labels: Microsoft submitter

#3547 Update Clear-MobileDevice.md
  exchange/exchange-ps/exchange/devices/Clear-MobileDevice.md
Labels: Microsoft submitter, area:exchange

#3545 Update Remove-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/users-and-groups/Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/users-and-groups/Remove-UnifiedGroupLinks.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md
Labels: Microsoft submitter, area:exchange, area:sp-server-powershell

#3572 Update Get-MessageTraceDetail.md
  exchange/exchange-ps/exchange/mail-flow/Get-MessageTraceDetail.md
Labels: Microsoft submitter

#3360 Corrected private key requirement
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPTrustedRootAuthority.md
Labels: Microsoft submitter, area:sp-server-powershell

#3535 Update Split-SPScaleOutDatabase.md
  sharepoint/sharepoint-ps/sharepoint-server/Split-SPScaleOutDatabase.md
Labels: area:sp-server-powershell

#3574 Patch 20
  skype/skype-ps/skype/New-CsAutoAttendant.md
Labels: area:skype, area:teams

#3576 Update New-OrganizationSegment.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-OrganizationSegment.md
Labels: Microsoft submitter, area:exchange

#3577 Update Remove-OrganizationSegment.md
  exchange/exchange-ps/exchange/policy-and-compliance/Remove-OrganizationSegment.md
Labels: Microsoft submitter, area:exchange

#3578 Update Set-OrganizationSegment.md
  exchange/exchange-ps/exchange/policy-and-compliance/Set-OrganizationSegment.md
Labels: Microsoft submitter, area:exchange

#3575 Update Export-AutoDiscoverConfig.md
  exchange/exchange-ps/exchange/client-access/Export-AutoDiscoverConfig.md
Labels: area:exchange

#3582 Merges Master to Live. See commits for details.
  exchange/exchange-ps/exchange/client-access/Export-AutoDiscoverConfig.md
  exchange/exchange-ps/exchange/devices/Clear-MobileDevice.md
  exchange/exchange-ps/exchange/mail-flow/Get-MessageTraceDetail.md
  exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md
  exchange/exchange-ps/exchange/users-and-groups/Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/users-and-groups/Remove-UnifiedGroupLinks.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPTrustedRootAuthority.md
  sharepoint/sharepoint-ps/sharepoint-server/Split-SPScaleOutDatabase.md
  skype/skype-ps/skype/New-CsAutoAttendant.md
  teams/teams-ps/teams/New-Team.md
  teams/teams-ps/teams/Set-Team.md
Labels: Microsoft submitter

#3585 get-spcontentdatabase change
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPContentDatabase.md
  sharepoint/sharepoint-ps/sharepoint-server/Update-SPProfileSync.md
Labels: Microsoft submitter

#3588 Add Get-Help documentation for (Add, Set, Get, Remove)-SPOOrgAssetsLi…
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: area:spo-powershell

#3593 Merges Master to Live. See commits for details.
  sharepoint/docfx.json
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
  sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md
Labels: Microsoft submitter

#3591 Added missing details
  skype/skype-ps/skype/Get-CsAdditionalInternalDomain.md
Labels: area:skype, area:teams

#3590 Update New-CsAutoAttendant.md
  skype/skype-ps/skype/New-CsAutoAttendant.md
Labels: area:skype, area:teams

#3602 App Permission placeholder docs
  skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/New-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md
Labels: Microsoft submitter

#3596 Corrected example 2
  exchange/exchange-ps/exchange/role-based-access-control/Remove-ManagementRoleEntry.md
Labels: area:exchange

#3583 Corrected example 1
  exchange/exchange-ps/exchange/devices/Set-DeviceConditionalAccessRule.md
Labels: area:exchange

#3604 added WorkplaceAnalytics to RecordType value in Search-UnifiedAuditLog
  exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md
Labels: Microsoft submitter

#3599 Update Set-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxFolderPermission.md
Labels: area:exchange

#3601 Update Set-CASMailbox.md to include changes to PublicFolderClientAccess
  exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md
Labels: area:exchange

#3605 Changed RecordType type value to AuditRecordType
  exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-ActivityAlert.md
  exchange/exchange-ps/exchange/policy-and-compliance/Set-ActivityAlert.md
Labels: Microsoft submitter

#3614 Master to Live
  exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md
  exchange/exchange-ps/exchange/devices/Set-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-ActivityAlert.md
  exchange/exchange-ps/exchange/policy-and-compliance/Set-ActivityAlert.md
  exchange/exchange-ps/exchange/role-based-access-control/Remove-ManagementRoleEntry.md
  skype/skype-ps/skype/Get-CsAdditionalInternalDomain.md
  skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/New-CsAutoAttendant.md
  skype/skype-ps/skype/New-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md
Labels: Microsoft submitter

#3598 Added an example
  skype/skype-ps/skype/Set-CsUser.md
Labels: area:skype

#3610 Update Grant-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppPermissionPolicy.md
Labels: Microsoft submitter

#3609 Update New-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/New-CsTeamsAppPermissionPolicy.md
Labels: Microsoft submitter

#3611 Update Remove-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsAppPermissionPolicy.md
Labels: Microsoft submitter

#3607 Update Get-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
Labels: Microsoft submitter

#3608 Update Set-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md
Labels: Microsoft submitter

#3615 Adding in app permission policy docs
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter

#3623 Pushing master -> live
  skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/New-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Set-CsUser.md
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter

#3625 Merges Master to Live. See commits for details.
  sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md
Labels: Microsoft submitter
