Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2019-04, with the labels that each got.

#3163 H1 missing a needed space
  skype/docs-conceptual/intro.md
Labels: Microsoft submitter

#3178 Update intro.md
  teams/docs-conceptual/intro.md
Labels: Microsoft submitter

#3180 Update Set-OMEConfiguration.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md
Labels: area:exchange

#3164 Minor edit to make it more clear (per escalation)
  exchange/exchange-ps/exchange/mailboxes/New-SweepRule.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/New-RetentionPolicyTag.md
Labels: Microsoft submitter, area:exchange

#3196 Update Set-SPOOrgNewsSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOOrgNewsSite.md
Labels: area:spo-powershell

#3199 Update Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/client-access/Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/database-availability-groups/Add-MailboxDatabaseCopy.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/New-OfflineAddressBook.md
  exchange/exchange-ps/exchange/mail-flow/Test-Mailflow.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Clean-MailboxDatabase.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Get-FailedContentIndexDocuments.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Get-MailboxDatabase.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Get-MailboxRepairRequest.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Move-DatabasePath.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/New-MailboxDatabase.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/New-MailboxRepairRequest.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Remove-MailboxDatabase.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Remove-StoreMailbox.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Set-MailboxDatabase.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Test-ExchangeSearch.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Update-DatabaseSchema.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Update-StoreMailboxState.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxExportRequest.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxExportRequestStatistics.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxImportRequest.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxImportRequestStatistics.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxRestoreRequestStatistics.md
  exchange/exchange-ps/exchange/mailboxes/Get-MailboxStatistics.md
  exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/mailboxes/New-SiteMailbox.md
  exchange/exchange-ps/exchange/mailboxes/Remove-MailboxExportRequest.md
  exchange/exchange-ps/exchange/mailboxes/Remove-MailboxImportRequest.md
  exchange/exchange-ps/exchange/mailboxes/Remove-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/mailboxes/Restore-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Test-MAPIConnectivity.md
  exchange/exchange-ps/exchange/move-and-migration/Get-MoveRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Get-MoveRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMailboxMigrationRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMailboxMigrationRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMigrationRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMigrationRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMoveRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMoveRequestStatistics.md
  exchange/exchange-ps/exchange/move-and-migration/New-MigrationBatch.md
  exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md
  exchange/exchange-ps/exchange/move-and-migration/New-PublicFolderMigrationRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Remove-MoveRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Remove-PublicFolderMailboxMigrationRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Remove-PublicFolderMigrationRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Remove-PublicFolderMoveRequest.md
  exchange/exchange-ps/exchange/move-and-migration/Set-MigrationBatch.md
  exchange/exchange-ps/exchange/move-and-migration/Set-MoveRequest.md
  exchange/exchange-ps/exchange/role-based-access-control/Get-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/role-based-access-control/New-ManagementScope.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Get-PublicFolderDatabase.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/New-PublicFolderDatabaseRepairRequest.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Remove-PublicFolderDatabase.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-PublicFolder.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-PublicFolderDatabase.md
  exchange/exchange-ps/exchange/users-and-groups/Get-Recipient.md
Labels: Microsoft submitter

#3201 update set-owamailboxpolicy
  exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#3203 Chrisda to Master
  exchange/exchange-ps/exchange/mail-flow/Set-RemoteDomain.md
  exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/mailboxes/Restore-RecoverableItems.md
Labels: Microsoft submitter

#3208 Update Get-RecoverableItems.md
  exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md
Labels: Microsoft submitter, area:exchange

#3207 Update Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/mailboxes/Restore-RecoverableItems.md
Labels: area:exchange

#3209 Update Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter, area:exchange

#3126 Update New-SPAccessServicesApplication.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPAccessServicesApplication.md
Labels: area:sp-server-powershell

#3127 Update Set-SPAccessServicesDatabaseServerGroupMapping.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPAccessServicesDatabaseServerGroupMapping.md
Labels: area:sp-server-powershell

#3128 Update Set-SPAccessServicesDatabaseServer.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPAccessServicesDatabaseServer.md
Labels: area:sp-server-powershell

#3129 Update Set-SPAccessServicesApplication.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPAccessServicesApplication.md
Labels: area:sp-server-powershell

#3130 Update New-SPAccessServicesDatabaseServer.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPAccessServicesDatabaseServer.md
Labels: area:sp-server-powershell

#3213 Update Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#3214 Update Get-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#3172 Update Connect-PnPMicrosoftGraph.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPMicrosoftGraph.md
Labels: area:pnp-powershell

#3173 Update Connect-PnPOnline.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md
Labels: area:pnp-powershell

#3174 Update Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: area:spo-powershell

#3184 URL in HTTPS
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md
Labels: area:spo-powershell

#3185 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter, area:spo-powershell

#3186 Update Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter, area:spo-powershell

#3187 Update Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter, area:spo-powershell

#3218 Removed duplicate -Identity description
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
Labels: area:spo-powershell

#3198 Update Get-PnPTermSet.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTermSet.md
Labels: area:pnp-powershell

#3222 Fixing Set-SPOSite.md to megabytes
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#3223 Merging latest updates to live
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPMicrosoftGraph.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTermSet.md
Labels: Microsoft submitter

#3225 Update Set-CsCallQueue.md
  skype/skype-ps/skype/Set-CsCallQueue.md
Labels: area:skype

#3215 Update Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-RetentionCompliancePolicy.md
Labels: area:exchange

#3233 Add files via upload
  Get-CsInboundBlockedNumberPattern.md
  Get-CsTenantBlockedNumberExceptionPattern.md
  New-CsInboundBlockedNumberPattern.md
  New-CsTenantBlockedNumberExceptionPattern.md
  Remove-CsInboundBlockedNumberPattern.md
  Remove-CsTenantBlockedNumberExceptionPattern.md
  Set-CsInboundBlockedNumberPattern.md
  Set-CsTenantBlockedNumberExceptionPattern.md
  Test-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Get-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/New-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Remove-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Set-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Test-CsInboundBlockedNumberPattern.md
Labels: Microsoft submitter, area:skype

#3239 Updates metadata.
  repo_docs/FAQ.md
Labels: Microsoft submitter

#3240 Chrisda to Master
  exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/reporting/Get-MailTrafficSummaryReport.md
Labels: Microsoft submitter

#3244 Merges Master to Live. See commits for details.
  exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/reporting/Get-MailTrafficSummaryReport.md
  repo_docs/FAQ.md
  skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Get-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/New-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Remove-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Set-CsCallQueue.md
  skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Set-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Test-CsInboundBlockedNumberPattern.md
Labels: Microsoft submitter

#3242 Update Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedContentFilterPolicy.md
Labels: Microsoft submitter, area:exchange

#3246 Updating intro text.
  teams/docs-conceptual/intro.md
Labels: Microsoft submitter

#3247 Chrisda to Master
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/New-ComplianceTag.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-ComplianceTag.md
Labels: Microsoft submitter

#3248 Master to Live
  exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/New-ComplianceTag.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-ComplianceTag.md
  teams/docs-conceptual/intro.md
Labels: Microsoft submitter

#3231 Disable incremental build
  .openpublishing.publish.config.json
Labels: Microsoft submitter, area:exchange

#3253 Update Install-UnifiedCompliancePrerequisite.md
  exchange/exchange-ps/exchange/policy-and-compliance/Install-UnifiedCompliancePrerequisite.md
Labels: area:exchange

#3254 Update connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md
Labels: Microsoft submitter, area:exchange

#3265 Chrisda to Master
  exchange/exchange-ps/exchange/mail-flow/Set-RemoteDomain.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/New-MailboxAuditLogSearch.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-MailboxAuditLog.md
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter

#3267 Master to Live
  exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md
  exchange/exchange-ps/exchange/mail-flow/Set-RemoteDomain.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/New-MailboxAuditLogSearch.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-MailboxAuditLog.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-MailboxSearch.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/Set-MailboxSearch.md
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter

#3268 Chrisda to Master
  exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-eop/exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/exchange-server/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-server/exchange-management-shell.md
  exchange/docs-conceptual/exchange-server/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/exchange-server/open-the-exchange-management-shell.md
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/docs-conceptual/exchange-server/recipient-filters/recipient-filters.md
  exchange/docs-conceptual/exchange-server/recipient-filters/recipientfilter-properties.md
  exchange/docs-conceptual/exchange-server/use-update-exchangehelp.md
Labels: Microsoft submitter

#3269 enabling moniker config for exchange powershell
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  exchange/docfx.json
  exchange/exchange-ps/exchange/active-directory/active-directory.md
  exchange/exchange-ps/exchange/advanced-threat-protection/advanced-threat-protection.md
  exchange/exchange-ps/exchange/antispam-antimalware/antispam-antimalware.md
  exchange/exchange-ps/exchange/client-access-servers/client-access-servers.md
  exchange/exchange-ps/exchange/client-access/client-access.md
  exchange/exchange-ps/exchange/connected-accounts/connected-accounts.md
  exchange/exchange-ps/exchange/database-availability-groups/database-availability-groups.md
  exchange/exchange-ps/exchange/devices/devices.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/email-addresses-and-address-books.md
  exchange/exchange-ps/exchange/encryption-and-certificates/encryption-and-certificates.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/exchange-ps/exchange/federation-and-hybrid/federation-and-hybrid.md
  exchange/exchange-ps/exchange/mail-flow/mail-flow.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/mailbox-databases-and-servers.md
  exchange/exchange-ps/exchange/mailboxes/mailboxes.md
  exchange/exchange-ps/exchange/move-and-migration/move-and-migration.md
  exchange/exchange-ps/exchange/organization/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/organization/organization.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/policy-and-compliance-audit.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/policy-and-compliance-content-search.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/policy-and-compliance-dlp.md
  exchange/exchange-ps/exchange/policy-and-compliance-ediscovery/policy-and-compliance-ediscovery.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/policy-and-compliance-retention.md
  exchange/exchange-ps/exchange/policy-and-compliance/policy-and-compliance.md
  exchange/exchange-ps/exchange/reporting/reporting.md
  exchange/exchange-ps/exchange/role-based-access-control/role-based-access-control.md
  exchange/exchange-ps/exchange/server-health-and-performance/server-health-and-performance.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/sharing-and-collaboration.md
  exchange/exchange-ps/exchange/unified-messaging/unified-messaging.md
  exchange/exchange-ps/exchange/users-and-groups/users-and-groups.md
  exchange/mapping/exchange2010mapping.json
  exchange/mapping/exchange2013mapping.json
  exchange/mapping/exchange2016mapping.json
  exchange/mapping/exchange2019mapping.json
  exchange/mapping/exchangeallmapping.json
  exchange/mapping/exchangeonlinemapping.json
  exchange/mapping/exchangeonlineprotectionmapping.json
  exchange/mapping/monikerMapping.json
  exchange/mapping/o365sccmapping.json
Labels: Microsoft submitter

#3270 merging exchange moniker changes to live
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  exchange/docfx.json
  exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-eop/exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/exchange-server/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-server/exchange-management-shell.md
  exchange/docs-conceptual/exchange-server/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/exchange-server/open-the-exchange-management-shell.md
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/docs-conceptual/exchange-server/recipient-filters/recipient-filters.md
  exchange/docs-conceptual/exchange-server/recipient-filters/recipientfilter-properties.md
  exchange/docs-conceptual/exchange-server/use-update-exchangehelp.md
  exchange/exchange-ps/exchange/active-directory/active-directory.md
  exchange/exchange-ps/exchange/advanced-threat-protection/advanced-threat-protection.md
  exchange/exchange-ps/exchange/antispam-antimalware/antispam-antimalware.md
  exchange/exchange-ps/exchange/client-access-servers/client-access-servers.md
  exchange/exchange-ps/exchange/client-access/client-access.md
  exchange/exchange-ps/exchange/connected-accounts/connected-accounts.md
  exchange/exchange-ps/exchange/database-availability-groups/database-availability-groups.md
  exchange/exchange-ps/exchange/devices/devices.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/email-addresses-and-address-books.md
  exchange/exchange-ps/exchange/encryption-and-certificates/encryption-and-certificates.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/exchange-ps/exchange/federation-and-hybrid/federation-and-hybrid.md
  exchange/exchange-ps/exchange/mail-flow/mail-flow.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/mailbox-databases-and-servers.md
  exchange/exchange-ps/exchange/mailboxes/mailboxes.md
  exchange/exchange-ps/exchange/move-and-migration/move-and-migration.md
  exchange/exchange-ps/exchange/organization/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/organization/organization.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/policy-and-compliance-audit.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/policy-and-compliance-content-search.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/policy-and-compliance-dlp.md
  exchange/exchange-ps/exchange/policy-and-compliance-ediscovery/policy-and-compliance-ediscovery.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/policy-and-compliance-retention.md
  exchange/exchange-ps/exchange/policy-and-compliance/policy-and-compliance.md
  exchange/exchange-ps/exchange/reporting/reporting.md
  exchange/exchange-ps/exchange/role-based-access-control/role-based-access-control.md
  exchange/exchange-ps/exchange/server-health-and-performance/server-health-and-performance.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/sharing-and-collaboration.md
  exchange/exchange-ps/exchange/unified-messaging/unified-messaging.md
  exchange/exchange-ps/exchange/users-and-groups/users-and-groups.md
  exchange/mapping/exchange2010mapping.json
  exchange/mapping/exchange2013mapping.json
  exchange/mapping/exchange2016mapping.json
  exchange/mapping/exchange2019mapping.json
  exchange/mapping/exchangeallmapping.json
  exchange/mapping/exchangeonlinemapping.json
  exchange/mapping/exchangeonlineprotectionmapping.json
  exchange/mapping/monikerMapping.json
  exchange/mapping/o365sccmapping.json
Labels: Microsoft submitter

#3271 Revert "merging exchange moniker changes to live"
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  exchange/docfx.json
  exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-eop/exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/exchange-server/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-server/exchange-management-shell.md
  exchange/docs-conceptual/exchange-server/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/exchange-server/open-the-exchange-management-shell.md
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/docs-conceptual/exchange-server/recipient-filters/recipient-filters.md
  exchange/docs-conceptual/exchange-server/recipient-filters/recipientfilter-properties.md
  exchange/docs-conceptual/exchange-server/use-update-exchangehelp.md
  exchange/exchange-ps/exchange/active-directory/active-directory.md
  exchange/exchange-ps/exchange/advanced-threat-protection/advanced-threat-protection.md
  exchange/exchange-ps/exchange/antispam-antimalware/antispam-antimalware.md
  exchange/exchange-ps/exchange/client-access-servers/client-access-servers.md
  exchange/exchange-ps/exchange/client-access/client-access.md
  exchange/exchange-ps/exchange/connected-accounts/connected-accounts.md
  exchange/exchange-ps/exchange/database-availability-groups/database-availability-groups.md
  exchange/exchange-ps/exchange/devices/devices.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/email-addresses-and-address-books.md
  exchange/exchange-ps/exchange/encryption-and-certificates/encryption-and-certificates.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/exchange-ps/exchange/federation-and-hybrid/federation-and-hybrid.md
  exchange/exchange-ps/exchange/mail-flow/mail-flow.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/mailbox-databases-and-servers.md
  exchange/exchange-ps/exchange/mailboxes/mailboxes.md
  exchange/exchange-ps/exchange/move-and-migration/move-and-migration.md
  exchange/exchange-ps/exchange/organization/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/organization/organization.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/policy-and-compliance-audit.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/policy-and-compliance-content-search.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/policy-and-compliance-dlp.md
  exchange/exchange-ps/exchange/policy-and-compliance-ediscovery/policy-and-compliance-ediscovery.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/policy-and-compliance-retention.md
  exchange/exchange-ps/exchange/policy-and-compliance/policy-and-compliance.md
  exchange/exchange-ps/exchange/reporting/reporting.md
  exchange/exchange-ps/exchange/role-based-access-control/role-based-access-control.md
  exchange/exchange-ps/exchange/server-health-and-performance/server-health-and-performance.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/sharing-and-collaboration.md
  exchange/exchange-ps/exchange/unified-messaging/unified-messaging.md
  exchange/exchange-ps/exchange/users-and-groups/users-and-groups.md
  exchange/mapping/exchange2010mapping.json
  exchange/mapping/exchange2013mapping.json
  exchange/mapping/exchange2016mapping.json
  exchange/mapping/exchange2019mapping.json
  exchange/mapping/exchangeallmapping.json
  exchange/mapping/exchangeonlinemapping.json
  exchange/mapping/exchangeonlineprotectionmapping.json
  exchange/mapping/monikerMapping.json
  exchange/mapping/o365sccmapping.json
Labels: Microsoft submitter

#3272 Revert "enabling moniker config for exchange powershell"
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  exchange/docfx.json
  exchange/exchange-ps/exchange/active-directory/active-directory.md
  exchange/exchange-ps/exchange/advanced-threat-protection/advanced-threat-protection.md
  exchange/exchange-ps/exchange/antispam-antimalware/antispam-antimalware.md
  exchange/exchange-ps/exchange/client-access-servers/client-access-servers.md
  exchange/exchange-ps/exchange/client-access/client-access.md
  exchange/exchange-ps/exchange/connected-accounts/connected-accounts.md
  exchange/exchange-ps/exchange/database-availability-groups/database-availability-groups.md
  exchange/exchange-ps/exchange/devices/devices.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/email-addresses-and-address-books.md
  exchange/exchange-ps/exchange/encryption-and-certificates/encryption-and-certificates.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/exchange-ps/exchange/federation-and-hybrid/federation-and-hybrid.md
  exchange/exchange-ps/exchange/mail-flow/mail-flow.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/mailbox-databases-and-servers.md
  exchange/exchange-ps/exchange/mailboxes/mailboxes.md
  exchange/exchange-ps/exchange/move-and-migration/move-and-migration.md
  exchange/exchange-ps/exchange/organization/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/organization/organization.md
  exchange/exchange-ps/exchange/policy-and-compliance-audit/policy-and-compliance-audit.md
  exchange/exchange-ps/exchange/policy-and-compliance-content-search/policy-and-compliance-content-search.md
  exchange/exchange-ps/exchange/policy-and-compliance-dlp/policy-and-compliance-dlp.md
  exchange/exchange-ps/exchange/policy-and-compliance-ediscovery/policy-and-compliance-ediscovery.md
  exchange/exchange-ps/exchange/policy-and-compliance-retention/policy-and-compliance-retention.md
  exchange/exchange-ps/exchange/policy-and-compliance/policy-and-compliance.md
  exchange/exchange-ps/exchange/reporting/reporting.md
  exchange/exchange-ps/exchange/role-based-access-control/role-based-access-control.md
  exchange/exchange-ps/exchange/server-health-and-performance/server-health-and-performance.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/sharing-and-collaboration.md
  exchange/exchange-ps/exchange/unified-messaging/unified-messaging.md
  exchange/exchange-ps/exchange/users-and-groups/users-and-groups.md
  exchange/mapping/exchange2010mapping.json
  exchange/mapping/exchange2013mapping.json
  exchange/mapping/exchange2016mapping.json
  exchange/mapping/exchange2019mapping.json
  exchange/mapping/exchangeallmapping.json
  exchange/mapping/exchangeonlinemapping.json
  exchange/mapping/exchangeonlineprotectionmapping.json
  exchange/mapping/monikerMapping.json
  exchange/mapping/o365sccmapping.json
Labels: Microsoft submitter

#3274 Replace all instances of > with Set-Content
  exchange/exchange-ps/exchange/client-access/Test-CalendarConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-EcpConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-ImapConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-PopConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-PowerShellConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-WebServicesConnectivity.md
  exchange/exchange-ps/exchange/devices/Test-ActiveSyncConnectivity.md
  exchange/exchange-ps/exchange/mail-flow/Get-SystemMessage.md
  exchange/exchange-ps/exchange/mail-flow/New-SystemMessage.md
  exchange/exchange-ps/exchange/mail-flow/Set-SystemMessage.md
  exchange/exchange-ps/exchange/mailboxes/Get-CalendarDiagnosticAnalysis.md
  exchange/exchange-ps/exchange/mailboxes/Get-CalendarDiagnosticLog.md
Labels: area:exchange

#3275 Added dannyle and waseemh as authors
  skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Get-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/New-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Remove-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Set-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Test-CsInboundBlockedNumberPattern.md
Labels: area:skype, area:teams

#3278 Pushing the updated Teams powershell docs to live!
  exchange/exchange-ps/exchange/client-access/Test-CalendarConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-EcpConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-ImapConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-PopConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-PowerShellConnectivity.md
  exchange/exchange-ps/exchange/client-access/Test-WebServicesConnectivity.md
  exchange/exchange-ps/exchange/devices/Test-ActiveSyncConnectivity.md
  exchange/exchange-ps/exchange/mail-flow/Get-SystemMessage.md
  exchange/exchange-ps/exchange/mail-flow/New-SystemMessage.md
  exchange/exchange-ps/exchange/mail-flow/Set-SystemMessage.md
  exchange/exchange-ps/exchange/mailboxes/Get-CalendarDiagnosticAnalysis.md
  exchange/exchange-ps/exchange/mailboxes/Get-CalendarDiagnosticLog.md
  skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Get-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/New-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Remove-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Set-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Test-CsInboundBlockedNumberPattern.md
  teams/teams-ps/teams/Add-TeamUser.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Disconnect-MicrosoftTeams.md
  teams/teams-ps/teams/Get-Team.md
  teams/teams-ps/teams/Get-TeamChannel.md
  teams/teams-ps/teams/Get-TeamFunSettings.md
  teams/teams-ps/teams/Get-TeamGuestSettings.md
  teams/teams-ps/teams/Get-TeamHelp.md
  teams/teams-ps/teams/Get-TeamMemberSettings.md
  teams/teams-ps/teams/Get-TeamMessagingSettings.md
  teams/teams-ps/teams/Get-TeamUser.md
  teams/teams-ps/teams/New-Team.md
  teams/teams-ps/teams/New-TeamChannel.md
  teams/teams-ps/teams/Remove-Team.md
  teams/teams-ps/teams/Remove-TeamChannel.md
  teams/teams-ps/teams/Remove-TeamUser.md
  teams/teams-ps/teams/Set-Team.md
  teams/teams-ps/teams/Set-TeamChannel.md
  teams/teams-ps/teams/Set-TeamFunSettings.md
  teams/teams-ps/teams/Set-TeamGuestSettings.md
  teams/teams-ps/teams/Set-TeamMemberSettings.md
  teams/teams-ps/teams/Set-TeamMessagingSettings.md
  teams/teams-ps/teams/Set-TeamPicture.md
Labels: Microsoft submitter

#3282 Chrisda to Master
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/mail-flow/New-ReceiveConnector.md
  exchange/exchange-ps/exchange/mail-flow/Set-ReceiveConnector.md
  exchange/exchange-ps/exchange/mail-flow/Set-TransportConfig.md
  exchange/exchange-ps/exchange/mail-flow/Set-TransportServer.md
  exchange/exchange-ps/exchange/mail-flow/Set-TransportService.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Set-MailboxServer.md
  exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md
  exchange/exchange-ps/exchange/mailboxes/Set-MailboxPlan.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/New-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/New-SyncMailPublicFolder.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-MailPublicFolder.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/users-and-groups/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/users-and-groups/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/users-and-groups/Set-MailContact.md
  exchange/exchange-ps/exchange/users-and-groups/Set-MailUser.md
  exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md
Labels: Microsoft submitter

#3290 Chrisda to Master
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/exchange-ps/exchange/client-access-servers/Set-ClientAccessServer.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/New-OfflineAddressBook.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/Set-OfflineAddressBook.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Set-MailboxDatabase.md
  exchange/exchange-ps/exchange/mailbox-databases-and-servers/Set-MailboxServer.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-PublicFolder.md
  exchange/exchange-ps/exchange/sharing-and-collaboration/Set-PublicFolderDatabase.md
  exchange/exchange-ps/exchange/unified-messaging/Set-UMAutoAttendant.md
  exchange/exchange-ps/exchange/unified-messaging/Set-UMService.md
  exchange/exchange-ps/exchange/unified-messaging/Set-UmServer.md
Labels: Microsoft submitter

#3292 Chrisda to Master
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
Labels: Microsoft submitter

#3293 Master to Live
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
Labels: Microsoft submitter

#3296 Update filter-properties.md
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
Labels: Microsoft submitter

#3297 Master to Live
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
Labels: Microsoft submitter

#3302 Chrisda to Master
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/Update-GlobalAddressList.md
Labels: Microsoft submitter

#3307 Master to Live
  exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/client-access/Get-TextMessagingAccount.md
  exchange/exchange-ps/exchange/email-addresses-and-address-books/Update-GlobalAddressList.md
Labels: Microsoft submitter

#3308 Islubin adding in TeamsChannelsPolicy docs
  skype/skype-ps/skype/Get-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
Labels: Microsoft submitter

#3311 Chrisda to Master
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/exchange-ps/exchange/policy-and-compliance/Get-MessageClassification.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-MessageClassification.md
  exchange/exchange-ps/exchange/policy-and-compliance/Remove-MessageClassification.md
  exchange/exchange-ps/exchange/policy-and-compliance/Set-MessageClassification.md
Labels: Microsoft submitter

#3310 Pushing teams and channels policy docs to live
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/exchange-ps/exchange/policy-and-compliance/Get-MessageClassification.md
  exchange/exchange-ps/exchange/policy-and-compliance/New-MessageClassification.md
  exchange/exchange-ps/exchange/policy-and-compliance/Remove-MessageClassification.md
  exchange/exchange-ps/exchange/policy-and-compliance/Set-MessageClassification.md
  skype/skype-ps/skype/Get-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
Labels: Microsoft submitter

#3309 Updating TOC for new policies
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter

#3314 Update Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedContentFilterPolicy.md
Labels: area:exchange

#3315 Update filter-properties.md
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
Labels: Microsoft submitter

#3316 Patch 1
  exchange/exchange-ps/exchange/encryption-and-certificates/New-OMEConfiguration.md
Labels: Microsoft submitter

#3317 Master to Live
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/encryption-and-certificates/New-OMEConfiguration.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHideDefaultThemes.md
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter

#3258 Add the Notes about Provisioning OneDrive
  sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md
Labels: area:spo-powershell

#3319 Chrisda to Master
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/exchange-ps/exchange/client-access/Get-TextMessagingAccount.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Get-OMEConfiguration.md
  exchange/exchange-ps/exchange/encryption-and-certificates/New-OMEConfiguration.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Remove-OMEConfiguration.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md
Labels: Microsoft submitter

#3320 Master to Live
  exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md
  exchange/exchange-ps/exchange/client-access/Get-TextMessagingAccount.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Get-OMEConfiguration.md
  exchange/exchange-ps/exchange/encryption-and-certificates/New-OMEConfiguration.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Remove-OMEConfiguration.md
  exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md
  sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md
Labels: Microsoft submitter

#3318 Fix minor typo ("you" -> "your")
  sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
Labels: area:pnp-powershell
