Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2020-09, with the labels that each got.

#6450 Chrisda to Master
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter

#6452 Master to Live
  exchange/exchange-ps/exchange/Search-MailboxAuditLog.md
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter

#6381 Replace legacy build pipeline with PowerShell SDP build pipeline for SharePoint docs
  .openpublishing.publish.config.json
  sharepoint/docfx.json
  sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
  sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubToHubAssociation.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteCollectionAppCatalog.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInDesignPackageVisibility.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMoveReport.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHomeSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoCompanyAllowedDataLocation.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteCollectionAppCatalogs.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteRenameState.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScriptFromWeb.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOStorageEntity.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroupMoveState.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPODataConnectionSetting.md
  sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOHomeSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOHubToHubAssociation.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOMultiGeoCompanyAllowedDataLocation.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteCollectionAppCatalog.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteCollectionAppCatalogById.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteUserInvitations.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOStorageEntity.md
  sharepoint/sharepoint-ps/sharepoint-online/Restore-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPODataConnectionSetting.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPODataConnectionSettingMetadata.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHomeSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoCompanyAllowedDataLocation.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoExperience.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUnifiedGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOWebTheme.md
  sharepoint/sharepoint-ps/sharepoint-online/Update-UserType.md
  sharepoint/sharepoint-ps/sharepoint-server/Add-FASTSearchSpelltuning.md
  sharepoint/sharepoint-ps/sharepoint-server/Add-SPAppDeniedEndpoint.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSpelltuningStatus.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPODataConnectionSetting.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPODataConnectionSettingMetadata.md
  sharepoint/sharepoint-ps/sharepoint-server/New-FASTSearchMetadataCrawledProperty.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchLinksDatabase.md
  sharepoint/sharepoint-ps/sharepoint-server/Remove-FASTSearchSpelltuning.md
  sharepoint/sharepoint-ps/sharepoint-server/Remove-SPApplicationCredentialKey.md
  sharepoint/sharepoint-ps/sharepoint-server/Stop-SPDistributedCacheServiceInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Test-SPProjectWebInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Uninstall-SPAppInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Update-SPAppInstance.md
  skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md
Labels: Microsoft submitter, area:spo-powershell

#6456 Replace legacy build pipeline with PowerShell SDP build pipeline for officewebapps docs
  .openpublishing.publish.config.json
  officewebapps/docfx.json
Labels: Microsoft submitter

#6457 Replace legacy build pipeline with PowerShell SDP build pipeline for SharePointMigrationTool docs
  .openpublishing.publish.config.json
  spmt/docfx.json
Labels: Microsoft submitter

#6445 Updated docs to include AutoNewsDigest
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell

#6463 Master into Live
  .openpublishing.publish.config.json
  officewebapps/docfx.json
  sharepoint/docfx.json
  sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
  sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubToHubAssociation.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteCollectionAppCatalog.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInDesignPackageVisibility.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMoveReport.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHomeSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoCompanyAllowedDataLocation.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteCollectionAppCatalogs.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteRenameState.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScriptFromWeb.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOStorageEntity.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroupMoveState.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPODataConnectionSetting.md
  sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOHomeSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOHubToHubAssociation.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOMultiGeoCompanyAllowedDataLocation.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteCollectionAppCatalog.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteCollectionAppCatalogById.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteUserInvitations.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOStorageEntity.md
  sharepoint/sharepoint-ps/sharepoint-online/Restore-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPODataConnectionSetting.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPODataConnectionSettingMetadata.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHomeSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoCompanyAllowedDataLocation.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoExperience.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUnifiedGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOWebTheme.md
  sharepoint/sharepoint-ps/sharepoint-online/Update-UserType.md
  sharepoint/sharepoint-ps/sharepoint-server/Add-FASTSearchSpelltuning.md
  sharepoint/sharepoint-ps/sharepoint-server/Add-SPAppDeniedEndpoint.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSpelltuningStatus.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPODataConnectionSetting.md
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPODataConnectionSettingMetadata.md
  sharepoint/sharepoint-ps/sharepoint-server/New-FASTSearchMetadataCrawledProperty.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchLinksDatabase.md
  sharepoint/sharepoint-ps/sharepoint-server/Remove-FASTSearchSpelltuning.md
  sharepoint/sharepoint-ps/sharepoint-server/Remove-SPApplicationCredentialKey.md
  sharepoint/sharepoint-ps/sharepoint-server/Stop-SPDistributedCacheServiceInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Test-SPProjectWebInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Uninstall-SPAppInstance.md
  sharepoint/sharepoint-ps/sharepoint-server/Update-SPAppInstance.md
  skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md
  spmt/docfx.json
Labels: Microsoft submitter

#6469 Chrisda to Master
  exchange/exchange-ps/exchange/Disable-MailUser.md
  exchange/exchange-ps/exchange/Disable-Mailbox.md
  exchange/exchange-ps/exchange/Get-SiteMailbox.md
  exchange/exchange-ps/exchange/Get-SiteMailboxDiagnostics.md
  exchange/exchange-ps/exchange/Get-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/New-SiteMailbox.md
  exchange/exchange-ps/exchange/New-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Remove-MailUser.md
  exchange/exchange-ps/exchange/Remove-Mailbox.md
  exchange/exchange-ps/exchange/Remove-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-SiteMailbox.md
  exchange/exchange-ps/exchange/Set-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Test-SiteMailbox.md
  exchange/exchange-ps/exchange/Update-SiteMailbox.md
Labels: Microsoft submitter

#6455 Replace legacy build pipeline with PowerShell SDP build pipeline for Exchange docs
  .openpublishing.publish.config.json
  exchange/docfx.json
Labels: Microsoft submitter

#6459 Replace legacy build pipeline with PowerShell SDP build pipeline for Teams docs
  .openpublishing.publish.config.json
  teams/docfx.json
Labels: Microsoft submitter

#6458 Replace legacy build pipeline with PowerShell SDP build pipeline for StaffHub docs
  .openpublishing.publish.config.json
  staffhub/docfx.json
  staffhub/staffhub-ps/staffhub/Remove-StaffHubUser.md
Labels: Microsoft submitter

#6380 Updated unmatched title and header in cmdlets in skype-ps
  .openpublishing.publish.config.json
  skype/docfx.json
  skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Get-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Get-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Grant-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Invoke-CsRgsStoreReplicateData.md
  skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/New-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/New-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Remove-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Remove-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Set-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Test-CsInboundBlockedNumberPattern.md
Labels: Microsoft submitter, area:teams / skype

#6471 Replace legacy build pipeline with PowerShell SDP build pipeline for Whiteboard docs
  .openpublishing.publish.config.json
  whiteboard/docfx.json
  whiteboard/docs-conceptual/overview.md
Labels: Microsoft submitter

#6472 Remove legacy packages from .openpublishing.publish.config.json
  .openpublishing.publish.config.json
Labels: Microsoft submitter

#6470 Master to Live
  .openpublishing.publish.config.json
  exchange/docfx.json
  exchange/exchange-ps/exchange/Disable-MailUser.md
  exchange/exchange-ps/exchange/Disable-Mailbox.md
  exchange/exchange-ps/exchange/Get-SiteMailbox.md
  exchange/exchange-ps/exchange/Get-SiteMailboxDiagnostics.md
  exchange/exchange-ps/exchange/Get-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/New-SiteMailbox.md
  exchange/exchange-ps/exchange/New-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Remove-MailUser.md
  exchange/exchange-ps/exchange/Remove-Mailbox.md
  exchange/exchange-ps/exchange/Remove-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-SiteMailbox.md
  exchange/exchange-ps/exchange/Set-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Test-SiteMailbox.md
  exchange/exchange-ps/exchange/Update-SiteMailbox.md
  skype/docfx.json
  skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Get-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Get-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Grant-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Invoke-CsRgsStoreReplicateData.md
  skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/New-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/New-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Remove-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Remove-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md
  skype/skype-ps/skype/Set-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Test-CsInboundBlockedNumberPattern.md
  staffhub/docfx.json
  staffhub/staffhub-ps/staffhub/Remove-StaffHubUser.md
  teams/docfx.json
  whiteboard/docfx.json
  whiteboard/docs-conceptual/overview.md
Labels: Microsoft submitter

#6442 Adding Teams admin center names for policies
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: area:teams

#6475 Safe Links updates
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
Labels: Microsoft submitter

#6476 Fix typo
  exchange/exchange-ps/exchange/Set-CalendarNotification.md
Labels: area:exchange

#6478 Add more details for New-MigrationBatch
  exchange/exchange-ps/exchange/New-MigrationBatch.md
Labels: Microsoft submitter

#6486 New mig branch chrisda
  exchange/exchange-ps/exchange/New-MigrationBatch.md
Labels: Microsoft submitter

#6487 Chrisda to Master
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
Labels: Microsoft submitter

#6489 Master to Live
  exchange/exchange-ps/exchange/Enable-OutlookAnywhere.md
  exchange/exchange-ps/exchange/Get-ThrottlingPolicyAssociation.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-CalendarNotification.md
  exchange/exchange-ps/exchange/Set-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-OutlookAnywhere.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#6490 Correct typo
  exchange/exchange-ps/exchange/New-MigrationBatch.md
Labels: Microsoft submitter, area:exchange

#6464 Added documents for application access policy cmdlets
  skype/skype-ps/skype/Get-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/New-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Remove-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Set-CsApplicationAccessPolicy.md
Labels: Microsoft submitter, area:teams / skype

#6509 OOB Publish 9/14/2020 12:06 PM PDT
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  skype/skype-ps/skype/Get-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/New-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Remove-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Set-CsApplicationAccessPolicy.md
Labels: Microsoft submitter

#6501 Update New-CsOnlineSession.md
  skype/skype-ps/skype/New-CsOnlineSession.md
Labels: area:teams / skype

#6508 Update Remove-DlpKeywordDictionary.md
  exchange/exchange-ps/exchange/Remove-DlpKeywordDictionary.md
Labels: Microsoft submitter, area:exchange

#6512 Update Get-CASMailbox.md
  exchange/exchange-ps/exchange/Get-CASMailbox.md
Labels: Microsoft submitter

#6516 Chrisda copy of qinezh test
  exchange/docfx.json
Labels: Microsoft submitter

#6519 Publish request 9/15/2020 11:43 AM PDT
  exchange/docfx.json
  exchange/exchange-ps/exchange/Get-CASMailbox.md
  exchange/exchange-ps/exchange/Remove-DlpKeywordDictionary.md
  skype/skype-ps/skype/New-CsOnlineSession.md
Labels: Microsoft submitter

#6520 Chrisda to Master
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Add-AvailabilityAddressSpace.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Import-RMSTrustedPublishingDomain.md
  exchange/exchange-ps/exchange/New-AuthRedirect.md
  exchange/exchange-ps/exchange/New-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/New-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/New-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-HostedOutboundSpamFilterPolicy.md
  exchange/exchange-ps/exchange/New-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/New-OrganizationRelationship.md
  exchange/exchange-ps/exchange/New-PolicyTipConfig.md
  exchange/exchange-ps/exchange/New-WebServicesVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-AuthRedirect.md
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/Set-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/Set-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Set-HoldCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxServer.md
  exchange/exchange-ps/exchange/Set-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-OabVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationRelationship.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-OwaVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Test-PowerShellConnectivity.md
Labels: Microsoft submitter

#6521 Master to live
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Add-AvailabilityAddressSpace.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Import-RMSTrustedPublishingDomain.md
  exchange/exchange-ps/exchange/New-AuthRedirect.md
  exchange/exchange-ps/exchange/New-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/New-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/New-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-HostedOutboundSpamFilterPolicy.md
  exchange/exchange-ps/exchange/New-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/New-OrganizationRelationship.md
  exchange/exchange-ps/exchange/New-PolicyTipConfig.md
  exchange/exchange-ps/exchange/New-WebServicesVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-AuthRedirect.md
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/Set-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/Set-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Set-HoldCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxServer.md
  exchange/exchange-ps/exchange/Set-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-OabVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationRelationship.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-OwaVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Test-PowerShellConnectivity.md
Labels: Microsoft submitter

#6503 Update New-CsAutoAttendantMenuOption.md
  skype/skype-ps/skype/New-CsAutoAttendantMenuOption.md
Labels: area:teams / skype

#6526 Chrisda to Master
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#6527 Master to Live
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-MoveRequestStatistics.md
  skype/skype-ps/skype/New-CsAutoAttendantMenuOption.md
Labels: Microsoft submitter

#6517 Adding param desc
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype

#6518 Typo
  teams/teams-ps/teams/Set-TeamPicture.md
Labels: area:teams

#6523 Adding note
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
Labels: area:spo-powershell

#6528 Update Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter, area:exchange

#6535 Master to Live
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-TeamPicture.md
Labels: Microsoft submitter

#6538 Chrisda to Master
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#6539 Master to lLive
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#6500 Add docs for new cmdlet Get/Set-CsApplicationMeetingConfiguration
  skype/skype-ps/skype/Get-CsApplicationMeetingConfiguration.md
  skype/skype-ps/skype/Set-CsApplicationMeetingConfiguration.md
Labels: area:teams / skype

#6545 Update docfx.json
  exchange/docfx.json
Labels: Microsoft submitter

#6557 Docs changes for PowerShell Core
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#6558 Updated Instructions for CBA
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#6532 Updated Examples for Parameter "-LanguageId" instead of "-Language"
  skype/skype-ps/skype/New-CsAutoAttendant.md
Labels: area:teams / skype

#6522 Update Add-SPOSiteCollectionAppCatalog.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteCollectionAppCatalog.md
Labels: area:spo-powershell

#6473 AddAutoNewsDigest to index
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter, area:spo-powershell

#6560 Update for IPAudioMode and IPVideoMode - Set-CsTeamsMeetingPolicy
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#6561 Update for IPAudioMode and IPVideoMode - New-CsTeamsMeetingPolicy
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#6562 Chrisda to Master
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#6563 Updated ModernGroup parameters in New/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: area:exchange

#6564 Added related links to *-MailboxFolderPermission cmdlets
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md
Labels: area:exchange

#6567 Chrisda to Master
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter

#6568 Master to Live
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteCollectionAppCatalog.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  skype/skype-ps/skype/New-CsAutoAttendant.md
  skype/skype-ps/skype/New-CsOnlineSession.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#6571 Updating version info for PSCore release
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#6572 Update exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#6579 Update exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#6581 Master to Live
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#6582 Typo fix
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter

#6587 DLP-chrisda to Master
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#6588 Master to Live
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#6556 fix redirection rules
  .openpublishing.redirection.json
Labels: Microsoft submitter

#6595 Chrisda to Master
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter

#6596 Master to Live
  .openpublishing.redirection.json
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter

#6593 Fix redirection rules
  .openpublishing.redirection.json
Labels: Microsoft submitter

#6597 Replacing LCID link
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: area:spo-powershell

#6598 Typo
  sharepoint/sharepoint-ps/sharepoint-server/Import-SPEnterpriseSearchThesaurus.md
Labels: area:sp-server-powershell

#6606 Chrisda to Master
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/filter-properties.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/use-update-exchangehelp.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
Labels: Microsoft submitter

#6604 Update config to enable docfx v3
  .openpublishing.publish.config.json
Labels: Microsoft submitter

#6608 Chrisda to Master
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#6609 Master to Live
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/filter-properties.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/use-update-exchangehelp.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-server/Import-SPEnterpriseSearchThesaurus.md
Labels: Microsoft submitter

#6548 Adjusting some details
  skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md
Labels: area:teams / skype

#6612 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#6611 Update Set-UnifiedGroup.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: area:exchange

#6614 ms.prod to ms.service to squelch build warnings
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/use-update-exchangehelp.md
Labels: Microsoft submitter

#6616 Added &preserve-view=true to required links
  exchange/docs-conceptual/exchange-management-shell.md
Labels: Microsoft submitter

#6615 Master to Live
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/use-update-exchangehelp.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
  skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md
Labels: Microsoft submitter

#6619 Deprecated 4 properties/parameters by request
  exchange/exchange-ps/exchange/Get-EventsFromEmailConfiguration.md
  exchange/exchange-ps/exchange/Set-EventsFromEmailConfiguration.md
Labels: Microsoft submitter

#6620 Master to Live
  exchange/exchange-ps/exchange/Get-EventsFromEmailConfiguration.md
  exchange/exchange-ps/exchange/Set-EventsFromEmailConfiguration.md
Labels: Microsoft submitter

#6621 Update connect-to-scc-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter

#6578 Removing TAP requirement
  skype/skype-ps/skype/Move-CsUser.md
Labels: area:teams / skype

#6583 Typo
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOHomeSite.md
Labels: area:spo-powershell

#6584 Typo
  sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOHubSiteRights.md
Labels: area:spo-powershell

#6585 Adding Synopsis
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBrowserIdleSignOut.md
Labels: area:spo-powershell

#6586 Add link to more information
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md
Labels: area:spo-powershell

#6601 fix broken link
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoAdministrator.md
Labels: area:spo-powershell

#6607 Adding suggestion
  skype/skype-ps/skype/Set-CsTeamsMessagingPolicy.md
Labels: area:teams / skype

#6623 Update Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#6624 Publishing to live
  exchange/docs-conceptual/connect-to-scc-powershell.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoAdministrator.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOHomeSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOHubSiteRights.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBrowserIdleSignOut.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Move-CsUser.md
  skype/skype-ps/skype/Set-CsTeamsMessagingPolicy.md
Labels: Microsoft submitter

#6625 Update Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter

#6626 Fixing link
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: Microsoft submitter
