Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2021-01, with the labels that each got.

#7001 Update Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
Labels: Microsoft submitter, area:exchange

#7002 Updated QuarantineRetentionPeriod default value in New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
Labels: area:exchange

#7009 Update Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter, area:exchange

#7020 Chrisda to Master
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-App.md
  exchange/exchange-ps/exchange/New-RpcClientAccess.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-App.md
  exchange/exchange-ps/exchange/Set-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-ThrottlingPolicy.md
  exchange/exchange-ps/exchange/Set-UMMailbox.md
Labels: Microsoft submitter

#7021 Master to Live
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-App.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-RpcClientAccess.md
  exchange/exchange-ps/exchange/Search-Mailbox.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-App.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-ThrottlingPolicy.md
  exchange/exchange-ps/exchange/Set-UMMailbox.md
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOUserAndContentMove.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPWorkflowConfig.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsComplianceRecordingApplication.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#7019 Fix verbiage
  skype/skype-ps/skype/New-CsTenantDialPlan.md
Labels: area:teams / skype

#7038 Chrisda to Master
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
Labels: Microsoft submitter

#7030 Update Set-CASMailbox.md
  exchange/exchange-ps/exchange/Set-CASMailbox.md
Labels: Microsoft submitter, area:exchange

#7039 Master to Live
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-CASMailbox.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
  skype/skype-ps/skype/New-CsTenantDialPlan.md
Labels: Microsoft submitter

#7023 Update Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter, area:spo-powershell

#7031 Adding description to parameter
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoUsers.md
Labels: area:spo-powershell

#7045 Update Test-DataClassification.md
  exchange/exchange-ps/exchange/Test-DataClassification.md
Labels: Microsoft submitter

#7046 Update Test-TextExtraction.md
  exchange/exchange-ps/exchange/Test-TextExtraction.md
Labels: Microsoft submitter, area:exchange

#7049 Update find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
Labels: Microsoft submitter

#7012 Example for MicrosoftTeams and unavailable params
  skype/skype-ps/skype/New-CsOnlineSession.md
Labels: area:teams / skype

#7056 Update New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7057 Update Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7054 Updated ConflictResolutionOption possible values for Exch 2013 in New-MailboxImportRequest.md
  exchange/exchange-ps/exchange/New-MailboxImportRequest.md
Labels: area:exchange

#7029 Adding description
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMigrationJobProgress.md
Labels: area:spo-powershell

#7061 Update New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Get-SafeLinksAggregateReport.md
  exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
Labels: Microsoft submitter

#7051 Corrected text for Unauthenticated Sender
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
Labels: Microsoft submitter, area:exchange

#7063 Chrisda to Master
  exchange/exchange-ps/exchange/Get-UnifiedAuditLogRetentionPolicy.md
  exchange/exchange-ps/exchange/New-UnifiedAuditLogRetentionPolicy.md
  exchange/exchange-ps/exchange/Set-UnifiedAuditLogRetentionPolicy.md
Labels: Microsoft submitter

#7064 Master to Live
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/exchange-ps/exchange/Get-SafeLinksAggregateReport.md
  exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md
  exchange/exchange-ps/exchange/Get-UnifiedAuditLogRetentionPolicy.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-MailboxImportRequest.md
  exchange/exchange-ps/exchange/New-UnifiedAuditLogRetentionPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-UnifiedAuditLogRetentionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoUsers.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMigrationJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  skype/skype-ps/skype/New-CsOnlineSession.md
Labels: Microsoft submitter

#7065 Reminders-chrisda to Master
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#7067 Updated New/Set-RetentionComplianceRule topics
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md
Labels: Microsoft submitter

#7055 Update Get-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
Labels: Microsoft submitter, area:spo-powershell

#7050 Improving descriptions
  skype/skype-ps/skype/Get-CsTenantDialPlan.md
  skype/skype-ps/skype/New-CsTenantDialPlan.md
  skype/skype-ps/skype/Set-CsTenantDialPlan.md
Labels: area:teams / skype

#7080 Update New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter

#7081 Update Test-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Test-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter

#7071 Update Get-SafeLinksDetailReport.md
  exchange/exchange-ps/exchange/Get-MobileDevice.md
  exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#7006 [Hold] Add a new switch to Remove-MailboxFolderPermission
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
Labels: Microsoft submitter, area:exchange

#7077 Delete note
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
Labels: Microsoft submitter, area:exchange

#7079 Delete note
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
Labels: Microsoft submitter, area:exchange

#7082 Master to Live
  exchange/exchange-ps/exchange/Get-MobileDevice.md
  exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
  skype/skype-ps/skype/Get-CsTenantDialPlan.md
  skype/skype-ps/skype/New-CsTenantDialPlan.md
  skype/skype-ps/skype/Set-CsTenantDialPlan.md
Labels: Microsoft submitter

#7083 Darep-chrisda to Master
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Test-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7084 Master to Live
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Test-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7086 Update Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
Labels: Microsoft submitter, area:exchange

#7087 Update Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7088 Update New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7096 DAREP-chrisda to Master
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter

#7097 Chrisda to Master
  exchange/exchange-ps/exchange/Export-TransportRuleCollection.md
  exchange/exchange-ps/exchange/Import-TransportRuleCollection.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
Labels: Microsoft submitter

#7098 Master to Live
  exchange/exchange-ps/exchange/Export-TransportRuleCollection.md
  exchange/exchange-ps/exchange/Import-TransportRuleCollection.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter

#7100 Update New-CsOnlineSession.md
  skype/skype-ps/skype/New-CsOnlineSession.md
Labels: area:teams / skype

#7099 Update connect-sharepoint-online.md
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
Labels: area:spo-powershell

#7107 Added values for Component parameter for Export-MailboxDiagnosticLogs
  exchange/exchange-ps/exchange/Export-MailboxDiagnosticLogs.md
Labels: Microsoft submitter, area:exchange

#7112 Update Get-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicyAssignment.md
Labels: Microsoft submitter, area:exchange

#7114 Update Get-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7115 Update Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7116 Update Set-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicyAssignment.md
Labels: Microsoft submitter, area:exchange

#7117 Update Test-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Test-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7108 Update Set-EmailAddressPolicy.md
  exchange/exchange-ps/exchange/Set-EmailAddressPolicy.md
Labels: area:exchange

#7123 Update Get-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicyAssignment.md
Labels: Microsoft submitter

#7122 DAREP-chrisda to Master
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Test-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter

#7125 CalDiagObj-chrisda to Master
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/values-for-custompropertynames-parameter.md
  exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md
Labels: Microsoft submitter

#7126 Master to Live
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/values-for-custompropertynames-parameter.md
  exchange/exchange-ps/exchange/Export-MailboxDiagnosticLogs.md
  exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Set-EmailAddressPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Test-M365DataAtRestEncryptionPolicy.md
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
  skype/skype-ps/skype/New-CsOnlineSession.md
Labels: Microsoft submitter

#7130 Update Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
Labels: Microsoft submitter, area:exchange

#7129 Adding Auto Answer setting
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter, area:teams / skype

#7074 Typos and Video embed fixes
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
Labels: area:spo-powershell

#7118 Update New-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: area:teams

#7135 Update Set-Label.md to clarify advanced settings are for AIP client only
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter, area:exchange

#7136 Update Set-LabelPolicy.md to clarify advanced settings are for AIP client only
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter

#7134 Update Get-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicyAssignment.md
Labels: Microsoft submitter, area:exchange

#7132 Update New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7133 Update Get-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7137 Chrisda to Master
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Get-ExchangeCertificate.md
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-User.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7138 DAREP-chrisda to Master
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Get-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter

#7139 Update Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7140 Update Set-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicyAssignment.md
Labels: Microsoft submitter, area:exchange

#7141 Update Test-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Test-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7146 Update Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter, area:exchange

#7148 Darep-chrisda to Master
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-M365DataAtRestEncryptionPolicyAssignment.md
  exchange/exchange-ps/exchange/Test-M365DataAtRestEncryptionPolicy.md
Labels: Microsoft submitter

#7149 DataExtract-chrisda to Master
  exchange/exchange-ps/exchange/Test-DataClassification.md
  exchange/exchange-ps/exchange/Test-TextExtraction.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#6964 Update Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter, area:exchange

#7153 Update Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
Labels: Microsoft submitter

#7157 Removed Doulbe Entry of [-OAuthAuthentication
  exchange/exchange-ps/exchange/Set-WebServicesVirtualDirectory.md
Labels: Microsoft submitter, area:exchange

#7160 Chrisda to Master
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#7161 Master to Live
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-WebServicesVirtualDirectory.md
Labels: Microsoft submitter

#7159 Adding the blob for AllowPrivateMeetNow policy setting
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#7162 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter, area:exchange

#7164 Master to Live
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#7165 Added *-MailboxSearch retirement note to cmdlet topics
  exchange/exchange-ps/exchange/Get-MailboxSearch.md
  exchange/exchange-ps/exchange/New-MailboxSearch.md
  exchange/exchange-ps/exchange/Remove-MailboxSearch.md
  exchange/exchange-ps/exchange/Set-MailboxSearch.md
  exchange/exchange-ps/exchange/Start-MailboxSearch.md
  exchange/exchange-ps/exchange/Stop-MailboxSearch.md
Labels: Microsoft submitter

#7167 Chrisda to Master
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/filter-properties.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/use-update-exchangehelp.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
Labels: Microsoft submitter

#7168 Master to Live
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/filter-properties.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/use-update-exchangehelp.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Get-MailboxSearch.md
  exchange/exchange-ps/exchange/New-MailboxSearch.md
  exchange/exchange-ps/exchange/Remove-MailboxSearch.md
  exchange/exchange-ps/exchange/Set-MailboxSearch.md
  exchange/exchange-ps/exchange/Start-MailboxSearch.md
  exchange/exchange-ps/exchange/Stop-MailboxSearch.md
Labels: Microsoft submitter

#7172 Revert "Update sharepoint-pnp-cmdlets.md"
  sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
Labels: Microsoft submitter

#7173 Master to Live
  sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
Labels: Microsoft submitter

#7176 Updated step 5 on app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/media/app-only-auth-role-assignment.png
Labels: area:exchange

#7180 Master to Live
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/media/app-only-auth-role-assignment.png
Labels: Microsoft submitter

#7158 Remove site identity parameter from SPO BYOK Commandlets
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Update-SPODataEncryptionPolicy.md
Labels: area:spo-powershell

#7191 AppAuthUpdate-chrisda to Master
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/media/exo-app-only-auth-admin-consent-granted.png
  exchange/docs-conceptual/media/exo-app-only-auth-app-assigned-to-role.png
  exchange/docs-conceptual/media/exo-app-only-auth-app-registration-page.png
  exchange/docs-conceptual/media/exo-app-only-auth-certificate-successfully-added.png
  exchange/docs-conceptual/media/exo-app-only-auth-find-add-select-app-for-assignment.PNG
  exchange/docs-conceptual/media/exo-app-only-auth-find-and-select-supported-role.png
  exchange/docs-conceptual/media/exo-app-only-auth-manage-ad-view.png
  exchange/docs-conceptual/media/exo-app-only-auth-new-app-registration.png
  exchange/docs-conceptual/media/exo-app-only-auth-original-permissions.png
  exchange/docs-conceptual/media/exo-app-only-auth-register-app.png
  exchange/docs-conceptual/media/exo-app-only-auth-role-assignments-click-add-assignments.png
  exchange/docs-conceptual/media/exo-app-only-auth-role-description-page-click-assignments.PNG
  exchange/docs-conceptual/media/exo-app-only-auth-select-api-permissions.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-app-registrations.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-certificates-and-secrets.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-manifest.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-roles-and-administrators.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-upload-certificate.png
  exchange/docs-conceptual/media/exo-app-only-auth-upload-certificate-dialog.png
Labels: Microsoft submitter

#7192 Master to Live
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/media/exo-app-only-auth-admin-consent-granted.png
  exchange/docs-conceptual/media/exo-app-only-auth-app-assigned-to-role.png
  exchange/docs-conceptual/media/exo-app-only-auth-app-registration-page.png
  exchange/docs-conceptual/media/exo-app-only-auth-certificate-successfully-added.png
  exchange/docs-conceptual/media/exo-app-only-auth-find-add-select-app-for-assignment.PNG
  exchange/docs-conceptual/media/exo-app-only-auth-find-and-select-supported-role.png
  exchange/docs-conceptual/media/exo-app-only-auth-manage-ad-view.png
  exchange/docs-conceptual/media/exo-app-only-auth-new-app-registration.png
  exchange/docs-conceptual/media/exo-app-only-auth-original-permissions.png
  exchange/docs-conceptual/media/exo-app-only-auth-register-app.png
  exchange/docs-conceptual/media/exo-app-only-auth-role-assignments-click-add-assignments.png
  exchange/docs-conceptual/media/exo-app-only-auth-role-description-page-click-assignments.PNG
  exchange/docs-conceptual/media/exo-app-only-auth-select-api-permissions.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-app-registrations.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-certificates-and-secrets.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-manifest.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-roles-and-administrators.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-upload-certificate.png
  exchange/docs-conceptual/media/exo-app-only-auth-upload-certificate-dialog.png
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Update-SPODataEncryptionPolicy.md
Labels: Microsoft submitter

#7193 AppAuthUpdates-chrisda to Master
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#7194 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#7195 Master to Live
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter
