Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2021-08, with the labels that each got.

#8134 Publish 08/02/2021, 10:30 AM
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#8128 Add MeetingRecordingExpirationDays
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: In review, Microsoft submitter, Sign off, area:teams / skype

#8097 Add details to get-sposite for the -GroupIdDefined parameter
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
Labels: In review, Sign off, area:spo-powershell

#8108 Adding Action Announcement & prompt - Fixing #8107
  skype/skype-ps/skype/New-CsAutoAttendantMenuOption.md
Labels: In review, Sign off, area:teams / skype

#8143 Issue #8095
  exchange/exchange-ps/exchange/Remove-UserPhoto.md
  exchange/exchange-ps/exchange/Set-UserPhoto.md
Labels: Microsoft submitter

#8144 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8120 Added TLS 1.2 Note
  skype/skype-ps/skype/Move-CsUser.md
Labels: area:teams / skype, Microsoft submitter, In review, Sign off

#8137 Clarify about template
  teams/teams-ps/teams/New-Team.md
Labels: In review, Sign off

#8145 Update recipientfilter-properties.md
  exchange/docs-conceptual/recipientfilter-properties.md
Labels: area:exchange, Microsoft submitter

#8140 Fixed missing quote in example
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
Labels: area:exchange

#8138 Update Get-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
Labels: area:spo-powershell, Microsoft submitter, In review, Sign off

#8150 Issue #8146
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
Labels: Microsoft submitter

#8151 Publish 08/05/2021, 10:30 AM
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Remove-UserPhoto.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-UserPhoto.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
  skype/skype-ps/skype/Move-CsUser.md
  teams/teams-ps/teams/New-Team.md
Labels: Microsoft submitter

#8139 Add DisableAddShortcutsToOneDrive
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell, Microsoft submitter, In review, Sign off

#8157 Publish 08/06/2021, 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#8159 Added new Get-DynamicDistributionGroupMember cmdlet
  exchange/exchange-ps/exchange/Get-DynamicDistributionGroupMember.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#8155 Update Disable-RemoteMailbox.md
  exchange/exchange-ps/exchange/Disable-RemoteMailbox.md
Labels: area:exchange, Microsoft submitter

#8160 Master to Live
  exchange/exchange-ps/exchange/Disable-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-DynamicDistributionGroupMember.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#8161 Update Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: Microsoft submitter

#8162 Update Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
Labels: area:exchange

#8168 Publish 08/10/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: Microsoft submitter

#8163 Update Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
Labels: area:exchange

#8164 Update New-CSTeamsShiftsPolicy.md
  teams/teams-ps/teams/New-CsTeamsShiftsPolicy.md
Labels: area:teams, Microsoft submitter

#8169 Update Test-IRMConfiguration.md
  exchange/exchange-ps/exchange/Test-IRMConfiguration.md
Labels: Microsoft submitter

#8170 Publish 08/11/2021, 10:30 AM
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Test-IRMConfiguration.md
  teams/teams-ps/teams/New-CsTeamsShiftsPolicy.md
Labels: Microsoft submitter

#8171 Update description for EncryptionTemplateId in New-Label
  exchange/exchange-ps/exchange/New-Label.md
Labels: area:exchange, Microsoft submitter

#8176 Chrisda to Master
  exchange/exchange-ps/exchange/Disable-OutlookAnywhere.md
  exchange/exchange-ps/exchange/Enable-OutlookAnywhere.md
  exchange/exchange-ps/exchange/Get-ManagedFolderMailboxPolicy.md
  exchange/exchange-ps/exchange/New-ClientAccessArray.md
  exchange/exchange-ps/exchange/New-ManagedFolderMailboxPolicy.md
  exchange/exchange-ps/exchange/Remove-ClientAccessArray.md
  exchange/exchange-ps/exchange/Remove-ManagedFolderMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-ClientAccessArray.md
  exchange/exchange-ps/exchange/Set-ManagedFolderMailboxPolicy.md
Labels: Microsoft submitter

#8178 Update Get-DynamicDistributionGroupMember.md
  exchange/exchange-ps/exchange/Get-DynamicDistributionGroupMember.md
Labels: Microsoft submitter

#8182 Publish 08/13/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-DynamicDistributionGroupMember.md
Labels: Microsoft submitter

#8179 Power BI default label supported as policy advanced setting
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter

#8186 Update New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: area:exchange, Microsoft submitter

#8188 Updated [ExceptIf]ContentContainsSensitiveInformation descriptions
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#8189 FindTime-chrisda to Master
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8190 Publish 08/16/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8191 Update Set-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
Labels: Microsoft submitter

#8192 Master to Live
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
Labels: Microsoft submitter

#8193 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: area:exchange, Microsoft submitter

#8200 Update New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
Labels: Microsoft submitter

#8201 Publish 08/17/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8210 Update Set-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
Labels: Microsoft submitter

#8198 Clarifying
  teams/teams-ps/teams/Get-Team.md
Labels: area:teams, In review, Sign off

#8196 Clarifying param use
  skype/skype-ps/skype/Get-CsAutoAttendant.md
Labels: area:teams / skype, In review, Sign off

#8184 Minor spelling fixes
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserAndContentMoveState.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPOrgNewsSite.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchCrawlContentSource.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPO365LinkSettings.md
Labels: area:spo-powershell, In review, Sign off

#8183 Add restrictions for ConcurrentInvitationCount and Paired Applications in CsTeamsComplianceRecordingApplication cmdlets
  skype/skype-ps/skype/New-CsTeamsComplianceRecordingApplication.md
  skype/skype-ps/skype/Set-CsTeamsComplianceRecordingApplication.md
Labels: area:teams / skype, Microsoft submitter, In review, Sign off

#8175 Update Get-SPOStructuralNavigationCacheSiteState.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOStructuralNavigationCacheSiteState.md
Labels: area:spo-powershell, In review, Sign off

#8174 Updated AutoAdmittedUsers description in New/Set-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, In review, Sign off

#8187 [Hold] Update Get-MigrationUser.md
  exchange/exchange-ps/exchange/Get-MigrationUser.md
Labels: area:exchange, Microsoft submitter

#8213 Chrisda to Master
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#8214 Publish 08/19/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-MigrationUser.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOStructuralNavigationCacheSiteState.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserAndContentMoveState.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPOrgAssetsLibrary.md
  sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPOrgNewsSite.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchCrawlContentSource.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPO365LinkSettings.md
  skype/skype-ps/skype/Get-CsAutoAttendant.md
  skype/skype-ps/skype/New-CsTeamsComplianceRecordingApplication.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsComplianceRecordingApplication.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Get-Team.md
Labels: Microsoft submitter

#8215 Added description for RecipientAddressType param
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#8221 Publish 08/20/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#8223 Chrisda to Master
  exchange/exchange-ps/exchange/Add-RoleGroupMember.md
  exchange/exchange-ps/exchange/Remove-RoleGroupMember.md
Labels: Microsoft submitter

#8225 Add periods to alt text
  README.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  repo_docs/ADVANCED.md
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTheme.md
Labels: Microsoft submitter

#8224 Update Set-MailboxCalendarConfiguration and Set-OrganizationConfig
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: area:exchange, Microsoft submitter

#8231 Added link to Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: area:exchange

#8232 Merge master to live 10:30 8/23
  README.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Add-RoleGroupMember.md
  exchange/exchange-ps/exchange/Remove-RoleGroupMember.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  repo_docs/ADVANCED.md
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTheme.md
Labels: Microsoft submitter

#8233 Added "retention" to "label" references in the description
  exchange/exchange-ps/exchange/Enable-ComplianceTagStorage.md
  exchange/exchange-ps/exchange/Get-ComplianceTag.md
  exchange/exchange-ps/exchange/Get-ComplianceTagStorage.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/Remove-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
Labels: Microsoft submitter

#8207 Changing Pipe for ConditionalAccessPolicy
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell, Microsoft submitter, In review, Sign off

#8234 Update New-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/New-InformationBarrierPolicy.md
Labels: Microsoft submitter

#8235 Publish 08/23/2021, 10:30 AM
  exchange/exchange-ps/exchange/Enable-ComplianceTagStorage.md
  exchange/exchange-ps/exchange/Get-ComplianceTag.md
  exchange/exchange-ps/exchange/Get-ComplianceTagStorage.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/Remove-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#8027 Added missing IsWBFluidEnabled Parameter
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell, In review, Sign off

#8211 Update Request-SPOPersonalSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md
Labels: area:spo-powershell, Microsoft submitter, In review, Sign off

#8238 Merge master to live, 10:30 AM 8/24
  sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#8034 Add External User Expiration Info
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: area:spo-powershell, Microsoft submitter

#8241 Update Set-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
Labels: area:teams / skype

#8248 Update never expire option
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#8244 Improve `EnabledWithoutIVR` details
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#8270 Publish 08/31/2021, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter
