Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2021-07, with the labels that each got.

#8014 Chrisda to Master
  exchange/exchange-ps/exchange/New-MailboxRepairRequest.md
Labels: Microsoft submitter

#7996 Update New-CsExternalAccessPolicy.md
  skype/skype-ps/skype/New-CsExternalAccessPolicy.md
Labels: In review, Sign off, area:teams / skype

#8015 Publish 07/02/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-MailboxRepairRequest.md
  skype/skype-ps/skype/New-CsExternalAccessPolicy.md
Labels: Microsoft submitter

#7961 Adding docs for Shifts Connector
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionUser.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md
Labels: In review, Sign off, area:teams

#8017 SkipRules-chrisda to Master
  exchange/exchange-ps/exchange/New-MigrationBatch.md
Labels: Microsoft submitter

#8018 Master to Live
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionUser.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md
Labels: Microsoft submitter

#8003 Updating Set-SPOTenant docs with new param details
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Sign off, area:spo-powershell

#8019 Update Get-SPOSiteRenameState.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteRenameState.md
Labels: In review, Microsoft submitter, Sign off, area:spo-powershell

#8025 Correcting description
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteGroup.md
Labels: In review, Sign off, area:spo-powershell

#8032 Publish 07/08/2021, 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteRenameState.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#8039 Chrisda to Master
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
Labels: Microsoft submitter

#8042 Chrisda to Master
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Remove-Mailbox.md
  exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md
Labels: Microsoft submitter

#8022 TargetDeliveryDomain_for_Onboarding.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
Labels: Microsoft submitter, area:exchange

#8036 Added recipientfilter limit (2048 characters)
  exchange/exchange-ps/exchange/New-DynamicDistributionGroup.md
Labels: area:exchange

#8043 Master to Live
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Remove-Mailbox.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md
Labels: Microsoft submitter

#8024 Adding EnableCORS
  skype/skype-ps/skype/Set-CsAutodiscoverConfiguration.md
Labels: In review, Sign off, area:teams / skype

#8050 Publish 07/14/2021, 10:30 AM
  skype/skype-ps/skype/Set-CsAutodiscoverConfiguration.md
Labels: Microsoft submitter

#8052 Chrisda to Master
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentDetail.md
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentReport.md
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionTrafficReport.md
  exchange/exchange-ps/exchange/Get-DlpDetailReport.md
  exchange/exchange-ps/exchange/Get-DlpDetectionsReport.md
  exchange/exchange-ps/exchange/Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/Get-MailDetailDlpPolicyReport.md
  exchange/exchange-ps/exchange/Get-MailDetailMalwareReport.md
  exchange/exchange-ps/exchange/Get-MailDetailSpamReport.md
  exchange/exchange-ps/exchange/Get-MailDetailTransportRuleReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficPolicyReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md
  exchange/exchange-ps/exchange/Get-SpoofMailReport.md
  exchange/exchange-ps/exchange/Remove-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#8054 Updated descriptions to for multi-workload
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
Labels: area:exchange

#7984 Hide Set-CsGroupPolicyAssignment
  teams/teams-ps/teams/Set-CsGroupPolicyAssignment.md
Labels: In review, Microsoft submitter, Sign off, area:teams

#8059 Publish 07/15/2021, 10:30 AM
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentDetail.md
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentReport.md
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionTrafficReport.md
  exchange/exchange-ps/exchange/Get-DlpDetailReport.md
  exchange/exchange-ps/exchange/Get-DlpDetectionsReport.md
  exchange/exchange-ps/exchange/Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/Get-MailDetailDlpPolicyReport.md
  exchange/exchange-ps/exchange/Get-MailDetailMalwareReport.md
  exchange/exchange-ps/exchange/Get-MailDetailSpamReport.md
  exchange/exchange-ps/exchange/Get-MailDetailTransportRuleReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficPolicyReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md
  exchange/exchange-ps/exchange/Get-SpoofMailReport.md
  exchange/exchange-ps/exchange/New-M365DataAtRestEncryptionPolicy.md
  exchange/exchange-ps/exchange/Remove-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Set-User.md
  teams/teams-ps/teams/Set-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#8061 Chrisda to Master
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailDetailMalwareReport.md
  exchange/exchange-ps/exchange/Get-MailDetailSpamReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficReport.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
Labels: Microsoft submitter

#8060 Add powerbimandatory as advanced setting for sensitivity labels
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter

#8067 Publish 07/16/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailDetailMalwareReport.md
  exchange/exchange-ps/exchange/Get-MailDetailSpamReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficReport.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
Labels: Microsoft submitter

#8055 Additional example to get Groups backing Teams
  exchange/exchange-ps/exchange/Get-UnifiedGroup.md
Labels: area:exchange

#8070 CIDR IP subnet mask clarification
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
Labels: Microsoft submitter, area:exchange

#8073 Publish 07/19/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-UnifiedGroup.md
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
Labels: Microsoft submitter

#8049 Update multiple versions note
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
Labels: Microsoft submitter, Sign off, area:spo-powershell

#8072 Adding new setting -ChannelRecordingDownload
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: In review, Microsoft submitter, Sign off

#8076 Chrisda to Master
  exchange/exchange-ps/exchange/Disable-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Enable-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentRule.md
Labels: Microsoft submitter

#8081 Publish 07/20/2021, 10:30 AM
  exchange/exchange-ps/exchange/Disable-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Enable-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentRule.md
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#8080 Fixed typo in 'can'
  exchange/exchange-ps/exchange/New-JournalRule.md
Labels: Microsoft submitter, area:exchange

#8084 Publish 07/21/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-JournalRule.md
Labels: Microsoft submitter

#8087 Chrisda to Master
  exchange/exchange-ps/exchange/Add-IPAllowListEntry.md
  exchange/exchange-ps/exchange/Add-IPBlockListEntry.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-ClientAccessRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/New-OutboundConnector.md
  exchange/exchange-ps/exchange/New-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/New-ReceiveConnector.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-HostedConnectionFilterPolicy.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OutboundConnector.md
  exchange/exchange-ps/exchange/Set-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Set-ReceiveConnector.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#8088 Fixed typo in second example
  exchange/exchange-ps/exchange/Test-TextExtraction.md
Labels: Microsoft submitter, area:exchange

#8089 Fixed variable name and typos in the examples
  exchange/exchange-ps/exchange/Test-TextExtraction.md
Labels: Microsoft submitter, area:exchange

#8092 Update New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: Microsoft submitter

#8096 Publish 07/22/2021, 10:30 AM
  exchange/exchange-ps/exchange/Add-IPAllowListEntry.md
  exchange/exchange-ps/exchange/Add-IPBlockListEntry.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-ClientAccessRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/New-OutboundConnector.md
  exchange/exchange-ps/exchange/New-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/New-ReceiveConnector.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-HostedConnectionFilterPolicy.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OutboundConnector.md
  exchange/exchange-ps/exchange/Set-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Set-ReceiveConnector.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
  exchange/exchange-ps/exchange/Test-TextExtraction.md
Labels: Microsoft submitter

#8104 Update New-Label.md
  exchange/exchange-ps/exchange/New-Label.md
Labels: area:exchange

#8112 Update Set-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#8114 Publish 07/26/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#8098 Added two new examples to related to Teams
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
Labels: Microsoft submitter, Sign off, area:spo-powershell

#8105 Fix description
  skype/skype-ps/skype/New-CsTeamsNetworkRoamingPolicy.md
Labels: In review, Sign off, area:teams / skype

#8118 Publish 07/27/2021, 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPTrustedRootAuthority.md
  skype/skype-ps/skype/New-CsTeamsNetworkRoamingPolicy.md
Labels: Microsoft submitter

#8071 Improved inaccurate description
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
Labels: In review, Microsoft submitter, Sign off, area:teams / skype

#8069 added filter example
  skype/skype-ps/skype/Get-CsTenantNetworkSite.md
Labels: In review, Sign off, area:teams / skype

#8119 Update Get-OrganizationSegment.md
  exchange/exchange-ps/exchange/Get-OrganizationSegment.md
Labels: area:exchange

#8101 Add example about enabling account
  skype/skype-ps/skype/Enable-CsUser.md
Labels: In review, Sign off, area:teams / skype

#8123 Publish 07/28/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-OrganizationSegment.md
  skype/skype-ps/skype/Enable-CsUser.md
  skype/skype-ps/skype/Get-CsTenantNetworkSite.md
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
Labels: Microsoft submitter

#8099 Add StopNew2013Workflows param to Set-SPOTenant
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off, area:spo-powershell

#8127 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter, area:exchange

#8130 Publish 07/30/2021, 10:30 AM
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#8129 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter
