Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2021-11, with the labels that each got.

#8539 Chrisda to Master
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
Labels: Microsoft submitter

#8541 Publish 11/02/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
Labels: Microsoft submitter

#8535 Update Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: area:teams, Microsoft submitter

#8542 Chrisda to Master
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter

#8543 Publish 11/02/2021, 3:30 PM
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: Microsoft submitter

#8546 Chrisda to Master
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#8551 Publish 11/04/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Get-ComplianceCaseMember.md
  exchange/exchange-ps/exchange/Get-DlpDetailReport.md
  exchange/exchange-ps/exchange/Get-PolicyConfig.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/New-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Remove-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Set-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/Set-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListSpoofItems.md
Labels: Microsoft submitter

#8553 Chrisda to Master
  exchange/exchange-ps/exchange/Enable-Mailbox.md
  exchange/exchange-ps/exchange/Enable-RemoteMailbox.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-RemoteMailbox.md
Labels: Microsoft submitter

#8557 Publish 11/05/2021, 10:30 AM
  exchange/exchange-ps/exchange/Enable-Mailbox.md
  exchange/exchange-ps/exchange/Enable-RemoteMailbox.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-RemoteMailbox.md
Labels: Microsoft submitter

#8559 Fixed Identity param description in Get-DLPPolicy
  exchange/exchange-ps/exchange/Get-DlpPolicy.md
  exchange/exchange-ps/exchange/New-DlpPolicy.md
  exchange/exchange-ps/exchange/Remove-DlpPolicy.md
  exchange/exchange-ps/exchange/Set-DlpPolicy.md
Labels: Microsoft submitter

#8565 Publish 11/05/2021, 3:30 PM
  .gitignore
  exchange/exchange-ps/exchange/Get-DlpPolicy.md
  exchange/exchange-ps/exchange/New-DlpPolicy.md
  exchange/exchange-ps/exchange/Remove-DlpPolicy.md
  exchange/exchange-ps/exchange/Set-DlpPolicy.md
Labels: Microsoft submitter

#8544 Adding Parameter for -AllowCartCaptionsScheduling
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#8569 Publish 11/08/2021, 10:30 AM
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#8560 Create export-csonlineaudiofile.md
  skype/skype-ps/skype/Get-CsOnlineAudioFile.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/New-CsOnlineAudioFile.md
  skype/skype-ps/skype/Remove-CsOnlineAudioFile.md
  skype/skype-ps/skype/export-csonlineaudiofile.md
Labels: Microsoft submitter

#8571 Publish 11/08/2021, 3:30 PM
  exchange/exchange-ps/exchange/Get-MailboxJunkEmailConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxJunkEmailConfiguration.md
  skype/skype-ps/skype/Get-CsOnlineAudioFile.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/New-CsOnlineAudioFile.md
  skype/skype-ps/skype/Remove-CsOnlineAudioFile.md
  skype/skype-ps/skype/export-csonlineaudiofile.md
Labels: Microsoft submitter

#8572 Fixed minor cmdlet topic issues.
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Disable-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-MigrationUser.md
  exchange/exchange-ps/exchange/Get-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/New-OutboundConnector.md
  exchange/exchange-ps/exchange/Remove-DlpPolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpKeywordDictionary.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Test-TextExtraction.md
Labels: Microsoft submitter

#8570 Update Export-CsOrganizationalAutoAttendantHolidays.md
  skype/skype-ps/skype/Export-CsOrganizationalAutoAttendantHolidays.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendant.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantHolidays.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantStatus.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantSupportedLanguage.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantSupportedTimeZone.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantTenantInformation.md
  skype/skype-ps/skype/Import-CsOrganizationalAutoAttendantHolidays.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendant.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantCallFlow.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantCallHandlingAssociation.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantCallableEntity.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantDialScope.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantMenu.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantMenuOption.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantPrompt.md
  skype/skype-ps/skype/Remove-CsOrganizationalAutoAttendant.md
  skype/skype-ps/skype/Set-CsOrganizationalAutoAttendant.md
  skype/skype-ps/skype/Update-CsOrganizationalAutoAttendant.md
Labels: Microsoft submitter

#8573 Publish 11/09/2021, 10:30 AM
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Disable-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-MigrationUser.md
  exchange/exchange-ps/exchange/Get-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/New-OutboundConnector.md
  exchange/exchange-ps/exchange/Remove-DlpPolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpKeywordDictionary.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Test-TextExtraction.md
  skype/skype-ps/skype/Export-CsOrganizationalAutoAttendantHolidays.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendant.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantHolidays.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantStatus.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantSupportedLanguage.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantSupportedTimeZone.md
  skype/skype-ps/skype/Get-CsOrganizationalAutoAttendantTenantInformation.md
  skype/skype-ps/skype/Import-CsOrganizationalAutoAttendantHolidays.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendant.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantCallFlow.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantCallHandlingAssociation.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantCallableEntity.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantDialScope.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantMenu.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantMenuOption.md
  skype/skype-ps/skype/New-CsOrganizationalAutoAttendantPrompt.md
  skype/skype-ps/skype/Remove-CsOrganizationalAutoAttendant.md
  skype/skype-ps/skype/Set-CsOrganizationalAutoAttendant.md
  skype/skype-ps/skype/Update-CsOrganizationalAutoAttendant.md
Labels: Microsoft submitter

#8575 Update New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#8577 Publish 11/09/2021, 3:30 PM
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#8576 Chrisda to Master
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-CASMailbox.md
Labels: area:exchange, Microsoft submitter

#8585 Publish 11/11/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-CASMailbox.md
Labels: Microsoft submitter

#8586 Chrisda to Master
  exchange/exchange-ps/exchange/Get-ComplianceCaseMember.md
  exchange/exchange-ps/exchange/Get-PolicyConfig.md
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/Set-SupervisoryReviewRule.md
Labels: Microsoft submitter

#8520 Update New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
Labels: area:exchange

#8588 Publish 11/11/2021, 3:30 PM
  exchange/exchange-ps/exchange/Get-ComplianceCaseMember.md
  exchange/exchange-ps/exchange/Get-PolicyConfig.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/Set-SupervisoryReviewRule.md
Labels: Microsoft submitter

#8584 Add DiscoveryHolds value and its description for 'SourceFolder' param.
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
Labels: area:exchange

#8593 Publish 11/12/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
Labels: Microsoft submitter

#8599 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8600 Update New-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#8604 Publish 11/15/2021, 3:30 PM
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#8605 Update disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
Labels: Microsoft submitter

#8591 Isrumnon patch 1
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
Labels: area:teams / skype, Microsoft submitter

#8590 Isrumnon patch 2
  skype/skype-ps/skype/Get-CsTenant.md
Labels: area:teams / skype, Microsoft submitter

#8589 Isrumnon patch 3
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype, Microsoft submitter

#8587 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype, Microsoft submitter

#8579 PhoneNumberAssignment and TeamsUnassignedNumberTreatment changes
  teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
Labels: area:teams, Microsoft submitter

#8334 Extended SpamFilteringEnabledType Description
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: area:teams / skype

#8610 Publish 11/16/2021, 10:30 AM
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
  skype/skype-ps/skype/Get-CsTenant.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
Labels: Microsoft submitter

#8574 Update export-csonlineaudiofile.md
  skype/skype-ps/skype/export-csonlineaudiofile.md
Labels: area:teams / skype, Microsoft submitter

#8611 Update New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
Labels: Microsoft submitter

#8606 Update New-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: area:teams, Microsoft submitter

#8612 Publish 11/16/2021, 3:30 PM
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
  skype/skype-ps/skype/export-csonlineaudiofile.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#8601 Removed ExternalInOutlookEnabled and added link to Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: area:exchange

#8615 Fix spaces from line in Set-CsPhoneNumberAssignment
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#8607 Add one more support language
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#8598 Remove preview not on onlineaudiofile cmdlets
  skype/skype-ps/skype/Get-CsOnlineAudioFile.md
  skype/skype-ps/skype/Remove-CsOnlineAudioFile.md
Labels: area:teams / skype, Microsoft submitter

#8602 Update Priority description in New/Set-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/New-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md
Labels: area:teams / skype

#8616 Publish 11/17/2021, 10:30 AM
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  skype/skype-ps/skype/Get-CsOnlineAudioFile.md
  skype/skype-ps/skype/New-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Remove-CsOnlineAudioFile.md
  skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#8617 Update Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
Labels: Microsoft submitter

#8619 Publish 11/17/2021, 3:30 PM
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
Labels: Microsoft submitter

#8618 Update AdmitAnonymousUsersByDefault description in Set-CsMeetingConfiguration.md
  skype/skype-ps/skype/Set-CsMeetingConfiguration.md
Labels: area:teams / skype

#8630 Publish 11/22/2021, 10:30 AM
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsMeetingConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#8625 Update creating and updating connection instance cmdlets by adding one parameter
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md
Labels: area:teams, Microsoft submitter

#8634 Publish 11/23/2021, 10:30 AM
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md
Labels: Microsoft submitter

#8635 Update links in -AllowAnonymousUsersToJoinMeeting param documentation.
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#8636 Publish 11/23/2021, 3:30 PM
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#8637 Update Set-OMEConfiguration.md
  exchange/exchange-ps/exchange/Set-OMEConfiguration.md
Labels: area:exchange, Microsoft submitter

#8645 Publish 11/29/2021, 10:30 AM
  exchange/exchange-ps/exchange/Set-OMEConfiguration.md
Labels: Microsoft submitter

#8646 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8650 Publish 11/30/2021, 10:30 AM
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter
