Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2021-09, with the labels that each got.

#8271 Update Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: area:exchange, Microsoft submitter

#8272 Update New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: area:exchange, Microsoft submitter

#8276 Publish 09/01/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#8281 Chrisda to Master
  exchange/exchange-ps/exchange/Remove-Mailbox.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8288 Publish 09/02/2021, 10:30 AM
  exchange/exchange-ps/exchange/Remove-Mailbox.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8289 Update Get-RMSTrustedPublishingDomain.md
  exchange/exchange-ps/exchange/Get-RMSTrustedPublishingDomain.md
Labels: Microsoft submitter

#8290 Update Move-CsUser.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: area:teams / skype, Microsoft submitter

#8294 Publish 09/03/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-RMSTrustedPublishingDomain.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#8303 Chrisda to Master
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
Labels: Microsoft submitter

#8304 AppRetComp to Master
  exchange/exchange-ps/exchange/Get-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Remove-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#8269 Update Get-CsTenant.md
  skype/skype-ps/skype/Get-CsTenant.md
Labels: area:teams / skype, Microsoft submitter

#8253 Added MeetingRecordingExpirationDays to New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype

#8263 Fix example
  sharepoint/sharepoint-ps/sharepoint-server/Add-SPClaimTypeMapping.md
Labels: area:sp-server-powershell

#8266 Update Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: area:teams

#8267 Update Set-CsClsConfiguration.md
  skype/skype-ps/skype/Set-CsClsConfiguration.md
Labels: Microsoft submitter

#8277 Correct param desc
  sharepoint/sharepoint-ps/sharepoint-server/New-SPProfileServiceApplication.md
Labels: area:sp-server-powershell

#8279 Update EmailAttestationRequired
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell, Microsoft submitter

#8280 Removed Public preview reference
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell, Microsoft submitter

#8308 Publish 09/08/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Remove-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-server/Add-SPClaimTypeMapping.md
  sharepoint/sharepoint-ps/sharepoint-server/New-SPProfileServiceApplication.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsTenant.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsCallQueue.md
  skype/skype-ps/skype/Set-CsClsConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: Microsoft submitter

#8309 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#7817 Add documentation for all TeamsCallHoldPolicy cmdlets
  skype/skype-ps/skype/Get-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/skype.md
Labels: area:teams / skype, Microsoft submitter, Do not merge

#8301 Updated OnlineAudioFile PS cmdlet description
  skype/skype-ps/skype/Get-CsOnlineAudioFile.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/Remove-CsOnlineAudioFile.md
Labels: area:teams / skype, Microsoft submitter

#8314 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8315 Chrisda to Master
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8317 Update Get-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Get-CsTeamsCallHoldPolicy.md
Labels: Microsoft submitter

#8316 Master to Live
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  skype/skype-ps/skype/Get-CsOnlineAudioFile.md
  skype/skype-ps/skype/Get-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/New-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Remove-CsOnlineAudioFile.md
  skype/skype-ps/skype/Remove-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter, Do not merge

#8318 Update Get-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Get-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallHoldPolicy.md
Labels: Microsoft submitter

#8310 PermanentlyClearPreviousMailboxInfo
  exchange/exchange-ps/exchange/Set-User.md
Labels: area:exchange

#8283 Update SyncPrivacyProfileProperties
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell, Microsoft submitter

#8291 Add ViewInFileExplorerEnabled
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: area:spo-powershell, Microsoft submitter

#8287 Update Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: area:teams, Microsoft submitter

#8298 Batch 4 of Grant cmdlet updates
  skype/skype-ps/skype/Grant-CsTenantDialPlan.md
  skype/skype-ps/skype/Grant-CsVoiceRoutingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#8297 Batch 3 of Grant cmdlet updates
  skype/skype-ps/skype/Grant-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsComplianceRecordingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCortanaPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsEmergencyCallRoutingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsFeedbackPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMessagingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMobilityPolicy.md
Labels: area:teams / skype, Microsoft submitter

#8296 Batch 2 of Grant Cmdlets Updates
  skype/skype-ps/skype/Grant-CsHostedVoicemailPolicy.md
  skype/skype-ps/skype/Grant-CsIPPhonePolicy.md
  skype/skype-ps/skype/Grant-CsMobilityPolicy.md
  skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppSetupPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#8319 loc updates
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/filter-properties.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/use-update-exchangehelp.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/docs-conceptual/values-for-custompropertynames-parameter.md
  sharepoint/docs-conceptual/index.yml
  skype/docs-conceptual/index.md
  skype/docs-conceptual/intro.md
  skype/skype-ps/skype/Get-CsMeetingConfiguration.md
  spmt/docs-conceptual/index.md
  spmt/docs-conceptual/intro.md
  teams/docs-conceptual/index.md
  teams/docs-conceptual/intro.md
Labels: Microsoft submitter

#8295 Batch 1 of Grant Cmdlets Updates
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Grant-CsBroadcastMeetingPolicy.md
  skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
  skype/skype-ps/skype/Grant-CsClientPolicy.md
  skype/skype-ps/skype/Grant-CsCloudMeetingPolicy.md
  skype/skype-ps/skype/Grant-CsExternalAccessPolicy.md
  skype/skype-ps/skype/Grant-CsExternalUserCommunicationPolicy.md
  skype/skype-ps/skype/Grant-CsGraphPolicy.md
Labels: area:teams / skype, Microsoft submitter

#8324 Publish 09/10/2021, 10:30 AM
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Grant-CsBroadcastMeetingPolicy.md
  skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
  skype/skype-ps/skype/Grant-CsClientPolicy.md
  skype/skype-ps/skype/Grant-CsCloudMeetingPolicy.md
  skype/skype-ps/skype/Grant-CsExternalAccessPolicy.md
  skype/skype-ps/skype/Grant-CsExternalUserCommunicationPolicy.md
  skype/skype-ps/skype/Grant-CsGraphPolicy.md
Labels: Microsoft submitter

#8284 Added details on ChannelUserObjectId
  skype/skype-ps/skype/New-CsCallQueue.md
Labels: area:teams / skype

#8329 Publish 09/13/2021, 10:30 AM
  skype/skype-ps/skype/New-CsCallQueue.md
Labels: Microsoft submitter

#8332 Chrisda to Master
  exchange/exchange-ps/exchange/Get-ATPTotalTrafficReport.md
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentReport.md
  exchange/exchange-ps/exchange/Get-DlpDetectionsReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficPolicyReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md
  exchange/exchange-ps/exchange/Get-SafeLinksAggregateReport.md
Labels: Microsoft submitter

#8325 Fix typo
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: area:exchange

#8330 Update New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
Labels: area:exchange, Microsoft submitter

#8337 Publish 09/14/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-ATPTotalTrafficReport.md
  exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentReport.md
  exchange/exchange-ps/exchange/Get-DlpDetectionsReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficPolicyReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md
  exchange/exchange-ps/exchange/Get-SafeLinksAggregateReport.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter

#8327 Updates for making .md files compatible for PlatyPS .xml conversion
  teams/teams-ps/teams/Get-CsTeamTemplate.md
  teams/teams-ps/teams/Get-CsTeamTemplateList.md
  teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
  teams/teams-ps/teams/Remove-CsTeamTemplate.md
  teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md
  teams/teams-ps/teams/Set-TeamTargetingHierarchy.md
Labels: area:teams

#8341 Publish 09/15/2021, 10:30 AM
  teams/teams-ps/teams/Get-CsTeamTemplate.md
  teams/teams-ps/teams/Get-CsTeamTemplateList.md
  teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
  teams/teams-ps/teams/Remove-CsTeamTemplate.md
  teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md
  teams/teams-ps/teams/Set-TeamTargetingHierarchy.md
Labels: Microsoft submitter

#8342 Inbound connector edits (no new functionality)
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
Labels: Microsoft submitter

#8345 Publish 09/16/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
Labels: Microsoft submitter

#7609 Update Get-SafeLinksDetailReport.md
  exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md
Labels: area:exchange

#8356 Publish 09/17/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md
Labels: Microsoft submitter

#8357 Chrisda to Master
  exchange/exchange-ps/exchange/New-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: Microsoft submitter

#8353 Add clarification about mailbox moves within EXO
  exchange/exchange-ps/exchange/New-MoveRequest.md
Labels: area:exchange

#8364 Additions
  exchange/exchange-ps/exchange/New-MobileDeviceMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-MobileDeviceMailboxPolicy.md
Labels: Microsoft submitter

#8365 Publish 09/20/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/New-MobileDeviceMailboxPolicy.md
  exchange/exchange-ps/exchange/New-MoveRequest.md
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-MobileDeviceMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: Microsoft submitter

#8360 Application parameter incorrect
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: area:exchange, Microsoft submitter

#8361 Application parameter incorrect
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
Labels: area:exchange, Microsoft submitter

#8367 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8374 [ExceptIf]AnyOfRecipientAddress params don't work right in ExO
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#8378 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#8379 Publish 09/24/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#8377 Create Get-SPOTenantRenameStatus
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRenameStatus
Labels: area:spo-powershell, Microsoft submitter

#8388 QT-chrisda to Master
  exchange/exchange-ps/exchange/Get-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-QuarantinePermissions.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Remove-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-QuarantinePermissions.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#8372 Exchange Server CU updates to Powershell
  exchange/exchange-ps/exchange/Set-ExchangeServer.md
Labels: area:exchange, Microsoft submitter, Do not merge

#8389 PhishSim-chrisda to Master
  exchange/exchange-ps/exchange/New-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Set-PhishSimOverrideRule.md
Labels: Microsoft submitter

#8390 Publish 09/28/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/New-QuarantinePermissions.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Remove-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-ExchangeServer.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Set-QuarantinePermissions.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRenameStatus
Labels: Microsoft submitter

#8373 Update text for Set-CsOnlineEnhancedEmergencyServiceDisclaimer
  skype/skype-ps/skype/Set-CsOnlineEnhancedEmergencyServiceDisclaimer.md
Labels: area:teams / skype, Microsoft submitter

#8393 Update New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
Labels: Microsoft submitter

#8394 Add advanced settings for default sharing link to new/set-label
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: area:exchange, Microsoft submitter

#8397 Chrisda to Master
  exchange/exchange-ps/exchange/Set-EventsFromEmailConfiguration.md
Labels: Microsoft submitter

#8398 Publish 09/29/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Set-EventsFromEmailConfiguration.md
  exchange/exchange-ps/exchange/Set-Label.md
  skype/skype-ps/skype/Set-CsOnlineEnhancedEmergencyServiceDisclaimer.md
Labels: Microsoft submitter

#8396 Update multi-language meeting invite control document
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype
