Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2021-04, with the labels that each got.

#7513 Update Set-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/Set-OwnerlessGroupPolicy.md
Labels: area:exchange

#7527 Maximum value of 100000 is misleading
  exchange/exchange-ps/exchange/Get-MessageTrace.md
Labels: Microsoft submitter, area:exchange

#7512 Update Get-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/Get-OwnerlessGroupPolicy.md
Labels: area:exchange

#7501 Correction on importance of the pfx file
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: area:exchange

#7535 Chrisda to Master
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
Labels: Microsoft submitter

#7537 Publish 04/01/2021, 4:30 PM (late due to DNS outage)
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Get-MessageTrace.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
Labels: Microsoft submitter

#7542 Update connect-to-scc-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter, area:exchange

#7543 Publish 4/5/2021 10:30 AM PT
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter

#7545 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#7546 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#7547 Publish 04/05/2021, 3:30 PM
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#7529 Correct examples and adding description
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOGeoStorageQuota.md
Labels: In review, Sign off, area:spo-powershell

#7526 Improving description
  teams/teams-ps/teams/Get-Team.md
Labels: In review, Sign off, area:teams

#7530 Correcting link
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
Labels: In review, Sign off, area:spo-powershell

#7550 Publish 04/06/2021, 3:30 PM
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOGeoStorageQuota.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  teams/teams-ps/teams/Get-Team.md
Labels: Microsoft submitter

#7531 Update documentation for BusyOnBusyEnabledType parameter in Set-CsTeamsCallingPolicy cmdlet
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: In review, Sign off

#7554 Publish 4/7/2021 10:30 AM PT
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter

#7556 Description for RecommendedPolicyType parameter
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-HostedOutboundSpamFilterPolicy.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
Labels: Microsoft submitter

#7558 Publish 04/07/2021, 3:30 PM
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-HostedOutboundSpamFilterPolicy.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
Labels: Microsoft submitter

#7564 Update New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
Labels: Microsoft submitter

#7565 Publish 4/8/2021 10:30 AM PT
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
Labels: Microsoft submitter

#7566 'bulk compliant' to 'bulk complaint'
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
Labels: Microsoft submitter

#7567 Chrisda to Master
  exchange/exchange-ps/exchange/New-ActivityAlert.md
  exchange/exchange-ps/exchange/New-ProtectionAlert.md
  exchange/exchange-ps/exchange/Set-ProtectionAlert.md
Labels: Microsoft submitter

#7568 Master to Live
  exchange/exchange-ps/exchange/New-ActivityAlert.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-ProtectionAlert.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-ProtectionAlert.md
Labels: Microsoft submitter

#7572 Update New-LabelPolicy.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
Labels: Microsoft submitter

#7573 Update Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter, area:exchange

#7574 Publish 04/09/2021 10:30AM PT
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter

#7577 Update exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#7578 Feedback-chrisda to Master
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#7581 Chrisda to Master
  exchange/exchange-ps/exchange/Get-HybridMailflow.md
  exchange/exchange-ps/exchange/Get-HybridMailflowDatacenterIPs.md
  exchange/exchange-ps/exchange/Import-RMSTrustedPublishingDomain.md
Labels: Microsoft submitter

#7582 Publish 04/09/2021, 3:30 PM
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-HybridMailflow.md
  exchange/exchange-ps/exchange/Get-HybridMailflowDatacenterIPs.md
  exchange/exchange-ps/exchange/Import-RMSTrustedPublishingDomain.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#7589 Apps-chrisda to Master
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#7590 Master to Live
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#7583 Update Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
Labels: Microsoft submitter, area:exchange

#7591 Publish 04/12/2021, 3:30 PM
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
Labels: Microsoft submitter

#7598 Chrisda to Master
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/media/connect-exo-mfa-verify-prompt.png
  exchange/docs-conceptual/media/connect-exo-password-prompt.png
  exchange/exchange-ps/exchange/Set-IRMConfiguration.md
Labels: Microsoft submitter

#7599 Publish 04/13/2021, 3:30 PM
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/media/connect-exo-mfa-verify-prompt.png
  exchange/docs-conceptual/media/connect-exo-password-prompt.png
  exchange/exchange-ps/exchange/Set-IRMConfiguration.md
Labels: Microsoft submitter

#7557 Update Set-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#7594 Update Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
Labels: Microsoft submitter, area:exchange

#7595 Update Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
Labels: Microsoft submitter, area:exchange

#7603 Publish 04/14/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#7596 Update Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
Labels: Microsoft submitter, area:exchange

#7597 Update Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
Labels: Microsoft submitter, area:exchange

#7605 Update Get-DlpSiDetectionsReport.md
  exchange/exchange-ps/exchange/Get-DlpSiDetectionsReport.md
Labels: Microsoft submitter

#7613 Publish 04/14/2021, 3:30 PM
  exchange/exchange-ps/exchange/Get-DlpSiDetectionsReport.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
Labels: Microsoft submitter

#7615 AccessRight param consistency updates
  exchange/exchange-ps/exchange/Add-ADPermission.md
  exchange/exchange-ps/exchange/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Add-RecipientPermission.md
  exchange/exchange-ps/exchange/Add-RoleGroupMember.md
  exchange/exchange-ps/exchange/Get-ADPermission.md
  exchange/exchange-ps/exchange/Get-EXORecipientPermission.md
  exchange/exchange-ps/exchange/Get-MailboxPermission.md
  exchange/exchange-ps/exchange/Get-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/Get-RecipientPermission.md
  exchange/exchange-ps/exchange/New-AvailabilityConfig.md
  exchange/exchange-ps/exchange/Remove-ADPermission.md
  exchange/exchange-ps/exchange/Remove-MailboxPermission.md
  exchange/exchange-ps/exchange/Remove-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/Remove-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Remove-RecipientPermission.md
  exchange/exchange-ps/exchange/Remove-RoleGroupMember.md
  exchange/exchange-ps/exchange/Set-AvailabilityConfig.md
Labels: Microsoft submitter

#7616 Update Set-TransportConfig.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter, area:exchange

#7620 Publish 04/15/2021, 10:30 AM
  exchange/exchange-ps/exchange/Add-ADPermission.md
  exchange/exchange-ps/exchange/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Add-RecipientPermission.md
  exchange/exchange-ps/exchange/Add-RoleGroupMember.md
  exchange/exchange-ps/exchange/Get-ADPermission.md
  exchange/exchange-ps/exchange/Get-EXORecipientPermission.md
  exchange/exchange-ps/exchange/Get-MailboxPermission.md
  exchange/exchange-ps/exchange/Get-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/Get-RecipientPermission.md
  exchange/exchange-ps/exchange/New-AvailabilityConfig.md
  exchange/exchange-ps/exchange/Remove-ADPermission.md
  exchange/exchange-ps/exchange/Remove-MailboxPermission.md
  exchange/exchange-ps/exchange/Remove-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/Remove-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Remove-RecipientPermission.md
  exchange/exchange-ps/exchange/Remove-RoleGroupMember.md
  exchange/exchange-ps/exchange/Set-AvailabilityConfig.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter

#7619 Chrisda to Master
  exchange/exchange-ps/exchange/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/Get-UserPhoto.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Remove-MailboxPermission.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#7607 Missing formatting mark
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: area:exchange

#7612 Adding example
  exchange/exchange-ps/exchange/Disable-App.md
  exchange/exchange-ps/exchange/Enable-App.md
Labels: area:exchange

#7624 Publish 04/15/2021, 3:30 PM
  exchange/exchange-ps/exchange/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/Disable-App.md
  exchange/exchange-ps/exchange/Enable-App.md
  exchange/exchange-ps/exchange/Get-UserPhoto.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Remove-MailboxPermission.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#7625 Update AdvancedSettings in Set-LabelPolicy & New-LabelPolicy
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter

#7570 Update Set-CsConferencingConfiguration.md
  skype/skype-ps/skype/Set-CsConferencingConfiguration.md
Labels: In review, Microsoft submitter, Sign off

#7629 Publish 04/16/2021, OOB
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  skype/skype-ps/skype/Set-CsConferencingConfiguration.md
Labels: Microsoft submitter

#7630 Update Get-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/Get-ComplianceSearchAction.md
Labels: Microsoft submitter

#7632 Update Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/Get-MailDetailATPReport.md
Labels: Microsoft submitter

#7633 Publish 04/16/2021, 3:30 PM
  exchange/exchange-ps/exchange/Get-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/Get-MailDetailATPReport.md
Labels: Microsoft submitter

#7561 Set-CsTeamsMeetingPolicy AllowEngagementReport
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off

#7102 Adding missing desc
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMigrationPackageAzureSource.md
Labels: In review, Sign off, area:spo-powershell

#7553 Update description of "allowShareFile" on Set-CsTeamsClientConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsClientConfiguration.md
Labels: In review, Sign off

#7483 Update Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
Labels: In review, Sign off, area:teams / skype

#7521 Added note about tenant with RHM enabled
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter, Sign off, area:teams / skype

#7520 Adding note about Tenant to consider when RHM is enabled.
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: Microsoft submitter, Sign off, area:teams / skype

#7517 Update Set-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingBroadcastPolicy.md
Labels: In review, Microsoft submitter, Sign off

#7508 Updating param desc
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off, area:teams / skype

#7493 Update Set-SPOSiteDesign.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteDesign.md
Labels: In review, Sign off, area:spo-powershell

#7627 Adding missing desc
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md
Labels: In review, Sign off, area:sp-server-powershell

#7602 Clarifying module changes
  teams/docs-conceptual/index.md
Labels: In review, Sign off, area:teams / skype

#7649 Chrisda to Master
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#7650 Master to Live
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMigrationPackageAzureSource.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteDesign.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Set-CsTeamsClientConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  teams/docs-conceptual/index.md
  teams/teams-ps/teams/Set-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#7492 Update Add-SPOSiteDesign.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md
Labels: In review, Sign off, area:spo-powershell

#7651 Update Suspend-Message.md
  exchange/exchange-ps/exchange/Suspend-Message.md
Labels: Microsoft submitter

#7654 Publish 04/20/2021, 3:30 PM
  exchange/exchange-ps/exchange/Suspend-Message.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md
Labels: Microsoft submitter

#7660 OGP-chrisda to Master
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/Set-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7661 Master to Live
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/Set-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7662 OGP-chrisda to Master
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/filter-properties.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/docs-conceptual/values-for-custompropertynames-parameter.md
Labels: Microsoft submitter

#7663 Publish 04/21/2021, 10:30 AM
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/filter-properties.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/docs-conceptual/values-for-custompropertynames-parameter.md
Labels: Microsoft submitter

#7671 ConnectionUri and AzureADAuthorizationEndpointUrl updates
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#7668 Adding teams
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
Labels: area:teams / skype

#7652 Update Grant-CsTeamsVideoInteropServicePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md
Labels: Microsoft submitter, Sign off, area:teams / skype

#7674 Publish 04/22/2021, 3:30 PM
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md
Labels: Microsoft submitter

#7681 Update Set-FederationTrust.md
  exchange/exchange-ps/exchange/Set-FederationTrust.md
Labels: Microsoft submitter

#7682 Publish 04/23/2021, 3:30 PM
  exchange/exchange-ps/exchange/Set-FederationTrust.md
Labels: Microsoft submitter

#7676 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: area:exchange

#7677 Update Set-Label.md - ContentType
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#7678 Update New-Label.md - Contenttype
  exchange/exchange-ps/exchange/New-Label.md
Labels: Microsoft submitter

#7648 Update Set-CsCallingLineIdentity.md
  skype/skype-ps/skype/Set-CsCallingLineIdentity.md
Labels: Microsoft submitter, area:teams / skype

#7645 Updated New-CsCallingLineIdentity
  skype/skype-ps/skype/New-CsCallingLineIdentity.md
Labels: Microsoft submitter, area:teams / skype

#7686 Publish 04/26/2021, 10:30 AM
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  skype/skype-ps/skype/New-CsCallingLineIdentity.md
  skype/skype-ps/skype/Set-CsCallingLineIdentity.md
Labels: Microsoft submitter

#7684 Update Get-MigrationUserStatistics.md
  exchange/exchange-ps/exchange/Get-MigrationUserStatistics.md
Labels: area:exchange

#7695 Publish 04/27/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-MigrationUserStatistics.md
Labels: Microsoft submitter

#7694 *-OutlookProtectionRule cmdlets no longer supported in the cloud
  exchange/exchange-ps/exchange/Disable-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/Enable-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/Get-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/New-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/Remove-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/Set-OutlookProtectionRule.md
Labels: Microsoft submitter

#7696 Publish 04/27/2021, 3:30 PM
  exchange/exchange-ps/exchange/Disable-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/Enable-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/Get-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/New-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/Remove-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/Set-OutlookProtectionRule.md
Labels: Microsoft submitter

#7699 Marked EnableDedupe as MS internal only as per engineering
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
Labels: Microsoft submitter

#7692 Clarifying Example 4 desc
  teams/teams-ps/teams/Get-Team.md
Labels: In review, Sign off, area:teams

#7641 Adding note about GCCH/DOD
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: In review, Microsoft submitter, Sign off, area:teams / skype

#7700 CalSync-chrisda to Master
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
Labels: Microsoft submitter

#7640 Adding missing params
  skype/skype-ps/skype/New-CsCallQueue.md
Labels: In review, Sign off, area:teams / skype

#7701 Publish 04/29/2021, 3:30 PM
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
  skype/skype-ps/skype/New-CsCallQueue.md
  teams/teams-ps/teams/Get-Team.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#7642 Template format note
  teams/teams-ps/teams/Get-CsTeamTemplate.md
  teams/teams-ps/teams/New-CsTeamTemplate.md
  teams/teams-ps/teams/Update-CsTeamTemplate.md
Labels: Microsoft submitter, Sign off, area:teams / skype

#7639 Added more detail about MediaRelayRoutingLocationOverride parameter
  skype/skype-ps/skype/New-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
Labels: In review, Sign off, area:teams / skype

#7702 Update Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
Labels: Microsoft submitter

#7703 Update Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
Labels: Microsoft submitter

#7704 Publish 04/30/2021, 10:30 AM
  skype/skype-ps/skype/New-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
  teams/teams-ps/teams/Get-CsTeamTemplate.md
  teams/teams-ps/teams/New-CsTeamTemplate.md
  teams/teams-ps/teams/Update-CsTeamTemplate.md
Labels: Microsoft submitter
