Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2021-05, with the labels that each got.

#7709 Chrisda to Master
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-AccessToCustomerDataRequest.md
  exchange/exchange-ps/exchange/Get-SCInsights.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-MoveRequest.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Search-AdminAuditLog.md
  exchange/exchange-ps/exchange/Set-MigrationUser.md
  exchange/exchange-ps/exchange/Set-MoveRequest.md
  exchange/exchange-ps/exchange/Set-OutboundConnector.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#7710 Publish 05/03/2021, 3:30 PM
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-AccessToCustomerDataRequest.md
  exchange/exchange-ps/exchange/Get-SCInsights.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-MoveRequest.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Search-AdminAuditLog.md
  exchange/exchange-ps/exchange/Set-MigrationUser.md
  exchange/exchange-ps/exchange/Set-MoveRequest.md
  exchange/exchange-ps/exchange/Set-OutboundConnector.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#7711 Viva-chrisda to Master
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7712 Master to Live
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7664 #7656 Fix missing learn more link
  teams/teams-ps/teams/New-CsTeamTemplate.md
Labels: In review, Microsoft submitter, Sign off, area:teams

#7717 Updated PollInterval parameter
  exchange/exchange-ps/exchange/Set-OabVirtualDirectory.md
Labels: Microsoft submitter

#7720 Publish 05/05/2021, 10:30 AM
  exchange/exchange-ps/exchange/Set-OabVirtualDirectory.md
  teams/teams-ps/teams/New-CsTeamTemplate.md
Labels: Microsoft submitter

#7532 Update Set-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter, Sign off

#7722 Publish 05/05/2021, 3:30 PM
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#7730 MyAnalytics/UserBrifingConfig/UserAnalyticsConfig consistency updates
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
Labels: Microsoft submitter

#7707 added a new cmdlet Get-LicenseReportForChangeNotificationSubscription
  teams/teams-ps/teams/Get-LicenseReportForChangeNotificationSubscription.md
Labels: In review, Microsoft submitter, Sign off

#7731 Publish 05/06/2021, 10:30 AM
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  teams/teams-ps/teams/Get-LicenseReportForChangeNotificationSubscription.md
Labels: Microsoft submitter

#7669 Update Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: In review, Sign off

#7734 Publish 05/06/2021, 3:30 PM
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
Labels: Microsoft submitter

#7737 Several fixes
  teams/teams-ps/teams/Get-LicenseReportForChangeNotificationSubscription.md
Labels: In review, Sign off

#7743 Update Set-OrganizationConfig.md - Correcting formatting in `AllowPlusAddressInRecipients`
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: area:exchange

#7748 Publish 05/10/2021, 3:30 PM
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#7729 Update Set-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
Labels: In review, Sign off, area:teams / skype

#7723 Adding NetworkRoamingPolicy to TenantNetworkSite
  skype/skype-ps/skype/New-CsTenantNetworkSite.md
  skype/skype-ps/skype/Set-CsTenantNetworkSite.md
Labels: In review, Microsoft submitter, Sign off, area:teams / skype

#7753 Publish 05/11/2021, 3:30 PM
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/New-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/New-CsTenantNetworkSite.md
  skype/skype-ps/skype/Set-CsCallQueue.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsTenantNetworkSite.md
Labels: Microsoft submitter

#7760 Chrisda to Master
  exchange/exchange-ps/exchange/Get-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/Import-ExchangeCertificate.md
Labels: Microsoft submitter

#7761 Update New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
Labels: Microsoft submitter

#7770 Publish 05/13/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/Import-ExchangeCertificate.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
Labels: Microsoft submitter

#7769 Update Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
Labels: Microsoft submitter

#7771 Publish 05/13/2021, 3:30 PM
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
Labels: Microsoft submitter

#7772 FPP-chrisda to Master
  exchange/exchange-ps/exchange/Export-FilePlanProperty.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyStructure.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/Import-FilePlanProperty.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/New-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7752 Update Set-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: In review, Microsoft submitter, Sign off, area:teams / skype

#7776 Publish 05/14/2021, 10:30 AM
  exchange/exchange-ps/exchange/Export-FilePlanProperty.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertyStructure.md
  exchange/exchange-ps/exchange/Get-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/Import-FilePlanProperty.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/New-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/New-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#7781 Fixed missing Type values
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#7782 Publish 05/17/2021, 3:30 PM
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#7754 Update Set-CsUserCallForwardingSettings.md
  skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md
Labels: In review, Microsoft submitter, Sign off, area:teams / skype

#7646 Minor mistakes edit
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
Labels: In review, Sign off, area:teams / skype

#7791 Update Update-DistributionGroupMember.md
  exchange/exchange-ps/exchange/Update-DistributionGroupMember.md
Labels: Microsoft submitter

#7792 Publish 05/18/2021, 10:30 AM
  exchange/exchange-ps/exchange/Update-DistributionGroupMember.md
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md
Labels: Microsoft submitter

#7796 MultiStage-chrisda to Master
  exchange/exchange-ps/exchange/Enable-ComplianceTagStorage.md
  exchange/exchange-ps/exchange/Get-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7797 Publish 05/18/2021, 3:30 PM
  exchange/exchange-ps/exchange/Enable-ComplianceTagStorage.md
  exchange/exchange-ps/exchange/Get-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7783 Updated description of Example 2
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantCdnPolicy.md
Labels: In review, Sign off, area:spo-powershell

#7799 Publish 05/19/2021, 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantCdnPolicy.md
Labels: Microsoft submitter

#7778 cmdlet is not anymore in preview
  teams/teams-ps/teams/New-TeamChannel.md
Labels: In review, Sign off, area:teams

#7764 Adding missing param
  skype/skype-ps/skype/Move-CsUser.md
Labels: In review, Sign off, area:teams / skype

#7732 Update Set-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter, Sign off, area:teams / skype

#7765 Updating to current behavior
  skype/skype-ps/skype/New-CsOnlineTimeRange.md
Labels: Sign off, area:teams / skype

#7762 Create Get-FileSensitivityLabelInfo
  sharepoint/sharepoint-ps/sharepoint-online/Get-FileSensitivityLabelInfo.md
Labels: In review, Microsoft submitter, Sign off, area:spo-powershell

#7802 Publish 05/19/2021, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Get-FileSensitivityLabelInfo.md
  skype/skype-ps/skype/Move-CsUser.md
  skype/skype-ps/skype/New-CsOnlineTimeRange.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/New-TeamChannel.md
Labels: Microsoft submitter

#7777 Updated tenant call blocking cmdlets
  skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md
  skype/skype-ps/skype/Get-CsTenantBlockedCallingNumbers.md
  skype/skype-ps/skype/Get-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md
  skype/skype-ps/skype/New-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md
  skype/skype-ps/skype/Remove-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md
  skype/skype-ps/skype/Set-CsTenantBlockedCallingNumbers.md
  skype/skype-ps/skype/Set-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/skype.md
Labels: Back to submitter, In review, Microsoft submitter, area:teams / skype

#7808 Publish 05/20/2021, 10:30 AM
  skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md
  skype/skype-ps/skype/Get-CsTenantBlockedCallingNumbers.md
  skype/skype-ps/skype/Get-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md
  skype/skype-ps/skype/New-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md
  skype/skype-ps/skype/Remove-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md
  skype/skype-ps/skype/Set-CsTenantBlockedCallingNumbers.md
  skype/skype-ps/skype/Set-CsTenantBlockedNumberExceptionPattern.md
  skype/skype-ps/skype/skype.md
Labels: Microsoft submitter

#7793 Adding state
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserAndContentMoveState.md
Labels: In review, Sign off, area:spo-powershell

#7779 Proposing expand description
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Sign off, area:spo-powershell

#7810 Publish 05/20/2021, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserAndContentMoveState.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#7805 Adding link and fixing two identical examples
  exchange/exchange-ps/exchange/Get-ActiveSyncDevice.md
Labels: area:exchange

#7814 Publish 05/21/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-ActiveSyncDevice.md
Labels: Microsoft submitter

#7818 Update Set-WebServicesVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-WebServicesVirtualDirectory.md
Labels: area:exchange

#7827 Publish 05/25/2021, 10:30 AM
  exchange/exchange-ps/exchange/Set-WebServicesVirtualDirectory.md
Labels: Microsoft submitter

#7804 Update Set-CsOnlineVoicemailUserSettings.md
  skype/skype-ps/skype/New-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md
Labels: In review, Microsoft submitter, Sign off, area:teams / skype

#7806 Update Set-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailPolicy.md
Labels: In review, Microsoft submitter, Sign off, area:teams / skype

#7819 Adding support to Enable/Disable PAIPassThrough
  skype/skype-ps/skype/New-CsTrunkConfiguration.md
  skype/skype-ps/skype/Set-CsTrunkConfiguration.md
Labels: In review, Sign off, area:teams / skype

#7831 Update New-OrganizationSegment.md
  exchange/exchange-ps/exchange/New-OrganizationSegment.md
Labels: area:exchange

#7833 Chrisda to Master
  exchange/exchange-ps/exchange/Get-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#7834 Publish 05/26/2021, 10:30 AM
  exchange/exchange-ps/exchange/Get-ExternalInOutlook.md
  exchange/exchange-ps/exchange/New-OrganizationSegment.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-User.md
  skype/skype-ps/skype/New-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/New-CsTrunkConfiguration.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md
  skype/skype-ps/skype/Set-CsTrunkConfiguration.md
Labels: Microsoft submitter

#7821 Trying to correct indentation
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off, area:teams / skype

#7836 Publish 5/26/2021 3:30 PM PT
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#7823 Correct example
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPWebApplication.md
Labels: In review, Sign off, area:sp-server-powershell

#7822 Update Get-FileSensitivityLabelInfo.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-FileSensitivityLabelInfo.md
Labels: In review, Microsoft submitter, Sign off, area:spo-powershell

#7809 Update Set-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off, area:teams / skype

#7828 Adding more info about Teams
  skype/skype-ps/skype/New-CsExternalAccessPolicy.md
  skype/skype-ps/skype/Set-CsExternalAccessPolicy.md
Labels: In review, Sign off, area:teams / skype

#7841 Publish 05/27/2021, 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Get-FileSensitivityLabelInfo.md
  sharepoint/sharepoint-ps/sharepoint-server/Set-SPWebApplication.md
  skype/skype-ps/skype/New-CsExternalAccessPolicy.md
  skype/skype-ps/skype/Set-CsExternalAccessPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#7835 Added Access Tokens for 2.3.2-preview
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: Microsoft submitter

#7826 Expanding descriptions
  skype/skype-ps/skype/Get-CsTeamsFeedbackPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsFeedbackPolicy.md
  skype/skype-ps/skype/Set-CsTeamsFeedbackPolicy.md
Labels: In review, Sign off, area:teams / skype

#7843 Publish 5/27/2021 3:30 PM PT
  skype/skype-ps/skype/Get-CsTeamsFeedbackPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsFeedbackPolicy.md
  skype/skype-ps/skype/Set-CsTeamsFeedbackPolicy.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: Microsoft submitter

#7845 Chrisda to Master
  exchange/exchange-ps/exchange/Get-AddressBookPolicy.md
  exchange/exchange-ps/exchange/Remove-AddressBookPolicy.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-MailboxAutoReplyConfiguration.md
Labels: Microsoft submitter

#7848 Update New-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md
Labels: Microsoft submitter, area:exchange

#7849 Chrisda to Master
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/Set-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7850 Publish 05/28/2021, 10:30 AM
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-AddressBookPolicy.md
  exchange/exchange-ps/exchange/Get-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/Remove-AddressBookPolicy.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-MailboxAutoReplyConfiguration.md
  exchange/exchange-ps/exchange/Set-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#7851 Chrisda to Master
  exchange/exchange-ps/exchange/Get-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/Set-OwnerlessGroupPolicy.md
Labels: Microsoft submitter

#7853 Publish 5/28/2021 3:30 PM PT
  exchange/exchange-ps/exchange/Get-OwnerlessGroupPolicy.md
  exchange/exchange-ps/exchange/Set-OwnerlessGroupPolicy.md
Labels: Microsoft submitter
