Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2022-06, with the labels that each got.

#9499 MbxIRM-chrisda to Main
  exchange/exchange-ps/exchange/Get-MailboxIRMAccess.md
  exchange/exchange-ps/exchange/Remove-MailboxIRMAccess.md
  exchange/exchange-ps/exchange/Set-MailboxIRMAccess.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9502 Publish 10:30 AM - 6/2/22
  exchange/exchange-ps/exchange/Get-MailboxIRMAccess.md
  exchange/exchange-ps/exchange/Get-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Remove-MailboxIRMAccess.md
  exchange/exchange-ps/exchange/Set-MailboxIRMAccess.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: Microsoft submitter

#9506 Update Set-MailboxIRMAccess.md
  exchange/exchange-ps/exchange/Set-MailboxIRMAccess.md
Labels: Microsoft submitter

#9503 various updates
  skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md
  skype/skype-ps/skype/Get-CsCallingLineIdentity.md
  skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
  skype/skype-ps/skype/New-CsCallingLineIdentity.md
  skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Remove-CsCallingLineIdentity.md
  skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/Set-CsCallingLineIdentity.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#9507 Publish 06/06/2022, 10:30 AM
  exchange/exchange-ps/exchange/Set-MailboxIRMAccess.md
  skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md
  skype/skype-ps/skype/Get-CsCallingLineIdentity.md
  skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
  skype/skype-ps/skype/New-CsCallingLineIdentity.md
  skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Remove-CsCallingLineIdentity.md
  skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/Set-CsCallingLineIdentity.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  whiteboard/whiteboard-ps/whiteboard/whiteboard.md
Labels: Microsoft submitter

#9508 Update Get-DistributionGroup.md
  exchange/exchange-ps/exchange/Get-DistributionGroup.md
  exchange/exchange-ps/exchange/Get-ForeignConnector.md
  exchange/exchange-ps/exchange/Remove-DeviceTenantPolicy.md
  exchange/exchange-ps/exchange/Remove-DeviceTenantRule.md
  exchange/exchange-ps/exchange/Remove-PhishSimOverridePolicy.md
Labels: Microsoft submitter

#9510 Publish 06/06/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Get-DistributionGroup.md
  exchange/exchange-ps/exchange/Get-ForeignConnector.md
  exchange/exchange-ps/exchange/Remove-DeviceTenantPolicy.md
  exchange/exchange-ps/exchange/Remove-DeviceTenantRule.md
  exchange/exchange-ps/exchange/Remove-PhishSimOverridePolicy.md
Labels: Microsoft submitter

#9511 NoExpiration does not apply for allow
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#9516 Security & Compliance Center replacement
  exchange/exchange-ps/exchange/Remove-ComplianceCaseMember.md
  exchange/exchange-ps/exchange/Remove-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/Remove-ComplianceSearch.md
  exchange/exchange-ps/exchange/Remove-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/Remove-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/Remove-ComplianceTag.md
  exchange/exchange-ps/exchange/Remove-DataClassification.md
  exchange/exchange-ps/exchange/Remove-DeviceConditionalAccessPolicy.md
  exchange/exchange-ps/exchange/Remove-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/Remove-DeviceConfigurationPolicy.md
  exchange/exchange-ps/exchange/Remove-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Remove-DeviceTenantPolicy.md
  exchange/exchange-ps/exchange/Remove-DeviceTenantRule.md
  exchange/exchange-ps/exchange/Remove-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Remove-DlpEdmSchema.md
  exchange/exchange-ps/exchange/Remove-DlpKeywordDictionary.md
  exchange/exchange-ps/exchange/Remove-DlpSensitiveInformationType.md
  exchange/exchange-ps/exchange/Remove-DlpSensitiveInformationTypeRulePackage.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Remove-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/Remove-HoldCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-HoldComplianceRule.md
  exchange/exchange-ps/exchange/Remove-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/Remove-Label.md
  exchange/exchange-ps/exchange/Remove-LabelPolicy.md
  exchange/exchange-ps/exchange/Remove-MailboxSearch.md
  exchange/exchange-ps/exchange/Remove-OrganizationSegment.md
  exchange/exchange-ps/exchange/Remove-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Remove-ProtectionAlert.md
  exchange/exchange-ps/exchange/Remove-RecordLabel.md
  exchange/exchange-ps/exchange/Remove-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Remove-RoleGroup.md
  exchange/exchange-ps/exchange/Remove-RoleGroupMember.md
  exchange/exchange-ps/exchange/Remove-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-SecOpsOverrideRule.md
  exchange/exchange-ps/exchange/Remove-SupervisoryReviewPolicyV2.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Remove-UnifiedAuditLogRetentionPolicy.md
  exchange/exchange-ps/exchange/Remove-eDiscoveryCaseAdmin.md
  exchange/exchange-ps/exchange/Search-AdminAuditLog.md
  exchange/exchange-ps/exchange/Set-ActivityAlert.md
  exchange/exchange-ps/exchange/Set-AdaptiveScope.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-AuditConfig.md
  exchange/exchange-ps/exchange/Set-AuditConfigurationRule.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-CaseHoldRule.md
  exchange/exchange-ps/exchange/Set-ComplianceCase.md
Labels: Microsoft submitter

#9517 Chrisda to Main
  exchange/exchange-ps/exchange/Remove-ComplianceCase.md
  exchange/exchange-ps/exchange/Set-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/Set-ComplianceSearch.md
  exchange/exchange-ps/exchange/Set-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/Set-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-DataClassification.md
  exchange/exchange-ps/exchange/Set-DeviceConditionalAccessPolicy.md
  exchange/exchange-ps/exchange/Set-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/Set-DeviceConfigurationPolicy.md
  exchange/exchange-ps/exchange/Set-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Set-DeviceTenantPolicy.md
  exchange/exchange-ps/exchange/Set-DeviceTenantRule.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpEdmSchema.md
  exchange/exchange-ps/exchange/Set-DlpKeywordDictionary.md
  exchange/exchange-ps/exchange/Set-DlpSensitiveInformationType.md
  exchange/exchange-ps/exchange/Set-DlpSensitiveInformationTypeRulePackage.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyAuthority.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyCategory.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyCitation.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyDepartment.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertyReferenceId.md
  exchange/exchange-ps/exchange/Set-FilePlanPropertySubCategory.md
  exchange/exchange-ps/exchange/Set-HoldCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-HoldComplianceRule.md
  exchange/exchange-ps/exchange/Set-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxSearch.md
  exchange/exchange-ps/exchange/Set-OrganizationSegment.md
  exchange/exchange-ps/exchange/Set-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Set-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-ProtectionAlert.md
  exchange/exchange-ps/exchange/Set-RecordReviewNotificationTemplateConfig.md
  exchange/exchange-ps/exchange/Set-RegulatoryComplianceUI.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-RoleGroup.md
  exchange/exchange-ps/exchange/Set-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Set-SecOpsOverrideRule.md
  exchange/exchange-ps/exchange/Set-SupervisoryReviewPolicyV2.md
  exchange/exchange-ps/exchange/Set-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Set-UnifiedAuditLogRetentionPolicy.md
  exchange/exchange-ps/exchange/Start-ComplianceSearch.md
  exchange/exchange-ps/exchange/Start-InformationBarrierPoliciesApplication.md
  exchange/exchange-ps/exchange/Start-MailboxSearch.md
  exchange/exchange-ps/exchange/Stop-ComplianceSearch.md
  exchange/exchange-ps/exchange/Stop-InformationBarrierPoliciesApplication.md
  exchange/exchange-ps/exchange/Stop-MailboxSearch.md
  exchange/exchange-ps/exchange/Test-DataClassification.md
  exchange/exchange-ps/exchange/Update-ComplianceCaseMember.md
  exchange/exchange-ps/exchange/Update-RoleGroupMember.md
  exchange/exchange-ps/exchange/Update-eDiscoveryCaseAdmin.md
  exchange/exchange-ps/exchange/Validate-RetentionRuleQuery.md
  repo_docs/NEW_CMDLETS.md
Labels: Microsoft submitter

#9523 Update New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
Labels: Microsoft submitter

#9512 Allows cannot be done from cmdlet
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
Labels: area:exchange, Microsoft submitter

#9531 Publish 06/10/2022, 10:30 AM
  cabgen-bootstrap.yml
Labels: Microsoft submitter

#9536 Chrisda to Main
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Add-ADPermission.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#9537 Publish 06/13/2022 3:30 PM PT
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Add-ADPermission.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#9532 Update ExchangeSenderMemberOf to include non mail-enabled security gr…
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
Labels: area:exchange

#9541 Publish 06/14/2022, 10:30 AM
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
Labels: Microsoft submitter

#9543 Publish 06/15/2022, 10:30 AM
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  skype/skype-ps/skype/New-CsTeamsComplianceRecordingPolicy.md
Labels: Microsoft submitter

#9544 Update New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
Labels: area:exchange, Microsoft submitter

#9555 Chrisda to Main
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#9573 Chrisda to Main
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Search-MailboxAuditLog.md
Labels: Microsoft submitter

#9574 Publish 06/21/2022 3:30 PM PT
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Search-MailboxAuditLog.md
Labels: Microsoft submitter

#9550 Update New-CsAutoAttendantMenuOption
  skype/skype-ps/skype/New-CsAutoAttendantMenuOption.md
Labels: area:teams / skype, Microsoft submitter

#9547 Update Set-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallHoldPolicy.md
Labels: area:teams / skype

#9576 Malware-chrisda to Main
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: Microsoft submitter

#9548 Update Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
Labels: area:teams / skype

#9552 Update New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#9578 Publish 06/22/2022, 10:30 AM
  exchange/exchange-ps/exchange/Get-ATPTotalTrafficReport.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/New-CsAutoAttendantMenuOption.md
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallHoldPolicy.md
Labels: Microsoft submitter

#9568 Update Remove-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-RetentionCompliancePolicy.md
Labels: area:exchange

#9575 Update New-SharingPolicy.md
  exchange/exchange-ps/exchange/New-SharingPolicy.md
Labels: area:exchange

#9582 Publish 06/23/2022, 10:30 AM
  exchange/exchange-ps/exchange/New-SharingPolicy.md
  exchange/exchange-ps/exchange/Remove-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#9583 Chrisda to Main
  exchange/exchange-ps/exchange/Get-ATPTotalTrafficReport.md
  exchange/exchange-ps/exchange/New-SharingPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
  exchange/exchange-ps/exchange/Set-SharingPolicy.md
Labels: Microsoft submitter

#9584 Publish 06/23/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Get-ATPTotalTrafficReport.md
  exchange/exchange-ps/exchange/New-SharingPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
  exchange/exchange-ps/exchange/Set-SharingPolicy.md
Labels: Microsoft submitter

#9585 Added FileTypeAction param
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: Microsoft submitter

#9579 Update New-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: area:teams, Microsoft submitter

#9551 Update Set-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#9586 Publish 06/24/2022, 10:30 AM
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#9590 Update Start-HistoricalSearch.md
  exchange/exchange-ps/exchange/Start-HistoricalSearch.md
Labels: Microsoft submitter

#9591 Publish 06/27/2022, 10:30 AM
  exchange/exchange-ps/exchange/Start-HistoricalSearch.md
Labels: Microsoft submitter

#9598 Chrisda to Main
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/filters-v2.md
Labels: Microsoft submitter

#9599 Publish 06/28/2022 3:30 PM PT
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/filters-v2.md
  exchange/exchange-ps/exchange/Get-EmailTenantSettings.md
  exchange/exchange-ps/exchange/Set-EmailTenantSettings.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9605 Updated SentToMemberOf
  exchange/exchange-ps/exchange/New-AntiPhishRule.md
  exchange/exchange-ps/exchange/New-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/New-MalwareFilterRule.md
  exchange/exchange-ps/exchange/New-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/New-SafeLinksRule.md
  exchange/exchange-ps/exchange/Set-AntiPhishRule.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/Set-MalwareFilterRule.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Set-SafeLinksRule.md
Labels: Microsoft submitter

#9606 Chrisda to Main
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#9610 S/MIME advanced settings support for sensitivity labels
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#9611 DLPF-chrisda to Main
  exchange/exchange-ps/exchange/New-DlpFingerprint.md
Labels: Microsoft submitter

#9602 Update Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: area:exchange

#9612 Chrisda to Main
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/New-AntiPhishRule.md
  exchange/exchange-ps/exchange/New-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/New-MalwareFilterRule.md
  exchange/exchange-ps/exchange/New-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/New-SafeLinksRule.md
  exchange/exchange-ps/exchange/Set-AntiPhishRule.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/Set-MalwareFilterRule.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Set-SafeLinksRule.md
Labels: Microsoft submitter

#9539 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype, Microsoft submitter

#9613 Publish 06/30/2022, 10:30 AM
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/New-AntiPhishRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpFingerprint.md
  exchange/exchange-ps/exchange/New-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-MalwareFilterRule.md
  exchange/exchange-ps/exchange/New-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/New-SafeLinksRule.md
  exchange/exchange-ps/exchange/Set-AntiPhishRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-MalwareFilterRule.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Set-SafeLinksRule.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: Microsoft submitter

#9589 Set-CsTenantFederationConfiguration - example changes
  skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md
Labels: area:teams / skype, Microsoft submitter

#9604 Documentation for New/Get/Remove-CsHybridTelephoneNumber
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/New-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md
Labels: area:teams, Microsoft submitter

#9614 Publish 06/30/2022 3:30 PM PT
  skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/New-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md
Labels: Microsoft submitter
