Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2022-09, with the labels that each got.

#9860 Update New-AdminAuditLogSearch.md
  exchange/exchange-ps/exchange/New-AdminAuditLogSearch.md
Labels: area:exchange, Microsoft submitter

#9863 Replaced commas with decimal places for GeoCoordinates
  exchange/exchange-ps/exchange/Set-Place.md
Labels: area:exchange

#9864 Chrisda to Main
  exchange/exchange-ps/exchange/Set-Contact.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#9866 Publish main to live on 9/2 @ 10:30 am
  exchange/exchange-ps/exchange/New-AdminAuditLogSearch.md
  exchange/exchange-ps/exchange/Set-Contact.md
  exchange/exchange-ps/exchange/Set-Place.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#9840 Update Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: area:exchange, Microsoft submitter, Do not merge

#9867 Publish 09/02/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#9848 Renaming file Get-CsBatchTeamsDeployment.md to Get-CsBatchTeamsDeploymentStatus
  teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md
  teams/teams-ps/teams/New-CsBatchTeamsDeployment.md
Labels: area:teams, Microsoft submitter

#9856 Removed irrelevant note on MediaRelayRoutingLocationOverride
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
Labels: area:teams / skype, Microsoft submitter

#9861 Basic Auth update
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: area:teams, Microsoft submitter

#9862 Update Grant-CsDialoutPolicy
  skype/skype-ps/skype/Grant-CsDialoutPolicy.md
Labels: area:teams / skype, Microsoft submitter

#9855 Get-CSTeamsShiftsConnectionInstance and Test-CSTeamsShiftsConnectionValidate docs updated
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md
Labels: area:teams, Microsoft submitter

#9873 Merge main to live on 9/6 @ 10:30 am
  skype/skype-ps/skype/Grant-CsDialoutPolicy.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/New-CsBatchTeamsDeployment.md
  teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md
Labels: Microsoft submitter

#9854 Remove unused flags, add description
  teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md
Labels: area:teams

#9869 Fix Identity Parameter for Remove cmdlet
  teams/teams-ps/teams/Remove-CsTeamsShiftsPolicy.md
Labels: area:teams

#9878 merge main to live Thursday 10:30
  teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsPolicy.md
Labels: Microsoft submitter

#9881 Added Feature to Get-VivaInsightsSettings
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
Labels: Microsoft submitter

#9882 Rewrote some sections on authentication regarding automation
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
Labels: area:exchange

#9883 Chrisda to Main
  exchange/exchange-ps/exchange/Set-MailboxAutoReplyConfiguration.md
Labels: Microsoft submitter

#9884 Publish main to live on 9/9 @ 10:30 am
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Set-MailboxAutoReplyConfiguration.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
Labels: Microsoft submitter

#9885 Prev8-chrisda to Main
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#9886 Deprecation info and MC links
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
Labels: Microsoft submitter

#9887 FeatureMES-chrisda
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
Labels: Microsoft submitter

#9888 Consistency updates
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
Labels: Microsoft submitter

#9889 Publish 09/09/2022 3:30 PM PT
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
Labels: Microsoft submitter

#9896 Add DefaultShareLinkToExistingAcces advanced setting for sensitivity label
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter, In review, Sign off

#9898 Publish main to live on 9/12 @ 10:30 am
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#9894 Revert "Update Set-OwaMailboxPolicy.md"
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: area:exchange, Microsoft submitter

#9899 Publish 09/12/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#9895 Add New|Get-CsCloudCallDataConnection cmdlets public docs
  teams/teams-ps/teams/Get-CsCloudCallDataConnection.md
  teams/teams-ps/teams/New-CsCloudCallDataConnection.md
  teams/teams-ps/teams/teams.md
Labels: area:teams

#9900 Publish main to live on 9/13 @ 10:30 am
  teams/teams-ps/teams/Get-CsCloudCallDataConnection.md
  teams/teams-ps/teams/New-CsCloudCallDataConnection.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#9901 Chrisda to Main
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-ConfigAnalyzerPolicyRecommendation.md
  exchange/exchange-ps/exchange/Get-MailContact.md
  exchange/exchange-ps/exchange/Get-MailPublicFolder.md
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/Get-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-MailboxPlan.md
  exchange/exchange-ps/exchange/Get-Recipient.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-SecurityPrincipal.md
  exchange/exchange-ps/exchange/Get-UnifiedGroup.md
  exchange/exchange-ps/exchange/Get-User.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md
Labels: Microsoft submitter

#9904 Publish main to live on 9/14 @ 10:30 am
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-ConfigAnalyzerPolicyRecommendation.md
  exchange/exchange-ps/exchange/Get-MailContact.md
  exchange/exchange-ps/exchange/Get-MailPublicFolder.md
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/Get-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-MailboxPlan.md
  exchange/exchange-ps/exchange/Get-Recipient.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-SecurityPrincipal.md
  exchange/exchange-ps/exchange/Get-UnifiedGroup.md
  exchange/exchange-ps/exchange/Get-User.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md
Labels: Microsoft submitter

#9905 Update Set-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#9893 Exchange Online Powershell - V3 Module updates - 6559839
  exchange/docs-conceptual/advantages-of-rest-cmdlets-over-rps.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/breaking-feature-announcements.md
  exchange/docs-conceptual/cmdlets-disabled-withdrawn.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/media/get-connection-info-v3.png
  exchange/docs-conceptual/new-upcoming-cmdlets-releases.md
  exchange/docs-conceptual/overview-exchange-online-powershell-v3.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/toc.yml
Labels: area:exchange, Do not merge

#9910 Fix link for Azure Communication Services
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#9911 Publish main to live on 9/15 @ 10:30 am
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#9912 Chrisda to Main
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#9913 Update Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#9914 Publish 09/15/2022 3:30 PM PT
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#9916 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/filters-v2.md
Labels: Microsoft submitter

#9917 microsoft-365/security/defender-endpoint/images/network-protection-c2-block-alert-page.jpg
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/filters-v2.md
Labels: Microsoft submitter

#9909 App based auth additions
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: area:teams, Microsoft submitter

#9920 Advanced settings for louder labels
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter

#9922 Publish 09/19/2022 3:30 PM PT
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: Microsoft submitter

#9921 Ctu 1
  teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsAcsFederationConfiguration.md
Labels: Microsoft submitter

#9930 EXOV3-chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/filter-properties.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
  exchange/exchange-ps/exchange/Get-CustomNudge.md
  exchange/exchange-ps/exchange/Get-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Get-CustomNudgeSettings.md
  exchange/exchange-ps/exchange/Get-EXOCasMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-EXOMailboxPermission.md
  exchange/exchange-ps/exchange/Get-EXOMailboxStatistics.md
  exchange/exchange-ps/exchange/Get-EXOMobileDeviceStatistics.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/Get-EXORecipientPermission.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/New-CustomNudge.md
  exchange/exchange-ps/exchange/New-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Remove-CustomNudge.md
  exchange/exchange-ps/exchange/Remove-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Set-CustomNudge.md
  exchange/exchange-ps/exchange/Set-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Set-CustomNudgeSettings.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/exchange.md
Labels: Microsoft submitter

#9842 Update doc for ShareWithTeam cmdlets
  teams/teams-ps/teams/Add-TeamChannelUser.md
  teams/teams-ps/teams/Get-AssociatedTeam.md
  teams/teams-ps/teams/Get-SharedWithTeam.md
  teams/teams-ps/teams/Get-SharedWithTeamUser.md
  teams/teams-ps/teams/Get-TeamAllChannel.md
  teams/teams-ps/teams/Get-TeamChannel.md
  teams/teams-ps/teams/Get-TeamIncomingChannel.md
  teams/teams-ps/teams/Remove-SharedWithTeam.md
  teams/teams-ps/teams/teams.md
Labels: area:teams

#9933 Update Move-CsUser.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#9934 docs to learn links
  exchange/exchange-ps/exchange/Add-ADPermission.md
  exchange/exchange-ps/exchange/Add-AttachmentFilterEntry.md
  exchange/exchange-ps/exchange/Add-AvailabilityAddressSpace.md
  exchange/exchange-ps/exchange/Add-ComplianceCaseMember.md
  exchange/exchange-ps/exchange/Add-ContentFilterPhrase.md
  exchange/exchange-ps/exchange/Add-DatabaseAvailabilityGroupServer.md
  exchange/exchange-ps/exchange/Add-DistributionGroupMember.md
  exchange/exchange-ps/exchange/Add-FederatedDomain.md
  exchange/exchange-ps/exchange/Add-GlobalMonitoringOverride.md
  exchange/exchange-ps/exchange/Add-IPAllowListEntry.md
  exchange/exchange-ps/exchange/Add-IPAllowListProvider.md
  exchange/exchange-ps/exchange/Add-IPBlockListEntry.md
  exchange/exchange-ps/exchange/Add-IPBlockListProvider.md
  exchange/exchange-ps/exchange/Add-MailboxDatabaseCopy.md
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/Add-ManagementRoleEntry.md
  exchange/exchange-ps/exchange/Add-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Add-RecipientPermission.md
  exchange/exchange-ps/exchange/Add-ResubmitRequest.md
  exchange/exchange-ps/exchange/Add-RoleGroupMember.md
  exchange/exchange-ps/exchange/Add-ServerMonitoringOverride.md
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Add-eDiscoveryCaseAdmin.md
  exchange/exchange-ps/exchange/Clean-MailboxDatabase.md
  exchange/exchange-ps/exchange/Clear-ActiveSyncDevice.md
  exchange/exchange-ps/exchange/Clear-MobileDevice.md
  exchange/exchange-ps/exchange/Clear-TextMessagingAccount.md
  exchange/exchange-ps/exchange/Compare-TextMessagingVerificationCode.md
  exchange/exchange-ps/exchange/Complete-MigrationBatch.md
Labels: Microsoft submitter

#9936 Update Set-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsAcsFederationConfiguration.md
Labels: Microsoft submitter

#9937 Publish 09/20/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Add-ADPermission.md
  exchange/exchange-ps/exchange/Add-AttachmentFilterEntry.md
  exchange/exchange-ps/exchange/Add-AvailabilityAddressSpace.md
  exchange/exchange-ps/exchange/Add-ComplianceCaseMember.md
  exchange/exchange-ps/exchange/Add-ContentFilterPhrase.md
  exchange/exchange-ps/exchange/Add-DatabaseAvailabilityGroupServer.md
  exchange/exchange-ps/exchange/Add-DistributionGroupMember.md
  exchange/exchange-ps/exchange/Add-FederatedDomain.md
  exchange/exchange-ps/exchange/Add-GlobalMonitoringOverride.md
  exchange/exchange-ps/exchange/Add-IPAllowListEntry.md
  exchange/exchange-ps/exchange/Add-IPAllowListProvider.md
  exchange/exchange-ps/exchange/Add-IPBlockListEntry.md
  exchange/exchange-ps/exchange/Add-IPBlockListProvider.md
  exchange/exchange-ps/exchange/Add-MailboxDatabaseCopy.md
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/Add-ManagementRoleEntry.md
  exchange/exchange-ps/exchange/Add-PublicFolderAdministrativePermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Add-RecipientPermission.md
  exchange/exchange-ps/exchange/Add-ResubmitRequest.md
  exchange/exchange-ps/exchange/Add-RoleGroupMember.md
  exchange/exchange-ps/exchange/Add-ServerMonitoringOverride.md
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Add-eDiscoveryCaseAdmin.md
  exchange/exchange-ps/exchange/Clean-MailboxDatabase.md
  exchange/exchange-ps/exchange/Clear-ActiveSyncDevice.md
  exchange/exchange-ps/exchange/Clear-MobileDevice.md
  exchange/exchange-ps/exchange/Clear-TextMessagingAccount.md
  exchange/exchange-ps/exchange/Compare-TextMessagingVerificationCode.md
  exchange/exchange-ps/exchange/Complete-MigrationBatch.md
  skype/skype-ps/skype/Move-CsUser.md
  teams/teams-ps/teams/Set-CsTeamsAcsFederationConfiguration.md
Labels: Microsoft submitter

#9935 Chrisda to Main
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#9938 Publish main to live on 9/21 @ 10:30 am
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#9939 Chrisda to Main
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#9940 Build report fixes
  skype/skype-ps/skype/New-CsTeamsAudioConferencingPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsAudioConferencingPolicy.md
Labels: Microsoft submitter

#9941 Publish 09/21/2022 3:30 PM PT
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  skype/skype-ps/skype/New-CsTeamsAudioConferencingPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsAudioConferencingPolicy.md
Labels: Microsoft submitter

#9925 Removal of RHM notice
  skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md
  skype/skype-ps/skype/Set-CsOnlineVoiceUser.md
  skype/skype-ps/skype/Set-CsUser.md
  teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: area:teams / skype, Microsoft submitter

#9845 Adding the docs for CsTeamsEventsPolicy cmdlets
  teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/teams.md
Labels: area:teams, Microsoft submitter

#9955 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#9956 Publish 09/23/2022 3:30 PM PT
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#9958 Publish main to live on 9/26 @ 10:30 am
  skype/skype-ps/skype/Sync-CsOnlineApplicationInstance.md
Labels: Microsoft submitter

#9959 Update Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#9963 Publish 09/26/2022 3:30 PM PT
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#9964 Update New-ServicePrincipal with correct AAD cmdlet name
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
Labels: area:exchange, Microsoft submitter

#9969 Publish main to live on 9/27 @ 10:30 am
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
Labels: Microsoft submitter

#9973 Update Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
Labels: Microsoft submitter

#9974 Get/Set-Content -Encoding Byte fixe
  skype/skype-ps/skype/Export-CsLisConfiguration.md
  skype/skype-ps/skype/Get-CsCallParkOrbit.md
  skype/skype-ps/skype/Import-CSAnnouncementFile.md
  skype/skype-ps/skype/Import-CsLisConfiguration.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/Import-CsRgsAudioFile.md
  skype/skype-ps/skype/New-CsAutoAttendantPrompt.md
  skype/skype-ps/skype/New-CsClientPolicy.md
  skype/skype-ps/skype/New-CsClientVersionPolicyRule.md
  skype/skype-ps/skype/New-CsPartnerApplication.md
  skype/skype-ps/skype/New-CsRgsPrompt.md
  skype/skype-ps/skype/Set-CsCallParkServiceMusicOnHoldFile.md
  skype/skype-ps/skype/Set-CsClientPolicy.md
  skype/skype-ps/skype/Set-CsPartnerApplication.md
  skype/skype-ps/skype/Set-CsRgsConfiguration.md
  skype/skype-ps/skype/Set-CsRgsWorkflow.md
Labels: Microsoft submitter

#9975 Publish 09/28/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  skype/skype-ps/skype/Export-CsLisConfiguration.md
  skype/skype-ps/skype/Get-CsCallParkOrbit.md
  skype/skype-ps/skype/Import-CSAnnouncementFile.md
  skype/skype-ps/skype/Import-CsLisConfiguration.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/Import-CsRgsAudioFile.md
  skype/skype-ps/skype/New-CsAutoAttendantPrompt.md
  skype/skype-ps/skype/New-CsClientPolicy.md
  skype/skype-ps/skype/New-CsClientVersionPolicyRule.md
  skype/skype-ps/skype/New-CsPartnerApplication.md
  skype/skype-ps/skype/New-CsRgsPrompt.md
  skype/skype-ps/skype/Set-CsCallParkServiceMusicOnHoldFile.md
  skype/skype-ps/skype/Set-CsClientPolicy.md
  skype/skype-ps/skype/Set-CsPartnerApplication.md
  skype/skype-ps/skype/Set-CsRgsConfiguration.md
  skype/skype-ps/skype/Set-CsRgsWorkflow.md
Labels: Microsoft submitter

#9979 Chrisda to Main
  exchange/exchange-ps/exchange/New-OutboundConnector.md
  exchange/exchange-ps/exchange/Set-AcceptedDomain.md
  exchange/exchange-ps/exchange/Set-OutboundConnector.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter

#9980 Publish 09/29/2022 3:30 PM PT
  exchange/exchange-ps/exchange/New-OutboundConnector.md
  exchange/exchange-ps/exchange/Set-AcceptedDomain.md
  exchange/exchange-ps/exchange/Set-OutboundConnector.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter

#9981 Chrisda to Main
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#9970 Update TOC for Teams PowerShell documentation
  teams/docs-conceptual/intro.md
  teams/docs-conceptual/toc.yml
Labels: area:teams

#9984 SensitivityLabelId param description in New/Set-UnifiedGroup
  exchange/exchange-ps/exchange/New-UnifiedGroup.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#9986 Publish main to live on 9/30 @ 10:30 am
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/New-UnifiedGroup.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
  teams/docs-conceptual/intro.md
  teams/docs-conceptual/toc.yml
Labels: Microsoft submitter
