Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2022-08, with the labels that each got.

#9745 CAB updates
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: area:exchange, Microsoft submitter

#9748 Publish main to live on 8/2 @ 10:30 am
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  skype/skype-ps/skype/Set-CsCloudCallDataConnector.md
Labels: Microsoft submitter

#9749 Recipient filters not additive note
  exchange/exchange-ps/exchange/New-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/New-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/New-AntiPhishRule.md
  exchange/exchange-ps/exchange/New-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/New-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/New-MalwareFilterRule.md
  exchange/exchange-ps/exchange/New-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/New-SafeLinksRule.md
  exchange/exchange-ps/exchange/Set-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/Set-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-AntiPhishRule.md
  exchange/exchange-ps/exchange/Set-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/Set-MalwareFilterRule.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Set-SafeLinksRule.md
Labels: Microsoft submitter

#9756 CNudge-chrisda to Main
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-CustomNudge.md
  exchange/exchange-ps/exchange/Get-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Get-CustomNudgeSettings.md
  exchange/exchange-ps/exchange/New-CustomNudge.md
  exchange/exchange-ps/exchange/New-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Remove-CustomNudge.md
  exchange/exchange-ps/exchange/Remove-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Set-CustomNudge.md
  exchange/exchange-ps/exchange/Set-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Set-CustomNudgeSettings.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9746 Added information about UTC time format
  exchange/exchange-ps/exchange/Get-MessageTrace.md
Labels: area:exchange

#9755 Add a note to search for O365 Exchange
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: area:exchange

#9757 Publish 08/03/2022 3:30 PM PT
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-CustomNudge.md
  exchange/exchange-ps/exchange/Get-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Get-CustomNudgeSettings.md
  exchange/exchange-ps/exchange/Get-MessageTrace.md
  exchange/exchange-ps/exchange/New-CustomNudge.md
  exchange/exchange-ps/exchange/New-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Remove-CustomNudge.md
  exchange/exchange-ps/exchange/Remove-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Set-CustomNudge.md
  exchange/exchange-ps/exchange/Set-CustomNudgeAssignment.md
  exchange/exchange-ps/exchange/Set-CustomNudgeSettings.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9744 Fix teamsMediaLoggingPolicy related links
  teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md
Labels: area:teams

#9761 Publish main to live on 8/4 @ 10:30 am
  skype/skype-ps/skype/Get-CsOnlineUser.md
  teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md
Labels: Microsoft submitter

#9762 Typo fix
  exchange/exchange-ps/exchange/Get-SweepRule.md
  exchange/exchange-ps/exchange/New-SweepRule.md
Labels: Microsoft submitter

#9763 Update New-ExchangeCertificate.md
  exchange/exchange-ps/exchange/New-ExchangeCertificate.md
Labels: Microsoft submitter

#9764 Publish 08/04/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Get-SweepRule.md
  exchange/exchange-ps/exchange/New-ExchangeCertificate.md
  exchange/exchange-ps/exchange/New-SweepRule.md
Labels: Microsoft submitter

#9765 Get-ComplianceCase and Get-CaseHoldPolicy
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Get-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Get-ComplianceCase.md
Labels: Microsoft submitter

#9767 Publish main to live on 8/5 @ 10:30 am
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Get-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Get-ComplianceCase.md
Labels: Microsoft submitter

#9747 remove note
  skype/skype-ps/skype/Set-CsPrivacyConfiguration.md
Labels: area:teams / skype

#9768 Publish 08/05/2022 3:30 PM PT
  skype/skype-ps/skype/Set-CsPrivacyConfiguration.md
Labels: Microsoft submitter

#9773 TABL-DKIM-chrisda to Main
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
Labels: Microsoft submitter

#9774 CloudAttach-chrisda to Main
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
Labels: Microsoft submitter

#9775 Publish main to live on 8/8 @ 10:30 am
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
Labels: Microsoft submitter

#9776 Chrisda to Main
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-EXOCasMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-EXOMailboxPermission.md
  exchange/exchange-ps/exchange/Get-EXOMailboxStatistics.md
  exchange/exchange-ps/exchange/Get-EXOMobileDeviceStatistics.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/Get-EXORecipientPermission.md
Labels: Microsoft submitter

#9777 Publish 08/08/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-EXOCasMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-EXOMailboxPermission.md
  exchange/exchange-ps/exchange/Get-EXOMailboxStatistics.md
  exchange/exchange-ps/exchange/Get-EXOMobileDeviceStatistics.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/Get-EXORecipientPermission.md
Labels: Microsoft submitter

#9782 Chrisda to Main
  exchange/exchange-ps/exchange/Get-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#9784 Chrisda to Main
  exchange/exchange-ps/exchange/Export-DlpPolicyCollection.md
  exchange/exchange-ps/exchange/Export-ExchangeCertificate.md
  exchange/exchange-ps/exchange/Export-JournalRuleCollection.md
  exchange/exchange-ps/exchange/Export-RecipientDataProperty.md
  exchange/exchange-ps/exchange/Export-TransportRuleCollection.md
  exchange/exchange-ps/exchange/Export-UMPrompt.md
  exchange/exchange-ps/exchange/Test-SystemHealth.md
Labels: Microsoft submitter

#9785 Publish 08/10/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Export-DlpPolicyCollection.md
  exchange/exchange-ps/exchange/Export-ExchangeCertificate.md
  exchange/exchange-ps/exchange/Export-JournalRuleCollection.md
  exchange/exchange-ps/exchange/Export-RecipientDataProperty.md
  exchange/exchange-ps/exchange/Export-TransportRuleCollection.md
  exchange/exchange-ps/exchange/Export-UMPrompt.md
  exchange/exchange-ps/exchange/Get-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Test-SystemHealth.md
Labels: Microsoft submitter

#9791 Update Get-MailflowStatusReport.md
  exchange/exchange-ps/exchange/Get-MailflowStatusReport.md
Labels: area:exchange, Microsoft submitter

#9787 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange

#9800 Chrisda to Main
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#9786 add missing parameters
  skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
Labels: area:teams / skype

#9801 Chrisda to Main
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#9789 Update New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: area:exchange

#9802 merge main to live, Monday 10:30
  exchange/exchange-ps/exchange/Get-MailflowStatusReport.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
  skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
Labels: Microsoft submitter

#9803 EAED-chrisda to Main
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9804 Main to Live
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9794 Add new cmdlet files
  teams/teams-ps/teams/Get-CsBatchTeamsDeployment.md
  teams/teams-ps/teams/New-CsBatchTeamsDeployment.md
Labels: area:teams, Microsoft submitter

#9805 Publish 08/16/2022 3:30 PM PT
  teams/teams-ps/teams/Get-CsBatchTeamsDeployment.md
  teams/teams-ps/teams/New-CsBatchTeamsDeployment.md
Labels: Microsoft submitter

#9809 Publish main to live on 8/17 @ 10:30 am
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9798 Update New-CsCallQueue.md
  skype/skype-ps/skype/New-CsCallQueue.md
Labels: area:teams / skype

#9799 Adding Live Interpretation parameter, and matching syntax for String
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#9807 Update Set-CsCallQueue.md
  skype/skype-ps/skype/Set-CsCallQueue.md
Labels: Microsoft submitter

#9816 Publish main to live on 8/18 @ 10:30 am
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/Set-CsCallQueue.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#9815 Update Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#9817 Publish main to live on 8/19 @ 10:30 am
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#9818 TABL-chrisda to Main
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListSpoofItems.md
Labels: Microsoft submitter

#9819 Chrisda to Main
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9820 Chrisda to Main
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#9821 Publish 08/19/2022 3:30 PM PT
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9824 Update Get-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Get-HostedContentFilterPolicy.md
Labels: Microsoft submitter

#9826 Publish 08/23/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Get-HostedContentFilterPolicy.md
Labels: Microsoft submitter

#9827 Update Set-UnifiedGroup.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: area:exchange, Microsoft submitter

#9825 Update Set-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/Set-ATPBuiltInProtectionRule.md
Labels: area:exchange

#9832 Chrisda to Main
  exchange/exchange-ps/exchange/Set-TransportAgent.md
Labels: Microsoft submitter

#9829 Update Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: area:exchange

#9833 Publish main to live on 8/25 @ 10:30 am
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Set-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/Set-TransportAgent.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#9837 Chrisda to Main
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9823 Various updates
  skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Get-CsOnlinePstnUsage.md
  skype/skype-ps/skype/Get-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/Get-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/New-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/New-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/New-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Remove-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Remove-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/Remove-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsOnlinePstnUsage.md
  skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/Set-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Test-CsTeamsUnassignedNumberTreatment.md
Labels: area:teams / skype, Microsoft submitter

#9838 Update New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
Labels: Microsoft submitter

#9839 Publish 08/26/2022 3:30 PM PT
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
  skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Get-CsOnlinePstnUsage.md
  skype/skype-ps/skype/Get-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/Get-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/New-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/New-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/New-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Remove-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Remove-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/Remove-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsOnlinePstnUsage.md
  skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md
  skype/skype-ps/skype/Set-CsOnlineVoiceRoutingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Test-CsTeamsUnassignedNumberTreatment.md
Labels: Microsoft submitter

#9831 documents updated with examples for UKG connector
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md
Labels: area:teams, Microsoft submitter

#9841 Publish main to live on 8/29 @ 10:30 am
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md
Labels: Microsoft submitter

#9835 Update Get-CsTeamsShiftsConnectionTeamMap.md and New-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md
Labels: area:teams

#9843 Update New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: area:exchange

#9844 Update Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: area:exchange

#9849 Publish main to live on 8/30 @ 10:30 am
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md
Labels: Microsoft submitter

#9850 Chrisda to Main
  exchange/exchange-ps/exchange/Get-AdaptiveScope.md
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Get-CalendarDiagnosticLog.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-DlpPolicy.md
  exchange/exchange-ps/exchange/Get-LabelPolicy.md
  exchange/exchange-ps/exchange/Get-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Get-MailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-MoveRequest.md
  exchange/exchange-ps/exchange/Get-MoveRequestStatistics.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/New-PowerShellVirtualDirectory.md
  exchange/exchange-ps/exchange/New-ProtectionAlert.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
  exchange/exchange-ps/exchange/Remove-ServicePrincipal.md
  exchange/exchange-ps/exchange/Set-AccessToCustomerDataRequest.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Set-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-ProtectionAlert.md
  exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md
  exchange/exchange-ps/exchange/Test-TextExtraction.md
  exchange/exchange-ps/exchange/Upgrade-DistributionGroup.md
Labels: Microsoft submitter

#9851 ExO 8/26 Blind Cmdlet Sweep - Removals
  exchange/exchange-ps/exchange/Export-UMCallDataRecord.md
  exchange/exchange-ps/exchange/Get-MoveRequest.md
  exchange/exchange-ps/exchange/Get-ServicePrincipal.md
  exchange/exchange-ps/exchange/Get-UMCallDataRecord.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#9852 Site mailbox cmdlet ExO removal
  exchange/exchange-ps/exchange/Get-SiteMailbox.md
  exchange/exchange-ps/exchange/Get-SiteMailboxDiagnostics.md
  exchange/exchange-ps/exchange/Get-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/New-SiteMailbox.md
  exchange/exchange-ps/exchange/New-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Remove-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Set-SiteMailbox.md
  exchange/exchange-ps/exchange/Set-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Test-SiteMailbox.md
  exchange/exchange-ps/exchange/Update-SiteMailbox.md
Labels: Microsoft submitter

#9853 Publish 8/30/2022 - 3:30 PM PST
  exchange/exchange-ps/exchange/Export-UMCallDataRecord.md
  exchange/exchange-ps/exchange/Get-AdaptiveScope.md
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Get-CalendarDiagnosticLog.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-DlpPolicy.md
  exchange/exchange-ps/exchange/Get-LabelPolicy.md
  exchange/exchange-ps/exchange/Get-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Get-MailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-MoveRequest.md
  exchange/exchange-ps/exchange/Get-MoveRequestStatistics.md
  exchange/exchange-ps/exchange/Get-ServicePrincipal.md
  exchange/exchange-ps/exchange/Get-SiteMailbox.md
  exchange/exchange-ps/exchange/Get-SiteMailboxDiagnostics.md
  exchange/exchange-ps/exchange/Get-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Get-UMCallDataRecord.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/New-PowerShellVirtualDirectory.md
  exchange/exchange-ps/exchange/New-ProtectionAlert.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
  exchange/exchange-ps/exchange/New-SiteMailbox.md
  exchange/exchange-ps/exchange/New-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Remove-ServicePrincipal.md
  exchange/exchange-ps/exchange/Remove-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Set-AccessToCustomerDataRequest.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Set-MapiVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-ProtectionAlert.md
  exchange/exchange-ps/exchange/Set-SiteMailbox.md
  exchange/exchange-ps/exchange/Set-SiteMailboxProvisioningPolicy.md
  exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md
  exchange/exchange-ps/exchange/Test-SiteMailbox.md
  exchange/exchange-ps/exchange/Test-TextExtraction.md
  exchange/exchange-ps/exchange/Update-SiteMailbox.md
  exchange/exchange-ps/exchange/Upgrade-DistributionGroup.md
Labels: Microsoft submitter

#9846 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: area:exchange

#9859 Publish main to live on 8/31 @ 10:30 am
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter
