Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2022-10, with the labels that each got.

#9992 Update control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
Labels: area:exchange

#9995 EnableAudit advanced setting now supported for OWA, rolling out for m…
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter

#9996 Add Mac to EnableAudit advanced setting
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: area:exchange, Microsoft submitter

#9997 Chrisda to Main
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  skype/skype-ps/skype/Get-CsTeamsAudioConferencingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAudioConferencingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAudioConferencingPolicy.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Get-CsTeamTemplate.md
  teams/teams-ps/teams/Get-CsTeamTemplateList.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md
  teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
  teams/teams-ps/teams/New-CsTeamTemplate.md
  teams/teams-ps/teams/New-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamTemplate.md
  teams/teams-ps/teams/Set-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Set-CsUserCallingSettings.md
Labels: Microsoft submitter

#9998 Chrisda to Main
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
Labels: Microsoft submitter

#9999 Publish 10/03/2022 3:30 PM PT
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  skype/skype-ps/skype/Get-CsTeamsAudioConferencingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAudioConferencingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAudioConferencingPolicy.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Get-CsTeamTemplate.md
  teams/teams-ps/teams/Get-CsTeamTemplateList.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md
  teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
  teams/teams-ps/teams/New-CsTeamTemplate.md
  teams/teams-ps/teams/New-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamTemplate.md
  teams/teams-ps/teams/Set-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Set-CsUserCallingSettings.md
Labels: Microsoft submitter

#10002 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
Labels: Microsoft submitter

#10003 Update New-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#10005 Chrisda to Main
  .openpublishing.redirection.json
  exchange/exchange-ps/exchange/Get-CalendarDiagnosticAnalysis.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
Labels: Microsoft submitter

#10006 Publish 10/04/2022 3:30 PM PT
  .openpublishing.redirection.json
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/Get-CalendarDiagnosticAnalysis.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
Labels: Microsoft submitter

#10008 Update .openpublishing.redirection.json
  .openpublishing.redirection.json
Labels: Microsoft submitter

#10009 Publish main to live on 10/5 @ 10:30 am
  .openpublishing.redirection.json
Labels: Microsoft submitter

#10010 Chrisda to Main
  teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter

#10013 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Get-ProtectionAlert.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/Remove-ProtectionAlert.md
  exchange/exchange-ps/exchange/Set-ProtectionAlert.md
Labels: Microsoft submitter

#10014 Publish 10/05/2022 3:30 PM PT
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Get-ProtectionAlert.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/Remove-ProtectionAlert.md
  exchange/exchange-ps/exchange/Set-ProtectionAlert.md
  teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter

#10018 Chrisda to Main
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/Get-User.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#10023 Publish main to live on 10/7 @ 10:30 am
  exchange/exchange-ps/exchange/Get-Contact.md
  exchange/exchange-ps/exchange/Get-DetailsTemplate.md
  exchange/exchange-ps/exchange/Get-EventLogLevel.md
  exchange/exchange-ps/exchange/Get-ExchangeServer.md
  exchange/exchange-ps/exchange/Get-ExchangeSettings.md
  exchange/exchange-ps/exchange/Get-LinkedUser.md
  exchange/exchange-ps/exchange/Get-MailContact.md
  exchange/exchange-ps/exchange/Get-MailPublicFolder.md
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-MailboxDatabase.md
  exchange/exchange-ps/exchange/Get-MailboxDatabaseCopyStatus.md
  exchange/exchange-ps/exchange/Get-MigrationBatch.md
  exchange/exchange-ps/exchange/Get-MigrationEndpoint.md
  exchange/exchange-ps/exchange/Get-MigrationUser.md
  exchange/exchange-ps/exchange/Get-OabVirtualDirectory.md
  exchange/exchange-ps/exchange/Get-OfflineAddressBook.md
  exchange/exchange-ps/exchange/Get-PolicyTipConfig.md
  exchange/exchange-ps/exchange/Get-PublicFolder.md
  exchange/exchange-ps/exchange/Get-PublicFolderMailboxMigrationRequest.md
  exchange/exchange-ps/exchange/Get-PublicFolderMigrationRequest.md
  exchange/exchange-ps/exchange/Get-PublicFolderMoveRequest.md
  exchange/exchange-ps/exchange/Get-Recipient.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-SecurityPrincipal.md
  exchange/exchange-ps/exchange/Get-SystemMessage.md
  exchange/exchange-ps/exchange/Get-ThrottlingPolicyAssociation.md
  exchange/exchange-ps/exchange/Get-UMMailbox.md
  exchange/exchange-ps/exchange/Get-UMMailboxPIN.md
  exchange/exchange-ps/exchange/Get-UnifiedGroup.md
  exchange/exchange-ps/exchange/Get-UserPhoto.md
  exchange/exchange-ps/exchange/New-AvailabilityReportOutage.md
  exchange/exchange-ps/exchange/New-ClientAccessArray.md
  exchange/exchange-ps/exchange/New-ManagedContentSettings.md
  exchange/exchange-ps/exchange/New-ManagedFolder.md
  exchange/exchange-ps/exchange/New-OwaVirtualDirectory.md
  exchange/exchange-ps/exchange/New-UMDialPlan.md
  exchange/exchange-ps/exchange/New-UMIPGateway.md
  exchange/exchange-ps/exchange/Test-AssistantHealth.md
  exchange/exchange-ps/exchange/Test-PowerShellConnectivity.md
Labels: Microsoft submitter

#10027 Or to And
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
Labels: Microsoft submitter

#10021 Added how to fix locking yourself out
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
Labels: area:exchange

#10028 Publish main to live on 10/10 @ 10:30 am
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
Labels: Microsoft submitter

#10034 retention policy updates
  exchange/exchange-ps/exchange/New-RetentionPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxPlan.md
  exchange/exchange-ps/exchange/Set-RetentionPolicy.md
Labels: Microsoft submitter

#10036 Update Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#10037 Publish 10/11/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/New-RetentionPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxPlan.md
  exchange/exchange-ps/exchange/Set-RetentionPolicy.md
Labels: Microsoft submitter

#10038 Chrisda to Main
  exchange/exchange-ps/exchange/Get-DataClassification.md
  exchange/exchange-ps/exchange/Get-MailboxRepairRequest.md
  exchange/exchange-ps/exchange/Get-MailboxSearch.md
  exchange/exchange-ps/exchange/Get-SystemMessage.md
  exchange/exchange-ps/exchange/New-MailboxExportRequest.md
  exchange/exchange-ps/exchange/New-MailboxRepairRequest.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-SystemMessage.md
  exchange/exchange-ps/exchange/Remove-SystemMessage.md
  exchange/exchange-ps/exchange/Set-SystemMessage.md
  exchange/exchange-ps/exchange/Test-OwaConnectivity.md
Labels: Microsoft submitter

#10033 Brenle mailboxplan updates
  exchange/exchange-ps/exchange/New-RetentionPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxPlan.md
  exchange/exchange-ps/exchange/Set-RetentionPolicy.md
Labels: area:exchange, Microsoft submitter

#10043 M365 Group and MS Graph deficiencies
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#10044 Publish main to live on 10/12 @ 10:30 am
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Get-DataClassification.md
  exchange/exchange-ps/exchange/Get-MailboxRepairRequest.md
  exchange/exchange-ps/exchange/Get-MailboxSearch.md
  exchange/exchange-ps/exchange/Get-SystemMessage.md
  exchange/exchange-ps/exchange/New-MailboxExportRequest.md
  exchange/exchange-ps/exchange/New-MailboxRepairRequest.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-RetentionPolicy.md
  exchange/exchange-ps/exchange/New-SystemMessage.md
  exchange/exchange-ps/exchange/Remove-SystemMessage.md
  exchange/exchange-ps/exchange/Set-MailboxPlan.md
  exchange/exchange-ps/exchange/Set-RetentionPolicy.md
  exchange/exchange-ps/exchange/Set-SystemMessage.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
  exchange/exchange-ps/exchange/Test-OwaConnectivity.md
Labels: Microsoft submitter

#10045 Chrisda to Main
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
Labels: Microsoft submitter

#10046 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/Get-ATPTotalTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailflowStatusReport.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-ServicePrincipal.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
  exchange/exchange-ps/exchange/Remove-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Remove-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter

#10048 Publish 10/12/2022 3:30 PM PT
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/Get-ATPTotalTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailflowStatusReport.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-ServicePrincipal.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
  exchange/exchange-ps/exchange/Remove-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Remove-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter

#10047 Chrisda to Main
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#10050 Publish main to live on 10/13 @ 10:30 am
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#10052 Update Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
Labels: area:exchange, Microsoft submitter

#10051 ExOV3-chrisda to Main
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/New-DlpFingerprint.md
Labels: area:exchange, Microsoft submitter

#10053 merge main to live Monday 10:30
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/New-DlpFingerprint.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
Labels: Microsoft submitter

#10054 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10055 Publish 10/17/2022 3:30 PM PT
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10062 Clarification around Organization param value
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter, In review, Sign off, Admin review

#10063 Publish 10/19/2022 3:30 PM PT
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#10064 Chrisda to Main
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
Labels: area:exchange, Microsoft submitter, In review, Sign off

#10065 Publish main to live on 10/20 @ 10:30 am
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
Labels: Microsoft submitter

#9903 Update Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: area:exchange, Microsoft submitter

#10067 Chrisda to Main
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
Labels: area:exchange, Microsoft submitter, In review, Sign off, Admin review

#10068 Publish 10/20/2022 3:30 PM PT
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#10070 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/media/exo-app-only-auth-find-app-registrations.png
  exchange/docs-conceptual/media/exo-app-only-auth-find-roles-and-administrators.png
Labels: area:exchange, Microsoft submitter, In review, Sign off

#10074 Publish main to live on 10/21 @ 10:30 am
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/media/exo-app-only-auth-find-app-registrations.png
  exchange/docs-conceptual/media/exo-app-only-auth-find-roles-and-administrators.png
Labels: Microsoft submitter

#10056 Update New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
Labels: area:exchange, Microsoft submitter

#10078 Update Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
Labels: Microsoft submitter

#10075 Updates for New-ComplianceSecurityFilter cmdlet per PM
  exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md
Labels: area:exchange, Microsoft submitter

#10080 Publish main to live on 10/24 @ 10:30 am
  exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
Labels: Microsoft submitter

#10069 Update Set-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: area:exchange, Microsoft submitter

#10079 Update Set-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-ComplianceSecurityFilter.md
Labels: area:exchange, Microsoft submitter

#10081 Publish 10/24/2022 3:30 PM PT
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#10088 Update descriptions for 2 parameters
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
Labels: Microsoft submitter

#10089 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10093 Publish main to live on 10/27 @ 10:30 am
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
Labels: Microsoft submitter

#10094 Minor PrimarySmtpAddress description updates
  exchange/exchange-ps/exchange/Enable-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Set-MailContact.md
  exchange/exchange-ps/exchange/Set-MailPublicFolder.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-RemoteMailbox.md
Labels: Microsoft submitter

#10095 Publish 10/27/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Enable-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Set-MailContact.md
  exchange/exchange-ps/exchange/Set-MailPublicFolder.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-RemoteMailbox.md
Labels: Microsoft submitter

#10082 Add deprecation note to Get-CsOnlineVoiceUser
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
  skype/skype-ps/skype/New-CsCallingLineIdentity.md
  skype/skype-ps/skype/Set-CsCallingLineIdentity.md
Labels: area:teams / skype, Microsoft submitter

#10099 Publish main to live on 10/28 @ 10:30 am
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
  skype/skype-ps/skype/New-CsCallingLineIdentity.md
  skype/skype-ps/skype/Set-CsCallingLineIdentity.md
Labels: Microsoft submitter

#10097 Powershell - v-smandalika - 6938435 - added a paragraph
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
Labels: area:exchange, Microsoft submitter

#10096 Remove -Confirm
  exchange/exchange-ps/exchange/Set-Place.md
Labels: area:exchange, Microsoft submitter

#10102 Publish main to live, 3:30 10/28
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: Microsoft submitter

#10103 Reformatted properties table
  exchange/docs-conceptual/filter-properties.md
Labels: area:exchange
