Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2022-05, with the labels that each got.

#9378 SCC Blind Cmdlet Sweep Updates
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-Label.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-ProtectionAlert.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
Labels: Microsoft submitter

#9379 Chrisda to Main
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: Microsoft submitter

#9381 Publish 05/02/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-Label.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/New-ProtectionAlert.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
Labels: Microsoft submitter

#9383 Added/updated EndpointDlp
  exchange/exchange-ps/exchange/Get-RegulatoryComplianceUI.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-RegulatoryComplianceUI.md
Labels: Microsoft submitter

#9389 Publish 05/04/2022, 10:30 AM
  exchange/exchange-ps/exchange/Get-RegulatoryComplianceUI.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-RegulatoryComplianceUI.md
Labels: Microsoft submitter

#9390 Update Set-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#9392 General cleanup and update
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
Labels: Microsoft submitter

#9382 Fix typo in app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: area:exchange

#9393 Publish 05/04/2022 3:30 PM PT
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
Labels: Microsoft submitter

#9396 DLPModSub-chrisda to Main
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#9398 Update Set-Place.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: area:exchange, Microsoft submitter

#9344 Update Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
Labels: area:teams / skype

#9345 Update New-CsAutoAttendantPrompt.md
  skype/skype-ps/skype/New-CsAutoAttendantPrompt.md
Labels: area:teams / skype

#9354 Various updates
  skype/skype-ps/skype/Get-CsEffectiveTenantDialPlan.md
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
Labels: area:teams / skype, Microsoft submitter

#9357 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype, Microsoft submitter

#9400 Publish 05/05/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Set-Place.md
  skype/skype-ps/skype/Get-CsEffectiveTenantDialPlan.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/Import-CsOnlineAudioFile.md
  skype/skype-ps/skype/New-CsAutoAttendantPrompt.md
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
Labels: Microsoft submitter

#9401 AdaptScope-chrisda to Main
  exchange/exchange-ps/exchange/Get-AdaptiveScope.md
  exchange/exchange-ps/exchange/New-AdaptiveScope.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-AdaptiveScope.md
  exchange/exchange-ps/exchange/Set-AdaptiveScope.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#9402 Update Set-MailboxJunkEmailConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxJunkEmailConfiguration.md
Labels: Microsoft submitter

#9370 Update New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#9386 Updates to Teams calling policy pages
  skype/skype-ps/skype/Get-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#9408 Publish 05/06/2022, 10:30 AM
  exchange/exchange-ps/exchange/Get-AdaptiveScope.md
  exchange/exchange-ps/exchange/Get-SharingPolicy.md
  exchange/exchange-ps/exchange/New-AdaptiveScope.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-AdaptiveScope.md
  exchange/exchange-ps/exchange/Set-AdaptiveScope.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-MailboxJunkEmailConfiguration.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
  skype/skype-ps/skype/Get-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter

#9399 Updates to LIS/NCS pages
  skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/Get-CsOnlineLisLocation.md
  skype/skype-ps/skype/Set-CsOnlineLisLocation.md
Labels: area:teams / skype

#9409 Publish 05/06/2022 3:30 PM PT
  skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/Get-CsOnlineLisLocation.md
  skype/skype-ps/skype/Set-CsOnlineLisLocation.md
Labels: Microsoft submitter

#9412 OWNOut-chrisda to Main
  exchange/exchange-ps/exchange/Set-CASMailbox.md
Labels: Microsoft submitter

#9413 Publish 05/09/2022, 10:30 AM
  exchange/exchange-ps/exchange/Set-CASMailbox.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: Microsoft submitter

#9414 Fixed 'unlimited archiving' references
  exchange/exchange-ps/exchange/Enable-Mailbox.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#9416 Update Export-MailboxDiagnosticLogs.md
  exchange/exchange-ps/exchange/Export-MailboxDiagnosticLogs.md
Labels: Microsoft submitter

#9417 Publish 05/10/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Enable-Mailbox.md
  exchange/exchange-ps/exchange/Export-MailboxDiagnosticLogs.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#9415 Update cloud support for phone number assignment cmdlets
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: area:teams, Microsoft submitter

#9424 Publish 05/12/2022, 10:30 AM
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#9430 Replaced weird … character
  teams/teams-ps/teams/Get-CsPolicyPackage.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md
Labels: Microsoft submitter

#9431 Publish 05/13/2022 3:30 PM PT
  teams/teams-ps/teams/Get-CsPolicyPackage.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md
Labels: Microsoft submitter

#9423 Updating OnlineVoicemailPolicy and OnlineVoicemailUserSettings
  skype/skype-ps/skype/Get-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Get-CsOnlineVoicemailUserSettings.md
  skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/New-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Remove-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md
Labels: area:teams / skype, Microsoft submitter

#9434 Publish 05/16/2022, 10:30 AM
  skype/skype-ps/skype/Get-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Get-CsOnlineVoicemailUserSettings.md
  skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/New-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Remove-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailPolicy.md
  skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md
Labels: Microsoft submitter

#9437 Note for CBA
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
Labels: area:exchange, Microsoft submitter

#9438 Updates to New/Set-CAR due to customer escalations.
  exchange/exchange-ps/exchange/New-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-ClientAccessRule.md
Labels: area:exchange, Microsoft submitter

#9440 Update Set-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: area:exchange

#9441 Update New-Label.md
  exchange/exchange-ps/exchange/New-Label.md
Labels: area:exchange

#9442 Chrisda to Main
  exchange/exchange-ps/exchange/Get-ActiveSyncDevice.md
  exchange/exchange-ps/exchange/Get-ActiveSyncDeviceClass.md
  exchange/exchange-ps/exchange/Get-CASMailbox.md
  exchange/exchange-ps/exchange/Get-CASMailboxPlan.md
  exchange/exchange-ps/exchange/Get-Contact.md
  exchange/exchange-ps/exchange/Get-DistributionGroup.md
  exchange/exchange-ps/exchange/Get-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Get-EXOCasMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailbox.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/Get-Group.md
  exchange/exchange-ps/exchange/Get-LinkedUser.md
  exchange/exchange-ps/exchange/Get-MailContact.md
  exchange/exchange-ps/exchange/Get-MailPublicFolder.md
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-MailboxPlan.md
  exchange/exchange-ps/exchange/Get-MailboxStatistics.md
  exchange/exchange-ps/exchange/Get-MobileDevice.md
  exchange/exchange-ps/exchange/Get-Recipient.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-RoleGroup.md
  exchange/exchange-ps/exchange/Get-SecurityPrincipal.md
  exchange/exchange-ps/exchange/Get-StoreUsageStatistics.md
  exchange/exchange-ps/exchange/Get-UMMailbox.md
  exchange/exchange-ps/exchange/Remove-UnifiedGroupLinks.md
Labels: Microsoft submitter

#9443 Filter syntax fixes
  exchange/exchange-ps/exchange/Get-UnifiedGroup.md
  exchange/exchange-ps/exchange/Get-User.md
  exchange/exchange-ps/exchange/Get-UserPhoto.md
  exchange/exchange-ps/exchange/New-AddressList.md
  exchange/exchange-ps/exchange/New-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/New-EmailAddressPolicy.md
  exchange/exchange-ps/exchange/New-GlobalAddressList.md
  exchange/exchange-ps/exchange/New-MailboxExportRequest.md
  exchange/exchange-ps/exchange/New-ManagementScope.md
  exchange/exchange-ps/exchange/New-OrganizationSegment.md
  exchange/exchange-ps/exchange/New-ProtectionAlert.md
  exchange/exchange-ps/exchange/Set-AddressList.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Set-EmailAddressPolicy.md
  exchange/exchange-ps/exchange/Set-ExchangeSettings.md
  exchange/exchange-ps/exchange/Set-GlobalAddressList.md
  exchange/exchange-ps/exchange/Set-ManagementScope.md
  exchange/exchange-ps/exchange/Set-OrganizationSegment.md
  exchange/exchange-ps/exchange/Set-ProtectionAlert.md
Labels: Microsoft submitter

#9444 Publish 05/17/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Get-ActiveSyncDevice.md
  exchange/exchange-ps/exchange/Get-ActiveSyncDeviceClass.md
  exchange/exchange-ps/exchange/Get-CASMailbox.md
  exchange/exchange-ps/exchange/Get-CASMailboxPlan.md
  exchange/exchange-ps/exchange/Get-Contact.md
  exchange/exchange-ps/exchange/Get-DistributionGroup.md
  exchange/exchange-ps/exchange/Get-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Get-EXOCasMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailbox.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/Get-Group.md
  exchange/exchange-ps/exchange/Get-Label.md
  exchange/exchange-ps/exchange/Get-LinkedUser.md
  exchange/exchange-ps/exchange/Get-MailContact.md
  exchange/exchange-ps/exchange/Get-MailPublicFolder.md
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-MailboxPlan.md
  exchange/exchange-ps/exchange/Get-MailboxStatistics.md
  exchange/exchange-ps/exchange/Get-MobileDevice.md
  exchange/exchange-ps/exchange/Get-Recipient.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Get-RoleGroup.md
  exchange/exchange-ps/exchange/Get-SecurityPrincipal.md
  exchange/exchange-ps/exchange/Get-StoreUsageStatistics.md
  exchange/exchange-ps/exchange/Get-UMMailbox.md
  exchange/exchange-ps/exchange/Get-UnifiedGroup.md
  exchange/exchange-ps/exchange/Get-User.md
  exchange/exchange-ps/exchange/Get-UserPhoto.md
  exchange/exchange-ps/exchange/New-AddressList.md
  exchange/exchange-ps/exchange/New-ClientAccessRule.md
  exchange/exchange-ps/exchange/New-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/New-EmailAddressPolicy.md
  exchange/exchange-ps/exchange/New-GlobalAddressList.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/New-MailboxExportRequest.md
  exchange/exchange-ps/exchange/New-ManagementScope.md
  exchange/exchange-ps/exchange/New-OrganizationSegment.md
  exchange/exchange-ps/exchange/New-ProtectionAlert.md
  exchange/exchange-ps/exchange/Remove-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Set-AddressList.md
  exchange/exchange-ps/exchange/Set-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Set-EmailAddressPolicy.md
  exchange/exchange-ps/exchange/Set-ExchangeSettings.md
  exchange/exchange-ps/exchange/Set-GlobalAddressList.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-ManagementScope.md
  exchange/exchange-ps/exchange/Set-OrganizationSegment.md
  exchange/exchange-ps/exchange/Set-ProtectionAlert.md
Labels: Microsoft submitter

#9429 Update Set-CsEnhancedEmergencyServiceDisclaimer.md
  skype/skype-ps/skype/Set-CsEnhancedEmergencyServiceDisclaimer.md
Labels: area:teams / skype

#9433 Update examples for Set/Get-CsUserCallingSettings
  teams/teams-ps/teams/Get-CsUserCallingSettings.md
  teams/teams-ps/teams/Set-CsUserCallingSettings.md
Labels: area:teams, Microsoft submitter

#9445 Publish 05/18/2022, 10:30 AM
  skype/skype-ps/skype/Set-CsEnhancedEmergencyServiceDisclaimer.md
  teams/teams-ps/teams/Get-CsUserCallingSettings.md
  teams/teams-ps/teams/Set-CsUserCallingSettings.md
Labels: Microsoft submitter

#9448 Chrisda to Main
  exchange/exchange-ps/exchange/Add-ComplianceCaseMember.md
Labels: Microsoft submitter

#9449 Publish 05/19/2022, 10:30 AM
  exchange/exchange-ps/exchange/Add-ComplianceCaseMember.md
Labels: Microsoft submitter

#9450 Update Get-MailTrafficTopReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md
Labels: Microsoft submitter

#9451 Publish 05/19/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md
Labels: Microsoft submitter

#9436 Update Set-CsAutoAttendant.md
  skype/skype-ps/skype/Set-CsAutoAttendant.md
Labels: area:teams / skype, Microsoft submitter

#9456 Publish 05/20/2022, 10:30 AM
  skype/skype-ps/skype/Set-CsAutoAttendant.md
Labels: Microsoft submitter

#9457 Chrisda to Main
  exchange/exchange-ps/exchange/Get-MailboxImportRequestStatistics.md
  exchange/exchange-ps/exchange/Get-MailboxRepairRequest.md
  exchange/exchange-ps/exchange/Remove-MailboxRepairRequest.md
Labels: Microsoft submitter

#9460 Publish 05/20/2022 3:30 PM PT
  exchange/exchange-ps/exchange/Get-MailboxImportRequestStatistics.md
  exchange/exchange-ps/exchange/Get-MailboxRepairRequest.md
  exchange/exchange-ps/exchange/Remove-MailboxRepairRequest.md
Labels: Microsoft submitter

#9463 Update New-CsTeamsUnassignedNumberTreatment
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
Labels: Microsoft submitter

#9471 Publish 05/25/2022, 10:30 AM
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
Labels: Microsoft submitter

#9473 RecommendedPolicyType param updates
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-HostedOutboundSpamFilterPolicy.md
Labels: Microsoft submitter

#9482 delete SP folder
  .openpublishing.publish.config.json
  sharepoint/TOC.yml
  sharepoint/breadcrumb/toc.yml
  sharepoint/docfx.json
  sharepoint/index.md
Labels: Microsoft submitter

#9324 WIP: Traya1 working
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  staffhub/docs-conceptual/index.md
  staffhub/docs-conceptual/intro.md
  staffhub/docs-conceptual/overview.md
  staffhub/docs-conceptual/toc.yml
  staffhub/mapping/monikerMapping.json
  staffhub/staffhub-ps/staffhub/Add-StaffHubMember.md
  staffhub/staffhub-ps/staffhub/Add-StaffHubShift.md
  staffhub/staffhub-ps/staffhub/Add-StaffHubTeam.md
  staffhub/staffhub-ps/staffhub/Connect-StaffHub.md
  staffhub/staffhub-ps/staffhub/Get-StaffHubMember.md
  staffhub/staffhub-ps/staffhub/Get-StaffHubShifts.md
  staffhub/staffhub-ps/staffhub/Get-StaffHubTeamsForTenant.md
  staffhub/staffhub-ps/staffhub/Get-StaffHubUsersForTenant.md
  staffhub/staffhub-ps/staffhub/Import-StaffHubMember.md
  staffhub/staffhub-ps/staffhub/Import-StaffHubShift.md
  staffhub/staffhub-ps/staffhub/Import-StaffHubTeam.md
  staffhub/staffhub-ps/staffhub/Remove-StaffHubMember.md
  staffhub/staffhub-ps/staffhub/Remove-StaffHubUser.md
  staffhub/staffhub-ps/staffhub/staffhub.md
Labels: Microsoft submitter, Do not merge

#9480 Added bulk domain procedures
  exchange/exchange-ps/exchange/New-SafeLinksRule.md
  exchange/exchange-ps/exchange/Set-SafeLinksRule.md
Labels: Microsoft submitter

#9483 Update New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
Labels: Microsoft submitter

#9484 Publish 05/27/2022 3:30 PM PT
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  exchange/exchange-ps/exchange/New-SafeLinksRule.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Set-SafeLinksRule.md
  sharepoint/TOC.yml
  sharepoint/breadcrumb/toc.yml
  sharepoint/docfx.json
  sharepoint/index.md
  staffhub/docs-conceptual/index.md
  staffhub/docs-conceptual/intro.md
  staffhub/docs-conceptual/overview.md
  staffhub/docs-conceptual/toc.yml
  staffhub/mapping/monikerMapping.json
  staffhub/staffhub-ps/staffhub/Add-StaffHubMember.md
  staffhub/staffhub-ps/staffhub/Add-StaffHubShift.md
  staffhub/staffhub-ps/staffhub/Add-StaffHubTeam.md
  staffhub/staffhub-ps/staffhub/Connect-StaffHub.md
  staffhub/staffhub-ps/staffhub/Get-StaffHubMember.md
  staffhub/staffhub-ps/staffhub/Get-StaffHubShifts.md
  staffhub/staffhub-ps/staffhub/Get-StaffHubTeamsForTenant.md
  staffhub/staffhub-ps/staffhub/Get-StaffHubUsersForTenant.md
  staffhub/staffhub-ps/staffhub/Import-StaffHubMember.md
  staffhub/staffhub-ps/staffhub/Import-StaffHubShift.md
  staffhub/staffhub-ps/staffhub/Import-StaffHubTeam.md
  staffhub/staffhub-ps/staffhub/Remove-StaffHubMember.md
  staffhub/staffhub-ps/staffhub/Remove-StaffHubUser.md
  staffhub/staffhub-ps/staffhub/staffhub.md
Labels: Microsoft submitter

#9477 Update Set-RemoteMailbox.md
  exchange/exchange-ps/exchange/Set-RemoteMailbox.md
Labels: area:exchange, Microsoft submitter

#9487 merge main to live Tues morning 10:30
  exchange/exchange-ps/exchange/Set-RemoteMailbox.md
Labels: Microsoft submitter
