Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2023-02, with the labels that each got.

#10401 Room mailbox account stuff
  exchange/exchange-ps/exchange/New-Mailbox.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#10398 Update Test-ServicePrincipalAuthorization.md
  exchange/exchange-ps/exchange/Test-ServicePrincipalAuthorization.md
Labels: area:exchange, Microsoft submitter

#10400 Update Test-ServicePrincipalAuthorization.md
  exchange/exchange-ps/exchange/Test-ServicePrincipalAuthorization.md
Labels: area:exchange, Microsoft submitter

#10404 Publish main to live on 2/1 @ 10:30 am
  exchange/exchange-ps/exchange/New-Mailbox.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#10405 TestSPA-chrisda to Main
  exchange/exchange-ps/exchange/Test-ServicePrincipalAuthorization.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10407 PM publish, Feb 1
  exchange/exchange-ps/exchange/Test-ServicePrincipalAuthorization.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10408 Update Set-RemoteDomain.md
  exchange/exchange-ps/exchange/Set-RemoteDomain.md
Labels: Microsoft submitter

#10409 updated online link for help doc
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
Labels: area:exchange

#10403 Update to Restore RecoverableItems
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
Labels: area:exchange, Microsoft submitter

#10410 updated online link to help doc
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
Labels: area:exchange

#10411 updated online link to help docs
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
Labels: area:exchange

#10412 updated online link to help docs
  exchange/exchange-ps/exchange/Get-DefaultTenantBriefingConfig.md
Labels: area:exchange

#10414 Publish main to live on 2/2 @ 10:30 am
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/Set-RemoteDomain.md
Labels: Microsoft submitter

#10415 Update Set-CsPhoneNumberAssignment
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#10416 Publish main to live on 2/3 @ 10:30 am
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#10417 Fixes per Jan 23 blind cmdlet sweep
  .openpublishing.redirection.json
  exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md
  exchange/exchange-ps/exchange/Get-PhishFilterPolicy.md
  exchange/exchange-ps/exchange/Get-UMCallSummaryReport.md
  exchange/exchange-ps/exchange/Set-MailContact.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-Place.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10418 Corrected filename capitalization 1of2
  exchange/exchange-ps/exchange/new-labelx.md
  exchange/exchange-ps/exchange/set-labelx.md
Labels: Microsoft submitter

#10419 Chrisda to Main
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#10421 Update .openpublishing.redirection.json
  .openpublishing.redirection.json
Labels: Microsoft submitter

#10394 Update group ID for Shared Voicemail in Set-CsCallQueue.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/Set-CsCallQueue.md
Labels: area:teams / skype

#10402 Updates to TeamsCallHoldPolicy and Get-CsOnlineVoiceUser
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
  skype/skype-ps/skype/Get-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/New-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallHoldPolicy.md
Labels: area:teams / skype, Microsoft submitter

#10420 Publish 02/03/2023 3:30 PM PT
  .openpublishing.redirection.json
  exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md
  exchange/exchange-ps/exchange/Get-PhishFilterPolicy.md
  exchange/exchange-ps/exchange/Get-UMCallSummaryReport.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-MailContact.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-Place.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
  skype/skype-ps/skype/Get-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/New-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Remove-CsTeamsCallHoldPolicy.md
  skype/skype-ps/skype/Set-CsCallQueue.md
  skype/skype-ps/skype/Set-CsTeamsCallHoldPolicy.md
Labels: Microsoft submitter, In review, Admin review

#10426 Chrisda to Main
  exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-User.md
  exchange/exchange-ps/exchange/Start-HistoricalSearch.md
  exchange/exchange-ps/exchange/Test-Message.md
Labels: Microsoft submitter

#10428 Publish main to live on 2/6 @ 10:30 am
  exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-User.md
  exchange/exchange-ps/exchange/Start-HistoricalSearch.md
  exchange/exchange-ps/exchange/Test-Message.md
Labels: Microsoft submitter

#10429 HbridRSVP-chrisda to Main
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#10430 Chrisda to Main
  exchange/exchange-ps/exchange/Get-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-ProtectionAlert.md
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-RoleGroup.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/New-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/Set-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#10432 Publish 02/06/2023 3:30 PM PT
  exchange/exchange-ps/exchange/Get-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-ProtectionAlert.md
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-RoleGroup.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/New-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/Set-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#10431 Delete Set-PhishFilterPolicy.md
  exchange/exchange-ps/exchange/Set-PhishFilterPolicy.md
Labels: Microsoft submitter

#10433 Update .openpublishing.redirection.json
  .openpublishing.redirection.json
Labels: Microsoft submitter

#10434 Fix AAD cmdlet name in "new-serviceprincipal"
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
Labels: area:exchange, Microsoft submitter

#10437 Update connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
Labels: Microsoft submitter, In review, Sign off

#10438 Publish main to live on 2/7 @ 10:30 am
  .openpublishing.redirection.json
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
  exchange/exchange-ps/exchange/Set-PhishFilterPolicy.md
Labels: Microsoft submitter

#10439 Update Search-AdminAuditLog.md
  exchange/exchange-ps/exchange/Search-AdminAuditLog.md
Labels: Microsoft submitter

#10440 Chrisda to Main
  .openpublishing.redirection.json
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: Microsoft submitter

#10441 More Basic auth demise for ExO
  .openpublishing.redirection.json
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
Labels: Microsoft submitter

#10442 Publish 02/07/2023 3:30 PM PT
  .openpublishing.redirection.json
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/basic-auth-connect-to-eop-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md
  exchange/docs-conceptual/basic-auth-connect-to-scc-powershell.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Search-AdminAuditLog.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: Microsoft submitter

#10435 Update New-CsTeamsTranslationRule.md
  skype/skype-ps/skype/New-CsTeamsTranslationRule.md
Labels: area:teams / skype, Microsoft submitter

#10444 Quarantine policy param adjustments
  exchange/exchange-ps/exchange/Get-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Remove-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
Labels: area:exchange, Microsoft submitter

#10445 Publish main to live on 2/9 @ 10:30 am
  exchange/exchange-ps/exchange/Get-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Remove-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
  skype/skype-ps/skype/New-CsTeamsTranslationRule.md
Labels: Microsoft submitter

#10447 EWSCortana-chrisda to Main
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#10448 Publish 02/09/2023 3:30 PM PT
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#10450 Update Set-CsTeamsEnhancedEncryptionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEnhancedEncryptionPolicy.md
Labels: Microsoft submitter, In review, Sign off

#10451 Update New-CsTeamsEnhancedEncryptionPolicy.md
  teams/teams-ps/teams/New-CsTeamsEnhancedEncryptionPolicy.md
Labels: Microsoft submitter, In review, Sign off

#10452 Publish main to live on 2/10 @ 10:30 am
  teams/teams-ps/teams/New-CsTeamsEnhancedEncryptionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEnhancedEncryptionPolicy.md
Labels: Microsoft submitter

#10453 Common attachments filter updates
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: Microsoft submitter

#10454 Publish 02/10/2023 3:30 PM PT
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: Microsoft submitter

#10443 Update Get-CsOnlineVoiceUser.md
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
Labels: area:teams / skype

#10456 Publish main to live on 2/13 @ 10:30 am
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
Labels: Microsoft submitter

#10462 Update connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
Labels: Microsoft submitter

#10463 Publish 02/15/2023 3:30 PM PT
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
Labels: Microsoft submitter

#10469 Removed EOP from affected cmdlets/params
  exchange/exchange-ps/exchange/Disable-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Disable-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Disable-SafeLinksRule.md
  exchange/exchange-ps/exchange/Enable-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Enable-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Enable-SafeLinksRule.md
  exchange/exchange-ps/exchange/Get-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/Get-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Get-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Get-CASMailbox.md
  exchange/exchange-ps/exchange/Get-ConfigAnalyzerPolicyRecommendation.md
  exchange/exchange-ps/exchange/Get-ContentMalwareMdoAggregateReport.md
  exchange/exchange-ps/exchange/Get-ContentMalwareMdoDetailReport.md
  exchange/exchange-ps/exchange/Get-ExoInformationBarrierPolicy.md
  exchange/exchange-ps/exchange/Get-ExoInformationBarrierRelationship.md
  exchange/exchange-ps/exchange/Get-ExoInformationBarrierSegment.md
  exchange/exchange-ps/exchange/Get-InboxRule.md
  exchange/exchange-ps/exchange/Get-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Get-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Get-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Get-SafeLinksRule.md
  exchange/exchange-ps/exchange/New-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/New-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/New-SafeLinksRule.md
  exchange/exchange-ps/exchange/Remove-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Remove-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Remove-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Remove-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Remove-SafeLinksRule.md
  exchange/exchange-ps/exchange/Set-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/Set-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-IRMConfiguration.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-SafeLinksRule.md
Labels: Microsoft submitter

#10459 Update New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
Labels: area:exchange, Microsoft submitter

#10466 Update New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: area:exchange, Microsoft submitter

#10467 Update Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: area:exchange, Microsoft submitter

#10474 Chrisda to Main
  exchange/exchange-ps/exchange/Disable-Mailbox.md
  exchange/exchange-ps/exchange/Enable-Mailbox.md
  exchange/exchange-ps/exchange/Get-DynamicDistributionGroupMember.md
  exchange/exchange-ps/exchange/Get-EligibleDistributionGroupForMigration.md
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/New-MailUser.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Set-Group.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MailContact.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#10476 EOP PowerShell changes
  .openpublishing.redirection.json
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-ConfigAnalyzerPolicyRecommendation.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Import-RecipientDataProperty.md
  exchange/exchange-ps/exchange/New-EOPDistributionGroup.md
  exchange/exchange-ps/exchange/New-EOPMailUser.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Remove-EOPDistributionGroup.md
  exchange/exchange-ps/exchange/Remove-EOPMailUser.md
  exchange/exchange-ps/exchange/Set-EOPDistributionGroup.md
  exchange/exchange-ps/exchange/Set-EOPGroup.md
  exchange/exchange-ps/exchange/Set-EOPMailUser.md
  exchange/exchange-ps/exchange/Set-EOPUser.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Update-EOPDistributionGroupMember.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10477 Publish 02/16/2023 3:30 PM PT
  .openpublishing.redirection.json
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Disable-Mailbox.md
  exchange/exchange-ps/exchange/Enable-Mailbox.md
  exchange/exchange-ps/exchange/Get-ConfigAnalyzerPolicyRecommendation.md
  exchange/exchange-ps/exchange/Get-DynamicDistributionGroupMember.md
  exchange/exchange-ps/exchange/Get-EligibleDistributionGroupForMigration.md
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/Get-RemoteMailbox.md
  exchange/exchange-ps/exchange/Import-RecipientDataProperty.md
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/New-EOPDistributionGroup.md
  exchange/exchange-ps/exchange/New-EOPMailUser.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-MailUser.md
  exchange/exchange-ps/exchange/Remove-EOPDistributionGroup.md
  exchange/exchange-ps/exchange/Remove-EOPMailUser.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Set-EOPDistributionGroup.md
  exchange/exchange-ps/exchange/Set-EOPGroup.md
  exchange/exchange-ps/exchange/Set-EOPMailUser.md
  exchange/exchange-ps/exchange/Set-EOPUser.md
  exchange/exchange-ps/exchange/Set-Group.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MailContact.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Update-EOPDistributionGroupMember.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10480 Chrisda to Main
  exchange/exchange-ps/exchange/Get-AdminAuditLogConfig.md
  exchange/exchange-ps/exchange/Set-AdminAuditLogConfig.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
Labels: Microsoft submitter

#10485 publish main to live, Tuesday 2/21 10:30 AM
  exchange/exchange-ps/exchange/Get-AdminAuditLogConfig.md
  exchange/exchange-ps/exchange/Set-AdminAuditLogConfig.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
Labels: Microsoft submitter

#10455 Update Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: area:teams, Microsoft submitter

#10488 Publish 02/21/2023 3:30 PM PT
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#10493 Publish main to live on 2/22 @ 10:30 am
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
Labels: Microsoft submitter

#10494 Chrisda to Main
  exchange/exchange-ps/exchange/Add-RoleGroupMember.md
  exchange/exchange-ps/exchange/Remove-RoleGroupMember.md
Labels: Microsoft submitter

#10495 Added information to clear confusion about allow
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#10496 Publish 02/22/2023 3:30 PM PT
  exchange/exchange-ps/exchange/Add-RoleGroupMember.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-RoleGroupMember.md
Labels: Microsoft submitter

#10497 Update Release-QuarantineMessage.md
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
Labels: Microsoft submitter

#10501 Update Set-HostedConnectionFilterPolicy.md
  exchange/exchange-ps/exchange/Set-HostedConnectionFilterPolicy.md
Labels: Microsoft submitter

#10502 Publish main to live on 2/23 @ 10:30 am
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
  exchange/exchange-ps/exchange/Set-HostedConnectionFilterPolicy.md
Labels: Microsoft submitter

#10506 BlockedConnector cmdlets
  exchange/exchange-ps/exchange/Get-BlockedConnector.md
  exchange/exchange-ps/exchange/Remove-BlockedConnector.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10508 Update Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
Labels: Microsoft submitter

#10509 Update Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10510 Update Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10512 Update Get-ReviewItems.md
  exchange/exchange-ps/exchange/Get-ReviewItems.md
Labels: Microsoft submitter

#10513 Update Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
Labels: Microsoft submitter

#10514 Publish main to live on 2/24 @ 10:30 am
  exchange/exchange-ps/exchange/Get-BlockedConnector.md
  exchange/exchange-ps/exchange/Remove-BlockedConnector.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10515 Update Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
Labels: Microsoft submitter

#10516 Update Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10504 add more info
  skype/skype-ps/skype/Start-CsExMeetingMigration.md
Labels: area:teams / skype

#10517 Update filter-properties.md
  exchange/docs-conceptual/filter-properties.md
Labels: area:exchange

#10520 RevItems-chrisda to main
  exchange/exchange-ps/exchange/Get-ReviewItems.md
Labels: Microsoft submitter

#10522 Get-ReviewItems
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10523 Publish main to live on 2/27 @ 10:30 am
  exchange/docs-conceptual/filter-properties.md
  exchange/exchange-ps/exchange/Get-ReviewItems.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
  skype/skype-ps/skype/Start-CsExMeetingMigration.md
Labels: Microsoft submitter

#10524 Update Update-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10503 Clarify more config is required
  skype/skype-ps/skype/New-CsOnlineSchedule.md
Labels: area:teams / skype

#10519 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype, Microsoft submitter

#10511 Various updates
  skype/skype-ps/skype/Find-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Get-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/New-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingExtendedNotification.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Sync-CsOnlineApplicationInstance.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsUserCallingSettings.md
Labels: area:teams / skype, Microsoft submitter

#10535 Publish main to live on 2/28 @ 10:30 am
  skype/skype-ps/skype/Find-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/New-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/New-CsOnlineSchedule.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingExtendedNotification.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Sync-CsOnlineApplicationInstance.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsUserCallingSettings.md
Labels: Microsoft submitter

#10528 Update Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10534 Update Update-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10533 Update Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10531 Update Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10530 Update Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
Labels: Microsoft submitter

#10529 Update Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
Labels: Microsoft submitter

#10521 Update Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
Labels: area:exchange, Microsoft submitter
