Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2023-09, with the labels that each got.

#11231 Chrisda to Main
  .openpublishing.redirection.json
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/index.yml
  exchange/docs-conceptual/invoke-command-workarounds-rest-api.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/use-update-exchangehelp.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-Place.md
  exchange/exchange-ps/exchange/Update-ExchangeHelp.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11238 Fixes link path
  skype/skype-ps/skype/Set-CsExternalAccessPolicy.md
Labels: Microsoft submitter

#11239 Update New-DistributionGroup.md
  exchange/exchange-ps/exchange/New-DistributionGroup.md
Labels: area:exchange, Microsoft submitter

#11240 Publish main to live, Tuesday, 10:30AM PDT, 9/5
  .openpublishing.redirection.json
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/index.yml
  exchange/docs-conceptual/invoke-command-workarounds-rest-api.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/use-update-exchangehelp.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-Place.md
  exchange/exchange-ps/exchange/Update-ExchangeHelp.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
  skype/skype-ps/skype/Set-CsExternalAccessPolicy.md
Labels: Microsoft submitter

#11222 Add TeamsVirtualAppointmentsPolicy cmdlet docs
  teams/teams-ps/teams/Get-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/New-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVirtualAppointmentsPolicy.md
Labels: Microsoft submitter

#11241 Update Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
Labels: Microsoft submitter

#11242 publish main to live, 3:30 PM 8/5
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
  teams/teams-ps/teams/Get-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/New-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVirtualAppointmentsPolicy.md
Labels: Microsoft submitter

#11178 Removing duplicate article
  teams/teams-ps/Remove-CsOnlineTelephoneNumber.md
Labels: area:teams

#11245 Update exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: area:exchange

#11243 Description for -RemoveCanceledMeetings property
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: area:exchange, Microsoft submitter

#11244 Update Set-ActiveSyncVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-ActiveSyncVirtualDirectory.md
Labels: area:exchange, Microsoft submitter

#11246 Publish main to live, Wednesday 10:30AM PDT, 9/6
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Set-ActiveSyncVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
  teams/teams-ps/Remove-CsOnlineTelephoneNumber.md
Labels: Microsoft submitter

#11247 v2 to v3
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11255 Publish main to live on 9/7 @ 10:30 am
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11256 Chrisda to Main
  .openpublishing.redirection.json
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/docs-conceptual/values-for-custompropertynames-parameter.md
Labels: Microsoft submitter

#11257 Publish main to live, Friday 10:30AM PDT, 9/8
  .openpublishing.redirection.json
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/toc.yml
  exchange/docs-conceptual/v1-module-mfa-connect-to-scc-powershell.md
  exchange/docs-conceptual/values-for-custompropertynames-parameter.md
Labels: Microsoft submitter

#11226 Add new Meeting Policy setting - ExternalMeetingJoin enum
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#11250 Update Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: area:teams, Microsoft submitter

#11259 Publish main to live, 10:30AM PDT, 9/11
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#11260 Chrisda to Main
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11262 Publish 09/11/2023, 3:30 PM
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11270 Chrisda to Main
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
Labels: Microsoft submitter

#11269 Update New-MoveRequest.md
  exchange/exchange-ps/exchange/New-MoveRequest.md
Labels: Microsoft submitter

#11267 Update NEW_CMDLETS.md
  repo_docs/NEW_CMDLETS.md
Labels: Microsoft submitter

#11271 Publish 09/12/2023, 3:30 PM
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/New-MoveRequest.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
  repo_docs/NEW_CMDLETS.md
Labels: Microsoft submitter

#11248 Update CsTenantNetworkxxx cmdlets
  skype/skype-ps/skype/Get-CsTenantNetworkRegion.md
  skype/skype-ps/skype/Get-CsTenantNetworkSite.md
  skype/skype-ps/skype/Get-CsTenantNetworkSubnet.md
  skype/skype-ps/skype/New-CsTenantNetworkRegion.md
  skype/skype-ps/skype/New-CsTenantNetworkSite.md
  skype/skype-ps/skype/New-CsTenantNetworkSubnet.md
  skype/skype-ps/skype/Remove-CsTenantNetworkRegion.md
  skype/skype-ps/skype/Remove-CsTenantNetworkSite.md
  skype/skype-ps/skype/Remove-CsTenantNetworkSubnet.md
  skype/skype-ps/skype/Set-CsTenantNetworkRegion.md
  skype/skype-ps/skype/Set-CsTenantNetworkSite.md
  skype/skype-ps/skype/Set-CsTenantNetworkSubnet.md
Labels: area:teams / skype, Microsoft submitter

#11233 Update Set-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#11232 Update New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#11216 Creating documentation for [Get|Set]-CsTeamsSipDevicesConfiguration commandlets
  teams/teams-ps/teams/Get-CsTeamsSipDevicesConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsSipDevicesConfiguration.md
Labels: area:teams, Microsoft submitter

#11281 Chrisda to Main
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#11156 Clarify limit and add example
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
Labels: area:teams / skype

#11158 Add missing params
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Grant-CsExternalAccessPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppSetupPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAudioConferencingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsComplianceRecordingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCortanaPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsFeedbackPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMessagingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMobilityPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md
  teams/teams-ps/teams/Grant-CsGroupPolicyPackageAssignment.md
  teams/teams-ps/teams/Grant-CsTeamsEnhancedEncryptionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Grant-CsUserPolicyPackage.md
Labels: area:teams / skype

#11284 Publish main to live, Friday 10:30AM PDT, 9/15
  skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md
  skype/skype-ps/skype/Grant-CsExternalAccessPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAppSetupPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsAudioConferencingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsComplianceRecordingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsCortanaPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsFeedbackPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsIPPhonePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMeetingBroadcastPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMessagingPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsMobilityPolicy.md
  skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
  skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Grant-CsGroupPolicyPackageAssignment.md
  teams/teams-ps/teams/Grant-CsTeamsEnhancedEncryptionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Grant-CsUserPolicyPackage.md
Labels: Microsoft submitter

#11285 Modernization of README article.
  README.md
  images/m365-cc-sc-edit-icon.png
  images/quick-update-comparing-changes-page.png
  images/quick-update-edit-button-on-github-page.png
  images/quick-update-edit-button-on-learn-page.png
  images/quick-update-editor-page.png
  images/quick-update-open-a-pull-request-page.png
  images/quick-update-propose-changes-dialog.png
Labels: Microsoft submitter

#11286 Chrisda to Main
  README.md
Labels: Microsoft submitter

#11287 Publish main to live, Monday 10:30AM PDT, 9/18
  README.md
  images/m365-cc-sc-edit-icon.png
  images/quick-update-comparing-changes-page.png
  images/quick-update-edit-button-on-github-page.png
  images/quick-update-edit-button-on-learn-page.png
  images/quick-update-editor-page.png
  images/quick-update-open-a-pull-request-page.png
  images/quick-update-propose-changes-dialog.png
Labels: Microsoft submitter

#11283 Update Set-MailboxCalendarFolder.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
Labels: area:exchange, Microsoft submitter

#11288 Publish 09/18/2023, 3:30 PM
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
Labels: Microsoft submitter

#11291 Update Get-Place.md
  exchange/exchange-ps/exchange/Get-Place.md
Labels: Microsoft submitter

#11289 updated Add-MailboxPermission.md -ADO-8336593
  exchange/exchange-ps/exchange/Add-ADPermission.md
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Connect-Mailbox.md
  exchange/exchange-ps/exchange/Get-ADPermission.md
  exchange/exchange-ps/exchange/Get-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-MailboxPermission.md
  exchange/exchange-ps/exchange/Get-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/Remove-ADPermission.md
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Remove-MailboxPermission.md
  exchange/exchange-ps/exchange/Remove-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Test-ClientAccessRule.md
Labels: area:exchange, Do not merge

#11292 Typo fixes
  exchange/exchange-ps/exchange/Disable-Mailbox.md
  exchange/exchange-ps/exchange/Enable-Mailbox.md
  exchange/exchange-ps/exchange/New-App.md
  exchange/exchange-ps/exchange/New-InboxRule.md
  exchange/exchange-ps/exchange/Set-InboxRule.md
Labels: Microsoft submitter

#11293 DLP-chrisda to Main
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#11294 Publish 09/19/2023, 3:30 PM
  exchange/exchange-ps/exchange/Add-ADPermission.md
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Connect-Mailbox.md
  exchange/exchange-ps/exchange/Disable-Mailbox.md
  exchange/exchange-ps/exchange/Enable-Mailbox.md
  exchange/exchange-ps/exchange/Get-ADPermission.md
  exchange/exchange-ps/exchange/Get-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-MailboxPermission.md
  exchange/exchange-ps/exchange/Get-Place.md
  exchange/exchange-ps/exchange/Get-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/New-App.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-InboxRule.md
  exchange/exchange-ps/exchange/New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/Remove-ADPermission.md
  exchange/exchange-ps/exchange/Remove-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Remove-MailboxPermission.md
  exchange/exchange-ps/exchange/Remove-PublicFolderClientPermission.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-InboxRule.md
  exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Test-ClientAccessRule.md
Labels: Microsoft submitter

#11272 Update Move-CsUser.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: area:teams / skype, Microsoft submitter

#11298 Publish main to live, Wednesday 10:30AM PDT, 9/20
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#11252 Add missing parameters
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: area:teams / skype

#11299 Publish main to live, Thursday 10:30AM PDT, 9/21
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter

#11300 Chrisda to Main
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
Labels: Microsoft submitter

#11301 Publish 09/21/2023, 3:30 PM
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
Labels: Microsoft submitter

#11249 Adding new PS cmdlets
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Get-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/New-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsSharedCallingRoutingPolicy.md
Labels: area:teams, Microsoft submitter, Do not merge

#11302 Update Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
Labels: area:exchange, Microsoft submitter

#11303 Update Get-MailboxStatistics.md
  exchange/exchange-ps/exchange/Get-MailboxStatistics.md
Labels: area:exchange, Microsoft submitter

#11304 Publish main to live, Friday 10:30AM PDT, 9/22
  exchange/exchange-ps/exchange/Get-MailboxStatistics.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Get-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/New-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsSharedCallingRoutingPolicy.md
Labels: Microsoft submitter

#11307 Update Import-TransportRuleCollection.md
  exchange/exchange-ps/exchange/Import-TransportRuleCollection.md
Labels: Microsoft submitter

#11308 Publish 09/25/2023, 3:30 PM
  exchange/exchange-ps/exchange/Import-TransportRuleCollection.md
Labels: Microsoft submitter

#11253 add UseDeviceAuthentication
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: area:teams / skype

#11309 Publish main to live, Tuesday 10:30 AM PDT, 9/26
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: Microsoft submitter

#11312 Update Add-RecipientPermission.md
  exchange/exchange-ps/exchange/Add-RecipientPermission.md
Labels: Microsoft submitter

#11313 Added line to Confirm for odd params
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Clear-ActiveSyncDevice.md
  exchange/exchange-ps/exchange/Clear-MobileDevice.md
  exchange/exchange-ps/exchange/Complete-MigrationBatch.md
  exchange/exchange-ps/exchange/Disable-AddressListPaging.md
  exchange/exchange-ps/exchange/Disable-AntiPhishRule.md
  exchange/exchange-ps/exchange/Disable-App.md
  exchange/exchange-ps/exchange/Disable-CmdletExtensionAgent.md
  exchange/exchange-ps/exchange/Disable-DistributionGroup.md
  exchange/exchange-ps/exchange/Disable-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Disable-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/Disable-HostedOutboundSpamFilterRule.md
  exchange/exchange-ps/exchange/Disable-InboxRule.md
  exchange/exchange-ps/exchange/Disable-JournalRule.md
  exchange/exchange-ps/exchange/Disable-MailContact.md
  exchange/exchange-ps/exchange/Disable-MailPublicFolder.md
  exchange/exchange-ps/exchange/Disable-MailUser.md
  exchange/exchange-ps/exchange/Disable-Mailbox.md
  exchange/exchange-ps/exchange/Disable-MailboxQuarantine.md
  exchange/exchange-ps/exchange/Disable-MalwareFilterRule.md
  exchange/exchange-ps/exchange/Disable-OutlookProtectionRule.md
  exchange/exchange-ps/exchange/Disable-PushNotificationProxy.md
  exchange/exchange-ps/exchange/Disable-RemoteMailbox.md
  exchange/exchange-ps/exchange/Disable-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Disable-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Disable-SafeLinksRule.md
  exchange/exchange-ps/exchange/Disable-ServiceEmailChannel.md
  exchange/exchange-ps/exchange/Disable-TransportAgent.md
  exchange/exchange-ps/exchange/Disable-TransportRule.md
  exchange/exchange-ps/exchange/Disable-UMCallAnsweringRule.md
  exchange/exchange-ps/exchange/Disable-UMIPGateway.md
  exchange/exchange-ps/exchange/Enable-MailboxQuarantine.md
  exchange/exchange-ps/exchange/Move-AddressList.md
  exchange/exchange-ps/exchange/Move-DatabasePath.md
  exchange/exchange-ps/exchange/Move-OfflineAddressBook.md
  exchange/exchange-ps/exchange/New-ClassificationRuleCollection.md
  exchange/exchange-ps/exchange/New-ClientAccessRule.md
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/Restore-DatabaseAvailabilityGroup.md
  exchange/exchange-ps/exchange/Restore-DetailsTemplate.md
  exchange/exchange-ps/exchange/Set-ClassificationRuleCollection.md
  exchange/exchange-ps/exchange/Set-DataEncryptionPolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpSensitiveInformationType.md
  exchange/exchange-ps/exchange/Set-DlpSensitiveInformationTypeRulePackage.md
  exchange/exchange-ps/exchange/Set-ExchangeSettings.md
  exchange/exchange-ps/exchange/Set-UserPhoto.md
Labels: Microsoft submitter

#11305 Dial Plan Cmdlets: Removing external access dialing parameters.
  skype/skype-ps/skype/Get-CsTenantDialPlan.md
  skype/skype-ps/skype/Grant-CsTenantDialPlan.md
  skype/skype-ps/skype/New-CsTenantDialPlan.md
  skype/skype-ps/skype/Remove-CsTenantDialPlan.md
  skype/skype-ps/skype/Set-CsTenantDialPlan.md
Labels: area:teams / skype

#11310 add AllowCreatePrivateChannels
  teams/teams-ps/teams/New-Team.md
  teams/teams-ps/teams/Set-Team.md
Labels: area:teams

#11314 Update Start-HistoricalSearch.md
  exchange/exchange-ps/exchange/Start-HistoricalSearch.md
Labels: Microsoft submitter

#11274 Update Set-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#11273 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange, Microsoft submitter

#11278 Update Set-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#11316 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: Microsoft submitter

#11318 Update Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
Labels: area:exchange, Microsoft submitter

#11320 Publish 09/27/2023, 3:30 PM
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
Labels: Microsoft submitter

#11319 PolicyRBACScopes param description
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#11321 ExpContExp-chrisda to Main
  exchange/exchange-ps/exchange/Export-ContentExplorerData.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11324 CalendarNotification cmdlet updates
  exchange/exchange-ps/exchange/Get-CalendarNotification.md
  exchange/exchange-ps/exchange/Set-CalendarNotification.md
Labels: Microsoft submitter

#11325 Publish main to live, Thursday 10:30AM PDT, 9/28
  exchange/exchange-ps/exchange/Export-ContentExplorerData.md
  exchange/exchange-ps/exchange/Get-CalendarNotification.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-CalendarNotification.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11326 Chrisda to Main
  exchange/exchange-ps/exchange/Enable-PushNotificationProxy.md
  exchange/exchange-ps/exchange/Get-Notification.md
  exchange/exchange-ps/exchange/Set-Notification.md
Labels: Microsoft submitter

#11329 Publish 09/28/2023, 3:30 PM
  exchange/exchange-ps/exchange/Enable-PushNotificationProxy.md
  exchange/exchange-ps/exchange/Get-Notification.md
  exchange/exchange-ps/exchange/Set-Notification.md
Labels: Microsoft submitter

#11333 Update Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: Microsoft submitter

#11334 Update Get-ConnectionInformation.md
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
Labels: Microsoft submitter

#11337 Publish 09/29/2023, 3:30 PM
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: Microsoft submitter
