Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2023-10, with the labels that each got.

#11342 Update Get-User.md
  exchange/exchange-ps/exchange/Get-User.md
Labels: Microsoft submitter

#11343 Publish main to live, Monday 10:30AM PDT, 10/02
  exchange/exchange-ps/exchange/Get-User.md
Labels: Microsoft submitter

#11335 Update New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
Labels: Microsoft submitter

#11344 Publish 10/02/2023, 3:30 PM
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
Labels: Microsoft submitter

#11330 Update Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
Labels: area:teams, Microsoft submitter

#11336 Update cmdlet syntax and examples according to removed external access dialing parameters
  skype/skype-ps/skype/New-CsTenantDialPlan.md
  skype/skype-ps/skype/Set-CsTenantDialPlan.md
Labels: area:teams / skype

#11339 Update Add-TeamChannelUser.md
  teams/teams-ps/teams/Add-TeamChannelUser.md
Labels: area:teams

#11345 UserPhoto-chrisda to Main
  exchange/exchange-ps/exchange/Get-UserPhoto.md
  exchange/exchange-ps/exchange/Remove-UserPhoto.md
  exchange/exchange-ps/exchange/Set-UserPhoto.md
Labels: Microsoft submitter

#11346 Publish main to live, Wednesday 10:30AM PDT, 10/04
  exchange/exchange-ps/exchange/Get-UserPhoto.md
  exchange/exchange-ps/exchange/Remove-UserPhoto.md
  exchange/exchange-ps/exchange/Set-UserPhoto.md
  skype/skype-ps/skype/New-CsTenantDialPlan.md
  skype/skype-ps/skype/Set-CsTenantDialPlan.md
  teams/teams-ps/teams/Add-TeamChannelUser.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#11347 Update Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
Labels: Microsoft submitter

#11348 Publish main to live, Thursday 10:30AM PDT, 10/05
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
Labels: Microsoft submitter

#11349 HolRemAct-chrisda to Main
  exchange/exchange-ps/exchange/Invoke-HoldRemovalAction.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11350 Publish 10/05/2023, 3:30 PM
  exchange/exchange-ps/exchange/Invoke-HoldRemovalAction.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11352 ARC-chrisda to Main
  exchange/exchange-ps/exchange/Get-ArcConfig.md
  exchange/exchange-ps/exchange/Set-ArcConfig.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11353 Update Set-ArcConfig.md
  exchange/exchange-ps/exchange/Set-ArcConfig.md
Labels: Microsoft submitter

#11354 Publish main to live on 10/6 @ 10:30 am
  exchange/exchange-ps/exchange/Get-ArcConfig.md
  exchange/exchange-ps/exchange/Set-ArcConfig.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11355 Update New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
Labels: area:exchange

#11356 Publish main to live on 10/9 @ 10:30 am
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
Labels: Microsoft submitter

#11341 updated docs to include the new copilot related meeting policy settings.
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams, Microsoft submitter

#11359 Publish 10/09/2023, 3:30 PM
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#11351 updated docs to include the new voice isolation in teams meeting policy
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#11363 Publish main to live, Wednesday 10:30AM PDT, 10/11
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#11205 Update Set-CsTenantFederationConfiguration.md
  skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md
Labels: area:teams / skype, Microsoft submitter

#11358 Update New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
Labels: area:teams

#11366 Publish main to live, Thursday 10:30AM PDT, 10/12
  skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
Labels: Microsoft submitter

#11365 Update Set-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#11369 Add -RecipientGroupScope parameter in New-ManagementRoleAssignment
  exchange/exchange-ps/exchange/New-ManagementRoleAssignment.md
Labels: area:exchange, Microsoft submitter

#11372 Publish to live, Friday 10:30AM PDT, 10/13
  exchange/exchange-ps/exchange/New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#11373 Chrisda to Main
  exchange/exchange-ps/exchange/Get-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-ManagementRoleAssignment.md
Labels: Microsoft submitter

#11374 IntraOrgFilterState
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
Labels: Microsoft submitter

#11375 Publish 10/13/2023, 3:30 PM
  exchange/exchange-ps/exchange/Get-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-ManagementRoleAssignment.md
Labels: Microsoft submitter

#11380 Publish 10/16/2023, 3:30 PM
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter

#11371 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: area:exchange, Microsoft submitter

#11213 Update Set-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: area:exchange

#11383 Update Set-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#11384 Publish main to live, Tuesday 10:30AM PDT, 10/17
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#11385 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#11386 Publish 10/17/2023, 3:30 PM
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#11368 add WelcomeTextToSpeechPrompt
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/Set-CsCallQueue.md
Labels: area:teams / skype

#11382 Update Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: area:exchange, Microsoft submitter

#11389 Publish main to live, Wednesday 10:30AM PDT, 10/18
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/Set-CsCallQueue.md
Labels: Microsoft submitter

#11390 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#11391 Publish 10/18/2023, 3:30 PM
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#11378 Update New-CsTeamTemplate.md
  teams/teams-ps/teams/New-CsTeamTemplate.md
Labels: area:teams, Microsoft submitter

#11397 Publish 10/19/2023, 3:30 PM
  teams/teams-ps/teams/New-CsTeamTemplate.md
Labels: Microsoft submitter

#11379 Update Update-CsTeamTemplate.md
  teams/teams-ps/teams/Update-CsTeamTemplate.md
Labels: area:teams, Microsoft submitter

#11399 Publish main to live, Friday 10:30AM PDT, 10/20
  teams/teams-ps/teams/Update-CsTeamTemplate.md
Labels: Microsoft submitter

#11393 [BULK] - DocuTune - Rebranding of Azure Active Directory to Microsoft Entra terminology (part 1)
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Connect-Mailbox.md
  exchange/exchange-ps/exchange/Enable-DistributionGroup.md
  exchange/exchange-ps/exchange/Enable-MailContact.md
  exchange/exchange-ps/exchange/Enable-MailUser.md
  exchange/exchange-ps/exchange/Enable-Mailbox.md
  exchange/exchange-ps/exchange/Enable-RemoteMailbox.md
  exchange/exchange-ps/exchange/Execute-AzureADLabelSync.md
  exchange/exchange-ps/exchange/Get-AdministrativeUnit.md
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
  exchange/exchange-ps/exchange/Get-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-EXOCasMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-EXOMailboxPermission.md
  exchange/exchange-ps/exchange/Get-EXOMobileDeviceStatistics.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/Get-EXORecipientPermission.md
  exchange/exchange-ps/exchange/Get-InboxRule.md
  exchange/exchange-ps/exchange/Get-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
Labels: area:exchange, Microsoft submitter

#11394 [BULK] - DocuTune - Rebranding of Azure Active Directory to Microsoft Entra terminology (part 2)
  exchange/exchange-ps/exchange/Get-OrganizationSegment.md
  exchange/exchange-ps/exchange/Get-ServicePrincipal.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/New-MailContact.md
  exchange/exchange-ps/exchange/New-MailUser.md
  exchange/exchange-ps/exchange/New-Mailbox.md
  exchange/exchange-ps/exchange/New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/New-RemoteMailbox.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
  exchange/exchange-ps/exchange/New-SyncMailPublicFolder.md
  exchange/exchange-ps/exchange/New-UnifiedGroup.md
  exchange/exchange-ps/exchange/Remove-RemoteMailbox.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
Labels: area:exchange, Microsoft submitter

#11395 [BULK] - DocuTune - Rebranding of Azure Active Directory to Microsoft Entra terminology (part 3)
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Set-FederationTrust.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-MailContact.md
  exchange/exchange-ps/exchange/Set-MailPublicFolder.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationSegment.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-RemoteMailbox.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
  skype/skype-ps/skype/Disable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Enable-CsOnlineSipDomain.md
  skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
  skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md
  skype/skype-ps/skype/New-CsHybridApplicationEndpoint.md
  skype/skype-ps/skype/New-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
Labels: area:exchange, Microsoft submitter

#11396 [BULK] - DocuTune - Rebranding of Azure Active Directory to Microsoft Entra terminology (part 4)
  skype/skype-ps/skype/New-CsVideoInteropServiceProvider.md
  skype/skype-ps/skype/Search-CsOnlineTelephoneNumberInventory.md
  skype/skype-ps/skype/Select-CsOnlineTelephoneNumberInventory.md
  skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md
  skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsUser.md
  skype/skype-ps/skype/Set-CsVideoInteropServiceProvider.md
  skype/skype-ps/skype/Sync-CsOnlineApplicationInstance.md
  spmt/spmt-ps/spmt/Register-SPMTMigration.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Get-CsUserPolicyAssignment.md
  teams/teams-ps/teams/Get-TeamsApp.md
  teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md
  teams/teams-ps/teams/New-CsTeamTemplate.md
  teams/teams-ps/teams/Set-TeamsEnvironmentConfig.md
  teams/teams-ps/teams/Update-CsTeamTemplate.md
  whiteboard/docs-conceptual/overview.md
Labels: area:teams / skype, Microsoft submitter

#11392 Updating Get-CsPhoneNumberAssignment
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
Labels: area:teams, Microsoft submitter

#11370 as per ask added
  exchange/exchange-ps/exchange/Set-CASMailbox.md
Labels: area:exchange, Microsoft submitter, In review, Sign off

#11410 fixing some issues with existing docs
  teams/teams-ps/teams/Get-CsTeamsFirstPartyMeetingTemplateConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsMeetingTemplateConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/New-CsTeamsHiddenMeetingTemplate.md
  teams/teams-ps/teams/New-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingTemplatePermissionPolicy.md
Labels: Microsoft submitter

#11412 OOB Publish
  teams/teams-ps/teams/Get-CsTeamsFirstPartyMeetingTemplateConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsMeetingTemplateConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/New-CsTeamsHiddenMeetingTemplate.md
  teams/teams-ps/teams/New-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsMeetingTemplatePermissionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingTemplatePermissionPolicy.md
Labels: Microsoft submitter

#11408 Correct default value
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype

#11409 Improve description for NotificationMode
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
Labels: area:teams / skype

#11411 Remove deprecated param
  spmt/spmt-ps/spmt/Register-SPMTMigration.md
Labels: area:spmt

#11420 Publish main to live, Tuesday 10:30AM PDT, 10/31
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
  spmt/spmt-ps/spmt/Register-SPMTMigration.md
  teams/teams-ps/teams/Get-Team.md
Labels: Microsoft submitter
