Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2023-05, with the labels that each got.

#10783 Correct description
  skype/skype-ps/skype/Set-CsTeamsClientConfiguration.md
Labels: area:teams / skype

#10784 Add deprecated notice
  skype/skype-ps/skype/Set-CsTeamsPinnedApp.md
Labels: area:teams / skype

#10786 Update to current params
  skype/skype-ps/skype/Get-CsTenantLicensingConfiguration.md
Labels: area:teams / skype

#10790 Publish to live, Monday 10:30AM PST, 5/1
  skype/skype-ps/skype/Get-CsTenantLicensingConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsClientConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsPinnedApp.md
Labels: Microsoft submitter

#10792 v3.2.0-Preview3 updates
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#10793 Publish 05/02/2023 3:30 PM PDT
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#10794 SCC UseRPSSession updates
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#10795 Publish to live, Wednesday 10:30AM PST, 5/3
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#10797 Update Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
Labels: Microsoft submitter

#10799 DMARCQ-chrisda to Main
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
Labels: Microsoft submitter

#10805 Publish to live, Thursday 10:30AM PDT, 5/4
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
Labels: Microsoft submitter

#10807 Direct param updates
  exchange/exchange-ps/exchange/Get-ATPTotalTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/Get-MailDetailDlpPolicyReport.md
  exchange/exchange-ps/exchange/Get-MailDetailEncryptionReport.md
  exchange/exchange-ps/exchange/Get-MailDetailTransportRuleReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficEncryptionReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficPolicyReport.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
Labels: Microsoft submitter

#10809 Update Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
Labels: Microsoft submitter

#10811 publish main to live, 3:30 PM 5/4
  exchange/exchange-ps/exchange/Get-ATPTotalTrafficReport.md
  exchange/exchange-ps/exchange/Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/Get-MailDetailDlpPolicyReport.md
  exchange/exchange-ps/exchange/Get-MailDetailEncryptionReport.md
  exchange/exchange-ps/exchange/Get-MailDetailTransportRuleReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficEncryptionReport.md
  exchange/exchange-ps/exchange/Get-MailTrafficPolicyReport.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
Labels: Microsoft submitter

#10810 Update Get-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelPolicy.md
Labels: Microsoft submitter

#10812 Update Set-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
Labels: Microsoft submitter

#10814 Publish main to live, 10:30AM PDT, 5/5
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
Labels: Microsoft submitter

#10815 Minor formatting updates
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10817 Update Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#10818 Publish main to live, Monday 10:30AM PDT, 5/8
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
  teams/teams-ps/teams/Clear-TeamsEnvironmentConfig.md
  teams/teams-ps/teams/Set-TeamsEnvironmentConfig.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#10819 TrustedOrganizations param
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
Labels: Microsoft submitter

#10820 Publish 05/07/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/Set-InboundConnector.md
Labels: Microsoft submitter

#10826 Chrisda to Main
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/exchange-ps/exchange/Delete-QuarantineMessage.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md
  exchange/exchange-ps/exchange/Preview-QuarantineMessage.md
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
Labels: Microsoft submitter

#10823 Update Get-SafeLinksDetailReport.md
  exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md
Labels: area:exchange

#10824 Update Get-DlpSensitiveInformationTypeRulePackage.md
  exchange/exchange-ps/exchange/Get-DlpSensitiveInformationTypeRulePackage.md
Labels: area:exchange, Microsoft submitter

#10827 Publish main to live, Wednesday 10:30AM PDT, 5/10
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/exchange-ps/exchange/Delete-QuarantineMessage.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-DlpSensitiveInformationTypeRulePackage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md
  exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md
  exchange/exchange-ps/exchange/Preview-QuarantineMessage.md
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
Labels: Microsoft submitter

#10830 Chrisda to Main
  exchange/exchange-ps/exchange/Get-ComplianceRetentionEvent.md
  exchange/exchange-ps/exchange/Get-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/Get-DlpEdmSchema.md
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/New-ComplianceRetentionEvent.md
  exchange/exchange-ps/exchange/New-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/New-DlpSensitiveInformationTypeRulePackage.md
  exchange/exchange-ps/exchange/New-OMEConfiguration.md
  exchange/exchange-ps/exchange/Remove-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/Remove-DlpEdmSchema.md
  exchange/exchange-ps/exchange/Remove-OMEConfiguration.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/Set-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/Set-DlpEdmSchema.md
Labels: Microsoft submitter

#10832 Publish 05/10/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/Get-ComplianceRetentionEvent.md
  exchange/exchange-ps/exchange/Get-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/Get-DlpEdmSchema.md
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/New-ComplianceRetentionEvent.md
  exchange/exchange-ps/exchange/New-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/New-DlpSensitiveInformationTypeRulePackage.md
  exchange/exchange-ps/exchange/New-OMEConfiguration.md
  exchange/exchange-ps/exchange/Remove-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/Remove-DlpEdmSchema.md
  exchange/exchange-ps/exchange/Remove-OMEConfiguration.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/Set-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-ComplianceRetentionEventType.md
  exchange/exchange-ps/exchange/Set-DlpEdmSchema.md
Labels: Microsoft submitter

#10831 Filled empty param descriptions
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#10838 Added CertificateThumbprint note
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
Labels: Microsoft submitter

#10839 Update Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#10837 Update Set-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange

#10836 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange

#10804 Update Set-TransportRule
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10803 Update New-TransportRule
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10802 Update Set-TransportRule
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10801 Update New-TransportRule
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10840 Publish main to live, Thursday 10:30AM PDT, 5/11
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10843 Simulate-chrisda to Main
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#10844 Publish 05/11/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
  exchange/exchange-ps/exchange/Start-HistoricalSearch.md
Labels: Microsoft submitter

#10845 Update Set-TransportService.md
  exchange/exchange-ps/exchange/Set-TransportService.md
Labels: Microsoft submitter

#10847 Removed DLP from quarantine
  exchange/exchange-ps/exchange/Delete-QuarantineMessage.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md
  exchange/exchange-ps/exchange/Preview-QuarantineMessage.md
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
Labels: Microsoft submitter

#10849 Publish main to live on 5/12 @ 3:30 PM PDT
  exchange/exchange-ps/exchange/Delete-QuarantineMessage.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md
  exchange/exchange-ps/exchange/Preview-QuarantineMessage.md
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
Labels: Microsoft submitter

#10848 Updates to some EXO V3 references
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
Labels: Microsoft submitter

#10853 Publish main to live, Monday 10:30AM PDT, 5/15
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#10854 Chrisda to Main
  exchange/exchange-ps/exchange/Get-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md
Labels: Microsoft submitter

#10856 Publish 05/15/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/Get-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md
Labels: Microsoft submitter

#10857 Publish main to live, Tuesday 10:30AM PDT, 5/16
  exchange/exchange-ps/exchange/Enable-TransportRule.md
Labels: Microsoft submitter

#10858 Update Set-RMSTemplate.md
  exchange/exchange-ps/exchange/Set-RMSTemplate.md
Labels: Microsoft submitter

#10859 Publish 05/16/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/Set-RMSTemplate.md
Labels: Microsoft submitter

#10865 Publish 05/18/2023 3:30 PM PDT
  officewebapps/docfx.json
Labels: Microsoft submitter

#10868 Update Set-UnifiedGroup.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: area:exchange

#10871 Update serviceMapping.json
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10872 Publish 05/22/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
  exchange/mapping/serviceMapping.json
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
Labels: Microsoft submitter

#10822 Update Set-ThrottlingPolicyAssociation.md
  exchange/exchange-ps/exchange/Set-ThrottlingPolicyAssociation.md
Labels: area:exchange, Microsoft submitter, In review, Sign off

#10876 Publish main to live, Tuesday 10:30AM PDT, 5/23/2023
  exchange/exchange-ps/exchange/Set-ThrottlingPolicyAssociation.md
Labels: Microsoft submitter

#10881 BccBlocked
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter

#10882 Publish 05/24/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter

#10877 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10884 [ExceptIf]FromScope and [ExceptIf]SentToScope updates
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10887 Publish 05/25/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10883 Adding clarity on cloud availability
  skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Set-CsUser.md
Labels: area:teams / skype, Microsoft submitter

#10890 P4-chrisda to Main
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
Labels: Microsoft submitter

#10891 Publish main to live, Friday 10:30AM PDF, 5/26
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
  skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
  skype/skype-ps/skype/Set-CsUser.md
Labels: Microsoft submitter

#10894 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10895 Update Set-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10896 Publish main to live, Tuesday 10:30AM PDT, 5/30
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10886 Fix description
  teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md
Labels: area:teams

#10885 Fix ForceListenMenuEnabled to SwitchParameter
  skype/skype-ps/skype/New-CsAutoAttendantCallFlow.md
Labels: area:teams / skype

#10889 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype, Microsoft submitter

#10897 Publish 05/30/2023 3:30 PM PDT
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/New-CsAutoAttendantCallFlow.md
  teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md
Labels: Microsoft submitter

#10898 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10899 Update Set-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10901 Publish main to live, Wednesday 10:30AM PDT, 5/31
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter
