Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2023-07, with the labels that each got.

#11023 Various updates
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/Set-CsOnlineLisLocation.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsUser.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#11028 Chrisda to Main
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
Labels: Microsoft submitter

#11017 Update New-CsCallQueue.md
  skype/skype-ps/skype/New-CsCallQueue.md
Labels: area:teams / skype, Microsoft submitter

#11029 Publish main to live, Wednesday 10:30AM publish, 7/5
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/New-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/Set-CsOnlineLisLocation.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsUser.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#11030 Minor syntax block formatting update
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11025 Update New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: area:exchange, Microsoft submitter

#11026 Update Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
Labels: area:exchange

#11031 [ExceptIf]AnyOfRecipientAddressContainsWords
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#11032 Publish main to live, Thursday 10:30AM PDT, 7/6
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11033 Added statement about Get-EXO cmdlets and multiple sessions
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#11034 New article about Invoke-Command workarounds
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/invoke-command-workarounds-rest-api.md
  exchange/docs-conceptual/toc.yml
Labels: Microsoft submitter

#11035 TP-chrisda to Main
  exchange/exchange-ps/exchange/Get-TeamsProtectionPolicy.md
  exchange/exchange-ps/exchange/Get-TeamsProtectionPolicyRule.md
  exchange/exchange-ps/exchange/New-TeamsProtectionPolicy.md
  exchange/exchange-ps/exchange/New-TeamsProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-TeamsProtectionPolicy.md
  exchange/exchange-ps/exchange/Set-TeamsProtectionPolicyRule.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11043 Publish 07/06/2023, 3:30 PM
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/invoke-command-workarounds-rest-api.md
  exchange/docs-conceptual/toc.yml
  exchange/exchange-ps/exchange/Get-TeamsProtectionPolicy.md
  exchange/exchange-ps/exchange/Get-TeamsProtectionPolicyRule.md
  exchange/exchange-ps/exchange/New-TeamsProtectionPolicy.md
  exchange/exchange-ps/exchange/New-TeamsProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-TeamsProtectionPolicy.md
  exchange/exchange-ps/exchange/Set-TeamsProtectionPolicyRule.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11044 Minor updates
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/New-SystemMessage.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-SystemMessage.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#11046 Publish main to live, Friday 10:30AM PDT, 7/7
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/New-SystemMessage.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-SystemMessage.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#11050 DMARC-chrisda to Main
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
Labels: Microsoft submitter

#11049 Yammer rebrand 7/12 publish
  exchange/exchange-ps/exchange/Get-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Get-LicenseVsUsageSummaryReport.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#11053 Publish main to live, Monday 10:30AM PDT, 7/10
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter

#11036 Update New-ServicePrincipal.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
Labels: area:exchange, Microsoft submitter

#11037 Update Get-ServicePrincipal.md
  exchange/exchange-ps/exchange/Get-ServicePrincipal.md
Labels: area:exchange, Microsoft submitter

#11038 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: area:exchange, Microsoft submitter, Do not merge

#11039 Update New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/New-ManagementRoleAssignment.md
Labels: area:exchange, Microsoft submitter

#11040 Update Set-ServicePrincipal.md
  exchange/exchange-ps/exchange/Set-ServicePrincipal.md
Labels: area:exchange, Microsoft submitter, Do not merge

#11041 Update Remove-ServicePrincipal.md
  exchange/exchange-ps/exchange/Remove-ServicePrincipal.md
Labels: area:exchange, Microsoft submitter

#11054 Update exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#11055 Publish 07/10/2023, 3:30 PM
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-ServicePrincipal.md
  exchange/exchange-ps/exchange/New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
  exchange/exchange-ps/exchange/Remove-ServicePrincipal.md
  exchange/exchange-ps/exchange/Set-ServicePrincipal.md
Labels: Microsoft submitter

#11066 SafeAttach-chrisda to Main
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
Labels: Microsoft submitter

#11067 Update exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#11068 Update Set-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: Microsoft submitter

#11052 Publish 7/12: Re-stage Yammer rebrand work
  exchange/exchange-ps/exchange/Get-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Get-LicenseVsUsageSummaryReport.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter, Do not merge

#11069 Chrisda to Main
  exchange/exchange-ps/exchange/Set-IRMConfiguration.md
Labels: Microsoft submitter

#11070 OOB Publish @ 2pm
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Get-LicenseVsUsageSummaryReport.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Remove-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-IRMConfiguration.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#11071 Chrisda to Main
  exchange/exchange-ps/exchange/Set-SearchDocumentFormat.md
  exchange/exchange-ps/exchange/Test-ImapConnectivity.md
Labels: Microsoft submitter

#11077 Publish main to live, Thursday 10:30AM PDT, 7/13
  exchange/exchange-ps/exchange/Set-SearchDocumentFormat.md
  exchange/exchange-ps/exchange/Test-ImapConnectivity.md
Labels: Microsoft submitter

#11063 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange, Microsoft submitter

#11073 Update Set-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#11076 Update Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: area:exchange, Microsoft submitter

#11080 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#11082 Update exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#11083 Publish 07/14/2023, 3:30 PM
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#11081 Update Set-OwaMailboxPolicy.md for PersonalAccountsEnabled
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: area:exchange, Microsoft submitter

#11085 Publish main to live, Monday 10:30AM PDT, 7/17
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#11078 Updates toCsTenantDialPlan and Set-CsUser
  skype/skype-ps/skype/Get-CsTenantDialPlan.md
  skype/skype-ps/skype/Grant-CsTenantDialPlan.md
  skype/skype-ps/skype/New-CsTenantDialPlan.md
  skype/skype-ps/skype/Remove-CsTenantDialPlan.md
  skype/skype-ps/skype/Set-CsTenantDialPlan.md
  skype/skype-ps/skype/Set-CsUser.md
Labels: area:teams / skype, Microsoft submitter

#11086 Publish 07/17/2023, 3:30 PM
  skype/skype-ps/skype/Get-CsTenantDialPlan.md
  skype/skype-ps/skype/Grant-CsTenantDialPlan.md
  skype/skype-ps/skype/New-CsTenantDialPlan.md
  skype/skype-ps/skype/Remove-CsTenantDialPlan.md
  skype/skype-ps/skype/Set-CsTenantDialPlan.md
  skype/skype-ps/skype/Set-CsUser.md
Labels: Microsoft submitter

#11089 Chrisda to Main
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#11090 Publish main to live, Tuesday 10:30AM PDT, 7/18
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter

#11079 Create docs for Teams Template Permission Policy
  teams/teams-ps/teams/Get-CsTeamsTemplatePermissionPolicy.md
  teams/teams-ps/teams/New-CsTeamsHiddenTemplate.md
  teams/teams-ps/teams/New-CsTeamsTemplatePermissionPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsTemplatePermissionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsTemplatePermissionPolicy.md
Labels: area:teams, Microsoft submitter

#11093 Publish main to live, Wednesday 10:30 AM PDT, 7/19
  teams/teams-ps/teams/Get-CsTeamsTemplatePermissionPolicy.md
  teams/teams-ps/teams/New-CsTeamsHiddenTemplate.md
  teams/teams-ps/teams/New-CsTeamsTemplatePermissionPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsTemplatePermissionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsTemplatePermissionPolicy.md
Labels: Microsoft submitter

#11072 Updates to Get/Set-CsPhoneNumberAssignment
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: area:teams, Microsoft submitter

#11094 Chrisda to Main
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#11095 Publish 07/20/2023, 3:30 PM
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#10946 Update Move-CsUser.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: area:teams / skype, Microsoft submitter

#11098 Publish main to live, Friday 10:30 AM PDT, 7/21
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#11099 Fixed tabs and non-ASCII characters
  skype/skype-ps/skype/Get-CsTeamsAppSetupPolicy.md
  skype/skype-ps/skype/New-CsTeamsAppSetupPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAppSetupPolicy.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionErrorReport.md
  teams/teams-ps/teams/Get-CsTeamsTemplatePermissionPolicy.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#11101 Publish main to live, Monday 10:30AM PDT, 7/24
  skype/skype-ps/skype/Get-CsTeamsAppSetupPolicy.md
  skype/skype-ps/skype/New-CsTeamsAppSetupPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md
  skype/skype-ps/skype/Set-CsTeamsAppSetupPolicy.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionErrorReport.md
  teams/teams-ps/teams/Get-CsTeamsTemplatePermissionPolicy.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#11102 Policheck Update - July 24 | Bulk Update
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/New-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Set-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/Set-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Set-TextMessagingAccount.md
  skype/skype-ps/skype/Set-CsOnlineEnhancedEmergencyServiceDisclaimer.md
  teams/teams-ps/teams/Get-CsOnlineTelephoneNumberCountry.md
  teams/teams-ps/teams/Get-CsOnlineTelephoneNumberType.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/New-CsOnlineTelephoneNumberOrder.md
Labels: area:teams / skype, Microsoft submitter

#11107 Publish main to live, Wednesday 10:30AM PDT, 7/26
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/New-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Set-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/Set-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Set-TextMessagingAccount.md
  skype/skype-ps/skype/Set-CsOnlineEnhancedEmergencyServiceDisclaimer.md
  teams/teams-ps/teams/Get-CsOnlineTelephoneNumberCountry.md
  teams/teams-ps/teams/Get-CsOnlineTelephoneNumberType.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/New-CsOnlineTelephoneNumberOrder.md
Labels: Microsoft submitter

#11106 ETR-chrisda to Main
  exchange/exchange-ps/exchange/Get-EtrLimits.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11110 URS-chrisda to Main
  exchange/exchange-ps/exchange/New-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/New-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Set-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/Set-ReportSubmissionRule.md
Labels: Microsoft submitter

#11109 July Blind Cmdlet Sweep
  exchange/exchange-ps/exchange/Add-AvailabilityAddressSpace.md
  exchange/exchange-ps/exchange/Get-AdaptiveScope.md
  exchange/exchange-ps/exchange/Get-Clutter.md
  exchange/exchange-ps/exchange/Get-FocusedInbox.md
  exchange/exchange-ps/exchange/Get-InboxRule.md
  exchange/exchange-ps/exchange/Get-MailboxAutoReplyConfiguration.md
  exchange/exchange-ps/exchange/Get-MailboxCalendarFolder.md
  exchange/exchange-ps/exchange/Get-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Get-MailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-MailboxJunkEmailConfiguration.md
  exchange/exchange-ps/exchange/Get-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Get-MailboxPermission.md
  exchange/exchange-ps/exchange/Get-MailboxRegionalConfiguration.md
  exchange/exchange-ps/exchange/Get-MailboxStatistics.md
  exchange/exchange-ps/exchange/Get-ManagementRoleEntry.md
  exchange/exchange-ps/exchange/Get-MobileDeviceStatistics.md
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/Get-SweepRule.md
  exchange/exchange-ps/exchange/Get-UserPhoto.md
  exchange/exchange-ps/exchange/New-AvailabilityConfig.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/Remove-CalendarEvents.md
  exchange/exchange-ps/exchange/Search-MailboxAuditLog.md
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/Set-AvailabilityConfig.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-Clutter.md
  exchange/exchange-ps/exchange/Set-FocusedInbox.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-MailboxRegionalConfiguration.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-UserPhoto.md
Labels: Microsoft submitter

#11112 July Blind Cmdlet Sweep
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#11114 Publish main to live on 7/27 @ 10:30 am
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: Microsoft submitter

#11115 Update Get-InformationBarrierRecipientStatus.md
  exchange/exchange-ps/exchange/Get-InformationBarrierRecipientStatus.md
Labels: Microsoft submitter

#11117 S&C Blind Cmdlet Sweep
  exchange/exchange-ps/exchange/Get-Label.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/New-AdaptiveScope.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/Set-AdaptiveScope.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#11118 Publish main to live, Friday 10:30 AM PDT, 7/28
  exchange/exchange-ps/exchange/Get-Label.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/New-AdaptiveScope.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/Set-AdaptiveScope.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#11119 Update New-ExchangeCertificate.md
  exchange/exchange-ps/exchange/New-ExchangeCertificate.md
Labels: Microsoft submitter

#11120 Publish 07/28/2023, 3:30 PM
  exchange/exchange-ps/exchange/New-ExchangeCertificate.md
Labels: Microsoft submitter
