Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2023-01, with the labels that each got.

#10288 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10294 CBA-chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10295 Update New-AdaptiveScope.md
  exchange/exchange-ps/exchange/New-AdaptiveScope.md
Labels: Microsoft submitter

#10296 FilterConditions update
  exchange/exchange-ps/exchange/New-AdaptiveScope.md
  exchange/exchange-ps/exchange/Set-AdaptiveScope.md
Labels: Microsoft submitter

#10297 Publish main to live on 1/3 @ 10:30 am
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/exchange-ps/exchange/Add-MailboxPermission.md
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Get-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Get-ComplianceCase.md
  exchange/exchange-ps/exchange/New-AdaptiveScope.md
  exchange/exchange-ps/exchange/New-UnifiedGroup.md
  exchange/exchange-ps/exchange/Remove-UnifiedGroup.md
  exchange/exchange-ps/exchange/Remove-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/Set-AdaptiveScope.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#10282 Observed difference in behavior with -SourceFolder
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
Labels: area:exchange

#10299 Chrisda to Main
  exchange/exchange-ps/exchange/Get-CASMailbox.md
  exchange/exchange-ps/exchange/Get-DataRetentionReport.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/Get-Group.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-Recipient.md
  exchange/exchange-ps/exchange/Get-User.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: Microsoft submitter

#10300 Publish 01/03/2023 3:30 PM PT
  exchange/exchange-ps/exchange/Get-CASMailbox.md
  exchange/exchange-ps/exchange/Get-DataRetentionReport.md
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  exchange/exchange-ps/exchange/Get-Group.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-Recipient.md
  exchange/exchange-ps/exchange/Get-RecoverableItems.md
  exchange/exchange-ps/exchange/Get-User.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: Microsoft submitter

#10293 Updated-7415858
  exchange/exchange-ps/exchange/Set-MailboxJunkEmailConfiguration.md
Labels: area:exchange, Microsoft submitter

#10301 More RecipientTypeDetails updates
  exchange/exchange-ps/exchange/Get-CASMailbox.md
  exchange/exchange-ps/exchange/Get-User.md
Labels: Microsoft submitter

#10302 Publish main to live on 1/4 @ 10:30 am
  exchange/exchange-ps/exchange/Get-CASMailbox.md
  exchange/exchange-ps/exchange/Get-User.md
  exchange/exchange-ps/exchange/Set-MailboxJunkEmailConfiguration.md
Labels: Microsoft submitter

#10274 add option to MembershipType
  teams/teams-ps/teams/New-TeamChannel.md
Labels: area:teams

#10304 Publish main to live on 1/5 @ 10:30 am
  teams/teams-ps/teams/New-TeamChannel.md
Labels: Microsoft submitter

#10306 RPS deprecation text and links
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter

#10307 Chrisda to Main
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
Labels: Microsoft submitter

#10308 Publish 01/06/2023 3:30 PM PT
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
Labels: Microsoft submitter

#10309 Default for common attachments filter to Quarantine
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: Microsoft submitter

#10313 Publish main to live on 1/9 @ 10:30 am
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: Microsoft submitter

#10315 Update Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: Microsoft submitter

#10316 Publish 01/09/2023 3:30 PM PT
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: Microsoft submitter

#10317 Chrisda to Main
  exchange/exchange-ps/exchange/Delete-QuarantineMessage.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/Preview-QuarantineMessage.md
Labels: Microsoft submitter

#10318 Update Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: area:exchange

#10323 Publish 01/10/2023 3:30 PM PT
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: Microsoft submitter

#10322 Update Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
Labels: Microsoft submitter

#10327 Publish main to live on 1/11 @ 10:30 am
  exchange/exchange-ps/exchange/Disable-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Enable-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/Get-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/New-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/New-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Remove-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/Remove-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Set-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/Set-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10326 Disconnect issues with special characters
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md
Labels: Microsoft submitter

#10330 More additions about connect/disconnect issues
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md
Labels: Microsoft submitter

#10331 Publish 01/11/2023 3:30 PM PT
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md
Labels: Microsoft submitter

#10332 Update New-Label.md
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#10333 Update Set-MailboxMessageConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#10305 Create Get-WhiteboardsForTenant.md
  whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardsForTenant.md
  whiteboard/whiteboard-ps/whiteboard/whiteboard.md
Labels: area:whiteboard

#10336 Publish main to live on 1/12 @ 10:30 am
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
  whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardsForTenant.md
  whiteboard/whiteboard-ps/whiteboard/whiteboard.md
Labels: Microsoft submitter

#10337 ApplyHtmlDisclaimerFallbackAction updates
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10338 Publish 01/12/2023 3:30 PM PT
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10339 Update New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#10340 Publish 01/13/2023 3:30 PM PT
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#10335 update parameter name
  skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
Labels: area:teams / skype

#10343 Update Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
Labels: area:exchange

#10321 Update New-CsAutoAttendantCallFlow.md
  skype/skype-ps/skype/New-CsAutoAttendantCallFlow.md
Labels: area:teams / skype

#10346 DefaultSubLabelId - new advantage setting supported for sensitivity …
  exchange/exchange-ps/exchange/new-label.md
  exchange/exchange-ps/exchange/set-label.md
Labels: In review, Sign off

#10350 Chrisda to Main
  exchange/exchange-ps/exchange/Set-Place.md
Labels: Microsoft submitter

#10358 Update Test-Message.md
  exchange/exchange-ps/exchange/Test-Message.md
Labels: area:exchange, Microsoft submitter

#10360 Chrisda to Main
  exchange/exchange-ps/exchange/New-RetentionPolicyTag.md
  exchange/exchange-ps/exchange/Set-RetentionPolicyTag.md
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
Labels: Microsoft submitter

#10361 Publish 01/20/2023 3:30 PM PT
  exchange/exchange-ps/exchange/New-RetentionPolicyTag.md
  exchange/exchange-ps/exchange/Set-RetentionPolicyTag.md
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
Labels: Microsoft submitter

#10375 Tm chrisda
  exchange/exchange-ps/exchange/exchange.md
  exchange/exchange-ps/exchange/test-message.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter, In review, Sign off

#10377 Publish 01/25/2023 3:30 PM PT
  exchange/exchange-ps/exchange/exchange.md
  exchange/exchange-ps/exchange/test-message.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#10384 Undo Reject for Fallback
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10385 Publish main to live on 1/30 @ 10:30 am
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10371 Update Set-MailboxCalendarFolder.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
Labels: area:exchange

#10380 PowerShel - v-smandalika - 7539478 - added a paragraph to two sections
  exchange/exchange-ps/exchange/New-MailboxRestoreRequest.md
Labels: area:exchange, Microsoft submitter

#10382 Update New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
Labels: area:exchange, Microsoft submitter

#10386 Update connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
Labels: Microsoft submitter

#10387 test-message back to correct case
  exchange/exchange-ps/exchange/Test-MessageX.md
Labels: Microsoft submitter

#10388 test-message back to correct case
  exchange/exchange-ps/exchange/Test-Message.md
Labels: Microsoft submitter

#10389 Publish 01/30/2023 3:30 PM PT
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/New-MailboxRestoreRequest.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md
  exchange/exchange-ps/exchange/Test-Message.md
Labels: Microsoft submitter

#10390 Update Remove-UserPhoto.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Remove-UserPhoto.md
Labels: Microsoft submitter

#10391 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10362 Update New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
Labels: area:teams, Microsoft submitter

#10364 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype, Microsoft submitter

#10370 Updates to the delegated flow
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: area:teams, Microsoft submitter

#10329 Update Set-CsTeamsGuestMessagingConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsGuestMessagingConfiguration.md
Labels: area:teams / skype, Microsoft submitter

#10396 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Get-Label.md
Labels: Microsoft submitter

#10393 Update New-DlpFingerprint.md
  exchange/exchange-ps/exchange/New-DlpFingerprint.md
Labels: area:exchange, Microsoft submitter

#10395 Update New-SharingPolicy.md
  exchange/exchange-ps/exchange/New-SharingPolicy.md
Labels: Microsoft submitter

#10397 Publish main to live on 1/31 @ 10:30 am
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/exchange-ps/exchange/Get-Label.md
  exchange/exchange-ps/exchange/New-DlpFingerprint.md
  exchange/exchange-ps/exchange/New-SharingPolicy.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md
  exchange/exchange-ps/exchange/Remove-UserPhoto.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/New-CsCallingLineIdentity.md
  skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md
  skype/skype-ps/skype/Set-CsCallingLineIdentity.md
  skype/skype-ps/skype/Set-CsTeamsGuestMessagingConfiguration.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter
