Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2023-12, with the labels that each got.

#11502 Chrisda to Main
  exchange/exchange-ps/exchange/New-Mailbox.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  images/open-a-pull-request-page.png
  images/propose-file-change.png
  images/upload_files.png
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
Labels: Microsoft submitter

#11503 CAF-chrisda to Main
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
Labels: Microsoft submitter

#11504 Publish 12/01/2023, 3:30 PM
  exchange/exchange-ps/exchange/New-Mailbox.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  images/open-a-pull-request-page.png
  images/propose-file-change.png
  images/upload_files.png
  repo_docs/NEW_CMDLETS.md
  repo_docs/UPDATE_CMDLETS.md
Labels: Microsoft submitter

#11501 Update Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
Labels: area:exchange, Microsoft submitter

#11499 Update Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
Labels: area:exchange

#11508 Update Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
Labels: Microsoft submitter

#11510 Publish 12/04/2023, 3:30 PM
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
Labels: Microsoft submitter

#11506 Update Get-CaseHoldRule.md
  exchange/exchange-ps/exchange/Get-CaseHoldRule.md
Labels: area:exchange, Do not merge

#11511 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#11515 add DisableShowSensitiveContent to New-LabelPolicy
  exchange/exchange-ps/exchange/New-LabelPolicy.md
Labels: Microsoft submitter

#11517 There is an error in the last change in the article. Submitting this change with the fix.
  exchange/exchange-ps/exchange/Get-CaseHoldRule.md
Labels: Microsoft submitter

#11518 Publish main to live, Wednesday 10:30AM PST, 12/6
  exchange/exchange-ps/exchange/Get-CaseHoldRule.md
  exchange/exchange-ps/exchange/New-LabelPolicy.md
Labels: Microsoft submitter

#11516 Update Start-HistoricalSearch.md
  exchange/exchange-ps/exchange/Start-HistoricalSearch.md
Labels: area:exchange, Microsoft submitter

#11519 update Invoke-HoldRemovalAction
  exchange/exchange-ps/exchange/Invoke-HoldRemovalAction.md
Labels: area:exchange, Microsoft submitter

#11520 Publish main to live, Thursday 10:30AM PST, 12/7
  exchange/exchange-ps/exchange/Invoke-HoldRemovalAction.md
  exchange/exchange-ps/exchange/Start-HistoricalSearch.md
Labels: Microsoft submitter

#11521 Add issue template config file and update docfx.json
  .github/ISSUE_TEMPLATE/config.yml
  exchange/docfx.json
  officewebapps/docfx.json
  skype/docfx.json
  spmt/docfx.json
  staffhub/docfx.json
  teams/docfx.json
  whiteboard/docfx.json
Labels: Microsoft submitter

#11523 OOB UUF changes
  .github/ISSUE_TEMPLATE/config.yml
  exchange/docfx.json
  officewebapps/docfx.json
  skype/docfx.json
  spmt/docfx.json
  staffhub/docfx.json
  teams/docfx.json
  whiteboard/docfx.json
Labels: Microsoft submitter

#11527 Update Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
Labels: Microsoft submitter

#11528 Update Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11529 Update Update-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11532 Update Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
Labels: Microsoft submitter

#11531 Update Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11530 Update Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11534 Publish main to live 12/08/2023, 3:30 PM
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11533 Update Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
Labels: area:exchange, Microsoft submitter, Do not merge

#11535 Publish main to live 12/11/2023, 3:30 PM
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
Labels: Microsoft submitter

#11537 Update Get-EXOMailboxFolderStatistics.md
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md
Labels: Microsoft submitter

#11525 Managed Identity update to Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
Labels: Microsoft submitter

#11509 Add CsTeamsCustomBannerText
  teams/teams-ps/teams/Get-CsTeamsCustomBannerText
  teams/teams-ps/teams/New-CsTeamsCustomBannerText
  teams/teams-ps/teams/Remove-CsTeamsCustomBannerText
  teams/teams-ps/teams/Set-CsTeamsCustomBannerText
Labels: area:teams, Microsoft submitter

#11542 Publish main to live, Tuesday 10:30AM PST, 12/12
  exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Get-CsTeamsCustomBannerText
  teams/teams-ps/teams/New-CsTeamsCustomBannerText
  teams/teams-ps/teams/Remove-CsTeamsCustomBannerText
  teams/teams-ps/teams/Set-CsTeamsCustomBannerText
Labels: Microsoft submitter

#11543 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#10863 Update Set-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#11544 Publish main to live 12/12/2023, 3:30 PM
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Add-AvailabilityAddressSpace.md
  exchange/exchange-ps/exchange/Get-AvailabilityConfig.md
  exchange/exchange-ps/exchange/New-AvailabilityConfig.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-AvailabilityConfig.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#11545 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#11546 Update Start-ManagedFolderAssistant.md
  exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md
Labels: area:exchange, Microsoft submitter

#11547 12/22 3:30PM PST Publish
  exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md
Labels: Microsoft submitter
