Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2023-03, with the labels that each got.

#10545 Publish main to live on 3/1 @ 10:30 am
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter

#10540 Update Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10541 Update Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10542 Update Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10543 Update Update-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10546 Update Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
Labels: Microsoft submitter

#10544 Update Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
Labels: Microsoft submitter

#10550 Update Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10551 Update Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10552 Update Update-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10553 Update Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
Labels: Microsoft submitter

#10558 RejectMessageReasonText and GenerateNotification
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10560 Publish main to live on 3/2 @ 10:30 am
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10561 Added note about DLP reporting cmdlet retirement
  exchange/exchange-ps/exchange/Get-DlpDetailReport.md
  exchange/exchange-ps/exchange/Get-DlpDetectionsReport.md
  exchange/exchange-ps/exchange/Get-DlpIncidentDetailReport.md
  exchange/exchange-ps/exchange/Get-DlpSiDetectionsReport.md
Labels: Microsoft submitter

#10563 Removed insecure example
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter

#10565 Publish 03/02/2023 3:30 PM PT
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Get-DlpDetailReport.md
  exchange/exchange-ps/exchange/Get-DlpDetectionsReport.md
  exchange/exchange-ps/exchange/Get-DlpIncidentDetailReport.md
  exchange/exchange-ps/exchange/Get-DlpSiDetectionsReport.md
Labels: Microsoft submitter

#10526 Update description for BusyOnBusyEnabledType
  skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#10554 Add parameter
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype

#10569 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10570 Update Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10571 Update Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10574 Update New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
Labels: area:exchange, Microsoft submitter

#10573 Update Remove-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/Remove-ApplicationAccessPolicy.md
Labels: area:exchange, Microsoft submitter

#10576 Add files via upload
  ContentOwners.txt
Labels: Microsoft submitter

#10578 Update Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10577 OOB Publish
  ContentOwners.txt
Labels: Microsoft submitter

#10579 Update Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10581 Update Update-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10580 Update Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10583 DefaultTenant-chrisda to Main
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/exchange.md
Labels: Microsoft submitter

#10555 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype, Microsoft submitter

#10586 Publish main to live on 3/7 @ 10:30 am
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/exchange.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: Microsoft submitter

#10590 Chrisda to Main
  exchange/exchange-ps/exchange/Enable-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Get-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/New-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
  exchange/exchange-ps/exchange/Test-DataClassification.md
  exchange/exchange-ps/exchange/Test-ServicePrincipalAuthorization.md
Labels: Microsoft submitter

#10591 Publish 03/08/2023 3:30 PM PT
  exchange/exchange-ps/exchange/Enable-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Get-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-ReportSubmissionPolicy.md
  exchange/exchange-ps/exchange/New-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
  exchange/exchange-ps/exchange/Test-DataClassification.md
  exchange/exchange-ps/exchange/Test-ServicePrincipalAuthorization.md
Labels: Microsoft submitter

#10593 Chrisda to Main
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: Microsoft submitter

#10585 CloudCallDataConnection cmdlets update
  teams/teams-ps/teams/Get-CsCloudCallDataConnection.md
  teams/teams-ps/teams/New-CsCloudCallDataConnection.md
Labels: area:teams, Microsoft submitter

#10595 Chrisda to Main
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/mapping/monikerMapping.json
Labels: Microsoft submitter

#10596 Publish main to live on 3/9 @ 10:30 am
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/exchange-ps/exchange/Get-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/mapping/monikerMapping.json
  skype/skype-ps/skype/Get-CsOnlineUser.md
  teams/teams-ps/teams/Get-CsCloudCallDataConnection.md
  teams/teams-ps/teams/New-CsCloudCallDataConnection.md
Labels: Microsoft submitter

#10584 Updates to emergency calling and trunks
  skype/skype-ps/skype/New-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingExtendedNotification.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#10600 Publish main to live on 3/10 @ 10:30 am
  skype/skype-ps/skype/New-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingExtendedNotification.md
  skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
  skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md
  skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
Labels: Microsoft submitter

#10601 Update Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10602 Update Update-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#10608 Advanced setting for label inheritance
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter, In review, Sign off

#10609 Publish 03/13/2023 3:30 PM PT
  exchange/exchange-ps/exchange/New-LabelPolicy.md
  exchange/exchange-ps/exchange/Set-LabelPolicy.md
Labels: Microsoft submitter

#10610 Update app-only-auth-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10616 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10617 Publish main to live on 3/14 @ 10:30 am
  exchange/docfx.json
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
Labels: Microsoft submitter

#10548 Update Set-CsCallQueue.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/Set-CsCallQueue.md
Labels: Microsoft submitter

#10620 Publish 03/14/2023 3:30 PM PT
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/Set-CsCallQueue.md
Labels: Microsoft submitter

#10623 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#10624 Publish main to live on 3/15 @ 10:30 am
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#10607 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype

#10588 Removing any reference of Conference ID reset from the page
  skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md
Labels: area:teams / skype, Microsoft submitter

#10627 Publish main to live on 3/16 @ 10:30 am
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md
  spmt/docfx.json
Labels: Microsoft submitter

#10628 Chrisda to Main
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10630 Publish 03/16/2023 3:30 PM PT
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10622 Update Get-CsOnlineVoiceUser.md
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
Labels: area:teams / skype, Microsoft submitter

#10621 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: area:teams / skype, Microsoft submitter

#10633 Publish main to live on 3/17 @ 10:30 am
  exchange/exchange-ps/exchange/Set-RemoteMailbox.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
Labels: Microsoft submitter

#10634 Update New-ClientAccessRule.md
  exchange/exchange-ps/exchange/New-ClientAccessRule.md
Labels: Microsoft submitter

#10635 Added CAR deprecation note
  exchange/exchange-ps/exchange/Get-ClientAccessRule.md
  exchange/exchange-ps/exchange/Remove-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-ClientAccessRule.md
  exchange/exchange-ps/exchange/Test-ClientAccessRule.md
Labels: Microsoft submitter

#10637 Publish 03/17/2023 3:30 PM PT
  exchange/exchange-ps/exchange/Get-ClientAccessRule.md
  exchange/exchange-ps/exchange/New-ClientAccessRule.md
  exchange/exchange-ps/exchange/Remove-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-ClientAccessRule.md
  exchange/exchange-ps/exchange/Test-ClientAccessRule.md
Labels: Microsoft submitter

#10619 Update TeamsMeetingPolicy commands with WM settings
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: area:teams / skype, Microsoft submitter

#10626 Updating to current params
  skype/skype-ps/skype/Get-CsOnlineSchedule.md
Labels: area:teams / skype

#10639 Publish main to live on 3/20 @ 10:30 am
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
  skype/skype-ps/skype/Get-CsOnlineSchedule.md
  skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#10643 VMF-chrisda to Main
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
Labels: Microsoft submitter

#10644 Publish 03/21/2023 3:30 PM PT
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
Labels: Microsoft submitter

#10648 Publish 03/22/2023 3:30 PM PT
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
Labels: Microsoft submitter

#10636 Update Move-CsUser.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: area:teams / skype, Microsoft submitter

#10646 Update Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: area:exchange, Microsoft submitter

#10652 Publish main to live on 3/23 @ 10:30 am
  exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#10653 ContentType updates
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#10654 Publish 03/23/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#10614 Update Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: area:teams, Microsoft submitter

#10656 Update Set-CsUser
  skype/skype-ps/skype/Set-CsUser.md
Labels: area:teams / skype, Microsoft submitter

#10665 Update Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/Get-MailDetailATPReport.md
Labels: Microsoft submitter

#10668 Set-TransportRule SenderIpRanges/ExceptIfSenderIpRanges
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10663 New-TransportRule SenderIpRanges/ExceptIfSenderIpRanges
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10669 Update MessageTypeMatches/ExceptIfMessageTypeMatches
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: Microsoft submitter

#10671 Publish main to live on 3/29 @ 10:30 am
  exchange/exchange-ps/exchange/Get-MailDetailATPReport.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10670 Update MessageTypeMatches/ExceptIfMessageTypeMatches
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10673 Publish 03/29/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#10679 Update New-TransportRule -SenderAddressLocation section
  exchange/exchange-ps/exchange/New-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10680 Update Set-TransportRule -SenderAddressLocation section
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: area:exchange, Microsoft submitter

#10681 Update Set-Mailbox.md
  exchange/exchange-ps/exchange/Set-Mailbox.md
Labels: area:exchange, Microsoft submitter

#10684 Update Export-MailboxDiagnosticLogs.md to include missing components
  exchange/exchange-ps/exchange/Export-MailboxDiagnosticLogs.md
Labels: area:exchange

#10685 Publish 03/30/2023 3:30 PM PDT
  exchange/exchange-ps/exchange/Export-MailboxDiagnosticLogs.md
Labels: Microsoft submitter
