Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2024-10, with the labels that each got.

#12134 added warning
  exchange/exchange-ps/exchange/Get-IPv6StatusForAcceptedDomain.md
Labels: Microsoft submitter, In review, Sign off

#12144 Published main to live, Tuesday 10:30 PM PST, 10/01
  exchange/exchange-ps/exchange/Get-IPv6StatusForAcceptedDomain.md
Labels: Microsoft submitter

#12145 Update Set-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/Set-ComplianceSecurityFilter.md
Labels: Microsoft submitter

#12146 Publish main to live -10:30 AM Oct 2
  exchange/exchange-ps/exchange/Set-ComplianceSecurityFilter.md
Labels: Microsoft submitter

#12143 Add descriptions to granular federation control field
  teams/teams-ps/teams/Set-CsExternalAccessPolicy.md
  teams/teams-ps/teams/Set-CsTenantFederationConfiguration.md
Labels: In review, Sign off

#12147 Publish main to live, Wednesday 3:30PM PDT, 10/02
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsExternalAccessPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTenantFederationConfiguration.md
  teams/teams-ps/teams/get-csteamsmessagingconfiguration.md
  teams/teams-ps/teams/set-csteamsmessagingconfiguration.md
Labels: Microsoft submitter

#12149 Typos and other fixes
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
Labels: Microsoft submitter

#12150 Publish main to live, Thursday 3:30PM PDT, 10/03
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
Labels: Microsoft submitter

#12151 Publish main to live, Friday 10:30AM PDT, 10/04
  exchange/exchange-ps/exchange/Get-RecipientPermission.md
Labels: Microsoft submitter

#12152 Update Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#12154 Publish main to live, Monday 10:30AM PDT, 10/7
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#12157 publish main to live, 10/9/24, 10:30 AM
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
Labels: Microsoft submitter

#12158 Update Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#12159 Publish main to live, Wednesday 3:30PM PDT, 10/9
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#12160 update/add new field for TeamsCallingPolicy.Copilot
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
Labels: In review, Sign off

#12163 OOB publish to update Set-CsExternalAccessPolicy.md
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsExternalAccessPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter

#12161 Update recipientfilter-properties.md
  exchange/docs-conceptual/recipientfilter-properties.md
Labels: Microsoft submitter, exchange-powershell/svc

#12165 main to live publish, 10/10/2024, 10:30 AM PT
  exchange/docs-conceptual/recipientfilter-properties.md
Labels: Microsoft submitter, exchange-powershell/svc

#12164 Re-remove Skype for Business Online
  teams/teams-ps/teams/Set-CsExternalAccessPolicy.md
Labels: Microsoft submitter

#12167 Update New-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLocationDetectionPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12169 Update New-CsExternalAccessPolicy.md for granular federation control
  teams/teams-ps/teams/New-CsExternalAccessPolicy.md
Labels: In review, Sign off

#12170 publish main to live, 10/11/24, 3:30 pm
  teams/teams-ps/teams/New-CsExternalAccessPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLocationDetectionPolicy.md
Labels: Microsoft submitter

#12171 Update Get-SpoofIntelligenceInsight.md
  exchange/exchange-ps/exchange/Get-SpoofIntelligenceInsight.md
Labels: Microsoft submitter

#12172 Publish main to live, Monday 10:30AM PDT, 10/14
  exchange/exchange-ps/exchange/Get-SpoofIntelligenceInsight.md
Labels: Microsoft submitter

#12174 Update Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#12175 Publish main to live, Tuesday 10:30 PM PST, 10/15
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#12176 Add example for global disable for Set-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
Labels: In review, Sign off

#12177 Publish main to live, Wednesday 3:30PM PDT, 10/16
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
Labels: Microsoft submitter

#12210 Update Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#12315 publish main to live, 10/21/24, 3:30 pm
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#12320 Update New-TransportRule.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#12321 Publish main to live, Wednesday 10:30 AM PST, 10/23
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#12325 Publish main to live, Wednesday 3:30PM PDT, 10/23
  exchange/exchange-ps/exchange/Disable-DnssecForVerifiedDomain.md
  exchange/exchange-ps/exchange/Disable-SmtpDaneInbound.md
  exchange/exchange-ps/exchange/Enable-DnssecForVerifiedDomain.md
  exchange/exchange-ps/exchange/Enable-SmtpDaneInbound.md
  exchange/exchange-ps/exchange/Get-DnssecStatusForVerifiedDomain.md
  exchange/exchange-ps/exchange/Get-SmtpDaneInboundStatus.md
Labels: Microsoft submitter

#12290 Update Get-ALLM365TeamsApps.md
  teams/teams-ps/teams/Get-ALLM365TeamsApps.md
Labels: In review, Sign off

#12330 Publish main to live, Monday 10:30 AM PST, 10/28
  teams/teams-ps/teams/Get-ALLM365TeamsApps.md
  teams/teams-ps/teams/Get-M365TeamsApp.md
Labels: Microsoft submitter

#12317 Update Update-M365TeamsApp.md
  teams/teams-ps/teams/Update-M365TeamsApp.md
Labels: In review

#12319 Create Update-M365UnifiedTenantSettings.md
  teams/teams-ps/teams/Update-M365UnifiedTenantSettings.md
Labels: In review, Sign off

#12318 Create Get-M365UnifiedTenantSettings.md
  teams/teams-ps/teams/Get-M365UnifiedTenantSettings.md
Labels: In review, Sign off

#12331 publish main to live, 3:30 pm, 10/28/24
  teams/teams-ps/teams/Get-M365UnifiedTenantSettings.md
  teams/teams-ps/teams/Update-M365TeamsApp.md
  teams/teams-ps/teams/Update-M365UnifiedTenantSettings.md
Labels: Microsoft submitter

#12324 Update README.md
  README.md
Labels: Microsoft submitter, In review, Sign off

#12334 publish main to live, spooky 10/31/2024, 10:30 am
  README.md
Labels: Microsoft submitter

#12335 Publish main to live 10/31/2024, 3:30 PM
  teams/teams-ps/teams/New-CsAutoAttendantCallableEntity.md
Labels: Microsoft submitter
