Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2024-07, with the labels that each got.

#11958 Publish main to live, 07/01, 3:30 PM IST
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11891 Create Get-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Get-CsTeamsFilesPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11951 Update Set-CsTeamsCallParkPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallParkPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11948 Update Grant-CsApplicationAccessPolicy.md
  teams/teams-ps/teams/Grant-CsApplicationAccessPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11949 Update Get-CsApplicationAccessPolicy.md
  teams/teams-ps/teams/Get-CsApplicationAccessPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11702 Create Get-CsTenantNetworkConfiguration.md
  teams/teams-ps/teams/Get-CsTenantNetworkConfiguration.md
Labels: Microsoft submitter, In review, Sign off

#11833 Add docs for TeamsCustomAppSetting
  teams/teams-ps/teams/Get-CsTeamsSettingsCustomApp.md
  teams/teams-ps/teams/Set-CsTeamsSettingsCustomApp.md
Labels: Microsoft submitter, In review, Sign off

#11960 Updating Parameters for 7 Grant Cmdlets
  teams/teams-ps/teams/Grant-CsExternalAccessPolicy.md
  teams/teams-ps/teams/Grant-CsOnlineVoiceRoutingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsUpgradePolicy.md
  teams/teams-ps/teams/Grant-CsTenantDialPlan.md
Labels: Microsoft submitter, In review, Sign off

#11961 Wrap-chrisda to Main
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
Labels: Microsoft submitter

#11963 Publish main to live, Monday 10:30AM PDT, 07/01
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Set-TransportRule.md
  teams/teams-ps/teams/Get-CsApplicationAccessPolicy.md
  teams/teams-ps/teams/Get-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Get-CsTeamsSettingsCustomApp.md
  teams/teams-ps/teams/Get-CsTenantNetworkConfiguration.md
  teams/teams-ps/teams/Grant-CsApplicationAccessPolicy.md
  teams/teams-ps/teams/Grant-CsExternalAccessPolicy.md
  teams/teams-ps/teams/Grant-CsOnlineVoiceRoutingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsUpgradePolicy.md
  teams/teams-ps/teams/Grant-CsTenantDialPlan.md
  teams/teams-ps/teams/Set-CsTeamsCallParkPolicy.md
  teams/teams-ps/teams/Set-CsTeamsSettingsCustomApp.md
Labels: Microsoft submitter

#11914 Update Get-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.md
Labels: Microsoft submitter, In review, Sign off

#11798 Add SdnRuntimeConfiguration to Set-CsTeamsMeetingBroadcastConfigurati…
  teams/teams-ps/teams/Set-CsTeamsMeetingBroadcastConfiguration.md
Labels: Microsoft submitter, In review, Sign off

#11962 Update Get-CsTeamsExternalAccessConfiguration.md to 2.0.0 schema
  teams/teams-ps/teams/Get-CsTeamsExternalAccessConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsExternalAccessConfiguration.md
Labels: Microsoft submitter, In review, Sign off

#11799 Adding the missing properties to New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11964 Publish main to live 07/01/2024, 3:30 PM
  teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsExternalAccessConfiguration.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsExternalAccessConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsMeetingBroadcastConfiguration.md
Labels: Microsoft submitter

#11801 Kennywan70/teams vdi policy
  teams/teams-ps/teams/Get-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/New-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter, In review, Sign off

#11968 Update Get-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/Get-CsGroupPolicyAssignment.md
Labels: Microsoft submitter, In review, Sign off

#11965 Update Get-CsApplicationAccessPolicy.md
  teams/teams-ps/teams/Get-CsApplicationAccessPolicy.md
Labels: Microsoft submitter

#11969 Publish main to live, Tuesday 3:30PM PDT, 07/02
  teams/teams-ps/teams/Get-CsApplicationAccessPolicy.md
  teams/teams-ps/teams/Get-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/Get-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/New-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#11971 Update Update-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11972 Update Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11976 Publish main to live, Monday 10:30AM PDT, 07/08
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11977 Add dynamic watermarking parameters to Set-Label
  exchange/exchange-ps/exchange/Set-Label.md
Labels: area:exchange, Microsoft submitter, Do not merge

#11978 Update Set-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter

#11979 Update New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
Labels: Microsoft submitter

#11980 Publish main to live, Tuesday 3:30PM PDT, 07/09
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter

#11982 DynWat-chrisda to Main
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#11987 Publish main to live, 07/11, 3:30 PM IST
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#11981 Adding new cmdlets for Phone Number Export
  Export-CsAcquiredPhoneNumber.md
  Get-CsExportAcquiredPhoneNumberStatus.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#11988 publish main to live, 10:30 AM 7/11/24
  Export-CsAcquiredPhoneNumber.md
  Get-CsExportAcquiredPhoneNumberStatus.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#11993 publish main to live 10:30 AM 7/12/24
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#11997 v3.5.1 updates
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#11998 Publish main to live, 07/17, 3:30 PM IST
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#12000 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#11984 Create New-CsSdgBulkSignInRequest.md
  teams/teams-ps/teams/New-CsSdgBulkSignInRequest.md
Labels: Microsoft submitter, Sign off

#12006 RemoveAfter
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#12008 BCS-chrisda to Main
  .openpublishing.redirection.json
  exchange/exchange-ps/exchange/Get-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Get-ConnectionByClientTypeDetailReport.md
  exchange/exchange-ps/exchange/Get-ConnectionByClientTypeReport.md
  exchange/exchange-ps/exchange/Get-CsAVConferenceTimeReport.md
  exchange/exchange-ps/exchange/Get-CsActiveUserReport.md
  exchange/exchange-ps/exchange/Get-CsClientDeviceDetailReport.md
  exchange/exchange-ps/exchange/Get-CsClientDeviceReport.md
  exchange/exchange-ps/exchange/Get-CsConferenceReport.md
  exchange/exchange-ps/exchange/Get-CsP2PAVTimeReport.md
  exchange/exchange-ps/exchange/Get-CsP2PSessionReport.md
  exchange/exchange-ps/exchange/Get-CsPSTNConferenceTimeReport.md
  exchange/exchange-ps/exchange/Get-CsPSTNUsageDetailReport.md
  exchange/exchange-ps/exchange/Get-CsUserActivitiesReport.md
  exchange/exchange-ps/exchange/Get-CsUsersBlockedReport.md
  exchange/exchange-ps/exchange/Get-DistributionGroup.md
  exchange/exchange-ps/exchange/Get-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Get-FederatedOrganizationIdentifier.md
  exchange/exchange-ps/exchange/Get-GroupActivityReport.md
  exchange/exchange-ps/exchange/Get-HybridMailflow.md
  exchange/exchange-ps/exchange/Get-LicenseVsUsageSummaryReport.md
  exchange/exchange-ps/exchange/Get-MailboxActivityReport.md
  exchange/exchange-ps/exchange/Get-MailboxUsageDetailReport.md
  exchange/exchange-ps/exchange/Get-MailboxUsageReport.md
  exchange/exchange-ps/exchange/Get-MailflowStatusReport.md
  exchange/exchange-ps/exchange/Get-MigrationUserStatistics.md
  exchange/exchange-ps/exchange/Get-O365ClientBrowserDetailReport.md
  exchange/exchange-ps/exchange/Get-O365ClientBrowserReport.md
  exchange/exchange-ps/exchange/Get-O365ClientOSDetailReport.md
  exchange/exchange-ps/exchange/Get-O365ClientOSReport.md
  exchange/exchange-ps/exchange/Get-SPOActiveUserReport.md
  exchange/exchange-ps/exchange/Get-SPOSkyDriveProDeployedReport.md
  exchange/exchange-ps/exchange/Get-SPOSkyDriveProStorageReport.md
  exchange/exchange-ps/exchange/Get-SPOTeamSiteDeployedReport.md
  exchange/exchange-ps/exchange/Get-SPOTeamSiteStorageReport.md
  exchange/exchange-ps/exchange/Get-SPOTenantStorageMetricReport.md
  exchange/exchange-ps/exchange/Get-StaleMailboxDetailReport.md
  exchange/exchange-ps/exchange/Get-StaleMailboxReport.md
  exchange/exchange-ps/exchange/Get-UnifiedGroup.md
  exchange/exchange-ps/exchange/New-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/New-InboundConnector.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-MigrationEndpoint.md
  exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-FederatedOrganizationIdentifier.md
  exchange/exchange-ps/exchange/Set-HybridMailflow.md
  exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter, Merge large pull request

#12009 RemoveAfter description and related updates
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#12011 Publish main to live, 07/19, 3:30 PM IST
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#12012 Chrisda to Main
  exchange/exchange-ps/exchange/New-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
Labels: Microsoft submitter

#11999 Remove Desks from Set-Place.md
  exchange/exchange-ps/exchange/Set-Place.md
Labels: area:exchange

#12014 Minor typo/formatting fix
  exchange/exchange-ps/exchange/Set-MailContact.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter

#12004 Update Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off

#12015 Publish main to live 07/19/2024, 3:30 PM
  exchange/exchange-ps/exchange/Set-MailContact.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12016 Blind cmdlet sweep EOP and S&C
  exchange/exchange-ps/exchange/Get-ComplianceTagStorage.md
  exchange/exchange-ps/exchange/Get-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Get-RoleGroup.md
  exchange/exchange-ps/exchange/Get-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Get-SweepRule.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/New-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/New-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-SecOpsOverridePolicy.md
Labels: Microsoft submitter

#12017 Publish main to live, 07/22, 3:30 PM IST
  exchange/exchange-ps/exchange/Get-ComplianceTagStorage.md
  exchange/exchange-ps/exchange/Get-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Get-RoleGroup.md
  exchange/exchange-ps/exchange/Get-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Get-SweepRule.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/New-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/New-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-InformationBarrierPolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Set-PolicyConfig.md
  exchange/exchange-ps/exchange/Set-SecOpsOverridePolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12022 publish main to live, 10:30 AM 7/23/24
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: Microsoft submitter

#12027 Update Grant-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsShiftsPolicy.md
Labels: In review, Sign off

#12025 Creating documentation for existing TeamsRoomVideoTeleConferencingPolicy Cmdlets
  teams/teams-ps/teams/Get-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsAppPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/New-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsShiftsAppPolicy.md
Labels: In review, Sign off

#12026 Update Set-CsTeamsGuestMeetingConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsGuestMeetingConfiguration.md
Labels: In review, Sign off

#11986 Create Get-CsSdgBulkSignInRequestsSummary.md
  teams/teams-ps/teams/Get-CsSdgBulkSignInRequestsSummary.md
Labels: Microsoft submitter, In review, Sign off

#12029 Publish main to live, 07/24, 3:30 PM IST
  teams/teams-ps/teams/Get-CsSdgBulkSignInRequestsSummary.md
  teams/teams-ps/teams/Get-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsAppPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/New-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsGuestMeetingConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsShiftsAppPolicy.md
Labels: Microsoft submitter

#12030 Update Teams Shifts Cmdlets
  teams/teams-ps/teams/Get-CsTeamsNotificationAndFeedsPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnection.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionErrorReport.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md
  teams/teams-ps/teams/Get-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnection.md
  teams/teams-ps/teams/New-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsNotificationAndFeedsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md
  teams/teams-ps/teams/Set-CsTeamsNotificationAndFeedsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsShiftsConnection.md
  teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md
  teams/teams-ps/teams/Set-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Update-CsTeamsShiftsConnection.md
  teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
Labels: In review, Sign off

#11908 Update client-advanced-settings.md
  exchange/docs-conceptual/client-advanced-settings.md
Labels: In review, Sign off, purview/svc, Tier3

#11894 Create New-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/New-CsTeamsFilesPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12021 Update Update-M365TeamsApp.md
  teams/teams-ps/teams/Update-M365TeamsApp.md
Labels: In review, Sign off

#11938 Update Get-CsOnlineUser.md
  teams/teams-ps/teams/Get-CsOnlineUser.md
Labels: Microsoft submitter, In review, Sign off

#12020 Update Get-ALLM365TeamsApps.md
  teams/teams-ps/teams/Get-ALLM365TeamsApps.md
Labels: In review, Sign off

#11893 Create Remove-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsFilesPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12046 publish main to live 10:30 AM 7/30/24
  skype/skype-ps/skype/skype.md
  teams/teams-ps/teams/Get-ALLM365TeamsApps.md
  teams/teams-ps/teams/Get-CsOnlineUser.md
  teams/teams-ps/teams/Remove-CsTeamsFilesPolicy.md
Labels: Microsoft submitter

#12048 Update Set-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#12049 Publish main to live, 07/31, 3:30 PM IST
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#12050 publish main to live 10:30 AM 8/1/24
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
Labels: Microsoft submitter
