Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2024-06, with the labels that each got.

#11876 Update Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: Microsoft submitter

#11877 Publish main to live, 06/04, 3:30 PM IST
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: Microsoft submitter

#11884 update PS syntax
  teams/teams-ps/teams/New-CsOnlineLisCivicAddress.md
Labels: Microsoft submitter

#11885 merging to live
  teams/teams-ps/teams/New-CsOnlineLisCivicAddress.md
Labels: Microsoft submitter

#11883 Add metadata: "Module Name: MicrosoftTeams"
  teams/teams-ps/teams/New-CsOnlineLisCivicAddress.md
Labels: Microsoft submitter, In review, Sign off

#11887 Publish main to live, 06/05, 3:30 PM IST
  teams/teams-ps/teams/New-CsOnlineLisCivicAddress.md
Labels: Microsoft submitter

#11896 Update Set-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEmergencyCallingPolicy.md
Labels: Microsoft submitter

#11897 Advanced setting BlockContentAnalysisServices for New-Label & Set-Label
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#11901 Publish main to live, Thursday 10:30AM PDT, 06/06
  teams/teams-ps/teams/New-CsTeamsEmergencyCallingExtendedNotification.md
Labels: Microsoft submitter

#11899 Add docs for TeamsUpdateManagementPolicy
  teams/teams-ps/teams/Get-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/New-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Set-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#11902 Chrisda to Main
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Update-HybridConfiguration.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter, exchange-powershell/svc

#11903 Publish main to live, Thursday 3:30PM PDT, 06/06
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Update-HybridConfiguration.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
  teams/teams-ps/teams/Get-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/New-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Set-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter, exchange-powershell/svc

#11907 Publish main to live, 06/10, 3:30 PM IST
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11904 Update Set-CsOnlineDialInConferencingUserDefaultNumber.md
  teams/teams-ps/teams/Set-CsOnlineDialInConferencingUserDefaultNumber.md
Labels: Microsoft submitter

#11910 Update Set-CsOnlineDialInConferencingUserDefaultNumber.md
  teams/teams-ps/teams/Set-CsOnlineDialInConferencingUserDefaultNumber.md
Labels: Microsoft submitter

#11909 merge to live
  teams/teams-ps/teams/Set-CsOnlineDialInConferencingUserDefaultNumber.md
Labels: Microsoft submitter

#11912 Update Set-CsTeamsMobilityPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMobilityPolicy.md
Labels: Microsoft submitter

#11913 publish main to live 10:30 AM 6/12/24
  teams/teams-ps/teams/Set-CsTeamsMobilityPolicy.md
Labels: Microsoft submitter

#11916 EmailAuth-chrisda to Main
  exchange/exchange-ps/exchange/New-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
Labels: Microsoft submitter

#11915 Update Set-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsAcsFederationConfiguration.md
Labels: Microsoft submitter, In review, Sign off

#11895 Create Set-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Set-CsTeamsFilesPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11918 Publish main to live, Wednesday 3:30PM PDT, 06/19
  exchange/exchange-ps/exchange/New-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Set-CsTenantFederationConfiguration.md
Labels: Microsoft submitter

#11919 Update Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#11920 Publish main to live, Thursday 10:30AM PDT, 06/20
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#11923 Publish main to live, Monday 10:30AM PDT, 06/24
  exchange/exchange-ps/exchange/Get-DnssecStatusForVerifiedDomain.md
Labels: Microsoft submitter

#11925 GA updates
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Update-HybridConfiguration.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#11921 Update New-CsTeamsEmergencyCallingExtendedNotification.md
  teams/teams-ps/teams/New-CsTeamsEmergencyCallingExtendedNotification.md
Labels: Microsoft submitter

#11926 Publish main to live 06/24/2024, 3:30 PM
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Update-HybridConfiguration.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
  teams/teams-ps/teams/New-CsTeamsEmergencyCallingExtendedNotification.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#11786 Remove Meeting Policy setting from doc - EnableAnonymousUserCaptcha
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#11928 Publish main to live, 06/25, 3:30 PM IST
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#11931 publish main to live 10:30 AM 6/25/24
  exchange/exchange-ps/exchange/New-AdminAuditLogSearch.md
  exchange/exchange-ps/exchange/Search-AdminAuditLog.md
  teams/teams-ps/teams/Get-CsTeamsExternalAccessConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsExternalAccessConfiguration.md
Labels: Microsoft submitter

#11924 Update Set-CsTeamsComplianceRecordingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsComplianceRecordingPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11932 Publish main to live, Tuesday 3:30PM PDT, 06/25
  teams/teams-ps/teams/Set-CsTeamsComplianceRecordingPolicy.md
Labels: Microsoft submitter

#11933 Update exchange-online-powershell-v2.md
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/invoke-command-workarounds-rest-api.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#11934 Publish main to live, Wednesday 3:30PM PDT, 06/26/2025
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/invoke-command-workarounds-rest-api.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#11940 Update Set-CsTeamsComplianceRecordingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsComplianceRecordingPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11950 Update Get-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelPolicy.md
Labels: Microsoft submitter

#11953 Publish main to live, Friday 10:30AM PDT, 06/28
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#11947 Update Set-CsApplicationAccessPolicy.md
  teams/teams-ps/teams/Set-CsApplicationAccessPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11946 Creating Teams Survivable Branch Cmdlets
  teams/teams-ps/teams/Get-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Get-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Grant-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/New-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/New-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Remove-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Remove-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Set-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Set-CsTeamsSurvivableBranchAppliancePolicy.md
Labels: Microsoft submitter, In review, Sign off

#11956 Publish main to live 06/28/2024, 3:30 PM
  teams/teams-ps/teams/Get-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Get-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Grant-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/New-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/New-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Remove-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Remove-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Set-CsApplicationAccessPolicy.md
  teams/teams-ps/teams/Set-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Set-CsTeamsSurvivableBranchAppliancePolicy.md
Labels: Microsoft submitter

#11957 Viva feature chrisda
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter
