Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2024-09, with the labels that each got.

#12095 Update Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#12096 Publish main to live, 09/03, 11:00 AM IST
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#12094 Updating Export-CsAcquiredPhoneNumber examples
  teams/teams-ps/teams/Export-CsAcquiredPhoneNumber.md
  teams/teams-ps/teams/Get-CsExportAcquiredPhoneNumberStatus.md
Labels: Microsoft submitter

#12097 Publish main to live, Tuesday 3:30PM PDT, 09/03
  teams/teams-ps/teams/Export-CsAcquiredPhoneNumber.md
  teams/teams-ps/teams/Get-CsExportAcquiredPhoneNumberStatus.md
Labels: Microsoft submitter

#12092 Update New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12098 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter, In review, Sign off

#12099 publish main to live, 10:30 AM 9/4/24
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12077 Add TeamsAIPolicy cmdlets public docs
  teams/teams-ps/teams/Get-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsAIPolicy.md
  teams/teams-ps/teams/New-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
Labels: In review, Sign off

#12100 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#12101 Publish main to live, Wednesday 3:30PM PDT, 09/04
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  teams/teams-ps/teams/Get-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsAIPolicy.md
  teams/teams-ps/teams/New-CsTeamsAIPolicy.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
Labels: Microsoft submitter

#12102 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#12103 Publish main to live, 09/05, 11:00 AM IST
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#12105 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#12106 publish main to live 10:30 AM 9/5/2024
  exchange/exchange-ps/exchange/Enable-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#12107 Update Set-Label.md with content mark alignment clarification
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#12109 Update Invoke-ComplianceSecurityFilterAction.md
  exchange/exchange-ps/exchange/Invoke-ComplianceSecurityFilterAction.md
Labels: Microsoft submitter

#12110 Publish main to live, Thursday 3:30PM PDT, 09/05
  exchange/exchange-ps/exchange/Invoke-ComplianceSecurityFilterAction.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#12108 Update New-Label.md with content mark clarification
  exchange/exchange-ps/exchange/New-Label.md
Labels: Microsoft submitter, In review, Sign off

#12111 Publish main to live, Friday 10:30AM PDT, 09/06/2024
  exchange/exchange-ps/exchange/New-Label.md
Labels: Microsoft submitter

#12112 Update Invoke-ComplianceSecurityFilterAction.md
  exchange/exchange-ps/exchange/Invoke-ComplianceSecurityFilterAction.md
Labels: Microsoft submitter

#12113 Publish main to live, Tuesday 3:30PM PDT, 09/10
  exchange/exchange-ps/exchange/Invoke-ComplianceSecurityFilterAction.md
Labels: Microsoft submitter

#12114 IPv6-chrisda to Main
  exchange/exchange-ps/exchange/Disable-IPv6ForAcceptedDomain.md
  exchange/exchange-ps/exchange/Enable-IPv6ForAcceptedDomain.md
  exchange/exchange-ps/exchange/Get-IPv6StatusForAcceptedDomain.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#12115 10:30 AM main to live publish 9/13
  exchange/exchange-ps/exchange/Disable-IPv6ForAcceptedDomain.md
  exchange/exchange-ps/exchange/Enable-IPv6ForAcceptedDomain.md
  exchange/exchange-ps/exchange/Get-IPv6StatusForAcceptedDomain.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#12023 Update New-CsCallQueue.md
  teams/teams-ps/teams/New-CsCallQueue.md
  teams/teams-ps/teams/Set-CsCallQueue.md
Labels: Microsoft submitter

#12116 Publish main to live, Monday 10:30AM PDT, 09/16
  teams/teams-ps/teams/New-CsCallQueue.md
  teams/teams-ps/teams/Set-CsCallQueue.md
Labels: Microsoft submitter

#11837 Update Set-CsOnlineVoicemailUserSettings.md
  teams/teams-ps/teams/Set-CsOnlineVoicemailUserSettings.md
Labels: Microsoft submitter

#12117 Publish main to live, Tuesday 10:30 AM PDT, 09/17
  teams/teams-ps/teams/Set-CsOnlineVoicemailUserSettings.md
Labels: Microsoft submitter

#12118 IP address support in TABL
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#12119 Update Get-ConnectionInformation.md
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
Labels: Microsoft submitter

#12120 Publish main to live, 09/23, 11:00 AM IST
  exchange/exchange-ps/exchange/Get-ConnectionInformation.md
Labels: Microsoft submitter

#12121 Add more examples for Set-CsTeamsAiPolicy doc
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
Labels: In review, Sign off

#12122 Publish main to live, Tuesday 3:30PM PDT, 09/24
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
Labels: Microsoft submitter

#12123 Update Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12126 Viva-chrisda to Main
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#12125 Update Set-CsTeamsMessagingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMessagingPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12127 Published main to live, Wednesday 10:30 AM PDT, 09/25
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-MessageTrackingLog.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMessagingPolicy.md
Labels: Microsoft submitter

#12128 v3.6.0 EXO Module release
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#12129 Publish main to live, Wednesday 3:30PM PDT, 09/25
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#12131 Adding Missing Documentation for Parameters available on TPM
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/New-CsTeamsEmergencyCallRoutingPolicy.md
  teams/teams-ps/teams/Set-CsExternalAccessPolicy.md
  teams/teams-ps/teams/Set-CsTeamsFeedbackPolicy.md
  teams/teams-ps/teams/Set-CsTenantFederationConfiguration.md
Labels: Microsoft submitter, In review, Sign off

#12132 Publish main to live, Thursday 3:30PM PDT, 09/26
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/New-CsTeamsEmergencyCallRoutingPolicy.md
  teams/teams-ps/teams/Set-CsExternalAccessPolicy.md
  teams/teams-ps/teams/Set-CsTeamsFeedbackPolicy.md
  teams/teams-ps/teams/Set-CsTenantFederationConfiguration.md
Labels: Microsoft submitter

#12130 PowerShell - v-smandalika - 9375980 - Updated the information of a parameter-specific section
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter, In review, Sign off

#12133 Publish main to live, 09/27, 11:00 AM IST
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter

#12139 Adding Teams Messaging Configuration Docs
  teams/teams-ps/teams/get-csteamsmessagingconfiguration.md
  teams/teams-ps/teams/set-csteamsmessagingconfiguration.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter, In review, Sign off

#12140 TABL-chrisda to Main
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#12135 Add missing params to teams ai policy cmdlet docs
  teams/teams-ps/teams/Get-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsAIPolicy.md
  teams/teams-ps/teams/New-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
Labels: In review, Sign off

#12141 Publish main to live 09/27/2024, 3:30 PM
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
  teams/teams-ps/teams/Get-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsAIPolicy.md
  teams/teams-ps/teams/New-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
  teams/teams-ps/teams/get-csteamsmessagingconfiguration.md
  teams/teams-ps/teams/set-csteamsmessagingconfiguration.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter
