Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2024-12, with the labels that each got.

#12395 Updated Get-CsOnlineTelephoneNumberOrder and new cmdlets for creating…
  teams/teams-ps/teams/Get-CsOnlineTelephoneNumberOrder.md
  teams/teams-ps/teams/New-CsOnlineDirectRoutingTelephoneNumberUploadOrder.md
  teams/teams-ps/teams/New-CsOnlineTelephoneNumberReleaseOrder.md
Labels: Microsoft submitter

#12397 Publish main to live, Tuesday 3:30PM PST, 12/03
  teams/teams-ps/teams/Get-CsOnlineTelephoneNumberOrder.md
  teams/teams-ps/teams/New-CsOnlineDirectRoutingTelephoneNumberUploadOrder.md
  teams/teams-ps/teams/New-CsOnlineTelephoneNumberReleaseOrder.md
Labels: Microsoft submitter

#12398 Fixes per build report
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  spmt/docs-conceptual/index.md
  spmt/docs-conceptual/intro.md
  spmt/docs-conceptual/overview.md
  teams/docs-conceptual/index.md
  teams/docs-conceptual/overview.md
  teams/teams-ps/teams/Get-CsOnlineTelephoneNumberOrder.md
  teams/teams-ps/teams/New-CsOnlineDirectRoutingTelephoneNumberUploadOrder.md
  teams/teams-ps/teams/New-CsOnlineTelephoneNumberReleaseOrder.md
Labels: Microsoft submitter, exchange-powershell/svc

#12399 Publish main to live, 12/04, 11:00 AM IST
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  spmt/docs-conceptual/index.md
  spmt/docs-conceptual/intro.md
  spmt/docs-conceptual/overview.md
  teams/docs-conceptual/index.md
  teams/docs-conceptual/overview.md
  teams/teams-ps/teams/Get-CsOnlineTelephoneNumberOrder.md
  teams/teams-ps/teams/New-CsOnlineDirectRoutingTelephoneNumberUploadOrder.md
  teams/teams-ps/teams/New-CsOnlineTelephoneNumberReleaseOrder.md
Labels: Microsoft submitter, exchange-powershell/svc

#12391 Update Teams Calling Policy - Add spend limits parameters
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
Labels: In review, Sign off

#12390 Add description attribute to Teams AI Policy cmdlet documentation
  teams/teams-ps/teams/New-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
Labels: In review, Sign off

#12403 Published main to live, Thursday 10:30 AM PST, 12/05
  teams/teams-ps/teams/Get-CsTeamsMultiTenantOrganizationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsMultiTenantOrganizationConfiguration.md
Labels: Microsoft submitter

#12402 Update Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off, PubOps fixes

#12404 Publish main to live, 12/05/24, 3:30 PM PT
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12406 Removing Service Number reference
  teams/teams-ps/teams/New-CsCallingLineIdentity.md
  teams/teams-ps/teams/Set-CsCallingLineIdentity.md
Labels: Microsoft submitter

#12407 Update New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
Labels: Microsoft submitter

#12408 main to live publish, 12/6/24, 3:30 PM PT
  teams/teams-ps/teams/New-CsCallingLineIdentity.md
  teams/teams-ps/teams/Set-CsCallingLineIdentity.md
Labels: Microsoft submitter

#12409 Update Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
Labels: Microsoft submitter

#12410 Quarantine 'Move to' to 'Deliver to'
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
Labels: Microsoft submitter

#12411 Published main to live, Monday 5:00 PM IST, 12/09
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
Labels: Microsoft submitter

#12412 PoliCheck fix
  skype/skype-ps/skype/New-CsRgsWorkflow.md
Labels: Microsoft submitter

#12415 Published main to live, Tuesday 10:30 AM PST, 12/10
  exchange/exchange-ps/exchange/Get-EXORecipient.md
  skype/skype-ps/skype/New-CsRgsWorkflow.md
Labels: Microsoft submitter

#12416 Consistency updates for RemotePowerShellEnabled param
  exchange/exchange-ps/exchange/New-MailUser.md
  exchange/exchange-ps/exchange/New-Mailbox.md
  exchange/exchange-ps/exchange/New-RemoteMailbox.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#12417 Update disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
Labels: Microsoft submitter, exchange-powershell/svc

#12418 Published main to live, Wednesday 10:30 AM PST, 12/11
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/exchange-ps/exchange/New-MailUser.md
  exchange/exchange-ps/exchange/New-Mailbox.md
  exchange/exchange-ps/exchange/New-RemoteMailbox.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter, exchange-powershell/svc

#12419 Chrisda to Main
  .openpublishing.redirection.json
  exchange/exchange-ps/exchange/Get-ClientAccessRule.md
  exchange/exchange-ps/exchange/Get-FederatedOrganizationIdentifier.md
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Get-SecOpsOverrideRule.md
  exchange/exchange-ps/exchange/New-ClientAccessRule.md
  exchange/exchange-ps/exchange/New-MailUser.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-MoveRequest.md
  exchange/exchange-ps/exchange/Remove-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-AcceptedDomain.md
  exchange/exchange-ps/exchange/Set-CASMailboxPlan.md
  exchange/exchange-ps/exchange/Set-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Set-FederatedOrganizationIdentifier.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-MoveRequest.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Test-ClientAccessRule.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#12420 Publish main to live, 12/12, 11:00 AM IST
  .openpublishing.redirection.json
  exchange/exchange-ps/exchange/Get-ClientAccessRule.md
  exchange/exchange-ps/exchange/Get-FederatedOrganizationIdentifier.md
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Get-SecOpsOverrideRule.md
  exchange/exchange-ps/exchange/New-ClientAccessRule.md
  exchange/exchange-ps/exchange/New-MailUser.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-MoveRequest.md
  exchange/exchange-ps/exchange/Remove-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-AcceptedDomain.md
  exchange/exchange-ps/exchange/Set-CASMailboxPlan.md
  exchange/exchange-ps/exchange/Set-ClientAccessRule.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DynamicDistributionGroup.md
  exchange/exchange-ps/exchange/Set-FederatedOrganizationIdentifier.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-MoveRequest.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Test-ClientAccessRule.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#12360 Update parameters for legacy Exchange tokens
  exchange/exchange-ps/exchange/Get-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
Labels: area:exchange, Microsoft submitter

#12422 Chrisda to Main
  exchange/exchange-ps/exchange/Export-ContentExplorerData.md
  exchange/exchange-ps/exchange/Get-ComplianceTag.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Get-PendingDelicenseUser.md
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Import-TransportRuleCollection.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Remove-ComplianceTag.md
  exchange/exchange-ps/exchange/Remove-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md
Labels: Microsoft submitter

#12423 Publish main to live, 12/12/24, 3:30 PM PT
  exchange/exchange-ps/exchange/Export-ContentExplorerData.md
  exchange/exchange-ps/exchange/Get-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Get-ComplianceTag.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Get-PendingDelicenseUser.md
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Import-TransportRuleCollection.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Remove-ComplianceTag.md
  exchange/exchange-ps/exchange/Remove-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md
Labels: Microsoft submitter

#12424 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#12425 Publish main to live, 12/17, 11:00 AM IST
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#12414 Update Set-CsOnlineLisCivicAddress.md
  teams/teams-ps/teams/Set-CsOnlineLisCivicAddress.md
Labels: In review, Sign off, PubOps fixes

#12426 Published main to live, Wednesday 10:30 AM PST, 12/18
  teams/teams-ps/teams/Set-CsOnlineLisCivicAddress.md
Labels: Microsoft submitter

#12428 Publish main to live, 12/18/24, 3:30 PM PT
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#12430 Update Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#12432 Publish main to live, 12/20/24, 3:30 PM PT
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-MailUser.md
Labels: Microsoft submitter

#12434 Adding missing tpm documentation for several parameters
  teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md
  teams/teams-ps/teams/Get-CsTeamsEducationConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsMediaConnectivityPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md
  teams/teams-ps/teams/Get-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/New-CsTeamsChannelsPolicy.md
  teams/teams-ps/teams/New-CsTeamsMediaConnectivityPolicy.md
  teams/teams-ps/teams/New-CsTeamsMessagingPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/Remove-CsUserLicenseGracePeriod.md
  teams/teams-ps/teams/Set-CsOnlineDialInConferencingTenantSettings.md
  teams/teams-ps/teams/Set-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12436 Publish main to live, 12/31/24, 3:30 PM PT
  teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md
  teams/teams-ps/teams/Get-CsTeamsEducationConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsMediaConnectivityPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md
  teams/teams-ps/teams/Get-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/New-CsTeamsChannelsPolicy.md
  teams/teams-ps/teams/New-CsTeamsMediaConnectivityPolicy.md
  teams/teams-ps/teams/New-CsTeamsMessagingPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/Remove-CsUserLicenseGracePeriod.md
  teams/teams-ps/teams/Set-CsOnlineDialInConferencingTenantSettings.md
  teams/teams-ps/teams/Set-CsTeamsWorkLoadPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter
