Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2024-05, with the labels that each got.

#11790 date-time field in UTC time zone
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#11793 Push to live
  .openpublishing.publish.config.json
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
  informationprotection/TOC.yml
  informationprotection/breadcrumb/purviewinformationprotection-ps/toc.yml
  informationprotection/index.md
  sharepoint/TOC.yml
  sharepoint/breadcrumb/sharepoint-ps/toc.yml
  sharepoint/index.md
Labels: Microsoft submitter

#11794 remove offline docset
  .openpublishing.publish.config.json
  sharepoint/TOC.yml
  sharepoint/breadcrumb/sharepoint-ps/toc.yml
  sharepoint/docfx.json
  sharepoint/index.md
Labels: Microsoft submitter

#11795 merging to live
  .openpublishing.publish.config.json
  sharepoint/TOC.yml
  sharepoint/breadcrumb/sharepoint-ps/toc.yml
  sharepoint/docfx.json
  sharepoint/index.md
Labels: Microsoft submitter

#11796 remove docset folder
  purviewinformationprotection-ps/docfx.json
Labels: Microsoft submitter

#11797 merge to live
  purviewinformationprotection-ps/docfx.json
Labels: Microsoft submitter

#11803 merge to live
  .openpublishing.publish.config.json
  informationprotection/TOC.yml
  informationprotection/breadcrumb/purviewinformationprotection-ps/toc.yml
  informationprotection/docfx.json
  informationprotection/index.md
Labels: Microsoft submitter

#11804 Update Rotate-DkimSigningConfig.md
  exchange/exchange-ps/exchange/Rotate-DkimSigningConfig.md
Labels: Microsoft submitter

#11805 Publish main to live, Wednesday 3:30PM PDT, 05/08
  exchange/exchange-ps/exchange/Rotate-DkimSigningConfig.md
Labels: Microsoft submitter

#11806 Added 'p' to fwlink in CommonParameters
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Set-ExoPhishSimOverrideRule.md
Labels: Microsoft submitter

#11809 Publish main to live, 05/09, 3:30 PM IST
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Set-ExoPhishSimOverrideRule.md
Labels: Microsoft submitter

#11807 Customer Request : Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
Labels: Microsoft submitter

#11810 Update New-InboundConnector.md
  exchange/exchange-ps/exchange/New-InboundConnector.md
Labels: Microsoft submitter

#11811 5/9/2024, 3:30 pm publish
  exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md
  exchange/exchange-ps/exchange/New-InboundConnector.md
Labels: Microsoft submitter

#11808 as per 8970175
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter, In review, Sign off

#11817 Publish main to live, Friday 10:30AM PDT, 05/10
  exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md
Labels: Microsoft submitter

#11818 QuarantineTag references to QuarantinePolicy
  exchange/exchange-ps/exchange/New-QuarantinePermissions.md
  exchange/exchange-ps/exchange/Set-QuarantinePermissions.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
Labels: Microsoft submitter

#11819 Publish main to live, 05/13, 3:30 PM IST
  exchange/exchange-ps/exchange/New-QuarantinePermissions.md
  exchange/exchange-ps/exchange/Set-QuarantinePermissions.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
Labels: Microsoft submitter

#11820 Chrisda to Main
  exchange/exchange-ps/exchange/Start-HistoricalSearch.md
Labels: Microsoft submitter

#11822 Quarantine permission updates
  exchange/exchange-ps/exchange/New-QuarantinePermissions.md
  exchange/exchange-ps/exchange/Set-QuarantinePermissions.md
Labels: Microsoft submitter

#11824 Publish main to live, 05/14, 3:30 PM IST
  exchange/exchange-ps/exchange/New-QuarantinePermissions.md
  exchange/exchange-ps/exchange/Set-QuarantinePermissions.md
Labels: Microsoft submitter

#11828 Updating few new examples for TeamsEmergencyCallingPolicy
  teams/teams-ps/teams/New-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEmergencyCallingPolicy.md
Labels: Microsoft submitter

#11829 Publish main to live, Tuesday 3:30PM PDT, 05/14
  teams/teams-ps/teams/New-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEmergencyCallingPolicy.md
Labels: Microsoft submitter

#11791 Update Get-CsOnlineUser.md with missing parameters
  teams/teams-ps/teams/Get-CsOnlineUser.md
Labels: Microsoft submitter, In review, Sign off

#11831 publish main to live 5/15/24 10:30 AM
  exchange/exchange-ps/exchange/Get-Group.md
  teams/teams-ps/teams/Get-CsOnlineUser.md
Labels: Microsoft submitter

#11836 Publish main to live, 3:30 PM 5/16
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/cmdlet-property-sets.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-exchange-online-protection-powershell.md
  exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md
  exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md
  exchange/docs-conceptual/exchange-cmdlet-syntax.md
  exchange/docs-conceptual/exchange-management-shell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
  exchange/docs-conceptual/exchange-online-protection-powershell.md
  exchange/docs-conceptual/filter-properties.md
  exchange/docs-conceptual/filters-v2.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/index.yml
  exchange/docs-conceptual/invoke-command-workarounds-rest-api.md
  exchange/docs-conceptual/open-the-exchange-management-shell.md
  exchange/docs-conceptual/recipient-filters.md
  exchange/docs-conceptual/recipientfilter-properties.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/docs-conceptual/values-for-custompropertynames-parameter.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc, subservice/subsvc

#11838 VivaFeature-chrisda to Main
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaFeatureCategory.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11839 Publish main to live 05/17/2024, 3:30 PM
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-VivaFeatureCategory.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#11840 v3.5.0
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#11841 Update whats-new-in-the-exo-module.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc

#11842 Publish main to live, 05/20, 3:30 PM IST
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#11602 Documentation approval for cmdlet 'Remove-CsUserLicenseGracePeriod'
  teams/teams-ps/teams/Remove-CsUserLicenseGracePeriod
Labels: In review, Sign off

#11851 Publish main to live 05/24/2024, 3:30 PM
  teams/teams-ps/teams/Remove-CsUserLicenseGracePeriod
Labels: Microsoft submitter

#11852 Update Set-DistributionGroup.md
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter

#11853 publish main to live 10:30 5/28/24
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter

#11857 updates
  teams/teams-ps/teams/Remove-CsUserLicenseGracePeriod
Labels: Microsoft submitter

#11861 Defender repo link fixes
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/find-exchange-cmdlet-permissions.md
  exchange/docs-conceptual/scc-powershell.md
  exchange/exchange-ps/exchange/Disable-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Disable-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Disable-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Enable-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Enable-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Enable-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Get-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/Get-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Get-ActivityAlert.md
  exchange/exchange-ps/exchange/Get-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Get-ConfigAnalyzerPolicyRecommendation.md
  exchange/exchange-ps/exchange/Get-DeviceConditionalAccessPolicy.md
  exchange/exchange-ps/exchange/Get-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/Get-DeviceConfigurationPolicy.md
  exchange/exchange-ps/exchange/Get-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Get-DevicePolicy.md
  exchange/exchange-ps/exchange/Get-DeviceTenantPolicy.md
  exchange/exchange-ps/exchange/Get-DeviceTenantRule.md
  exchange/exchange-ps/exchange/Get-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Get-ExoPhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Get-ExoSecOpsOverrideRule.md
  exchange/exchange-ps/exchange/Get-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Get-PhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Get-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Get-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Get-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Get-SecOpsOverrideRule.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Get-UnifiedAuditLogRetentionPolicy.md
  exchange/exchange-ps/exchange/New-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/New-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/New-ActivityAlert.md
  exchange/exchange-ps/exchange/New-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/New-AntiPhishRule.md
  exchange/exchange-ps/exchange/New-DeviceConditionalAccessPolicy.md
  exchange/exchange-ps/exchange/New-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/New-DeviceConfigurationPolicy.md
  exchange/exchange-ps/exchange/New-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/New-DeviceTenantPolicy.md
  exchange/exchange-ps/exchange/New-DeviceTenantRule.md
  exchange/exchange-ps/exchange/New-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/New-ExoPhishSimOverrideRule.md
  exchange/exchange-ps/exchange/New-ExoSecOpsOverrideRule.md
  exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/New-HostedOutboundSpamFilterPolicy.md
  exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/New-MalwareFilterRule.md
  exchange/exchange-ps/exchange/New-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/New-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/New-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/New-SafeLinksRule.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#11862 Defender repo link fixes 2
  exchange/exchange-ps/exchange/New-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/New-TeamsProtectionPolicy.md
  exchange/exchange-ps/exchange/New-TeamsProtectionPolicyRule.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-UnifiedAuditLogRetentionPolicy.md
  exchange/exchange-ps/exchange/Remove-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Remove-ActivityAlert.md
  exchange/exchange-ps/exchange/Remove-DeviceConditionalAccessPolicy.md
  exchange/exchange-ps/exchange/Remove-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/Remove-DeviceConfigurationPolicy.md
  exchange/exchange-ps/exchange/Remove-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Remove-DeviceTenantPolicy.md
  exchange/exchange-ps/exchange/Remove-DeviceTenantRule.md
  exchange/exchange-ps/exchange/Remove-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Remove-ExoPhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Remove-ExoSecOpsOverrideRule.md
  exchange/exchange-ps/exchange/Remove-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Remove-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Remove-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Remove-UnifiedAuditLogRetentionPolicy.md
  exchange/exchange-ps/exchange/Set-ATPBuiltInProtectionRule.md
  exchange/exchange-ps/exchange/Set-ATPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-ActivityAlert.md
  exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md
  exchange/exchange-ps/exchange/Set-AntiPhishRule.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-DeviceConditionalAccessPolicy.md
  exchange/exchange-ps/exchange/Set-DeviceConditionalAccessRule.md
  exchange/exchange-ps/exchange/Set-DeviceConfigurationPolicy.md
  exchange/exchange-ps/exchange/Set-DeviceConfigurationRule.md
  exchange/exchange-ps/exchange/Set-DeviceTenantPolicy.md
  exchange/exchange-ps/exchange/Set-DeviceTenantRule.md
  exchange/exchange-ps/exchange/Set-EOPProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-ExoPhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Set-ExoSecOpsOverrideRule.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/Set-HostedOutboundSpamFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md
  exchange/exchange-ps/exchange/Set-MalwareFilterRule.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md
  exchange/exchange-ps/exchange/Set-SafeAttachmentRule.md
  exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md
  exchange/exchange-ps/exchange/Set-SafeLinksRule.md
  exchange/exchange-ps/exchange/Set-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Set-TeamsProtectionPolicy.md
  exchange/exchange-ps/exchange/Set-TeamsProtectionPolicyRule.md
  exchange/exchange-ps/exchange/Set-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-UnifiedAuditLogRetentionPolicy.md
Labels: Microsoft submitter

#11863 QuarAS-chrisda to Main
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/New-QuarantinePermissions.md
  exchange/exchange-ps/exchange/New-QuarantinePolicy.md
  exchange/exchange-ps/exchange/Set-QuarantinePermissions.md
  exchange/exchange-ps/exchange/Set-QuarantinePolicy.md
Labels: Microsoft submitter

#11866 Another attempt at getting an updated file WITH an extension added
  teams/teams-ps/teams/Remove-CsUserLicenseGracePeriod.md
Labels: Microsoft submitter, In review, Sign off

#11868 Smtpdane-chrisda to Main
  exchange/exchange-ps/exchange/Disable-DnssecForVerifiedDomain.md
  exchange/exchange-ps/exchange/Disable-SmtpDaneInbound.md
  exchange/exchange-ps/exchange/Enable-DnssecForVerifiedDomain.md
  exchange/exchange-ps/exchange/Enable-SmtpDaneInbound.md
  exchange/exchange-ps/exchange/Get-DnssecStatusForVerifiedDomain.md
  exchange/exchange-ps/exchange/Get-SmtpDaneInboundStatus.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11869 publish main to live 10;30 AM 5/29/24
  exchange/exchange-ps/exchange/Disable-DnssecForVerifiedDomain.md
  exchange/exchange-ps/exchange/Disable-SmtpDaneInbound.md
  exchange/exchange-ps/exchange/Enable-DnssecForVerifiedDomain.md
  exchange/exchange-ps/exchange/Enable-SmtpDaneInbound.md
  exchange/exchange-ps/exchange/Get-DnssecStatusForVerifiedDomain.md
  exchange/exchange-ps/exchange/Get-SmtpDaneInboundStatus.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#11848 Updated deprecated usage and params for New-CsOnlineLisLocation.md
  teams/teams-ps/teams/New-CsOnlineLisLocation.md
Labels: Microsoft submitter

#11847 Mandated latitude & longitude params for New-CsOnlineLisCivicAddress
  teams/teams-ps/teams/New-CsOnlineLisCivicAddress.md
Labels: Microsoft submitter

#11870 Publish main to live, Wednesday 3:30PM PDT, 05/29
  teams/teams-ps/teams/New-CsOnlineLisCivicAddress.md
  teams/teams-ps/teams/New-CsOnlineLisLocation.md
Labels: Microsoft submitter

#11871 Update Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter

#11873 Update New-FeatureConfiguration.md
  exchange/exchange-ps/exchange/New-FeatureConfiguration.md
Labels: area:exchange

#11874 Update Get-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Get-FeatureConfiguration.md
Labels: area:exchange
