Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2024-08, with the labels that each got.

#12051 Update Get-CsOnlineUser.md
  teams/teams-ps/teams/Get-CsOnlineUser.md
Labels: Microsoft submitter, In review, Sign off

#12052 publish main to live 10:30 AM 8/7
  teams/teams-ps/teams/Get-CsOnlineUser.md
Labels: Microsoft submitter

#12055 Removing unsupported properties from Export-CsAcquiredPhoneNumber
  teams/teams-ps/teams/Export-CsAcquiredPhoneNumber.md
Labels: Microsoft submitter

#12054 Update Set-CalendarProcessing.md
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
Labels: area:exchange, Microsoft submitter

#12057 Publish main to live, Friday 10:30AM PDT, 08/09
  exchange/exchange-ps/exchange/Set-CalendarProcessing.md
  teams/teams-ps/teams/Export-CsAcquiredPhoneNumber.md
Labels: Microsoft submitter

#12056 Updating cmdlet documentation on ReverseNumberLookup
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: area:teams / skype, Microsoft submitter

#12059 Global admin updates
  teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsEducationConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsSipDevicesConfiguration.md
  teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md
  teams/teams-ps/teams/Set-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsEducationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsSipDevicesConfiguration.md
Labels: Microsoft submitter, Sign off

#12061 Publish main to live 08/09/2024, 3:30 PM
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsEducationConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsSipDevicesConfiguration.md
  teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsEducationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsSipDevicesConfiguration.md
Labels: Microsoft submitter

#12064 Update Set-User.md
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#12065 Publish main to live, Monday 10:30AM PDT, 08/12
  exchange/exchange-ps/exchange/Set-User.md
Labels: Microsoft submitter

#12066 Update Set-RemoteDomain.md
  exchange/exchange-ps/exchange/Set-RemoteDomain.md
Labels: Microsoft submitter

#12067 Publish main to live 08/12/2024, 3:30 PM
  exchange/exchange-ps/exchange/Set-RemoteDomain.md
Labels: Microsoft submitter

#12063 Update Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12062 Update New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12072 publish main to live 10:30 AM 8/13/24
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12073 Publish main to live, Tuesday 3:30PM PDT, 08/13
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter

#12074 updates documentation for Add-VivaModuleFeaturePolicy and Update-VivaModuleFeaturePolicy
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter

#12075 Update Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off

#12053 Update EmergencyCallingPolicy documentation with clarification on the use of UPN vs. SMTP address for notification group
  teams/teams-ps/teams/New-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEmergencyCallingPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12068 Update Move-CsUser.md to address minimum MicrosoftTeams module versio…
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter, In review, Sign off

#11892 Create Grant-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsFilesPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11985 Create Get-CsSdgBulkSignInRequestStatus.md
  teams/teams-ps/teams/Get-CsSdgBulkSignInRequestStatus.md
Labels: Microsoft submitter, In review, Sign off

#12076 Publish main to live, Friday 10:30AM PDT, 08/16
  skype/skype-ps/skype/Move-CsUser.md
  teams/teams-ps/teams/Get-CsSdgBulkSignInRequestStatus.md
  teams/teams-ps/teams/Grant-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/New-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#11927 Add new Meeting Policy setting - CaptchaVerificationForMeetingJoin
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter, In review, Sign off

#11769 Update Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12078 Publish main to live 08/16/2024, 3:30 PM
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12080 OOB publish main to live to revert content
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12069 Update New-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLocationDetectionPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12082 Merging workflows to main
  .github/workflows/AutoLabelAssign.yml
  .github/workflows/AutoLabelMsftContributor.yml
  .github/workflows/BackgroundTasks.yml
  .github/workflows/LiveMergeCheck.yml
  .github/workflows/PrFileCount.yml
  .github/workflows/ProtectedFiles.yml
Labels: Microsoft submitter

#12083 Merge main into live
  .github/workflows/AutoLabelAssign.yml
  .github/workflows/AutoLabelMsftContributor.yml
  .github/workflows/BackgroundTasks.yml
  .github/workflows/LiveMergeCheck.yml
  .github/workflows/PrFileCount.yml
  .github/workflows/ProtectedFiles.yml
  teams/teams-ps/teams/New-CsTeamsWorkLocationDetectionPolicy.md
Labels: Microsoft submitter

#12085 LegacyExchangeToken param
  exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
Labels: Microsoft submitter

#12086 DateTime DW Updates
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#12087 Publish main to live, Thursday 3:30PM PDT, 08/22
  exchange/exchange-ps/exchange/New-Label.md
  exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-Label.md
Labels: Microsoft submitter

#12088 Remove unreferenced media files
  exchange/docs-conceptual/media/0fd389a1-a32d-4e2f-bf5f-78e9b6407d4c.png
  exchange/docs-conceptual/media/24645e56-8b11-4c0f-ace4-09bdb2703562.png
  exchange/docs-conceptual/media/MSN_Video_Widget.gif
  exchange/docs-conceptual/media/app-only-auth-exchange-api-perms.png
  exchange/docs-conceptual/media/app-only-auth-exchange-manageasapp.png
  exchange/docs-conceptual/media/app-only-auth-register-app.png
  exchange/docs-conceptual/media/app-only-auth-role-assignment.png
  exchange/docs-conceptual/media/app-only-auth-upload-cert.png
  exchange/docs-conceptual/media/b85d80d9-1043-4c7c-8f14-d87d8d56b188.png
  exchange/docs-conceptual/media/checkmark.png
  exchange/docs-conceptual/media/d3a405ce-5364-4732-a7bb-2cc9c678da2d.png
  exchange/docs-conceptual/media/exo-app-only-auth-manage-ad-view.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-api-permissions.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-app-registrations.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-roles-and-administrators.png
  exchange/docs-conceptual/media/f3b4c351-17d9-42d9-8540-e48e01779b31.png
  exchange/docs-conceptual/media/mi-automation-account-id.png
  images/add_related_link.png
  images/auto_fork.png
  images/comparing-changes-page.png
  images/contrib-consumption-model-orig.png
  images/contrib-consumption-model.png
  images/edit_icon.png
  images/edit_video_capture.jpg
  images/propose_file_change.png
  images/quick-update-edit.png
  images/quick-update-github.png
Labels: Microsoft submitter

#12090 Merge to live
  exchange/docs-conceptual/media/0fd389a1-a32d-4e2f-bf5f-78e9b6407d4c.png
  exchange/docs-conceptual/media/24645e56-8b11-4c0f-ace4-09bdb2703562.png
  exchange/docs-conceptual/media/MSN_Video_Widget.gif
  exchange/docs-conceptual/media/app-only-auth-exchange-api-perms.png
  exchange/docs-conceptual/media/app-only-auth-exchange-manageasapp.png
  exchange/docs-conceptual/media/app-only-auth-register-app.png
  exchange/docs-conceptual/media/app-only-auth-role-assignment.png
  exchange/docs-conceptual/media/app-only-auth-upload-cert.png
  exchange/docs-conceptual/media/b85d80d9-1043-4c7c-8f14-d87d8d56b188.png
  exchange/docs-conceptual/media/checkmark.png
  exchange/docs-conceptual/media/d3a405ce-5364-4732-a7bb-2cc9c678da2d.png
  exchange/docs-conceptual/media/exo-app-only-auth-manage-ad-view.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-api-permissions.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-app-registrations.png
  exchange/docs-conceptual/media/exo-app-only-auth-select-roles-and-administrators.png
  exchange/docs-conceptual/media/f3b4c351-17d9-42d9-8540-e48e01779b31.png
  exchange/docs-conceptual/media/mi-automation-account-id.png
  images/add_related_link.png
  images/auto_fork.png
  images/comparing-changes-page.png
  images/contrib-consumption-model-orig.png
  images/contrib-consumption-model.png
  images/edit_icon.png
  images/edit_video_capture.jpg
  images/propose_file_change.png
  images/quick-update-edit.png
  images/quick-update-github.png
Labels: Microsoft submitter
