Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2024-02, with the labels that each got.

#11603 Update Import-RecipientDataProperty.md
  exchange/exchange-ps/exchange/Import-RecipientDataProperty.md
Labels: Microsoft submitter

#11607 Audit-chrisda to Main
  exchange/exchange-ps/exchange/New-AdminAuditLogSearch.md
  exchange/exchange-ps/exchange/New-MailboxAuditLogSearch.md
  exchange/exchange-ps/exchange/Search-AdminAuditLog.md
  exchange/exchange-ps/exchange/Search-MailboxAuditLog.md
Labels: Microsoft submitter

#11608 Publish main to live, Monday 10:30AM PST, 02/05
  exchange/exchange-ps/exchange/Import-RecipientDataProperty.md
  exchange/exchange-ps/exchange/New-AdminAuditLogSearch.md
  exchange/exchange-ps/exchange/New-MailboxAuditLogSearch.md
  exchange/exchange-ps/exchange/Search-AdminAuditLog.md
  exchange/exchange-ps/exchange/Search-MailboxAuditLog.md
Labels: Microsoft submitter

#11609 Update Remove-PublicFolderMailboxMigrationRequest.md
  exchange/exchange-ps/exchange/Remove-PublicFolderMailboxMigrationRequest.md
Labels: Microsoft submitter

#11610 Publish main to live on 2/5 @ 3:30 pm
  exchange/exchange-ps/exchange/Remove-PublicFolderMailboxMigrationRequest.md
Labels: Microsoft submitter

#11604 Update Set-MailContact.md
  exchange/exchange-ps/exchange/Set-MailContact.md
Labels: area:exchange

#11600 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: Microsoft submitter

#11612 Publish main to live 02/06/2024
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
  skype/skype-ps/skype/Set-CsTeamsMeetingConfiguration.md
  skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#11613 Chrisda to Main
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-ServicePrincipal.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/Set-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter, exchange-online/svc

#11614 Publish 02/07, 3:30 PM IST
  exchange/docs-conceptual/app-only-auth-powershell-v2.md
  exchange/docs-conceptual/connect-exo-powershell-managed-identity.md
  exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Get-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Get-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Get-ServicePrincipal.md
  exchange/exchange-ps/exchange/Get-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Get-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeature.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeatureEnablement.md
  exchange/exchange-ps/exchange/Get-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/New-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/New-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/New-ServicePrincipal.md
  exchange/exchange-ps/exchange/Remove-VivaModuleFeaturePolicy.md
  exchange/exchange-ps/exchange/Set-DefaultTenantBriefingConfig.md
  exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-HostedContentFilterRule.md
  exchange/exchange-ps/exchange/Set-ManagementRoleAssignment.md
  exchange/exchange-ps/exchange/Set-MyAnalyticsFeatureConfig.md
  exchange/exchange-ps/exchange/Set-UserBriefingConfig.md
  exchange/exchange-ps/exchange/Set-VivaInsightsSettings.md
  exchange/exchange-ps/exchange/Update-VivaModuleFeaturePolicy.md
Labels: Microsoft submitter, exchange-online/svc

#11621 QuarDLP-chrisda to Main
  exchange/exchange-ps/exchange/Delete-QuarantineMessage.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md
  exchange/exchange-ps/exchange/Preview-QuarantineMessage.md
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
Labels: Microsoft submitter

#11622 Publish main to live on 2/13 @ 10:30 am
  exchange/exchange-ps/exchange/Delete-QuarantineMessage.md
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md
  exchange/exchange-ps/exchange/Preview-QuarantineMessage.md
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
Labels: Microsoft submitter

#11619 Update New-CsCallQueue.md
  skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/New-CsOnlineApplicationInstanceAssociation.md
  skype/skype-ps/skype/Set-CsCallQueue.md
Labels: Microsoft submitter

#11617 Update Set-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
Labels: Microsoft submitter, Sign off

#11623 Publish main to live on 2/15 @ 3:30 pm
  skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/New-CsOnlineApplicationInstanceAssociation.md
  skype/skype-ps/skype/Set-CsCallQueue.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
Labels: Microsoft submitter

#11616 Add TeamsWorkLocationDetectionPolicy cmdlets public docs
  teams/teams-ps/teams/Get-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsWorkLocationDetectionPolicy.md
Labels: Microsoft submitter, Back to submitter

#11624 Publish main to live, 02/20, 3:30 PM IST
  teams/teams-ps/teams/Get-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsWorkLocationDetectionPolicy.md
Labels: Microsoft submitter

#11627 Update Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
Labels: Microsoft submitter

#11628 Publish main to live, Thursday 10:30AM PST, 02/22
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
Labels: Microsoft submitter

#11625 Update Get-CsTeamsAcsFederationConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.md
Labels: Microsoft submitter

#11629 Publish main to live on 2/22 @ 3:30 pm
  teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.md
Labels: Microsoft submitter

#11620 Update Get-CsOnlineUser.md
  skype/skype-ps/skype/Get-CsOnlineUser.md
Labels: Microsoft submitter

#11618 Update Move-CsUser.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#11630 Publish main to live, 02/23, 3:30 PM IST
  skype/skype-ps/skype/Get-CsOnlineUser.md
  skype/skype-ps/skype/Move-CsUser.md
Labels: Microsoft submitter

#11632 Publish main to live on 2/23 @ 3:30 pm
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
Labels: Microsoft submitter

#11633 Update Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#11635 Update Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#11636 Update connect-to-scc-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
Labels: Microsoft submitter, exchange-powershell/svc

#11637 publish main to live, 10:30 AM 2/27/24
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter, exchange-powershell/svc

#11638 Updating the Set-CsTeamsEducationConfiguration documention to incorporate the new education setting UpdateParentInformation.
  teams/teams-ps/teams/Get-CsTeamsEducationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsEducationConfiguration.md
Labels: Microsoft submitter

#11641 Publish main to live, 02/28, 3:30 PM IST
  teams/teams-ps/teams/Get-CsTeamsEducationConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsEducationConfiguration.md
Labels: Microsoft submitter

#11643 publish main to live 10:30 AM 2/28/24
  exchange/exchange-ps/exchange/New-MailboxExportRequest.md
Labels: Microsoft submitter

#11644 Publish main to live, Wednesday 3:30PM PST, 02/28
  skype/skype-ps/skype/New-CsCallQueue.md
  skype/skype-ps/skype/Set-CsCallQueue.md
Labels: Microsoft submitter
