Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2025-01, with the labels that each got.

#12438 Update Export-ContentExplorerData.md
  exchange/exchange-ps/exchange/Export-ContentExplorerData.md
Labels: Microsoft submitter

#12439 Publish main to live, 01/06/25, 10:30 AM PT
  exchange/exchange-ps/exchange/Export-ContentExplorerData.md
Labels: Microsoft submitter

#12322 Update TeamTargetingHierarchy documentation.
  teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
  teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md
  teams/teams-ps/teams/Set-TeamTargetingHierarchy.md
Labels: Microsoft submitter, In review, Sign off

#12433 Update Set-CsOnlineDialInConferencingUser.md
  teams/teams-ps/teams/Set-CsOnlineDialInConferencingUser.md
Labels: Microsoft submitter, In review, Sign off

#12421 Update TeamsCallingPolicy.copilot docs
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12431 Update New-CsCallQueue.md
  teams/teams-ps/teams/New-CsCallQueue.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12440 Published main to live, Wednesday 10:30 AM PST, 01/08
  teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
  teams/teams-ps/teams/New-CsCallQueue.md
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md
  teams/teams-ps/teams/Set-CsOnlineDialInConferencingUser.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-TeamTargetingHierarchy.md
Labels: Microsoft submitter

#12441 Add Immersive Events setting in TeamsEventsPolicy into the docs
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12443 Update New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
Labels: In review, Sign off

#12444 QuarRR-chrisda to Main
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
Labels: Microsoft submitter

#12442 Update Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off

#12445 Publish main to live, 01/09/25, 3:30 PM PT
  exchange/exchange-ps/exchange/Release-QuarantineMessage.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12446 Update CsTeamsCallingPolicy/CsTeamsMeetingPolicy for AI Interpreter related policies change
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12454 Publish main to live, 01/13/25, 3:30 PM PT
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12455 DLP-chrisda to Main
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
Labels: Microsoft submitter

#12456 Update Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
Labels: Microsoft submitter

#12457 main to live publish, 1/14/2025, 10:45 AM
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
Labels: Microsoft submitter

#12435 Update Get-CsOnlineUser.md
  teams/teams-ps/teams/Get-CsOnlineUser.md
Labels: Microsoft submitter, In review, Sign off

#12460 Update New-CsExternalAccessPolicy.md
  teams/teams-ps/teams/New-CsExternalAccessPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12461 Published main to live, Wednesday 10:30 AM PST, 01/15
  teams/teams-ps/teams/Get-CsOnlineUser.md
  teams/teams-ps/teams/New-CsAutoAttendantCallableEntity.md
  teams/teams-ps/teams/New-CsCallQueue.md
  teams/teams-ps/teams/New-CsExternalAccessPolicy.md
  teams/teams-ps/teams/Set-CsCallQueue.md
Labels: Microsoft submitter

#12462 Updating documentation for several policies
  teams/teams-ps/teams/Find-CsGroup.md
  teams/teams-ps/teams/Get-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md
  teams/teams-ps/teams/Get-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/Grant-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/New-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/New-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/New-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Remove-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsConnection.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Remove-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/Set-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter, In review, Sign off

#12463 Publish main to live, 01/15/25, 3:30 PM PT
  teams/teams-ps/teams/Find-CsGroup.md
  teams/teams-ps/teams/Get-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md
  teams/teams-ps/teams/Get-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/Grant-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/New-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/New-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/New-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Remove-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsConnection.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md
  teams/teams-ps/teams/Remove-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/Set-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#12464 Adding parameters for multiple policies and configurations
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Get-CsPolicyPackage.md
  teams/teams-ps/teams/Get-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/New-CsOnlineVoicemailPolicy.md
  teams/teams-ps/teams/New-CsTeamsAppSetupPolicy.md
  teams/teams-ps/teams/New-CsTeamsCallParkPolicy.md
  teams/teams-ps/teams/New-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/New-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsOnlineVoicemailPolicy.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsAppSetupPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Set-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter, In review, Sign off

#12448 Update Grant-CsTeamsAppPermissionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsAppPermissionPolicy.md
Labels: In review, Sign off, PubOps fixes

#12451 Update Remove-CsTeamsAppPermissionPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsAppPermissionPolicy.md
Labels: In review, Sign off

#12452 Update Get-CsTeamsAppPermissionPolicy.md
  teams/teams-ps/teams/Get-CsTeamsAppPermissionPolicy.md
Labels: In review, Sign off, PubOps fixes

#12437 chore: update on ExplicitRecordingConsent in TeamsMeetingPolicy
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off

#12467 Published main to live, Thursday 5:00 PM IST, 01/16
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Get-CsPolicyPackage.md
  teams/teams-ps/teams/Get-CsTeamsAppPermissionPolicy.md
  teams/teams-ps/teams/Get-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsAppPermissionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/New-CsOnlineVoicemailPolicy.md
  teams/teams-ps/teams/New-CsTeamsAppPermissionPolicy.md
  teams/teams-ps/teams/New-CsTeamsAppSetupPolicy.md
  teams/teams-ps/teams/New-CsTeamsCallParkPolicy.md
  teams/teams-ps/teams/New-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/New-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsAppPermissionPolicy.md
  teams/teams-ps/teams/Set-CsOnlineVoicemailPolicy.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsAppSetupPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#12466 Update Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#12469 Published main to live, Thursday 10:30 AM PST, 01/16
  exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#12471 Update Get-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
Labels: Microsoft submitter

#12472 Published main to live, Tuesday 10:30 AM PST, 01/21
  exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md
Labels: Microsoft submitter

#12470 Updating DR number update and release examples
  teams/teams-ps/teams/New-CsOnlineDirectRoutingTelephoneNumberUploadOrder.md
  teams/teams-ps/teams/New-CsOnlineTelephoneNumberReleaseOrder.md
Labels: area:teams, Microsoft submitter, In review, Sign off

#12473 Updating Multiple Cmdlets with Missing Info
  teams/teams-ps/teams/New-CsTeamsComplianceRecordingPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsFeedbackPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingBrandingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsUpgradeConfiguration.md
Labels: Microsoft submitter, In review, Sign off

#12474 Publish main to live, 01/21/25, 3:30 PM PT
  teams/teams-ps/teams/New-CsOnlineDirectRoutingTelephoneNumberUploadOrder.md
  teams/teams-ps/teams/New-CsOnlineTelephoneNumberReleaseOrder.md
  teams/teams-ps/teams/New-CsTeamsComplianceRecordingPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsFeedbackPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingBrandingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsUpgradeConfiguration.md
Labels: Microsoft submitter

#12459 Create Update-M365UnifiedCustomPendingApp Docs
  teams/teams-ps/teams/Update-M365UnifiedCustomPendingApp.md
  teams/teams-ps/teams/teams.md
Labels: area:teams, Microsoft submitter, In review, Sign off

#12458 Create Get-M365UnifiedCustomPendingApps Docs
  teams/teams-ps/teams/Get-M365UnifiedCustomPendingApps.md
  teams/teams-ps/teams/teams.md
Labels: area:teams, Microsoft submitter, In review, Sign off

#12475 Published main to live, Thursday 10:30 AM PST, 01/23
  teams/teams-ps/teams/Get-M365UnifiedCustomPendingApps.md
  teams/teams-ps/teams/Update-M365UnifiedCustomPendingApp.md
  teams/teams-ps/teams/teams.md
Labels: Microsoft submitter

#12480 Update Set-TransportConfig.md
  exchange/exchange-ps/exchange/Set-TransportConfig.md
Labels: Microsoft submitter

#12481 Update index.yml
  exchange/docs-conceptual/index.yml
Labels: Microsoft submitter, exchange-online/svc

#12485 ms.author fixes per build report
  teams/teams-ps/teams/Get-CsCallQueue.md
  teams/teams-ps/teams/Get-CsTeamsAppSetupPolicy.md
  teams/teams-ps/teams/Get-CsTeamsEducationAssignmentsAppPolicy.md
  teams/teams-ps/teams/Get-CsTeamsFeedbackPolicy.md
  teams/teams-ps/teams/Get-CsTeamsMeetingBrandingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsConnection.md
  teams/teams-ps/teams/Grant-CsTeamsAppSetupPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsFeedbackPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsMeetingBrandingPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingBrandingPolicy.md
  teams/teams-ps/teams/New-CsTeamsPinnedApp.md
  teams/teams-ps/teams/New-CsTeamsShiftsConnection.md
  teams/teams-ps/teams/Remove-CsCallQueue.md
  teams/teams-ps/teams/Remove-CsTeamsFeedbackPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsMeetingBrandingPolicy.md
  teams/teams-ps/teams/Set-CsCallQueue.md
  teams/teams-ps/teams/Set-CsTeamsAppPermissionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEducationAssignmentsAppPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingBrandingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsShiftsConnection.md
  teams/teams-ps/teams/Update-CsTeamsShiftsConnection.md
Labels: Microsoft submitter

#12487 Fixed author value
  teams/teams-ps/teams/Find-CsOnlineApplicationInstance.md
  teams/teams-ps/teams/Get-AssociatedTeam.md
  teams/teams-ps/teams/Get-CsCallingLineIdentity.md
  teams/teams-ps/teams/Get-CsEffectiveTenantDialPlan.md
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Get-CsInboundBlockedNumberPattern.md
  teams/teams-ps/teams/Get-CsInboundExemptNumberPattern.md
  teams/teams-ps/teams/Get-CsOnlineApplicationInstance.md
  teams/teams-ps/teams/Get-CsOnlineAudioFile.md
  teams/teams-ps/teams/Get-CsOnlineDialOutPolicy.md
  teams/teams-ps/teams/Get-CsOnlineLisCivicAddress.md
  teams/teams-ps/teams/Get-CsOnlineLisLocation.md
  teams/teams-ps/teams/Get-CsOnlineLisPort.md
  teams/teams-ps/teams/Get-CsOnlineLisSubnet.md
  teams/teams-ps/teams/Get-CsOnlineLisSwitch.md
  teams/teams-ps/teams/Get-CsOnlineLisWirelessAccessPoint.md
  teams/teams-ps/teams/Get-CsOnlinePSTNGateway.md
  teams/teams-ps/teams/Get-CsOnlinePstnUsage.md
  teams/teams-ps/teams/Get-CsOnlineTelephoneNumber.md
  teams/teams-ps/teams/Get-CsOnlineVoiceRoute.md
  teams/teams-ps/teams/Get-CsOnlineVoiceRoutingPolicy.md
  teams/teams-ps/teams/Get-CsOnlineVoiceUser.md
  teams/teams-ps/teams/Get-CsOnlineVoicemailPolicy.md
  teams/teams-ps/teams/Get-CsOnlineVoicemailUserSettings.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Get-CsTeamsCallHoldPolicy.md
  teams/teams-ps/teams/Get-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsCortanaPolicy.md
  teams/teams-ps/teams/Get-CsTeamsEmergencyCallRoutingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsEnhancedEncryptionPolicy.md
  teams/teams-ps/teams/Get-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsTranslationRule.md
  teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Get-CsTenantBlockedCallingNumbers.md
  teams/teams-ps/teams/Get-CsTenantDialPlan.md
  teams/teams-ps/teams/Get-CsTenantNetworkRegion.md
  teams/teams-ps/teams/Get-CsTenantNetworkSite.md
  teams/teams-ps/teams/Get-CsTenantNetworkSubnet.md
  teams/teams-ps/teams/Get-CsUserCallingSettings.md
  teams/teams-ps/teams/Get-LicenseReportForChangeNotificationSubscription.md
  teams/teams-ps/teams/Get-SharedWithTeam.md
  teams/teams-ps/teams/Get-SharedWithTeamUser.md
  teams/teams-ps/teams/Get-TeamAllChannel.md
  teams/teams-ps/teams/Get-TeamIncomingChannel.md
  teams/teams-ps/teams/Grant-CsCallingLineIdentity.md
  teams/teams-ps/teams/Grant-CsDialoutPolicy.md
  teams/teams-ps/teams/export-csonlineaudiofile.md
Labels: Microsoft submitter, Merge large pull request

#12488 Fixed author value 2
  teams/teams-ps/teams/Grant-CsOnlineVoiceRoutingPolicy.md
  teams/teams-ps/teams/Grant-CsOnlineVoicemailPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsCallHoldPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsCallParkPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsCortanaPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsEmergencyCallRoutingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsEnhancedEncryptionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Grant-CsTenantDialPlan.md
  teams/teams-ps/teams/Import-CsOnlineAudioFile.md
  teams/teams-ps/teams/New-CsCallingLineIdentity.md
  teams/teams-ps/teams/New-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/New-CsInboundBlockedNumberPattern.md
  teams/teams-ps/teams/New-CsInboundExemptNumberPattern.md
  teams/teams-ps/teams/New-CsOnlineApplicationInstance.md
  teams/teams-ps/teams/New-CsOnlineLisCivicAddress.md
  teams/teams-ps/teams/New-CsOnlineLisLocation.md
  teams/teams-ps/teams/New-CsOnlineVoiceRoute.md
  teams/teams-ps/teams/New-CsOnlineVoiceRoutingPolicy.md
  teams/teams-ps/teams/New-CsOnlineVoicemailPolicy.md
  teams/teams-ps/teams/New-CsTeamsCallHoldPolicy.md
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/New-CsTeamsCortanaPolicy.md
  teams/teams-ps/teams/New-CsTeamsEmergencyCallRoutingPolicy.md
  teams/teams-ps/teams/New-CsTeamsEmergencyCallingExtendedNotification.md
  teams/teams-ps/teams/New-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/New-CsTeamsEmergencyNumber.md
  teams/teams-ps/teams/New-CsTeamsEnhancedEncryptionPolicy.md
  teams/teams-ps/teams/New-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/New-CsTeamsTranslationRule.md
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/New-CsTenantDialPlan.md
  teams/teams-ps/teams/New-CsTenantNetworkRegion.md
  teams/teams-ps/teams/New-CsTenantNetworkSite.md
  teams/teams-ps/teams/New-CsTenantNetworkSubnet.md
  teams/teams-ps/teams/New-CsUserCallingDelegate.md
  teams/teams-ps/teams/New-CsVoiceNormalizationRule.md
  teams/teams-ps/teams/Remove-CsCallingLineIdentity.md
  teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Remove-CsInboundBlockedNumberPattern.md
  teams/teams-ps/teams/Remove-CsInboundExemptNumberPattern.md
  teams/teams-ps/teams/Remove-CsOnlineAudioFile.md
  teams/teams-ps/teams/Remove-CsOnlineLisCivicAddress.md
  teams/teams-ps/teams/Remove-CsOnlineLisLocation.md
  teams/teams-ps/teams/Remove-CsOnlineLisPort.md
  teams/teams-ps/teams/Remove-CsOnlineLisSwitch.md
  teams/teams-ps/teams/Remove-CsUserLicenseGracePeriod.md
Labels: Microsoft submitter, Merge large pull request

#12490 Fix author value 4
  teams/teams-ps/teams/Set-CsOnlineLisSubnet.md
  teams/teams-ps/teams/Set-CsOnlineLisSwitch.md
  teams/teams-ps/teams/Set-CsOnlineLisWirelessAccessPoint.md
  teams/teams-ps/teams/Set-CsOnlinePSTNGateway.md
  teams/teams-ps/teams/Set-CsOnlinePstnUsage.md
  teams/teams-ps/teams/Set-CsOnlineVoiceApplicationInstance.md
  teams/teams-ps/teams/Set-CsOnlineVoiceRoutingPolicy.md
  teams/teams-ps/teams/Set-CsOnlineVoiceUser.md
  teams/teams-ps/teams/Set-CsOnlineVoicemailPolicy.md
  teams/teams-ps/teams/Set-CsOnlineVoicemailUserSettings.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsCallHoldPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCortanaPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEmergencyCallRoutingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEmergencyCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEnhancedEncryptionPolicy.md
  teams/teams-ps/teams/Set-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsTranslationRule.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Set-CsTenantBlockedCallingNumbers.md
  teams/teams-ps/teams/Set-CsTenantDialPlan.md
  teams/teams-ps/teams/Set-CsTenantNetworkRegion.md
  teams/teams-ps/teams/Set-CsTenantNetworkSite.md
  teams/teams-ps/teams/Set-CsTenantNetworkSubnet.md
  teams/teams-ps/teams/Set-CsUserCallingDelegate.md
  teams/teams-ps/teams/Set-CsUserCallingSettings.md
  teams/teams-ps/teams/Sync-CsOnlineApplicationInstance.md
  teams/teams-ps/teams/Test-CsTeamsTranslationRule.md
  teams/teams-ps/teams/Test-CsVoiceNormalizationRule.md
Labels: Microsoft submitter

#12491 Update Add-TeamsAppInstallation.md
  teams/teams-ps/teams/Add-TeamsAppInstallation.md
Labels: Microsoft submitter

#12492 Adding missing title property
  teams/teams-ps/teams/Add-TeamChannelUser.md
  teams/teams-ps/teams/Add-TeamUser.md
  teams/teams-ps/teams/Add-TeamsAppInstallation.md
  teams/teams-ps/teams/Clear-TeamsEnvironmentConfig.md
  teams/teams-ps/teams/Connect-MicrosoftTeams.md
  teams/teams-ps/teams/Disconnect-MicrosoftTeams.md
  teams/teams-ps/teams/Get-AssociatedTeam.md
  teams/teams-ps/teams/Get-CsBatchPolicyAssignmentOperation.md
  teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md
  teams/teams-ps/teams/Get-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Get-CsInboundExemptNumberPattern.md
  teams/teams-ps/teams/Get-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Get-CsOnlineAudioFile.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Get-CsTeamsAudioConferencingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Get-CsTeamsExternalAccessConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Get-CsTeamsNotificationAndFeedsPolicy.md
  teams/teams-ps/teams/Get-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsSettingsCustomApp.md
  teams/teams-ps/teams/Get-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsAppPolicy.md
  teams/teams-ps/teams/Get-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Get-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Get-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Get-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Get-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Get-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Get-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Get-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Get-CsUserCallingSettings.md
  teams/teams-ps/teams/Get-CsUserPolicyAssignment.md
  teams/teams-ps/teams/Get-SharedWithTeam.md
  teams/teams-ps/teams/Get-SharedWithTeamUser.md
  teams/teams-ps/teams/Get-Team.md
  teams/teams-ps/teams/Get-TeamAllChannel.md
  teams/teams-ps/teams/Get-TeamChannel.md
  teams/teams-ps/teams/Get-TeamChannelUser.md
  teams/teams-ps/teams/Get-TeamIncomingChannel.md
  teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
  teams/teams-ps/teams/Get-TeamUser.md
  teams/teams-ps/teams/Get-TeamsAppInstallation.md
  teams/teams-ps/teams/Grant-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsAudioConferencingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsFilesPolicy.md
Labels: Microsoft submitter, Merge large pull request

#12493 Chrisda2 to Main
  teams/teams-ps/teams/Get-CsTeamsCustomBannerText.md
  teams/teams-ps/teams/Grant-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Grant-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md
  teams/teams-ps/teams/New-CsBatchTeamsDeployment.md
  teams/teams-ps/teams/New-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/New-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/New-CsInboundExemptNumberPattern.md
  teams/teams-ps/teams/New-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/New-CsTeamsAudioConferencingPolicy.md
  teams/teams-ps/teams/New-CsTeamsCustomBannerText.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/New-CsTeamsPinnedApp.md
  teams/teams-ps/teams/New-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/New-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/New-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/New-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/New-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/New-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/New-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/New-CsTenantTrustedIPAddress.md
  teams/teams-ps/teams/New-CsUserCallingDelegate.md
  teams/teams-ps/teams/New-Team.md
  teams/teams-ps/teams/New-TeamChannel.md
  teams/teams-ps/teams/New-TeamsApp.md
  teams/teams-ps/teams/Remove-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Remove-CsInboundExemptNumberPattern.md
  teams/teams-ps/teams/Remove-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Remove-CsOnlineAudioFile.md
  teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Remove-CsTeamsAudioConferencingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsCustomBannerText.md
  teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsNotificationAndFeedsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCustomBannerText.md
Labels: Microsoft submitter, Merge large pull request

#12484 Update docfx.json
  whiteboard/docfx.json
Labels: Microsoft submitter, In review, Sign off, Admin review

#12478 Updating DR inventory examples
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/New-CsOnlineDirectRoutingTelephoneNumberUploadOrder.md
  teams/teams-ps/teams/New-CsOnlineTelephoneNumberReleaseOrder.md
Labels: Microsoft submitter, In review, Sign off

#12477 Switch 'UPN' to 'email address' in Remove-TeamChannelUser docs
  teams/teams-ps/teams/Remove-TeamChannelUser.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12494 Added missing title property 3
  teams/teams-ps/teams/Remove-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Remove-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Remove-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Remove-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Remove-CsUserCallingDelegate.md
  teams/teams-ps/teams/Remove-SharedWithTeam.md
  teams/teams-ps/teams/Remove-Team.md
  teams/teams-ps/teams/Remove-TeamChannel.md
  teams/teams-ps/teams/Remove-TeamChannelUser.md
  teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md
  teams/teams-ps/teams/Remove-TeamUser.md
  teams/teams-ps/teams/Remove-TeamsApp.md
  teams/teams-ps/teams/Remove-TeamsAppInstallation.md
  teams/teams-ps/teams/Set-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/Set-CsInboundExemptNumberPattern.md
  teams/teams-ps/teams/Set-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsAudioConferencingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsExternalAccessConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsFilesPolicy.md
Labels: Microsoft submitter

#12476 Update CsTeamsWorkLocationDetectionPolicy documentation
  teams/teams-ps/teams/Get-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsWorkLocationDetectionPolicy.md
Labels: In review, Sign off

#12499 Published main to live, Thursday 10:30 AM PST, 01/30
  teams/teams-ps/teams/Get-CsTeamsFirstPartyMeetingTemplateConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsGuestCallingConfiguration.md
  teams/teams-ps/teams/Get-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Get-CsTenantBlockedCallingNumbers.md
  teams/teams-ps/teams/Grant-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/New-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Remove-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Remove-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Remove-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Remove-CsUserCallingDelegate.md
  teams/teams-ps/teams/Remove-SharedWithTeam.md
  teams/teams-ps/teams/Remove-Team.md
  teams/teams-ps/teams/Remove-TeamChannel.md
  teams/teams-ps/teams/Remove-TeamChannelUser.md
  teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md
  teams/teams-ps/teams/Remove-TeamUser.md
  teams/teams-ps/teams/Remove-TeamsApp.md
  teams/teams-ps/teams/Remove-TeamsAppInstallation.md
  teams/teams-ps/teams/Set-CsGroupPolicyAssignment.md
  teams/teams-ps/teams/Set-CsInboundExemptNumberPattern.md
  teams/teams-ps/teams/Set-CsOnlineAudioConferencingRoutingPolicy.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsAudioConferencingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsExternalAccessConfiguration.md
  teams/teams-ps/teams/Set-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Set-CsTeamsNotificationAndFeedsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsRoomVideoTeleConferencingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsSettingsCustomApp.md
  teams/teams-ps/teams/Set-CsTeamsSharedCallingRoutingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsShiftsAppPolicy.md
  teams/teams-ps/teams/Set-CsTeamsShiftsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsSurvivableBranchAppliance.md
  teams/teams-ps/teams/Set-CsTeamsSurvivableBranchAppliancePolicy.md
  teams/teams-ps/teams/Set-CsTeamsTargetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md
  teams/teams-ps/teams/Set-CsTeamsVdiPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVirtualAppointmentsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsWorkLocationDetectionPolicy.md
  teams/teams-ps/teams/Set-CsTenantBlockedCallingNumbers.md
  teams/teams-ps/teams/Set-CsUserCallingDelegate.md
  teams/teams-ps/teams/Set-CsUserCallingSettings.md
  teams/teams-ps/teams/Set-Team.md
  teams/teams-ps/teams/Set-TeamArchivedState.md
  teams/teams-ps/teams/Set-TeamChannel.md
  teams/teams-ps/teams/Set-TeamPicture.md
  teams/teams-ps/teams/Set-TeamTargetingHierarchy.md
  teams/teams-ps/teams/Set-TeamsApp.md
  teams/teams-ps/teams/Set-TeamsEnvironmentConfig.md
  teams/teams-ps/teams/Test-CsTeamsTranslationRule.md
  teams/teams-ps/teams/Update-TeamsAppInstallation.md
Labels: Microsoft submitter

#12496 Delete redundant file
  teams/teams-ps/teams/Get-CsTeamsCustomBannerText
Labels: Microsoft submitter

#12501 Publish main to live, 01/30/25, 3:30 PM PT
  teams/teams-ps/teams/Get-CsTeamsCustomBannerText
Labels: Microsoft submitter
