Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2025-03, with the labels that each got.

#12447 Update legacy Exchange token documentation
  exchange/exchange-ps/exchange/Get-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
Labels: area:exchange, Microsoft submitter

#12559 Update Start-ManagedFolderAssistant.md
  exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md
Labels: Microsoft submitter

#12561 Publish main to live, 03/03, 11:00 AM IST
  exchange/exchange-ps/exchange/Get-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-ArcConfig.md
  exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
  exchange/exchange-ps/exchange/Set-ExternalInOutlook.md
  exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md
Labels: Microsoft submitter

#12563 Publish main to live, 03/03/25, 3:30 PM PT
  exchange/exchange-ps/exchange/Set-ReportSubmissionPolicy.md
Labels: Microsoft submitter

#12565 Updated for creating allow directly from TABL
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
Labels: Microsoft submitter

#12564 Removing Immersive events TPM Documentation
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12570 Publish main to live 03/04/2025, 10:30 AM (late)
  exchange/exchange-ps/exchange/New-ProtectionAlert.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter

#12572 Update New-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
Labels: Microsoft submitter

#12574 Publish main to live, 03/07, 11:00 AM IST
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md
Labels: Microsoft submitter

#12581 Update AutoLabelMsftContributor workflow from PAT to GH app and OOB publish
  .github/workflows/AutoLabelMsftContributor.yml
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
Labels: Microsoft submitter

#12580 Update Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#12575 Add Caution info about duplicate SMTP addresses
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#12584 Published main to live, Tuesday 5:00 PM IST, 03/11
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#12573 Update Set-AutoSensitivityLabelRule.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelRule.md
Labels: Microsoft submitter

#12329 Update Test-TextExtraction.md
  exchange/exchange-ps/exchange/Test-TextExtraction.md
Labels: area:exchange, Microsoft submitter

#12585 Update Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
Labels: Microsoft submitter

#12587 Update Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
Labels: Microsoft submitter

#12591 Remove extra spaces and returns
  exchange/exchange-ps/exchange/Export-ContentExplorerData.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-ArcConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#12594 Publish main to live, 03/11/25, 3:30 PM PDT
  exchange/exchange-ps/exchange/Export-ContentExplorerData.md
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-ArcConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#12593 Update New-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/New-CsHybridTelephoneNumber.md
Labels: Microsoft submitter, In review, Sign off

#12592 Update Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
Labels: Microsoft submitter, In review, Sign off

#12578 Update [Get|Update]-M365UnifiedCustomPendingApp[s]
  teams/teams-ps/teams/Get-M365UnifiedCustomPendingApps.md
  teams/teams-ps/teams/Update-M365UnifiedCustomPendingApp.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12595 Update Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
Labels: Microsoft submitter

#12597 372-chrisda to Main
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#12598 Published main to live, Wednesday 10:30 AM PDT, 03/12
  exchange/exchange-ps/exchange/Restore-RecoverableItems.md
  exchange/exchange-ps/exchange/Set-IRMConfiguration.md
  teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Get-M365UnifiedCustomPendingApps.md
  teams/teams-ps/teams/New-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md
  teams/teams-ps/teams/Update-M365UnifiedCustomPendingApp.md
Labels: Microsoft submitter

#12599 Update Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#12602 Publish main to live, 03/12/25, 3:30 PM PDT
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
Labels: Microsoft submitter

#12600 Update Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Add-VivaOrgInsightsDelegatedRole.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-VivaOrgInsightsDelegatedRole.md
  exchange/exchange-ps/exchange/Remove-VivaOrgInsightsDelegatedRole.md
Labels: Microsoft submitter

#12603 Publish main to live, 03/13/25, 10:30 AM PDT
  exchange/exchange-ps/exchange/Add-VivaOrgInsightsDelegatedRole.md
  exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
  exchange/exchange-ps/exchange/Get-VivaOrgInsightsDelegatedRole.md
  exchange/exchange-ps/exchange/Remove-VivaOrgInsightsDelegatedRole.md
Labels: Microsoft submitter

#12601 Update Get-AuthenticationPolicy
  exchange/exchange-ps/exchange/Get-AuthenticationPolicy.md
Labels: Microsoft submitter

#12605 Publish main to live, 03/13/25, 3:30 PM PDT
  exchange/exchange-ps/exchange/Get-AuthenticationPolicy.md
Labels: Microsoft submitter

#12554 Update RealTimeText documentation in TeamsMeetingPolicy and TeamsCallingPolicy
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12606 publish main to live, 3/14/25, 10:30 AM PT
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12607 Set-OWAMailboxPolicy -SetPhotoEnabled Guidance for Exchange Online.
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#12608 Publish main to live, 03/17/25, 3:30 PM PDT
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter

#12604 Update Set-CsTenantFederationConfiguration.md
  teams/teams-ps/teams/Set-CsTenantFederationConfiguration.md
Labels: Microsoft submitter, In review, Sign off

#12609 Publish main to live, 03/18/25, 10:30 AM PDT
  teams/teams-ps/teams/Set-CsTenantFederationConfiguration.md
Labels: Microsoft submitter

#12614 Published main to live, Wednesday 10:30 AM PST, 03/19
  exchange/exchange-ps/exchange/Set-TransportServer.md
Labels: Microsoft submitter

#12615 Updating Set/New-InboxRule to specify the mailbox the inbox rule will be created in.
  exchange/exchange-ps/exchange/New-InboxRule.md
  exchange/exchange-ps/exchange/Set-InboxRule.md
Labels: Microsoft submitter

#12616 Publish main to live, 03/19/25, 3:30 PM PDT
  exchange/exchange-ps/exchange/New-InboxRule.md
  exchange/exchange-ps/exchange/Set-InboxRule.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12619 Chrisda to Main
  exchange/exchange-ps/exchange/Resume-MoveRequest.md
  exchange/exchange-ps/exchange/Resume-PublicFolderMoveRequest.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-ContentFilterConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Test-MigrationServerAvailability.md
Labels: Microsoft submitter

#12618 Update Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#12620 Update Set-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12622 Publish main to live, 03/21/25, 3:30 PM PDT
  exchange/exchange-ps/exchange/Resume-MoveRequest.md
  exchange/exchange-ps/exchange/Resume-PublicFolderMoveRequest.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-ContentFilterConfig.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Test-MigrationServerAvailability.md
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: Microsoft submitter

#12625 Update New-FeatureConfiguration.md
  exchange/exchange-ps/exchange/New-FeatureConfiguration.md
Labels: Microsoft submitter

#12624 Update Remove-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Remove-FeatureConfiguration.md
Labels: Microsoft submitter

#12623 Update Get-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Get-FeatureConfiguration.md
Labels: Microsoft submitter

#12626 Update Teams AI Policy cmdlets docs with SpeakerAttributionBYOD
  teams/teams-ps/teams/Get-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsAIPolicy.md
  teams/teams-ps/teams/New-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12628 Publish main to live, 03/25/25, 3:30 PM PDT
  teams/teams-ps/teams/Get-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Grant-CsTeamsAIPolicy.md
  teams/teams-ps/teams/New-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Remove-CsTeamsAIPolicy.md
  teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
Labels: Microsoft submitter

#12631 Add check to run only if triggered from MicrosoftDocs repo
  .github/workflows/AutoLabelAssign.yml
  .github/workflows/AutoLabelMsftContributor.yml
  .github/workflows/BackgroundTasks.yml
  .github/workflows/BuildValidation.yml
  .github/workflows/LiveMergeCheck.yml
  .github/workflows/PrFileCount.yml
  .github/workflows/ProtectedFiles.yml
  .github/workflows/Stale.yml
  .github/workflows/StaleBranch.yml
  .github/workflows/TierManagement.yml
Labels: Microsoft submitter

#12632 3.7.2
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#12634 Published main to live, Thursday 5:00 PM IST, 03/27
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#12633 Update Set-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Set-FeatureConfiguration.md
Labels: Microsoft submitter

#12636 Publish main to live, 03/27/25, 10:30 AM PDT
  exchange/exchange-ps/exchange/Get-FeatureConfiguration.md
  exchange/exchange-ps/exchange/New-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Remove-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Set-FeatureConfiguration.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#12639 Get/Set-Notification deprecation note
  exchange/exchange-ps/exchange/Get-Notification.md
  exchange/exchange-ps/exchange/Set-Notification.md
Labels: Microsoft submitter

#12640 Publish main to live, 03/28/25, 3:30 PM PDT
  exchange/exchange-ps/exchange/Get-Notification.md
  exchange/exchange-ps/exchange/Set-Notification.md
Labels: Microsoft submitter

#12642 Schedule to 1st of the month at 9am UTC. Disable manual trigger. Disa…
  .github/workflows/StaleBranch.yml
Labels: Microsoft submitter
