Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2025-05, with the labels that each got.

#12711 ARCP-chrisda to Main
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
Labels: Microsoft submitter

#12713 ARCP-chrisda to Main
  exchange/exchange-ps/exchange/New-AppRetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionCompliancePolicy.md
Labels: Microsoft submitter

#12683 Update New-CsComplianceRecordingForCallQueueTemplate.md
  teams/teams-ps/teams/Get-CsSharedCallQueueHistoryTemplate.md
  teams/teams-ps/teams/New-CsCallQueue.md
  teams/teams-ps/teams/New-CsSharedCallQueueHistoryTemplate.md
  teams/teams-ps/teams/Remove-CsSharedCallQueueHistoryTemplate.md
  teams/teams-ps/teams/Set-CsCallQueue.md
  teams/teams-ps/teams/Set-CsSharedCallQueueHistoryTemplate.md
Labels: Microsoft submitter

#12722 Update Set-CsOnlineLisCivicAddress.md
  teams/teams-ps/teams/Set-CsOnlineLisCivicAddress.md
Labels: Microsoft submitter

#12723 Chrisda to Main
  exchange/docs-conceptual/connect-to-exchange-online-powershell.md
  exchange/docs-conceptual/connect-to-scc-powershell.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell.md
Labels: Microsoft submitter, exchange-powershell/svc

#12724 Update Get-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Get-FeatureConfiguration.md
Labels: Microsoft submitter

#12726 Update New-FeatureConfiguration.md
  exchange/exchange-ps/exchange/New-FeatureConfiguration.md
Labels: Microsoft submitter

#12725 Update Set-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Set-FeatureConfiguration.md
Labels: Microsoft submitter

#12727 Update Remove-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Remove-FeatureConfiguration.md
Labels: Microsoft submitter

#12730 Update Get-CsCallQueue.md
  teams/teams-ps/teams/Get-CsAutoAttendant.md
  teams/teams-ps/teams/Get-CsCallQueue.md
Labels: Microsoft submitter

#12638 Update missing parameters
  teams/teams-ps/teams/New-CsTeamsChannelsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsChannelsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTenantFederationConfiguration.md
  teams/teams-ps/teams/set-csteamsmessagingconfiguration.md
Labels: Microsoft submitter, In review, Sign off

#12734 Update Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
Labels: Microsoft submitter

#12738 Blind cmdlet sweep updates
  exchange/exchange-ps/exchange/Get-AuditConfigurationPolicy.md
  exchange/exchange-ps/exchange/Get-AuditConfigurationRule.md
  exchange/exchange-ps/exchange/Get-MailPublicFolder.md
  exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md
  exchange/exchange-ps/exchange/Get-Mailbox.md
  exchange/exchange-ps/exchange/Get-MailboxPermission.md
  exchange/exchange-ps/exchange/Get-MigrationConfig.md
  exchange/exchange-ps/exchange/Get-Recipient.md
  exchange/exchange-ps/exchange/Get-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/Get-User.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-Mailbox.md
  exchange/exchange-ps/exchange/New-MigrationBatch.md
  exchange/exchange-ps/exchange/New-SupervisoryReviewPolicyV2.md
  exchange/exchange-ps/exchange/New-SupervisoryReviewRule.md
  exchange/exchange-ps/exchange/Remove-AuditConfigurationPolicy.md
  exchange/exchange-ps/exchange/Remove-AuditConfigurationRule.md
  exchange/exchange-ps/exchange/Remove-RecipientPermission.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-MailUser.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-SmimeConfig.md
  exchange/exchange-ps/exchange/Set-SupervisoryReviewPolicyV2.md
  exchange/exchange-ps/exchange/Set-SupervisoryReviewRule.md
Labels: Microsoft submitter

#12739 Chrisda to Main
  .openpublishing.redirection.json
  exchange/exchange-ps/exchange/Get-ActivityAlert.md
  exchange/exchange-ps/exchange/Get-AuditConfigurationPolicy.md
  exchange/exchange-ps/exchange/Get-AuditConfigurationRule.md
  exchange/exchange-ps/exchange/New-ActivityAlert.md
  exchange/exchange-ps/exchange/New-AuditConfigurationPolicy.md
  exchange/exchange-ps/exchange/New-AuditConfigurationRule.md
  exchange/exchange-ps/exchange/Remove-ActivityAlert.md
  exchange/exchange-ps/exchange/Remove-AuditConfigurationPolicy.md
  exchange/exchange-ps/exchange/Remove-AuditConfigurationRule.md
  exchange/exchange-ps/exchange/Set-ActivityAlert.md
  exchange/exchange-ps/exchange/Set-AuditConfigurationRule.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#12740 Removed Remove-RecordLabel
  .openpublishing.redirection.json
  exchange/exchange-ps/exchange/Remove-RecordLabel.md
  exchange/exchange-ps/exchange/exchange.md
  exchange/mapping/serviceMapping.json
Labels: Microsoft submitter

#12743 New ApplicationIdentifier param on New/Set-AuthServer
  exchange/exchange-ps/exchange/New-AuthServer.md
  exchange/exchange-ps/exchange/Set-AuthServer.md
Labels: Microsoft submitter

#12749 Update New-CsExternalAccessPolicy.md
  skype/skype-ps/skype/New-CsExternalAccessPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12747 Update Set-CsTenantFederationConfiguration.md
  teams/teams-ps/teams/Set-CsTenantFederationConfiguration.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12752 Export-chrisda to Main
  exchange/exchange-ps/exchange/Get-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/Set-ComplianceSearchAction.md
Labels: Microsoft submitter

#12755 Update New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: Microsoft submitter

#12754 Chrisda to Main
  README.md
  images/quick-update-fork-this-repository-page.png
  images/quick-update-github-edit-icon.png
Labels: Microsoft submitter, In review, Sign off

#12757 DLP-chrisda to Main
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#12737 Update New-CsComplianceRecordingForCallQueueTemplate.md
  teams/teams-ps/teams/New-CsAutoAttendantCallableEntity.md
  teams/teams-ps/teams/New-CsCallQueue.md
  teams/teams-ps/teams/New-CsComplianceRecordingForCallQueueTemplate.md
  teams/teams-ps/teams/New-CsOnlineApplicationInstanceAssociation.md
  teams/teams-ps/teams/Set-CsCallQueue.md
Labels: Microsoft submitter

#12761 Update New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
Labels: Microsoft submitter

#12762 Update Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
Labels: Microsoft submitter

#12769 Update New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
Labels: Microsoft submitter
