Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2025-04, with the labels that each got.

#12643 38-chrisda to Main
  exchange/exchange-ps/exchange/Connect-IPPSSession.md
Labels: Microsoft submitter

#12637 Update New-CsAutoAttendant.md
  teams/teams-ps/teams/Get-CsComplianceRecordingForCallQueueTemplate.md
  teams/teams-ps/teams/New-CsComplianceRecordingForCallQueueTemplate.md
  teams/teams-ps/teams/Remove-CsComplianceRecordingForCallQueueTemplate.md
  teams/teams-ps/teams/Set-CsComplianceRecordingForCallQueueTemplate.md
Labels: Microsoft submitter

#12646 Update Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
Labels: Microsoft submitter

#12649 Publish main to live, 04/02/25, 3:30 PM PDT
  exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md
  exchange/exchange-ps/exchange/Remove-UnifiedGroupLinks.md
Labels: Microsoft submitter

#12648 Update New-CsCallQueue.md
  teams/teams-ps/teams/New-CsCallQueue.md
  teams/teams-ps/teams/Set-CsCallQueue.md
Labels: Microsoft submitter

#12650 Publish main to live, 04/03, 11:00 AM IST
  teams/teams-ps/teams/New-CsCallQueue.md
  teams/teams-ps/teams/Set-CsCallQueue.md
Labels: Microsoft submitter

#12655 Update Set-OrganizationConfig.md
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#12661 Publish main to live, 04/03/25, 3:30 PM PDT
  exchange/exchange-ps/exchange/Set-OrganizationConfig.md
Labels: Microsoft submitter

#12662 Update Set-MailUser.md
  exchange/exchange-ps/exchange/Set-MailUser.md
Labels: Microsoft submitter

#12663 Publish main to live, 04/04, 11:00 AM IST
  exchange/exchange-ps/exchange/Set-MailUser.md
Labels: Microsoft submitter

#12667 Publish main to live, 04/07/25, 10:30 AM PDT
  teams/teams-ps/teams/Set-CsCallQueue.md
Labels: Microsoft submitter

#12668 Update Set-CASMailbox.md
  exchange/exchange-ps/exchange/Set-CASMailbox.md
Labels: Microsoft submitter

#12669 Publish main to live, 04/08, 11:00 AM IST
  exchange/exchange-ps/exchange/Set-CASMailbox.md
Labels: Microsoft submitter

#12675 Update Get-CsOnlineUser.md
  teams/teams-ps/teams/Get-CsOnlineUser.md
Labels: Microsoft submitter, In review, Sign off

#12676 Published main to live, Wednesday 10:30 AM PST, 04/09
  teams/teams-ps/teams/Get-CsOnlineUser.md
Labels: Microsoft submitter

#12681 Update Set-AcceptedDomain.md
  exchange/exchange-ps/exchange/Set-AcceptedDomain.md
Labels: Microsoft submitter

#12687 Update Set-MailUser.md
  exchange/exchange-ps/exchange/Set-MailUser.md
Labels: Microsoft submitter

#12659 Update New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
Labels: Microsoft submitter

#12692 StaleBranch reporting updates and cron changes to live
  .github/workflows/StaleBranch.yml
Labels: Microsoft submitter

#12693 Creating new cmdlets for telephone number tagging feature
  teams/teams-ps/teams/Get-CsPhoneNumberTag.md
  teams/teams-ps/teams/Remove-CsPhoneNumberTag.md
  teams/teams-ps/teams/Set-CsPhoneNumberTag.md
  teams/teams-ps/teams/Update-CsPhoneNumberTag.md
Labels: Microsoft submitter

#12694 Update New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12660 Update TeamsCallingPolicy.copilot docs
  teams/teams-ps/teams/New-CsTeamsCallingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsCallingPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12685 Admin commands documentation update for whiteboard to get migrated and originally created fluid boards
  whiteboard/whiteboard-ps/whiteboard/Get-OriginalFluidWhiteboards.md
  whiteboard/whiteboard-ps/whiteboard/Get-OriginalFluidWhiteboardsForTenant.md
  whiteboard/whiteboard-ps/whiteboard/Get-Whiteboard.md
  whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardSettings.md
  whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardsForTenant.md
  whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardsForTenantMigrated.md
  whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardsMigrated.md
  whiteboard/whiteboard-ps/whiteboard/Restore-Whiteboard.md
  whiteboard/whiteboard-ps/whiteboard/Set-WhiteboardSettings.md
  whiteboard/whiteboard-ps/whiteboard/whiteboard.md
Labels: Admin review, PubOps fixes

#12700 Qp-chrisda to Main
  exchange/exchange-ps/exchange/Export-QuarantineMessage.md
Labels: Microsoft submitter

#12698 Update New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12709 Update Remove-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Remove-FeatureConfiguration.md
Labels: Microsoft submitter

#12707 Update Set-FeatureConfiguration.md
  exchange/exchange-ps/exchange/Set-FeatureConfiguration.md
Labels: Microsoft submitter
