Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2025-06, with the labels that each got.

#12777 Updating end user notification and phone number Filter options
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter

#12780 Update New-CsExternalAccessPolicy.md
  teams/teams-ps/teams/New-CsExternalAccessPolicy.md
Labels: Microsoft submitter, In review, Sign off, Triage-InProgress

#12786 Update Get-MessageTraceDetailV2.md
  exchange/exchange-ps/exchange/Get-MessageTraceDetailV2.md
Labels: Microsoft submitter

#12783 Create MAML2Yaml subfolder to store monikerMapping.json
  .openpublishing.publish.config.json
  exchange/mapping/MAML2Yaml/monikerMapping.json
  officewebapps/mapping/MAML2Yaml/monikerMapping.json
  skype/mapping/MAML2Yaml/monikerMapping.json
  spmt/mapping/MAML2Yaml/monikerMapping.json
  staffhub/docfx.json
  staffhub/docs-conceptual/LICENSE.txt
  staffhub/mapping/monikerMapping.json
  teams/mapping/MAML2Yaml/monikerMapping.json
  whiteboard/mapping/MAML2Yaml/monikerMapping.json
Labels: Microsoft submitter

#12787 Publish
  .openpublishing.publish.config.json
  exchange/mapping/MAML2Yaml/monikerMapping.json
  officewebapps/mapping/MAML2Yaml/monikerMapping.json
  skype/mapping/MAML2Yaml/monikerMapping.json
  spmt/mapping/MAML2Yaml/monikerMapping.json
  staffhub/docfx.json
  staffhub/docs-conceptual/LICENSE.txt
  staffhub/mapping/monikerMapping.json
  teams/mapping/MAML2Yaml/monikerMapping.json
  whiteboard/mapping/MAML2Yaml/monikerMapping.json
Labels: Microsoft submitter

#12789 Update Get-MessageTraceV2.md
  exchange/exchange-ps/exchange/Get-MessageTraceV2.md
Labels: Microsoft submitter

#12790 MTv2-chrisda to Main
  exchange/exchange-ps/exchange/Get-MessageTraceDetailV2.md
  exchange/exchange-ps/exchange/Get-MessageTraceV2.md
Labels: Microsoft submitter

#12791 SPO to SP and ODfB to OD
  exchange/exchange-ps/exchange/Get-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Get-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/Get-DlpDetailReport.md
  exchange/exchange-ps/exchange/Get-DlpDetectionsReport.md
  exchange/exchange-ps/exchange/Get-DlpIncidentDetailReport.md
  exchange/exchange-ps/exchange/Install-UnifiedCompliancePrerequisite.md
  exchange/exchange-ps/exchange/Invoke-HoldRemovalAction.md
  exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/New-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/New-ComplianceRetentionEvent.md
  exchange/exchange-ps/exchange/New-ComplianceSearch.md
  exchange/exchange-ps/exchange/New-ComplianceSearchAction.md
  exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpComplianceRule.md
  exchange/exchange-ps/exchange/New-HoldCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-UnifiedGroup.md
  exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md
  exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
  exchange/exchange-ps/exchange/Set-AutoSensitivityLabelPolicy.md
  exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
  exchange/exchange-ps/exchange/Set-ComplianceSearch.md
  exchange/exchange-ps/exchange/Set-ComplianceSecurityFilter.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpComplianceRule.md
  exchange/exchange-ps/exchange/Set-HoldCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-OwaVirtualDirectory.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-UnifiedGroup.md
Labels: Microsoft submitter, Merge large pull request

#12794 Update New-SensitiveInformationScan.md
  exchange/exchange-ps/exchange/New-SensitiveInformationScan.md
Labels: Microsoft submitter, Triage-InProgress

#12795 Update New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
Labels: Microsoft submitter

#12796 Update New-ApplicationAccessPolicy.md
  exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md
Labels: Microsoft submitter

#12760 Update Get-CsOnlineUser.md
  teams/teams-ps/teams/Get-CsOnlineUser.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes, Triage-DRI

#12782 Update New-CsAutoAttendantCallFlow.md
  teams/teams-ps/teams/New-CsAutoAttendantCallFlow.md
Labels: Microsoft submitter, Triage-InProgress

#12804 Update Get-EXOMailbox.md
  exchange/exchange-ps/exchange/Get-EXOMailbox.md
Labels: Microsoft submitter

#12806 Update New-OrganizationRelationship.md
  exchange/exchange-ps/exchange/New-OrganizationRelationship.md
Labels: Microsoft submitter

#12810 Add priority cleanup description
  exchange/exchange-ps/exchange/Remove-RetentionCompliancePolicy.md
Labels: Microsoft submitter

#12816 PriorityCleanup update updates
  exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Remove-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Remove-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md
Labels: Microsoft submitter

#12736 Update TeamsMeetingPolicy
  teams/teams-ps/teams/New-CsTeamsMeetingPolicy.md
  teams/teams-ps/teams/Set-CsTeamsMeetingPolicy.md
Labels: In review, Sign off, PubOps fixes, Triage-Completed

#12819 LOBAppAccount to MS reserved
  exchange/exchange-ps/exchange/Get-MailUser.md
  exchange/exchange-ps/exchange/New-MailUser.md
  exchange/exchange-ps/exchange/Set-MailUser.md
Labels: Microsoft submitter

#12820 Update Get-MailUser.md
  exchange/exchange-ps/exchange/Get-MailUser.md
Labels: Microsoft submitter

#12821 Chrisda to Main
  exchange/exchange-ps/exchange/Get-PublicFolderClientPermission.md
Labels: Microsoft submitter

#12823 v3.8.0 release updates
  exchange/docs-conceptual/exchange-online-powershell-v2.md
  exchange/docs-conceptual/whats-new-in-the-exo-module.md
Labels: Microsoft submitter, exchange-online/svc, exchange-powershell/svc

#12825 Update Set-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md
Labels: Microsoft submitter

#12826 Update New-DlpCompliancePolicy.md
  exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md
Labels: Microsoft submitter

#12830 Blocked file types update
  exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
Labels: Microsoft submitter, Do not merge

#12831 Update New-CsCallQueue.md
  teams/teams-ps/teams/New-CsCallQueue.md
Labels: In review, Sign off, Triage-Completed
