Repository MicrosoftDocs/office-docs-powershell, pull requests merged in 2025-07, with the labels that each got.

#12326 Update New-CsOnlinePSTNGateway.md
  teams/teams-ps/teams/New-CsOnlinePSTNGateway.md
Labels: Microsoft submitter

#12815 Update New-ComplianceTag.md
  exchange/exchange-ps/exchange/New-ComplianceTag.md
Labels: Microsoft submitter

#12842 Blanked PriorityCleanup description
  exchange/exchange-ps/exchange/New-ComplianceTag.md
  exchange/exchange-ps/exchange/Set-ComplianceTag.md
Labels: Microsoft submitter

#12846 Update Check-PurviewConfig.md
  exchange/exchange-ps/exchange/Check-PurviewConfig.md
Labels: Microsoft submitter

#12852 Update Set-CsExternalAccessPolicy.md
  teams/teams-ps/teams/Set-CsExternalAccessPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12853 Update New-CsExternalAccessPolicy.md
  teams/teams-ps/teams/New-CsExternalAccessPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12327 Update Set-CsOnlinePSTNGateway.md
  teams/teams-ps/teams/Set-CsOnlinePSTNGateway.md
Labels: Microsoft submitter

#12858 Update SamAccountName description
  exchange/exchange-ps/exchange/New-DistributionGroup.md
  exchange/exchange-ps/exchange/Set-DistributionGroup.md
Labels: Microsoft submitter

#12863 Documentation for -OCDIRedirect attribute in TeamsUpdateManagementPolicy
  teams/teams-ps/teams/New-CsTeamsUpdateManagementPolicy.md
  teams/teams-ps/teams/Set-CsTeamsUpdateManagementPolicy.md
Labels: In review, Sign off

#12869 Update Check-PurviewConfig.md
  exchange/exchange-ps/exchange/Check-PurviewConfig.md
Labels: Microsoft submitter

#12861 Update Remove-TeamUser.md
  teams/teams-ps/teams/Remove-TeamUser.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12571 [Release on 7/7 at 10am PST] Immersive events TPM Documentation
  teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
  teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
Labels: Microsoft submitter, In review, Sign off

#12876 Migrate officewebapps docset to use PSMD2Yaml and new page template
  .openpublishing.publish.config.json
  officewebapps/mapping/monikerMapping.json
  officewebapps/officewebapps-ps/officewebapps/officewebapps.md
Labels: Microsoft submitter

#12889 Update Export-ActivityExplorerData.md
  exchange/exchange-ps/exchange/Export-ActivityExplorerData.md
Labels: Microsoft submitter

#12893 Update Remove-SensitiveInformationScan.md
  exchange/exchange-ps/exchange/Remove-SensitiveInformationScan.md
  exchange/exchange-ps/exchange/Remove-SensitiveInformationScanRule.md
Labels: Microsoft submitter

#12894 Update Set-SensitiveInformationScanRule.md
  exchange/exchange-ps/exchange/Set-SensitiveInformationScanRule.md
Labels: Microsoft submitter

#12895 Update Set-SensitiveInformationScan.md
  exchange/exchange-ps/exchange/Set-SensitiveInformationScan.md
Labels: Microsoft submitter

#12897 Fix content in OfficeWebApps & SPMT
  .openpublishing.publish.config.json
  .openpublishing.redirection.exchange.json
  .openpublishing.redirection.json
  .openpublishing.redirection.officewebapps.json
  .openpublishing.redirection.skype.json
  .openpublishing.redirection.spmt.json
  .openpublishing.redirection.teams.json
  .openpublishing.redirection.whiteboard.json
  officewebapps/officewebapps-ps/officewebapps/Get-OfficeWebAppsFarm.md
  officewebapps/officewebapps-ps/officewebapps/Get-OfficeWebAppsHost.md
  officewebapps/officewebapps-ps/officewebapps/Get-OfficeWebAppsMachine.md
  officewebapps/officewebapps-ps/officewebapps/New-OfficeWebAppsExcelUserDefinedFunction.md
  officewebapps/officewebapps-ps/officewebapps/New-OfficeWebAppsFarm.md
  officewebapps/officewebapps-ps/officewebapps/New-OfficeWebAppsHost.md
  officewebapps/officewebapps-ps/officewebapps/New-OfficeWebAppsMachine.md
  officewebapps/officewebapps-ps/officewebapps/Remove-OfficeWebAppsHost.md
  officewebapps/officewebapps-ps/officewebapps/Remove-OfficeWebAppsMachine.md
  officewebapps/officewebapps-ps/officewebapps/Repair-OfficeWebAppsFarm.md
  officewebapps/officewebapps-ps/officewebapps/Set-OfficeWebAppsFarm.md
  officewebapps/officewebapps-ps/officewebapps/Set-OfficeWebAppsMachine.md
  officewebapps/officewebapps-ps/officewebapps/officewebapps.md
  spmt/spmt-ps/Microsoft.SharePoint.MigrationTool.PowerShell/Add-SPMTTask.md
  spmt/spmt-ps/Microsoft.SharePoint.MigrationTool.PowerShell/Get-SPMTMigration.md
  spmt/spmt-ps/Microsoft.SharePoint.MigrationTool.PowerShell/Microsoft.SharePoint.MigrationTool.PowerShell.md
  spmt/spmt-ps/Microsoft.SharePoint.MigrationTool.PowerShell/Register-SPMTMigration.md
  spmt/spmt-ps/Microsoft.SharePoint.MigrationTool.PowerShell/Remove-SPMTTask.md
  spmt/spmt-ps/Microsoft.SharePoint.MigrationTool.PowerShell/Show-SPMTMigration.md
  spmt/spmt-ps/Microsoft.SharePoint.MigrationTool.PowerShell/Start-SPMTMigration.md
  spmt/spmt-ps/Microsoft.SharePoint.MigrationTool.PowerShell/Stop-SPMTMigration.md
  spmt/spmt-ps/Microsoft.SharePoint.MigrationTool.PowerShell/Unregister-SPMTMigration.md
  spmt/spmt-ps/spmt/Register-SPMTMigration.md
  spmt/spmt-ps/spmt/Remove-SPMTTask.md
  spmt/spmt-ps/spmt/SharePointMigrationTool.md
  spmt/spmt-ps/spmt/Show-SPMTMigration.md
  spmt/spmt-ps/spmt/Start-SPMTMigration.md
  spmt/spmt-ps/spmt/Stop-SPMTMigration.md
  whiteboard/mapping/MAML2Yaml/monikerMapping.json
Labels: Microsoft submitter

#12905 Add AutoShareFilesInExternalChats attribute to TeamsFilesPolicy
  teams/teams-ps/teams/New-CsTeamsFilesPolicy.md
  teams/teams-ps/teams/Set-CsTeamsFilesPolicy.md
Labels: In review, Sign off

#12904 Update New-CsAutoAttendant.md
  teams/teams-ps/teams/Get-CsMainlineAttendantFlow.md
  teams/teams-ps/teams/New-CsAutoAttendant.md
  teams/teams-ps/teams/New-CsAutoAttendantCallFlow.md
  teams/teams-ps/teams/New-CsAutoAttendantMenu.md
  teams/teams-ps/teams/New-CsAutoAttendantMenuOption.md
  teams/teams-ps/teams/New-CsMainlineAttendantAppointmentBookingFlow.md
  teams/teams-ps/teams/New-CsMainlineAttendantQuestionAnswerFlow.md
Labels: Microsoft submitter, In review, Sign off

#12918 Update .openpublishing.redirection.exchange.json
  .openpublishing.redirection.exchange.json
Labels: Microsoft submitter

#12920 Third-party to non-Microsoft
  exchange/exchange-ps/exchange/Disable-CmdletExtensionAgent.md
  exchange/exchange-ps/exchange/Enable-CmdletExtensionAgent.md
  exchange/exchange-ps/exchange/Get-CmdletExtensionAgent.md
  exchange/exchange-ps/exchange/Get-ExoPhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Get-ExoSecOpsOverrideRule.md
  exchange/exchange-ps/exchange/Get-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Get-QuarantineMessage.md
  exchange/exchange-ps/exchange/Get-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Get-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-ActiveSyncMailboxPolicy.md
  exchange/exchange-ps/exchange/New-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/New-DatabaseAvailabilityGroup.md
  exchange/exchange-ps/exchange/New-ExoPhishSimOverrideRule.md
  exchange/exchange-ps/exchange/New-ExoSecOpsOverrideRule.md
  exchange/exchange-ps/exchange/New-ForeignConnector.md
  exchange/exchange-ps/exchange/New-ManagementRole.md
  exchange/exchange-ps/exchange/New-MobileDeviceMailboxPolicy.md
  exchange/exchange-ps/exchange/New-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/New-ReportSubmissionPolicy.md
Labels: Microsoft submitter

#12922 Third-party to non-Microsoft 2
  exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
  exchange/exchange-ps/exchange/New-ReportSubmissionRule.md
  exchange/exchange-ps/exchange/New-RetentionComplianceRule.md
  exchange/exchange-ps/exchange/New-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/New-SendConnector.md
  exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/New-TransportRule.md
  exchange/exchange-ps/exchange/Remove-DlpSensitiveInformationTypeRulePackage.md
  exchange/exchange-ps/exchange/Remove-ExoPhishSimOverrideRule.md
  exchange/exchange-ps/exchange/Remove-ExoSecOpsOverrideRule.md
  exchange/exchange-ps/exchange/Remove-PhishSimOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-SecOpsOverridePolicy.md
  exchange/exchange-ps/exchange/Remove-TenantAllowBlockListItems.md
  exchange/exchange-ps/exchange/Set-ActiveSyncMailboxPolicy.md
  exchange/exchange-ps/exchange/Set-AppRetentionComplianceRule.md
  exchange/exchange-ps/exchange/Set-CmdletExtensionAgent.md
  exchange/exchange-ps/exchange/Set-EcpVirtualDirectory.md
Labels: Microsoft submitter, exchange-powershell/svc

#12926 Updating parameter definition
  teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
  teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
Labels: Microsoft submitter, In review, Sign off, PubOps fixes

#12933 Update exchange-online-powershell-v2.md
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: exchange-powershell/svc

#12943 Update .openpublishing.redirection.exchange.json
  .openpublishing.redirection.exchange.json
Labels: Microsoft submitter

#12944 [redirects] paths update for exchange
  .openpublishing.redirection.exchange.json
Labels: Microsoft submitter

#12947 Revert "Update exchange-online-powershell-v2.md"
  exchange/docs-conceptual/exchange-online-powershell-v2.md
Labels: Microsoft submitter, exchange-powershell/svc
